from case_MBPP_312 import find_literals


def check(candidate):
    assert candidate('The quick brown fox jumps over the lazy dog.', 'fox') == ('fox', 16, 19)
    assert candidate('Its been a very crazy procedure right', 'crazy') == ('crazy', 16, 21)
    assert candidate('Hardest choices required strongest will', 'will') == ('will', 35, 39)
    assert candidate('LXxeSbWvzawAlOcaKrGKXiuEIHe.srfYrWGZdwu', 'dwu') == ('dwu', 36, 39)
    assert candidate('EwCX jrp.GWGQQOmtVAeWBZQlwZXpuisiUkjOQuUVDJ', 'pui') == ('pui', 28, 31)
    assert candidate('KGtkF .oQLFFFjTZZB cleMy xzQxzjhDkGMLKalwgHNkaB', 'alw') == ('alw', 38, 41)
    assert candidate('TozjWtQpOgblHHNXwrLghpiRwDTNCirWiIqLPcHTyAfuZydC', 'hpi') == ('hpi', 20, 23)
    assert candidate('NNgx sdzoBNoHPqefqjEfHLXJLQJjHhuZniiQEIg', 'nii') == ('nii', 33, 36)
    assert candidate('GnDBpBXrCYznxAMHFCqMyiOxDSDkTVzMU.xpMWqxhWF', 'znx') == ('znx', 10, 13)
    assert candidate('JKnnfxbbuZCws.pjoZobhuAuMIQmkwxAb gkiiuinx', 'fxb') == ('fxb', 4, 7)
    assert candidate('CKxtlpIXpOUocFHCBraoGcwySBeCSfmAvvcZGOvaFg', 'xtl') == ('xtl', 2, 5)
    assert candidate('XtcyOkhnKguYhYOTBuQYwYKlVAyjYSVSeOBhpFqauE', 'tcy') == ('tcy', 1, 4)
    assert candidate('Lpm.PMNBYBZTvAsycizmSOaO.qJATNaXFRMTQFBXbiAP', 'ciz') == ('ciz', 16, 19)
    assert candidate('tpjItbVLhwlwbGJpYCKUOWBlNCyHHkAestDEQwGiWOSxM', 'wlw') == ('wlw', 9, 12)
    assert candidate('Uxyw Kl.KCacwhzR.YT.AXbodPqjTeqlZazwRPCmsPaGCHaI', 'bod') == ('bod', 22, 25)
    assert candidate('nqcvywoUBrAw ylWQkynZkAOSdelHpIkotNSt IjZQHisA', 'cvy') == ('cvy', 2, 5)
    assert candidate('itsDuwLyNioLEewPmLGpufCWcBOhSpqyOdyCITyKgci', 'gci') == ('gci', 40, 43)
    assert candidate('CqFZAMWBtugdEIIiGIJKhZMTjoBlQBUTZvrCHRgtpvU', 'tpv') == ('tpv', 39, 42)
    assert candidate('ToIKXKQFWoCIhCcFnpwimtmutITmjfllQHXHsNjIwOAkIlP', 'imt') == ('imt', 19, 22)
    assert candidate('rwEjqoRqdVKwlchvSmExSZJWyNMdlfvFgEAegPosPAsqSdqq', 'jqo') == ('jqo', 3, 6)
    assert candidate('PXaWfW KDvTeAytWslwzNpGrnNHDHnzVmApUIGqppYgKqRBe', 'lwz') == ('lwz', 17, 20)
    assert candidate('DNdkaBp.sJsOqvhfZRumbwDLzMWhzjmwAxlJBciMeq', 'umb') == ('umb', 18, 21)
    assert candidate('PCMJGMOnKnInQwDHuspNaxjLOxcJBx WFcDiEgvcviEkLNN', 'cvi') == ('cvi', 39, 42)
    assert candidate('rZuqUEWsGFnkBv.Yz tiAANgMZfHgSRP zqhHSeR', 'zqh') == ('zqh', 33, 36)
    assert candidate('usaqICNAN mkcploJDHSQTchjraBhWFzZPnivKwSmUx', 'plo') == ('plo', 13, 16)
    assert candidate(' AtWXaBMjfwDicpLVFRixZKBCRvnDksbO kqsIAsLJszquPa', 'szq') == ('szq', 42, 45)
    assert candidate('YGZBDMChroBOyEj.BLjVaCPaSxetpmbbgfjfjsE', 'fjs') == ('fjs', 35, 38)
    assert candidate('xlLOrAaCaqABox LVHxckbjalaf DlILkGVfxrF k', 'alaf') == ('alaf', 23, 27)
    assert candidate('oxUQdEuZwPWrtyblCiVraHvpmVEAQVsvpiS ZEMAQdBjsR', 'ybl') == ('ybl', 13, 16)
    assert candidate('UFzdKejZBuWMvrPTynIbQ t.PURsdbIkynacdlY', 'yna') == ('yna', 32, 35)
    assert candidate('neEGnco.FwzqTReaKGAkYPTmqpBMuGOgLDgadyRAi YExX', 'nco') == ('nco', 4, 7)
    assert candidate('HbrATGhz Gpp.DyIAJIoTmaBBfIaMUybDcoprv.so', 'opr') == ('opr', 34, 37)
    assert candidate('VFAWyEFlrRMqxgvWKNiwpr.eirRaxjgYgtsEjuRzIJ', 'iwp') == ('iwp', 18, 21)
    assert candidate('TFSQcQftdgxkzXGhErlZLdacHWhnQsFCvw.cClgeusxoyoT', 'ftd') == ('ftd', 6, 9)
    assert candidate('uFbTGJQeTLsdwOrEAGZkDPMFMo lrtid.AewPTlYPKrtE', 'rti') == ('rti', 28, 31)
    assert candidate('ZImVKHbcHjqUThUFdrWdRssRpmdMlMSfuoiKWgWXzyaVVJ', 'zya') == ('zya', 40, 43)
    assert candidate('quntTpCmSRwjQoaooE XGBawdteXozKDAg', 'awd') == ('awd', 22, 25)
    assert candidate('SlwRqEzqSYidxKkrduoTlglSooAtMWjYsyNSy', 'rdu') == ('rdu', 15, 18)
    assert candidate('KDrrnVx oUQfNiJvzWSOWMQaKzDbhTbOgjK', 'rrn') == ('rrn', 2, 5)
    assert candidate('IkyGeZnpXyEdAc ilxK vRMRGpvTMdyhgrr', 'ilx') == ('ilx', 15, 18)
    assert candidate('KjPgDbtCoOolzrvovQEwaTgNiHxrvVNbowivTG', 'wiv') == ('wiv', 33, 36)
    assert candidate('AUYcXyjfOxlFaObOZVzivilvfcgBrMaNVOSujcjR', 'vfc') == ('vfc', 23, 26)
    assert candidate('XNtrkdVcENjMRXaryPZpiuMSCxMXCQrPoadJ q', 'piu') == ('piu', 19, 22)
    assert candidate('fwxHBbYndHJDAivkexUKCHOwfhrJiHBmyNrNbw', 'fwx') == ('fwx', 0, 3)
    assert candidate('KFsNEaUpjaQbDIdEzsEhUwHczYgVNgzoODPAkI', 'gzo') == ('gzo', 29, 32)
    assert candidate('NZiNZyMxcvJ yUShNFaLQtINoatHHT MHwJOVKuBn', 'xcv') == ('xcv', 7, 10)
    assert candidate('jDEQlQrqyluDeHsuPlBAbixmDVADLqNmqM', 'ylu') == ('ylu', 8, 11)
    assert candidate('lWvzpyXskSztNUUVspbMpxdqjdwroOAeLZfK', 'dwr') == ('dwr', 25, 28)
    assert candidate('KkSnmgGCsbjoMHYdHIKoNnrUtddhWlBXyRYysgr', 'bjo') == ('bjo', 9, 12)
    assert candidate('KKZkashxkvoFAgvnALUFvHXYDnFAqv wxIvXEVeki', 'shx') == ('shx', 5, 8)
    assert candidate('tcDAvxcXlnOUpDxjgdvkegQyDgXewjSXHubql k', 'ewj') == ('ewj', 27, 30)
    assert candidate('xmxWJY  KMfmFxzHTARaKmgxWHNvBkxMf', 'xmx') == ('xmx', 0, 3)
    assert candidate('DTpScHJdgmoQdktUYbjSvesnegyuIQdCRl', 'sne') == ('sne', 22, 25)
    assert candidate('HpNqIizMAoWvPnYVVLpfxyVulCLohuooZM', 'fxy') == ('fxy', 19, 22)
    assert candidate('iyuliKaIxnOnYqJiGRwQiIlxSDZpkckg sL', 'uli') == ('uli', 2, 5)
    assert candidate('D HGCcww PjvblOmsIKpaqYOJfhDWcuQWYYaiJXj', 'vbl') == ('vbl', 11, 14)
    assert candidate('LwUTTiZefX vAfH AZWzvLtGAAAeXDpaxptatlWDE', 'paxp') == ('paxp', 30, 34)
    assert candidate('KAdEBQtcIpFuZpSqWqivXhjwvqoUfr YxSMtgdVEwh', 'qiv') == ('qiv', 17, 20)
    assert candidate('cdRrtriobyWaUMalSBDBzcMjiMcPxbnUbNUdaGb', 'rtr') == ('rtr', 3, 6)
    assert candidate('iq QfLwJ rXzuynQmcydEmFJfqiM sUYUdaO', 'cyd') == ('cyd', 17, 20)
    assert candidate('exafTFoANrWYCSYMTHypmdI tqVpeQViPuwd', 'ypm') == ('ypm', 18, 21)
    assert candidate('AAzyfiPRzrDXiiQvvkKZkLcOZOYqUqmws', 'vvk') == ('vvk', 15, 18)
    assert candidate('KeVX VYFlzP ztCgfdyGgyeKtJBEUwthmDaDsfdKV', 'sfd') == ('sfd', 36, 39)
    assert candidate('MohNlGTQsPUakFsbwCGdmnFQXMFUIlhojhHIuUjTH', 'dmn') == ('dmn', 19, 22)
    assert candidate('HYwCnqvlUmyEHAUZHYUudN xkpCSZBIjGptvxKE', 'xkp') == ('xkp', 23, 26)
    assert candidate('dkYpBwjpFKGDUpsaqIRwIQvUmnPZaAAdegNmOZ', 'wjp') == ('wjp', 5, 8)
    assert candidate('BnmQMfunRJB ysrRdMpWovKVfojuXLogJolGJU', 'fun') == ('fun', 5, 8)
    assert candidate('otVuJbzeIeTcsyfBavboHHsnH tkIrsLupMgC', 'avb') == ('avb', 16, 19)
    assert candidate('dVNSeYufrDgAbJPoxqDsTYKNurRBXQBNBZxFwO', 'oxq') == ('oxq', 15, 18)
    assert candidate('PJiYhnEdrVcHdixMbijfHvXXgP wExGkzeHnpKKlXQ', 'kze') == ('kze', 31, 34)
    assert candidate('WUv zWXqdbCVmoexoPvxY IlimTCOeymdfovedER', 'qdb') == ('qdb', 7, 10)
    assert candidate('m eyGPNwyLooQujIEsZzUCbSFVYyFbskCeFrBA ', 'bsk') == ('bsk', 29, 32)
    assert candidate('nOyvKJkfgtrfLtloqlvkmWrsJdgCFasnUOGBodUKW', 'loq') == ('loq', 14, 17)
    assert candidate('zOHraIHjIfdCizmUfYDVZkgbcrzIBQWtCGuSZJrKrLvj', 'izm') == ('izm', 12, 15)
    assert candidate('ZEWBziqmciWQnqeqsyOJuWcrwFjmEwfcFvQtXFWBK', 'iqmc') == ('iqmc', 5, 9)
    assert candidate('gKG zSQEpzhmwrkamhPKbRSPoOyqBbEoqwBVslbOnFd', 'zhm') == ('zhm', 9, 12)
    assert candidate('aTOyDyogvCjQdZNLIoXMJIyLPcNgKcCkthHPnmOddq', 'yog') == ('yog', 5, 8)
    assert candidate('w WXjlsXvPaGGKscZqkLfZcjUjNwOQgBlcqJZa', 'jls') == ('jls', 4, 7)
    assert candidate('OXwhdXNzbVuqPzHqkmboiuKRkLjTLjDgjYzUtgbZqr', 'qkm') == ('qkm', 15, 18)
    assert candidate('PSlWvKcH CanGnxrSRnlpYphJOH UCvtxWFitrMmTu', 'vtx') == ('vtx', 30, 33)
    assert candidate('GMbBuofcqwYwMshCCNAXANHcyYeqRrFFOyag', 'yag') == ('yag', 33, 36)
    assert candidate('YIrRqeMHHuJkMEiaDckhNbvynUcUoUEsHKxZnRzkqvG', 'ckh') == ('ckh', 17, 20)
    assert candidate('JQHPaWFYhpAMCOmEanuKuFikltGMwOnZViJtJgBFMgJ', 'anu') == ('anu', 16, 19)
    assert candidate('uOANSXrGtkKunlTokqgYAPzfcPTbrjiEnVFQguHfalHD', 'rji') == ('rji', 28, 31)
    assert candidate('mQYwAQQ CenkkZDVi yBHUswyXZSoeoSMXXzXlKhClZH', 'nkk') == ('nkk', 10, 13)
    assert candidate('IWD EMHrWMjzlTdEPLMbDUoutmOatfvDdzwoTbjoxj', 'dzw') == ('dzw', 32, 35)
    assert candidate('vhtQkmQfqADbfUTVFjNXAxtnEffXTFoOVAAe', 'xtn') == ('xtn', 21, 24)
    assert candidate('jNSljnYmLUGltdtiWYLRsxJtcYAVjUUVddvXg', 'ljn') == ('ljn', 3, 6)
    assert candidate('PygXqjuqbquEACxjTTJnrfDLLLhCqXvdHftWzQIAiTnxe', 'nrf') == ('nrf', 19, 22)
    assert candidate('qoyUXocaOVuzcu hnxoVgsNUYRpC SXcPSBlieb', 'qoy') == ('qoy', 0, 3)
    assert candidate('NAEcUnSattaEjMMbBOqlFeWLoDCeiAuxuseYIeFdHQRi', 'use') == ('use', 32, 35)
    assert candidate('QvEujEyJfhQWPQffBrVCWHbvbQpEFqMW iAncZGQp', 'bvb') == ('bvb', 22, 25)
    assert candidate('rpXmailmMLMEDqNDbRhMLYSfrsuJawgfAkfeyhDfA', 'mai') == ('mai', 3, 6)
    assert candidate('DV QZzhoUrlCNrDfZIObqDkMJZHFBd XqV ohvZbdWmHn', 'ohv') == ('ohv', 35, 38)
    assert candidate('vksTBogCnqXXafOGypkUipFKtMnlebmxcwbnTGTPmcZ', 'wbn') == ('wbn', 33, 36)
    assert candidate('gnrLtSjYgcGbhKPJjCuRpuEgvbAffxPPgysyuGtODVMpF', 'ysy') == ('ysy', 33, 36)
    assert candidate('VIenRjanArgwFTSCSATPLYdPEwcfrPmbqHSVeIkHOOI', 'cfr') == ('cfr', 26, 29)
    assert candidate('uKlYmVPkPnxWHqwelP kWbOGnNPeeeGHXGnWgsmRUQ', 'wel') == ('wel', 14, 17)
    assert candidate('rHTOkpWVPWKoSRAPT eAeihclpvlihBXSkpmWT', 'ihc') == ('ihc', 21, 24)
    assert candidate(' uwtAKfnBlnjIEAZ phkkXDayre KqsQ XJOjJFnIYUbz', 'phk') == ('phk', 17, 20)
    assert candidate('kszkHCAaDYJiCbsTapnBrsbHiEsdsIlJYRgqHMWv', 'szk') == ('szk', 1, 4)
    assert candidate('XzgfKwoUQovT FiMn FCgPFzlciWEeWSvzOe TW', 'lci') == ('lci', 24, 27)

if __name__ == '__main__':
    check(find_literals)