from case_MBPP_412 import text_starta_endb


def check(candidate):
    assert candidate("aabbbb")==('Found a match!')
    assert candidate("aabAbbbc")==('Not matched!')
    assert candidate("accddbbjjj")==('Not matched!')
    assert candidate("mklgx") == "Not matched!"
    assert candidate("ujwkwbrkbehp") == "Not matched!"
    assert candidate("enqj") == "Not matched!"
    assert candidate("bnhxbhmrwc") == "Not matched!"
    assert candidate("thkj") == "Not matched!"
    assert candidate("bjzhy") == "Not matched!"
    assert candidate("dvax") == "Not matched!"
    assert candidate("ssj") == "Not matched!"
    assert candidate("gvfpfjutt") == "Not matched!"
    assert candidate("prsfymmiz") == "Not matched!"
    assert candidate("sqinxtz") == "Not matched!"
    assert candidate("seqtnfqqmd") == "Not matched!"
    assert candidate("xndozudunflo") == "Not matched!"
    assert candidate("kjatwysa") == "Not matched!"
    assert candidate("htd") == "Not matched!"
    assert candidate("hbalqixwjl") == "Not matched!"
    assert candidate("gxzhnwrix") == "Not matched!"
    assert candidate("euxdf") == "Not matched!"
    assert candidate("xdlkjcnam") == "Not matched!"
    assert candidate("jzafcsgym") == "Not matched!"
    assert candidate("gbnuuphdnkg") == "Not matched!"
    assert candidate("akjrq") == "Not matched!"
    assert candidate("flxb") == "Not matched!"
    assert candidate("valvloq") == "Not matched!"
    assert candidate("cdag") == "Not matched!"
    assert candidate("gskimg") == "Not matched!"
    assert candidate("foqalzgfrwt") == "Not matched!"
    assert candidate("smscbm") == "Not matched!"
    assert candidate("lvqwpy") == "Not matched!"
    assert candidate("xhaqpsydvlc") == "Not matched!"
    assert candidate("dwtqdp") == "Not matched!"
    assert candidate("fnkpju") == "Not matched!"
    assert candidate("tvkogkwk") == "Not matched!"
    assert candidate("xzECFpO") == "Not matched!"
    assert candidate("tjgT") == "Not matched!"
    assert candidate("iJXSgCTFC") == "Not matched!"
    assert candidate("tlSzoeXVI") == "Not matched!"
    assert candidate("YoCUnWKPmkf") == "Not matched!"
    assert candidate("eoTUWyeYgqg") == "Not matched!"
    assert candidate("aSdg") == "Not matched!"
    assert candidate("OiIyHfRSwbSe") == "Not matched!"
    assert candidate("wyTThPup") == "Not matched!"
    assert candidate("xVPCpgZR") == "Not matched!"
    assert candidate("SKdglCpGIB") == "Not matched!"
    assert candidate("PtVcgB") == "Not matched!"
    assert candidate("dRCR") == "Not matched!"
    assert candidate("qAmXE") == "Not matched!"
    assert candidate("ZJEArb") == "Not matched!"
    assert candidate("JyEtGO") == "Not matched!"
    assert candidate("LSUxpaomVhgn") == "Not matched!"
    assert candidate("EltrvoeQFW") == "Not matched!"
    assert candidate("uBT") == "Not matched!"
    assert candidate("ZPVNcpxL") == "Not matched!"
    assert candidate("bEblwfsE") == "Not matched!"
    assert candidate("TMnhBeRt") == "Not matched!"
    assert candidate("TZbjlLPrsS") == "Not matched!"
    assert candidate("bTVHY") == "Not matched!"
    assert candidate("rxrPlvdGjwe") == "Not matched!"
    assert candidate("iqDxarCYMwYZ") == "Not matched!"
    assert candidate("QqrCjg") == "Not matched!"
    assert candidate("GtWx") == "Not matched!"
    assert candidate("nSDec") == "Not matched!"
    assert candidate("OseVecIJsqWb") == "Not matched!"
    assert candidate("yYKap") == "Not matched!"
    assert candidate("tTCvXKfuao") == "Not matched!"
    assert candidate("ijCmflWAdBKO") == "Not matched!"
    assert candidate("ikdafqxbr") == "Not matched!"
    assert candidate("dbbvkmaklwcw") == "Not matched!"
    assert candidate("dkfyipkkdtibxa") == "Not matched!"
    assert candidate("pjahcspkrhdgp") == "Not matched!"
    assert candidate("tkbhob") == "Not matched!"
    assert candidate("vahbqvkrfqtqt") == "Not matched!"
    assert candidate("ackuqyddvgnk") == "Not matched!"
    assert candidate("caspafdpybtwgaj") == "Not matched!"
    assert candidate("jxeolnkmxjtee") == "Not matched!"
    assert candidate("dukltlngsr") == "Not matched!"
    assert candidate("esikinamftya") == "Not matched!"
    assert candidate("lekqqsx") == "Not matched!"
    assert candidate("sjxtawgo") == "Not matched!"
    assert candidate("matrzksufb") == "Found a match!"
    assert candidate("wxevpsqr") == "Not matched!"
    assert candidate("qvrzrflx") == "Not matched!"
    assert candidate("uguoirzh") == "Not matched!"
    assert candidate("mjonyiyxxq") == "Not matched!"
    assert candidate("bmrqqktbylks") == "Not matched!"
    assert candidate("bvonbzfvxht") == "Not matched!"
    assert candidate("imsgrjooip") == "Not matched!"
    assert candidate("vtbxtntzv") == "Not matched!"
    assert candidate("rnrfgtpj") == "Not matched!"
    assert candidate("xzrcahoy") == "Not matched!"
    assert candidate("cqokvrbaaob") == "Found a match!"
    assert candidate("ygyoezgfeyb") == "Not matched!"
    assert candidate("tqctkltxmueobn") == "Not matched!"
    assert candidate("mpitqqax") == "Not matched!"
    assert candidate("dsvnqblhnwkpwyh") == "Not matched!"
    assert candidate("jiccjpu") == "Not matched!"
    assert candidate("gcugvjrzyg") == "Not matched!"
    assert candidate("wqmsutwmveg") == "Not matched!"
    assert candidate("usjhbxj") == "Not matched!"

if __name__ == '__main__':
    check(text_starta_endb)