from case_MBPP_248 import upper_ctr


def check(candidate):
    assert candidate('PYthon') == 1
    assert candidate('BigData') == 1
    assert candidate('program') == 0
    assert candidate("uUUuER") == 0
    assert candidate("Vxb") == 1
    assert candidate("jWzwvwxMLie") == 0
    assert candidate("PHGrOeRkKgph") == 1
    assert candidate("hdL") == 0
    assert candidate("Gjqxipzbw") == 1
    assert candidate("hkJY") == 0
    assert candidate("UKP") == 1
    assert candidate("dFLDjzcPNpVe") == 0
    assert candidate("NZwTgqtvIwLI") == 1
    assert candidate("OMUuQ") == 1
    assert candidate("kSuZyEkiKQQ") == 0
    assert candidate("SqYRNoTZuEBe") == 1
    assert candidate("VYZEFWRl") == 1
    assert candidate("fHJXk") == 0
    assert candidate("hAmWCewaVb") == 0
    assert candidate("KEhk") == 1
    assert candidate("QtL") == 1
    assert candidate("xYrtuKYTPY") == 0
    assert candidate("VuocenzRbi") == 1
    assert candidate("vJyCuqBbtY") == 0
    assert candidate("kRPZRB") == 0
    assert candidate("JzTQnGpa") == 1
    assert candidate("bGhk") == 0
    assert candidate("KVUZQgqFm") == 1
    assert candidate("htk") == 0
    assert candidate("imKDYfDQzuzY") == 0
    assert candidate("dNLfkdYPg") == 0
    assert candidate("nbdpIi") == 0
    assert candidate("LPytDb") == 1
    assert candidate("IinsKCec") == 1
    assert candidate("dSpL") == 0
    assert candidate("vvgmqM") == 0
    assert candidate("kPqCGmU") == 0
    assert candidate("cSE") == 0
    assert candidate("NgoVigfGb") == 1
    assert candidate("rBObRKs") == 0
    assert candidate("JbikDXKUucBD") == 1
    assert candidate("seFuAvVIT") == 0
    assert candidate("wDPi") == 0
    assert candidate("DLUVbx") == 1
    assert candidate("jizC") == 0
    assert candidate("tqLol") == 0
    assert candidate("oWxlKeaim") == 0
    assert candidate("vXIfklVVz") == 0
    assert candidate("sMopfJDcLnX") == 0
    assert candidate("TDeKjBQnH") == 1
    assert candidate("kXGu") == 0
    assert candidate("yXAngvbCKWtg") == 0
    assert candidate("MpDsTkZw") == 1
    assert candidate("EFMjpyjlgzje") == 1
    assert candidate("XQxl") == 1
    assert candidate("rzs") == 0
    assert candidate("yDLhDPNBMFUm") == 0
    assert candidate("GbypqNwtX") == 1
    assert candidate("IhNjuehY") == 1
    assert candidate("ZbJsLF") == 1
    assert candidate("VKNkGqOmbIXy") == 1
    assert candidate("jSoO") == 0
    assert candidate("nZAwy") == 0
    assert candidate("TbF") == 1
    assert candidate("UnVvf") == 1
    assert candidate("YpkfQD") == 1
    assert candidate("unPCJwhJspM") == 0
    assert candidate("rUzhPokO") == 0
    assert candidate("lOx") == 0
    assert candidate("zgdvpduxp") == 0
    assert candidate("kzbfex") == 0
    assert candidate("gltlisoivj") == 0
    assert candidate("mvy") == 0
    assert candidate("pudynzp") == 0
    assert candidate("auimkfewjivk") == 0
    assert candidate("qjefepm") == 0
    assert candidate("dovygims") == 0
    assert candidate("bjdmpsabgrt") == 0
    assert candidate("ipgtk") == 0
    assert candidate("tyjgifx") == 0
    assert candidate("hfcssf") == 0
    assert candidate("gnohy") == 0
    assert candidate("cjcqmtm") == 0
    assert candidate("qvxyvp") == 0
    assert candidate("gjoupn") == 0
    assert candidate("tnwfqsxgovs") == 0
    assert candidate("dfajvidepxsi") == 0
    assert candidate("yxovmajbjayu") == 0
    assert candidate("tiaspzxkaj") == 0
    assert candidate("vywcrzhgy") == 0
    assert candidate("ohtz") == 0
    assert candidate("thpypre") == 0
    assert candidate("apiloool") == 0
    assert candidate("xqcoe") == 0
    assert candidate("ltnkgpjkajv") == 0
    assert candidate("ralm") == 0
    assert candidate("hqdp") == 0
    assert candidate("clqmrcbxzy") == 0
    assert candidate("dunkonb") == 0
    assert candidate("ftpkepgjow") == 0
    assert candidate("autq") == 0
    assert candidate("xcjrnm") == 0

if __name__ == '__main__':
    check(upper_ctr)