from case_MBPP_392 import remove_length


def check(candidate):
    assert candidate('The person is most value tet', 3) == 'person is most value'
    assert candidate('If you told me about this ok', 4) == 'If you me about ok'
    assert candidate('Forces of darkeness is come into the play', 4) == 'Forces of darkeness is the'
    assert candidate('eU rRkEcOyTXAHj XM ivLpGweqI', 7) == "eU rRkEcOyTXAHj XM ivLpGweqI"
    assert candidate('ipmFGrBxINGkCvmUSMluhqAEjXaEK', 6) == "ipmFGrBxINGkCvmUSMluhqAEjXaEK"
    assert candidate('vtbbUlWZusWbKQlmPWDwj cjKfkCaiSX', 1) == "vtbbUlWZusWbKQlmPWDwj cjKfkCaiSX"
    assert candidate('bkbCSYFVtqXeeZKhkVJLaqJMTSXly', 3) == "bkbCSYFVtqXeeZKhkVJLaqJMTSXly"
    assert candidate('iTVycZktuOlpluTWPmKfhDKiTqfQos', 2) == "iTVycZktuOlpluTWPmKfhDKiTqfQos"
    assert candidate('vTGukEWzKLWocvyORBMVSalcgy', 5) == "vTGukEWzKLWocvyORBMVSalcgy"
    assert candidate('y GymYeoVkbQnVmjGTbir  mGWA', 4) == "y GymYeoVkbQnVmjGTbir"
    assert candidate('IerbIUbfiLIhokWeNPJZpUcXiDBLXi', 6) == "IerbIUbfiLIhokWeNPJZpUcXiDBLXi"
    assert candidate('qlZETmgDMwTpjkrdZwGPIDfsTdjg', 5) == "qlZETmgDMwTpjkrdZwGPIDfsTdjg"
    assert candidate('uQeHqkAYsPRamCWvhW LsgUevelhApw ', 1) == "uQeHqkAYsPRamCWvhW LsgUevelhApw"
    assert candidate('McbJNRfghbejZZlGznhAk eWHgOkEw', 3) == "McbJNRfghbejZZlGznhAk eWHgOkEw"
    assert candidate('etE xezqELKKgcixclHROJjEATov', 7) == "etE xezqELKKgcixclHROJjEATov"
    assert candidate('yHatrLMOLAdXGBPztzrnJErofSedYskzf', 6) == "yHatrLMOLAdXGBPztzrnJErofSedYskzf"
    assert candidate('CgsVLauPykqdPPogFKYDURdFfkYdQG', 1) == "CgsVLauPykqdPPogFKYDURdFfkYdQG"
    assert candidate('dQFqhAnhfhZZCJwWGNFhcqoqzjeNWBJDG', 2) == "dQFqhAnhfhZZCJwWGNFhcqoqzjeNWBJDG"
    assert candidate('VwdaKOGsNEnCGWHbPyIPVSfDCOqMStF', 8) == "VwdaKOGsNEnCGWHbPyIPVSfDCOqMStF"
    assert candidate('WsLaSH qlNpdWfxxEYBTQpidOxnGt', 7) == "WsLaSH qlNpdWfxxEYBTQpidOxnGt"
    assert candidate('l QZDSbxUwwVpAtOXxFWrYFNpOmbN', 8) == "l QZDSbxUwwVpAtOXxFWrYFNpOmbN"
    assert candidate('olMbeYouDyrPBmf emXnqxfHprFaaQXbd', 1) == "olMbeYouDyrPBmf emXnqxfHprFaaQXbd"
    assert candidate('rkjiERLpiRkGOmdlHqg yYF ', 6) == "rkjiERLpiRkGOmdlHqg yYF"
    assert candidate('sVYpdqfYQymrblUYPwKFtqjAH U', 5) == "sVYpdqfYQymrblUYPwKFtqjAH U"
    assert candidate('NZEvzGPaFRoeGAllAYBxgDYT', 6) == "NZEvzGPaFRoeGAllAYBxgDYT"
    assert candidate('HVhOagCzxUcEshsNJ v iCfvxvz', 8) == "HVhOagCzxUcEshsNJ v iCfvxvz"
    assert candidate('zEqGaVGWDkCmFLSsymjdDEKhcTfC fj', 6) == "zEqGaVGWDkCmFLSsymjdDEKhcTfC fj"
    assert candidate('nJEhhrXwjUrFPXQYPnWInGokLJxVlNwu', 6) == "nJEhhrXwjUrFPXQYPnWInGokLJxVlNwu"
    assert candidate('MeLBXUgpTFczp aziphQpuK YEe', 4) == "MeLBXUgpTFczp aziphQpuK YEe"
    assert candidate('OGwAZldObdIhsxUwZDrRFekUTeXCNZtz', 7) == "OGwAZldObdIhsxUwZDrRFekUTeXCNZtz"
    assert candidate('GpTCNWVBkwvnBsmklwuuXGezR', 7) == "GpTCNWVBkwvnBsmklwuuXGezR"
    assert candidate('pSTlDqgGHCFfOYqraAgtnsZEJIMpM', 4) == "pSTlDqgGHCFfOYqraAgtnsZEJIMpM"
    assert candidate('LHEWDYAxbyaHkIjRlEbxsFob', 7) == "LHEWDYAxbyaHkIjRlEbxsFob"
    assert candidate('PnjOUDisIdaZRftCFQYLmidJjZQB', 8) == "PnjOUDisIdaZRftCFQYLmidJjZQB"
    assert candidate('ppZgsiiXxJWiqcrezQonmIlOdKOOh', 4) == "ppZgsiiXxJWiqcrezQonmIlOdKOOh"
    assert candidate('KOZUdLNTSiyRcVblVGZnnBkCjy', 2) == "KOZUdLNTSiyRcVblVGZnnBkCjy"
    assert candidate(' mxetWL FSl maNNiXbIawFDL', 4) == "mxetWL FSl maNNiXbIawFDL"
    assert candidate('ttSe gLZcNiwkLlCTuTcXmuH', 7) == "ttSe gLZcNiwkLlCTuTcXmuH"
    assert candidate('FicWmfmmRaBpavUMluXKbgcsfQW', 1) == "FicWmfmmRaBpavUMluXKbgcsfQW"
    assert candidate('n IqlgGOuaiIeJoyRfLPxKSoi', 5) == "n IqlgGOuaiIeJoyRfLPxKSoi"
    assert candidate('hsFDtvCffYfc  mgSBazxYMoNzaArKrDd', 1) == "hsFDtvCffYfc mgSBazxYMoNzaArKrDd"
    assert candidate('tcJNgLsOiiZcZgzbmojFbdMUcZpw', 8) == "tcJNgLsOiiZcZgzbmojFbdMUcZpw"
    assert candidate('diWAkqbEFCkEeOqcrBb rtrrWUUroOm', 6) == "diWAkqbEFCkEeOqcrBb rtrrWUUroOm"
    assert candidate('oJ JppKknyefVnQJYkhWMdwtdQn yAC', 7) == "oJ JppKknyefVnQJYkhWMdwtdQn yAC"
    assert candidate('LdoLwHmTQwOiFUrDIWFHCbCSQ', 2) == "LdoLwHmTQwOiFUrDIWFHCbCSQ"
    assert candidate('QdVkZOwyYlaiYfNqTZrTWD I', 9) == "QdVkZOwyYlaiYfNqTZrTWD I"
    assert candidate('FKlKTSZIzrfqFTZFwoGLusMfN', 3) == "FKlKTSZIzrfqFTZFwoGLusMfN"
    assert candidate('cSdJaWdcbzV WCZvgPCTETK gONVoNts', 2) == "cSdJaWdcbzV WCZvgPCTETK gONVoNts"
    assert candidate('KDKBcggKdPTSZPtglXerwgPhBTeFMksJ ', 2) == "KDKBcggKdPTSZPtglXerwgPhBTeFMksJ"
    assert candidate('hiMhOPFxrjBjdGIDhGMWoeWpjyvGNVgNz', 5) == "hiMhOPFxrjBjdGIDhGMWoeWpjyvGNVgNz"
    assert candidate('YtRQFeHsPhVxzct RWoJKWFS', 9) == "YtRQFeHsPhVxzct RWoJKWFS"
    assert candidate('HUgHnPlwcHnrPXkwolaLUbgpzDHjryk', 3) == "HUgHnPlwcHnrPXkwolaLUbgpzDHjryk"
    assert candidate('aaQkLGeKXvVXnBAIyxQDmBMOLnvFlNhE', 3) == "aaQkLGeKXvVXnBAIyxQDmBMOLnvFlNhE"
    assert candidate('QIuTtwaQyHpPWfobatSximVil', 2) == "QIuTtwaQyHpPWfobatSximVil"
    assert candidate('SoLvHYfcenXmJAUXVH MErSBYZLmpi', 4) == "SoLvHYfcenXmJAUXVH MErSBYZLmpi"
    assert candidate('eBpOyalrQhdVuK FHNnKldcO', 1) == "eBpOyalrQhdVuK FHNnKldcO"
    assert candidate('ozpYVwKFvqMLzjxyuuRTLupM', 8) == "ozpYVwKFvqMLzjxyuuRTLupM"
    assert candidate('ShKuelTsbwWKbECrivtsgMTDvweRPgmAb', 6) == "ShKuelTsbwWKbECrivtsgMTDvweRPgmAb"
    assert candidate('YlQitodYwGzmowFnzUScY iAh', 6) == "YlQitodYwGzmowFnzUScY iAh"
    assert candidate('IQiLFBqgefyLJAPCuFngDHRFhiUXB', 2) == "IQiLFBqgefyLJAPCuFngDHRFhiUXB"
    assert candidate('HKlqezqbkQpgLKmpbeAKSXCyFEwW', 4) == "HKlqezqbkQpgLKmpbeAKSXCyFEwW"
    assert candidate('NvVsghOIxPuEwB YxYDGklPfKBxQoH', 7) == "NvVsghOIxPuEwB YxYDGklPfKBxQoH"
    assert candidate('MJthTeogmZFNRdhCUVeHwJTufTMSntMGA', 6) == "MJthTeogmZFNRdhCUVeHwJTufTMSntMGA"
    assert candidate('NJWacKZsaGBOwgJPlEtBWKosDNGipPL', 5) == "NJWacKZsaGBOwgJPlEtBWKosDNGipPL"
    assert candidate('wjWjyVSuIrtTJg RgoHOlLipa', 9) == "wjWjyVSuIrtTJg RgoHOlLipa"
    assert candidate('ORwRjaKXrOOnmkYygCTfQrnrlhhZJYsh', 2) == "ORwRjaKXrOOnmkYygCTfQrnrlhhZJYsh"
    assert candidate('quDLaZPvXWAM ipRhwmEHmMcCNUbH', 2) == "quDLaZPvXWAM ipRhwmEHmMcCNUbH"
    assert candidate('KKwBlAeboT NPDjjbPlZXSODW', 5) == "KKwBlAeboT NPDjjbPlZXSODW"
    assert candidate('CmmRcduHTlkvzLjczfXiMECaBUa', 3) == "CmmRcduHTlkvzLjczfXiMECaBUa"
    assert candidate('B CRAhpOzFswvjggxbGETZSYLretUtsDngPixMaUTvPAy', 8) == "B CRAhpOzFswvjggxbGETZSYLretUtsDngPixMaUTvPAy"
    assert candidate('zzxoPNXrcDELWdWTYU NHpkmcoWtEdSQHIToVZNxMPk', 2) == "zzxoPNXrcDELWdWTYU NHpkmcoWtEdSQHIToVZNxMPk"
    assert candidate('DtkeLwZgMrMrUGEXZDAEoWaXvR QfjhUDHmDnjFI', 1) == "DtkeLwZgMrMrUGEXZDAEoWaXvR QfjhUDHmDnjFI"
    assert candidate('nhVrroHSjmyQSbhwEYOYhqUNbOpHAfiyoVoRl', 5) == "nhVrroHSjmyQSbhwEYOYhqUNbOpHAfiyoVoRl"
    assert candidate('ItuuLgBGmRRLFeByIdmlIAqiosHsnh zHon ', 3) == "ItuuLgBGmRRLFeByIdmlIAqiosHsnh zHon"
    assert candidate('mZYYltmyoWDUkOYESTNhYkqccEboZZjLfxb NKH', 7) == "mZYYltmyoWDUkOYESTNhYkqccEboZZjLfxb NKH"
    assert candidate('kfFIGUSZMqfTMmkYlBoHNklcEJILKOcRzvtNlhgfmUf', 8) == "kfFIGUSZMqfTMmkYlBoHNklcEJILKOcRzvtNlhgfmUf"
    assert candidate('vPJWewOERNqtQWJLPseNhFbkaoOuhyOTDKrQSEoZio', 3) == "vPJWewOERNqtQWJLPseNhFbkaoOuhyOTDKrQSEoZio"
    assert candidate('yJAFEjsclwQgwZnEScoAH tdUqvmRFyo ZIFVgmKbwFM', 2) == "yJAFEjsclwQgwZnEScoAH tdUqvmRFyo ZIFVgmKbwFM"
    assert candidate('OIoDTAsiNWuVqpxqqmAqHzJAJ aFbAutfzIxvtbeeP', 1) == "OIoDTAsiNWuVqpxqqmAqHzJAJ aFbAutfzIxvtbeeP"
    assert candidate('jwwECkBaKZjRIPCLqmeUDEPebaiUQIaAXkhdCIy ECuyK', 5) == "jwwECkBaKZjRIPCLqmeUDEPebaiUQIaAXkhdCIy"
    assert candidate('IbKaNrKJbnebaOSCSKFpokMbsRswsNhXVnCmkUAF', 1) == "IbKaNrKJbnebaOSCSKFpokMbsRswsNhXVnCmkUAF"
    assert candidate('UvUjigtBDOZdmEcqLFATaSFviccTvqshXWAppdLmDbh', 3) == "UvUjigtBDOZdmEcqLFATaSFviccTvqshXWAppdLmDbh"
    assert candidate('ee gG ZsFXUzHleSqzo h UxWRsAjObUPkWlJQirDlr', 8) == "ee gG ZsFXUzHleSqzo h UxWRsAjObUPkWlJQirDlr"
    assert candidate('QNbFPyDhhEYuWxPETuhDqtkQk ErEFEGUullTl', 6) == "QNbFPyDhhEYuWxPETuhDqtkQk ErEFEGUullTl"
    assert candidate('KzsgcbrHPVyDkgXLEoVWHiFNjwCTZmbqyjQMedni', 6) == "KzsgcbrHPVyDkgXLEoVWHiFNjwCTZmbqyjQMedni"
    assert candidate('lDFezIDhdwcCoDlnUdIwQGbWSCXZdddMmmfLkghiesRfi', 2) == "lDFezIDhdwcCoDlnUdIwQGbWSCXZdddMmmfLkghiesRfi"
    assert candidate('vMLfmFEwFrJgMOvZaUZJCqobpyWmjzFARgBrgrrfqPdVx', 6) == "vMLfmFEwFrJgMOvZaUZJCqobpyWmjzFARgBrgrrfqPdVx"
    assert candidate('pZUtwNOkCAYAvBJzUqwqXyysMNaWVggZyamvd', 2) == "pZUtwNOkCAYAvBJzUqwqXyysMNaWVggZyamvd"
    assert candidate('DsLiMzKGYQaGnHWyVDWfHYkTVEaZwJpGdXPrWoqHpUng', 8) == "DsLiMzKGYQaGnHWyVDWfHYkTVEaZwJpGdXPrWoqHpUng"
    assert candidate('GDzxvrTPGccxpxbnbdVMBbFJHITXEa gP OtwPAf', 2) == "GDzxvrTPGccxpxbnbdVMBbFJHITXEa OtwPAf"
    assert candidate('OBMgJBriRTmcIBkSXqDVVlSgVTactrBtAVd I', 7) == "OBMgJBriRTmcIBkSXqDVVlSgVTactrBtAVd I"
    assert candidate('qdmFPjpzTOHvUvaLUdvkjAUeVJaLBQKcvjptWMymPpnRn', 6) == "qdmFPjpzTOHvUvaLUdvkjAUeVJaLBQKcvjptWMymPpnRn"
    assert candidate('iyndfWtQDPrie PzRUlsNGjjkJbDkbaAAy KforR', 8) == "iyndfWtQDPrie PzRUlsNGjjkJbDkbaAAy KforR"
    assert candidate('rHtLvDcmuIyhIgPHScWKnBbzTNjkPeCtKYdE tFUJG', 8) == "rHtLvDcmuIyhIgPHScWKnBbzTNjkPeCtKYdE tFUJG"
    assert candidate('iumCguDHOSzYQflLOehCcOWTTgbOlTnGBIITy', 3) == "iumCguDHOSzYQflLOehCcOWTTgbOlTnGBIITy"
    assert candidate('gjTG oTkzprtcmZKmQuBLpMLdAXZpobPcptHb', 5) == "gjTG oTkzprtcmZKmQuBLpMLdAXZpobPcptHb"
    assert candidate('wJmOAgRjqhqtSWsVQAhJMiFaHkeDmAnRlYKMLHaDTd', 2) == "wJmOAgRjqhqtSWsVQAhJMiFaHkeDmAnRlYKMLHaDTd"
    assert candidate('mreQDMg NsTJKc XWwViwGIIxJAGqYHSGQaFmA', 8) == "mreQDMg NsTJKc XWwViwGIIxJAGqYHSGQaFmA"
    assert candidate('EfHeZVXYNcLbRWasVloRgosrhyethYiIXQUTR', 7) == "EfHeZVXYNcLbRWasVloRgosrhyethYiIXQUTR"
    assert candidate('AGEsoWBRruk EiWkWPXIUnWDmYODJkbjfTn AZdOdi', 5) == "AGEsoWBRruk EiWkWPXIUnWDmYODJkbjfTn AZdOdi"
    assert candidate('IjrMMlCqQLKR BcusnFqtBCzoiKR kkPEnk qMCyIBwR', 3) == "IjrMMlCqQLKR BcusnFqtBCzoiKR kkPEnk qMCyIBwR"
    assert candidate('aDiDHfwikjFpphJGyRDrJOJoajc wT ocvbHY', 5) == "aDiDHfwikjFpphJGyRDrJOJoajc wT ocvbHY"

if __name__ == '__main__':
    check(remove_length)