from case_MBPP_370 import capital_words_spaces


def check(candidate):
    assert candidate("Python") == 'Python'
    assert candidate("PythonProgrammingExamples") == 'Python Programming Examples'
    assert candidate("GetReadyToBeCodingFreak") == 'Get Ready To Be Coding Freak'
    assert candidate("NQhchIZD") == "N Qhch IZ D"
    assert candidate("aevsZpSRZ") == "aevs Zp SR Z"
    assert candidate("YHOPOXsD") == "Y HO PO Xs D"
    assert candidate("DKkLLPkBmQC") == "D Kk LL Pk Bm QC"
    assert candidate("dofHbRfSak") == "dof Hb Rf Sak"
    assert candidate("XHDDu") == "X HD Du"
    assert candidate("azHjNnRmqo") == "az Hj Nn Rmqo"
    assert candidate("oVStyiY") == "o VStyi Y"
    assert candidate("MlnoQfI") == "Mlno Qf I"
    assert candidate("SamDVNhmj") == "Sam DV Nhmj"
    assert candidate("eHIZSc") == "e HI ZSc"
    assert candidate("UPoTiB") == "U Po Ti B"
    assert candidate("qQiLr") == "q Qi Lr"
    assert candidate("salUhlqh") == "sal Uhlqh"
    assert candidate("pCulySI") == "p Culy SI"
    assert candidate("YNzO") == "Y Nz O"
    assert candidate("nTjb") == "n Tjb"
    assert candidate("CouySw") == "Couy Sw"
    assert candidate("UpASVPRFNJj") == "Up AS VP RF NJj"
    assert candidate("zMu") == "z Mu"
    assert candidate("THFSo") == "T HF So"
    assert candidate("SxgxIlnvoRt") == "Sxgx Ilnvo Rt"
    assert candidate("KOaKXuzwxqbJ") == "K Oa KXuzwxqb J"
    assert candidate("huMNkvmYTiX") == "hu MNkvm YTi X"
    assert candidate("mPhVxBVijMcv") == "m Ph Vx BVij Mcv"
    assert candidate("ihdWYSx") == "ihd WY Sx"
    assert candidate("gbxhlkYUS") == "gbxhlk YU S"
    assert candidate("FFPTX") == "F FP TX"
    assert candidate("pMtsbWC") == "p Mtsb WC"
    assert candidate("Gxir") == "Gxir"
    assert candidate("pdVPsexlueC") == "pd VPsexlue C"
    assert candidate("LdMIhY") == "Ld MIh Y"
    assert candidate("hZCimTr") == "h ZCim Tr"
    assert candidate("YUUrkkhmilZrEuUrbasUeHWOLGPS") == "Y UUrkkhmil Zr Eu Urbas Ue HW OL GP S"
    assert candidate("zTTSsHcEWgIJESqiXjttenDsSPk") == "z TT Ss Hc EWg IJ ESqi Xjtten Ds SPk"
    assert candidate("owrdBhxZLfQwKkqivjtsfpT") == "owrd Bhx ZLf Qw Kkqivjtsfp T"
    assert candidate("NPIxXxqBvirqiWCptrwMvSVctxW") == "N PIx Xxq Bvirqi WCptrw Mv SVctx W"
    assert candidate("MtgkNORdxgGkdGWmvPdnaJUyXo") == "Mtgk NO Rdxg Gkd GWmv Pdna JUy Xo"
    assert candidate("qczFfZBeYbqBkvvdHKpVPrjRXWFpG") == "qcz Ff ZBe Ybq Bkvvd HKp VPrj RX WFp G"
    assert candidate("gQldSBJAbTxqWlDpdQSfPoRDyboFoI") == "g Qld SB JAb Txq Wl Dpd QSf Po RDybo Fo I"
    assert candidate("EcZCONDLxwFbkENQZivlqkUGHsT") == "Ec ZC ON DLxw Fbk EN QZivlqk UG Hs T"
    assert candidate("AzQlWvBuyGZkJrbllpIgp") == "Az Ql Wv Buy GZk Jrbllp Igp"
    assert candidate("YxlHSADWaYumHPqcOnvKzQdgRX") == "Yxl HS AD Wa Yum HPqc Onv Kz Qdg RX"
    assert candidate("igQmpUnQoAsiKMLsznhEcGqgZqy") == "ig Qmp Un Qo Asi KM Lsznh Ec Gqg Zqy"
    assert candidate("TQEBkWYuNyOAvJCqSAMogwFD") == "T QE Bk WYu Ny OAv JCq SA Mogw FD"
    assert candidate("zXqWRFTfTElHHjAuawsrRr") == "z Xq WR FTf TEl HHj Auawsr Rr"
    assert candidate("UYAocFVshCtbNzdnUezvKW") == "U YAoc FVsh Ctb Nzdn Uezv KW"
    assert candidate("VwysSglJoEbrJiZdiVsrmQP") == "Vwys Sgl Jo Ebr Ji Zdi Vsrm QP"
    assert candidate("SRAJdmykNsAFWhbULYXlFtPazA") == "S RA Jdmyk Ns AF Whb UL YXl Ft Paz A"
    assert candidate("NbHfOCMGaSlyYgDrbTJef") == "Nb Hf OC MGa Sly Yg Drb TJef"
    assert candidate("RJDFnsnyVMddBRYIjkDTOF") == "R JD Fnsny VMdd BR YIjk DT OF"
    assert candidate("PmDqQlONEkfCmJEFPPhYovWShsx") == "Pm Dq Ql ON Ekf Cm JE FP Ph Yov WShsx"
    assert candidate("YNrvVZOeovFVaioEPzSeSHEYCX") == "Y Nrv VZ Oeov FVaio EPz Se SH EY CX"
    assert candidate("yJODPwHnAVbUQinGaOobH") == "y JO DPw Hn AVb UQin Ga Oob H"
    assert candidate("jHpwooaKBPQPcWLqMHrAlC") == "j Hpwooa KB PQ Pc WLq MHr Al C"
    assert candidate("SnYrEDBZvgSHZyliaTugNH") == "Sn Yr ED BZvg SH Zylia Tug NH"
    assert candidate("eviQDGUCVevYuUySjhxqgY") == "evi QD GU CVev Yu Uy Sjhxqg Y"
    assert candidate("OXHFxLMljvJeDkalbEbsvqWwu") == "O XH Fx LMljv Je Dkalb Ebsvq Wwu"
    assert candidate("OMJRkXpfETKpHWIrHOdvlcolxMIz") == "O MJ Rk Xpf ET Kp HW Ir HOdvlcolx MIz"
    assert candidate("OYTGJXObomipCVlfRPwHqhRCNEGlzg") == "O YT GJ XObomip CVlf RPw Hqh RC NE Glzg"
    assert candidate("ZUDOumSngETVgiUoiqTxEE") == "Z UD Oum Sng ET Vgi Uoiq Tx EE"
    assert candidate("XmVIJfsAYKTZcbCyYCaTyxVyCWbDb") == "Xm VI Jfs AY KT Zcb Cy YCa Tyx Vy CWb Db"
    assert candidate("UJSLkYCJFlvaFhJJXiHCPyKlUwQ") == "U JS Lk YC JFlva Fh JJ Xi HC Py Kl Uw Q"
    assert candidate("PjUszqopkMYESFMZfyCrpxBsKqoq") == "Pj Uszqopk MY ES FM Zfy Crpx Bs Kqoq"
    assert candidate("WAMQMDTTCLCpsIhTIeBkGlyZVHt") == "W AM QM DT TC LCps Ih TIe Bk Gly ZV Ht"
    assert candidate("YCbfAANoCaztlScKOAvxmc") == "Y Cbf AA No Caztl Sc KO Avxmc"
    assert candidate("CLJfQbLcKXcXkeJhyRVv") == "C LJf Qb Lc KXc Xke Jhy RVv"
    assert candidate("yViLBjfRAPUaYIKLqKxtX") == "y Vi LBjf RA PUa YI KLq Kxt X"
    assert candidate("tznarJzkZIQFEaqUvAJ") == "tznar Jzk ZI QF Eaq Uv AJ"
    assert candidate("cIpIJoJFRPuJVMMslxA") == "c Ip IJo JF RPu JV MMslx A"
    assert candidate("DjxMzWcKimOHOBoOKXahMRTosZ") == "Djx Mz Wc Kim OH OBo OK Xah MR Tos Z"
    assert candidate("puGUUGWpKjQcWQlsjogZTagboBC") == "pu GU UG Wp Kj Qc WQlsjog ZTagbo BC"
    assert candidate("OujjWmieveUdEyzbxvNzMM") == "Oujj Wmieve Ud Eyzbxv Nz MM"
    assert candidate("NmwRalFBJwjAJGUBNyheyTZBHr") == "Nmw Ral FB Jwj AJ GU BNyhey TZ BHr"
    assert candidate("ZzFNSiskOZlYxrTmPYRlLxN") == "Zz FN Sisk OZl Yxr Tm PY Rl Lx N"
    assert candidate("zLCTuxmwVAaGuXWRvAMes") == "z LC Tuxmw VAa Gu XW Rv AMes"
    assert candidate("bknOKLBbnSqLgnxXxnzyaRJS") == "bkn OK LBbn Sq Lgnx Xxnzya RJ S"
    assert candidate("eGjXmxcPdHiAUGlYrMicnb") == "e Gj Xmxc Pd Hi AU Gl Yr Micnb"
    assert candidate("qWNpbyWyRPAbgliXWP") == "q WNpby Wy RP Abgli XW P"
    assert candidate("wGGwYZsgUosiJjAEiOV") == "w GGw YZsg Uosi Jj AEi OV"
    assert candidate("iTXObQYesDdgvMmaKyVxu") == "i TX Ob QYes Ddgv Mma Ky Vxu"
    assert candidate("sAsnWaJjEvkQsOLVrgCD") == "s Asn Wa Jj Evk Qs OL Vrg CD"
    assert candidate("FLmuilQckpObaAMZmqKbWXzguat") == "F Lmuil Qckp Oba AM Zmq Kb WXzguat"
    assert candidate("uNLcbVlYsDZrPYRhVKyRy") == "u NLcb Vl Ys DZr PY Rh VKy Ry"
    assert candidate("YWppNiSGqGhZVVFhfqS") == "Y Wpp Ni SGq Gh ZV VFhfq S"
    assert candidate("sLFWlzXvwpSZqlLLFurSeOBlYg") == "s LF Wlz Xvwp SZql LL Fur Se OBl Yg"
    assert candidate("rZuinVDZWFYrVKoTrLyMP") == "r Zuin VD ZW FYr VKo Tr Ly MP"
    assert candidate("hnrBczEzekVMhmAQrnRI") == "hnr Bcz Ezek VMhm AQrn RI"
    assert candidate("LCfFBdTpGAqsVZBJDi") == "L Cf FBd Tp GAqs VZ BJ Di"
    assert candidate("wsNSXCYJpPMSzkmgZdRYsRbp") == "ws NS XC YJp PM Szkmg Zd RYs Rbp"
    assert candidate("dOdDZoTDDuSoaDJPkj") == "d Od DZo TD Du Soa DJ Pkj"
    assert candidate("uEucuotLGFKyJASsNMVFA") == "u Eucuot LG FKy JA Ss NM VF A"
    assert candidate("HDRoupsaRzhdaSuAtxHOqBVXh") == "H DRoupsa Rzhda Su Atx HOq BV Xh"
    assert candidate("jupHcQvzkMbhbsSToQiOyghWaX") == "jup Hc Qvzk Mbhbs STo Qi Oygh Wa X"
    assert candidate("isMHaALrrweaQynwLOOFNbpMpm") == "is MHa ALrrwea Qynw LO OF Nbp Mpm"
    assert candidate("rBoWKSnqtRXqjACRDFXwcupTyx") == "r Bo WK Snqt RXqj AC RD FXwcup Tyx"
    assert candidate("jBJtoJLDMlxySGREVOgmEIf") == "j BJto JL DMlxy SG RE VOgm EIf"
    assert candidate("IVLeWrUoATPynvjVajWytFgVX") == "I VLe Wr Uo AT Pynvj Vaj Wyt Fg VX"
    assert candidate("RYJxkvVUkefDyfpUwWaIYgNH") == "R YJxkv VUkef Dyfp Uw Wa IYg NH"

if __name__ == '__main__':
    check(capital_words_spaces)