from case_MBPP_043 import closest_num


def check(candidate):
    assert candidate(11) == 10
    assert candidate(7) == 6
    assert candidate(12) == 11
    assert candidate(8) == 7
    assert candidate(10) == 9
    assert candidate(16) == 15
    assert candidate(12) == 11
    assert candidate(16) == 15
    assert candidate(7) == 6
    assert candidate(7) == 6
    assert candidate(15) == 14
    assert candidate(12) == 11
    assert candidate(14) == 13
    assert candidate(9) == 8
    assert candidate(16) == 15
    assert candidate(15) == 14
    assert candidate(15) == 14
    assert candidate(14) == 13
    assert candidate(16) == 15
    assert candidate(9) == 8
    assert candidate(9) == 8
    assert candidate(16) == 15
    assert candidate(13) == 12
    assert candidate(6) == 5
    assert candidate(12) == 11
    assert candidate(15) == 14
    assert candidate(10) == 9
    assert candidate(7) == 6
    assert candidate(6) == 5
    assert candidate(14) == 13
    assert candidate(13) == 12
    assert candidate(14) == 13
    assert candidate(11) == 10
    assert candidate(9) == 8
    assert candidate(8) == 7
    assert candidate(14) == 13
    assert candidate(2) == 1
    assert candidate(8) == 7
    assert candidate(3) == 2
    assert candidate(5) == 4
    assert candidate(6) == 5
    assert candidate(9) == 8
    assert candidate(7) == 6
    assert candidate(6) == 5
    assert candidate(10) == 9
    assert candidate(7) == 6
    assert candidate(5) == 4
    assert candidate(12) == 11
    assert candidate(6) == 5
    assert candidate(8) == 7
    assert candidate(2) == 1
    assert candidate(12) == 11
    assert candidate(4) == 3
    assert candidate(11) == 10
    assert candidate(10) == 9
    assert candidate(3) == 2
    assert candidate(3) == 2
    assert candidate(8) == 7
    assert candidate(6) == 5
    assert candidate(10) == 9
    assert candidate(9) == 8
    assert candidate(8) == 7
    assert candidate(7) == 6
    assert candidate(10) == 9
    assert candidate(8) == 7
    assert candidate(11) == 10
    assert candidate(7) == 6
    assert candidate(11) == 10
    assert candidate(10) == 9
    assert candidate(10) == 9
    assert candidate(8) == 7
    assert candidate(12) == 11
    assert candidate(17) == 16
    assert candidate(16) == 15
    assert candidate(7) == 6
    assert candidate(14) == 13
    assert candidate(12) == 11
    assert candidate(12) == 11
    assert candidate(17) == 16
    assert candidate(9) == 8
    assert candidate(10) == 9
    assert candidate(9) == 8
    assert candidate(8) == 7
    assert candidate(17) == 16
    assert candidate(14) == 13
    assert candidate(17) == 16
    assert candidate(8) == 7
    assert candidate(13) == 12
    assert candidate(14) == 13
    assert candidate(8) == 7
    assert candidate(8) == 7
    assert candidate(11) == 10
    assert candidate(13) == 12
    assert candidate(13) == 12
    assert candidate(17) == 16
    assert candidate(16) == 15
    assert candidate(7) == 6
    assert candidate(15) == 14
    assert candidate(12) == 11
    assert candidate(13) == 12
    assert candidate(12) == 11
    assert candidate(7) == 6

if __name__ == '__main__':
    check(closest_num)