from case_MBPP_374 import jacobsthal_num


def check(candidate):
    assert candidate(5) == 11
    assert candidate(2) == 1
    assert candidate(4) == 5
    assert candidate(8) == 85
    assert candidate(9) == 171
    assert candidate(7) == 43
    assert candidate(5) == 11
    assert candidate(8) == 85
    assert candidate(2) == 1
    assert candidate(9) == 171
    assert candidate(4) == 5
    assert candidate(5) == 11
    assert candidate(5) == 11
    assert candidate(8) == 85
    assert candidate(8) == 85
    assert candidate(6) == 21
    assert candidate(5) == 11
    assert candidate(6) == 21
    assert candidate(7) == 43
    assert candidate(10) == 341
    assert candidate(8) == 85
    assert candidate(6) == 21
    assert candidate(8) == 85
    assert candidate(7) == 43
    assert candidate(5) == 11
    assert candidate(1) == 1
    assert candidate(8) == 85
    assert candidate(2) == 1
    assert candidate(2) == 1
    assert candidate(9) == 171
    assert candidate(7) == 43
    assert candidate(8) == 85
    assert candidate(2) == 1
    assert candidate(10) == 341
    assert candidate(4) == 5
    assert candidate(7) == 43
    assert candidate(2) == 1
    assert candidate(6) == 21
    assert candidate(7) == 43
    assert candidate(4) == 5
    assert candidate(4) == 5
    assert candidate(4) == 5
    assert candidate(6) == 21
    assert candidate(5) == 11
    assert candidate(6) == 21
    assert candidate(1) == 1
    assert candidate(3) == 3
    assert candidate(5) == 11
    assert candidate(3) == 3
    assert candidate(3) == 3
    assert candidate(6) == 21
    assert candidate(2) == 1
    assert candidate(6) == 21
    assert candidate(1) == 1
    assert candidate(4) == 5
    assert candidate(4) == 5
    assert candidate(5) == 11
    assert candidate(2) == 1
    assert candidate(2) == 1
    assert candidate(1) == 1
    assert candidate(4) == 5
    assert candidate(6) == 21
    assert candidate(6) == 21
    assert candidate(7) == 43
    assert candidate(2) == 1
    assert candidate(6) == 21
    assert candidate(4) == 5
    assert candidate(7) == 43
    assert candidate(6) == 21
    assert candidate(1) == 1
    assert candidate(9) == 171
    assert candidate(7) == 43
    assert candidate(7) == 43
    assert candidate(1) == 1
    assert candidate(7) == 43
    assert candidate(8) == 85
    assert candidate(5) == 11
    assert candidate(6) == 21
    assert candidate(4) == 5
    assert candidate(3) == 3
    assert candidate(7) == 43
    assert candidate(4) == 5
    assert candidate(3) == 3
    assert candidate(4) == 5
    assert candidate(2) == 1
    assert candidate(3) == 3
    assert candidate(2) == 1
    assert candidate(6) == 21
    assert candidate(5) == 11
    assert candidate(1) == 1
    assert candidate(5) == 11
    assert candidate(8) == 85
    assert candidate(6) == 21
    assert candidate(5) == 11
    assert candidate(4) == 5
    assert candidate(2) == 1
    assert candidate(1) == 1
    assert candidate(9) == 171
    assert candidate(3) == 3
    assert candidate(1) == 1
    assert candidate(5) == 11
    assert candidate(1) == 1

if __name__ == '__main__':
    check(jacobsthal_num)