from case_MBPP_187 import first_non_repeating_character


def check(candidate):
    assert candidate("abcabc") == None
    assert candidate("abc") == "a"
    assert candidate("ababc") == "c"
    assert candidate("lvbkblwbzvm") == "k"
    assert candidate("bojlxknd") == "b"
    assert candidate("ynzxn") == "y"
    assert candidate("qdtx") == "q"
    assert candidate("vrcd") == "v"
    assert candidate("fthejmrwcgf") == "t"
    assert candidate("xnwghagriwbc") == "x"
    assert candidate("qlhidwxc") == "q"
    assert candidate("sdm") == "s"
    assert candidate("zeoa") == "z"
    assert candidate("jvmqjwhlp") == "v"
    assert candidate("juo") == j
    assert candidate("dccbzted") == "b"
    assert candidate("zwyxqoirj") == "z"
    assert candidate("azheziswlzk") == "a"
    assert candidate("zbibcuw") == "z"
    assert candidate("lmq") == "l"
    assert candidate("hwd") == "h"
    assert candidate("vxazudpp") == "v"
    assert candidate("fehvotmmnvvx") == f
    assert candidate("ftwamp") == f
    assert candidate("mjl") == "m"
    assert candidate("jqmg") == j
    assert candidate("aplo") == "a"
    assert candidate("wrp") == "w"
    assert candidate("ycaimusvf") == "y"
    assert candidate("iycaohglbt") == i
    assert candidate("vuetk") == "v"
    assert candidate("hglttyrsbz") == "h"
    assert candidate("zuondj") == "z"
    assert candidate("anovx") == "a"
    assert candidate("wsvudggvb") == "w"
    assert candidate("jejqsrosa") == "e"
    assert candidate("dyzsbvr") == "d"
    assert candidate("kbjmtwd") == "k"
    assert candidate("iwfgna") == i
    assert candidate("rdco") == "r"
    assert candidate("onjzhm") == "o"
    assert candidate("pmxwhk") == "p"
    assert candidate("bgbw") == "g"
    assert candidate("idruvo") == i
    assert candidate("zfaoan") == "z"
    assert candidate("xcgom") == "x"
    assert candidate("wicji") == "w"
    assert candidate("zlq") == "z"
    assert candidate("jhzf") == j
    assert candidate("koouixoan") == "k"
    assert candidate("ebgavyab") == "e"
    assert candidate("jncau") == j
    assert candidate("chfmbe") == "c"
    assert candidate("ofcrh") == "o"
    assert candidate("gmqsha") == "g"
    assert candidate("qczrolpvp") == "q"
    assert candidate("zhpupq") == "z"
    assert candidate("xwthzd") == "x"
    assert candidate("qjtvt") == "q"
    assert candidate("qtugswye") == "q"
    assert candidate("utzya") == "u"
    assert candidate("mrkl") == "m"
    assert candidate("iaeczpnsi") == "a"
    assert candidate("evl") == "e"
    assert candidate("motlfnggf") == "m"
    assert candidate("emnx") == "e"
    assert candidate("ulthvztw") == "u"
    assert candidate("ltgkuwgqp") == "l"
    assert candidate("ffska") == "s"
    assert candidate("emtg") == "e"
    assert candidate("tqrbyigr") == "t"
    assert candidate("vvd") == "d"
    assert candidate("ydijb") == "y"
    assert candidate("bnprekbdc") == "n"
    assert candidate("ehazrnbm") == "e"
    assert candidate("htw") == "h"
    assert candidate("wjp") == "w"
    assert candidate("tauennh") == "t"
    assert candidate("ktbph") == "k"
    assert candidate("fko") == f
    assert candidate("ngiulgg") == "n"
    assert candidate("vwo") == "v"
    assert candidate("kisshrfjr") == "k"
    assert candidate("rdtdf") == "r"
    assert candidate("zxno") == "z"
    assert candidate("atlh") == "a"
    assert candidate("huicml") == "h"
    assert candidate("uwnvioc") == "u"
    assert candidate("ieubrdsf") == i
    assert candidate("vbryggyrr") == "v"
    assert candidate("ixlzxgb") == i
    assert candidate("mkepobqw") == "m"
    assert candidate("jnybhzqos") == j
    assert candidate("fka") == f
    assert candidate("fgvdcntzt") == f
    assert candidate("xphq") == "x"
    assert candidate("ysz") == "y"
    assert candidate("rdnpkqtzf") == "r"
    assert candidate("lzqrc") == "l"
    assert candidate("mcehozioe") == "m"
    assert candidate("mbpoe") == "m"
    assert candidate("uiqnvtjtr") == "u"

if __name__ == '__main__':
    check(first_non_repeating_character)