from case_MBPP_309 import reverse_words


def check(candidate):
    assert candidate("python program")==("program python")
    assert candidate("java language")==("language java")
    assert candidate("indian man")==("man indian")
    assert candidate("fnnbmvozts") == "fnnbmvozts"
    assert candidate("sejcdabrvt") == "sejcdabrvt"
    assert candidate("qpkqvadcvhc") == "qpkqvadcvhc"
    assert candidate("vaxsknszy pgml") == "pgml vaxsknszy"
    assert candidate("f szliexhefq") == "szliexhefq f"
    assert candidate("ukhlzcafyfgj") == "ukhlzcafyfgj"
    assert candidate("pvigsmligdlcjzli") == "pvigsmligdlcjzli"
    assert candidate("upruhewlweg") == "upruhewlweg"
    assert candidate("mxnw bhalertz") == "bhalertz mxnw"
    assert candidate("kxstlqnpa") == "kxstlqnpa"
    assert candidate("ozzumsbgtkgw") == "ozzumsbgtkgw"
    assert candidate("eoigfkrcaxnbt") == "eoigfkrcaxnbt"
    assert candidate("edlowruqtzpohzzclc") == "edlowruqtzpohzzclc"
    assert candidate("nqtqhruskawysy") == "nqtqhruskawysy"
    assert candidate("qcklemcre") == "qcklemcre"
    assert candidate("akevcehzqu y qjvta") == "qjvta y akevcehzqu"
    assert candidate("fvqdlobhojcltixse") == "fvqdlobhojcltixse"
    assert candidate("ipxewyfgsbqzoq") == "ipxewyfgsbqzoq"
    assert candidate("ikyoludvrvbyls") == "ikyoludvrvbyls"
    assert candidate("ymdszbuatlrlfrzi") == "ymdszbuatlrlfrzi"
    assert candidate("pppubp lvkyy") == "lvkyy pppubp"
    assert candidate("k ssmvjbfmyscvv") == "ssmvjbfmyscvv k"
    assert candidate("awqwieidbhm ecttw") == "ecttw awqwieidbhm"
    assert candidate("smleeofnbc") == "smleeofnbc"
    assert candidate("ufz symnwtsgjf") == "symnwtsgjf ufz"
    assert candidate("vzzff fihvd") == "fihvd vzzff"
    assert candidate(" dryqvdsozivivs") == "dryqvdsozivivs"
    assert candidate("klllodvmhub pkmq") == "pkmq klllodvmhub"
    assert candidate(" zudodfiv") == "zudodfiv"
    assert candidate("rymqrdcom") == "rymqrdcom"
    assert candidate("mzrnzllaqv") == "mzrnzllaqv"
    assert candidate("wma rhjbliqkgx ") == "rhjbliqkgx wma"
    assert candidate("zqzxryzjvtzpful") == "zqzxryzjvtzpful"
    assert candidate("phketbbfzz") == "phketbbfzz"
    assert candidate("scumjgzltqek") == "scumjgzltqek"
    assert candidate("hicmhpfw rdu") == "rdu hicmhpfw"
    assert candidate("wlqazpa rktbvwcmqy") == "rktbvwcmqy wlqazpa"
    assert candidate("vk eqpi tohlkx") == "tohlkx eqpi vk"
    assert candidate("ugoopmipd") == "ugoopmipd"
    assert candidate("pyqavfiidishmm") == "pyqavfiidishmm"
    assert candidate("gzwfjcsbwytiaffqi") == "gzwfjcsbwytiaffqi"
    assert candidate("whnwkhncwnkn ah") == "ah whnwkhncwnkn"
    assert candidate("yezixcxjjvhyzcmap") == "yezixcxjjvhyzcmap"
    assert candidate("xrubuzwxb") == "xrubuzwxb"
    assert candidate("dbvbhdvkfd xcmbhsn") == "xcmbhsn dbvbhdvkfd"
    assert candidate("yabtwgdyh") == "yabtwgdyh"
    assert candidate("mltbomxtzgskjap") == "mltbomxtzgskjap"
    assert candidate("neuvkgspdhvfbwibgx") == "neuvkgspdhvfbwibgx"
    assert candidate("hjkibplpl lh") == "lh hjkibplpl"
    assert candidate("klw heawqebbs") == "heawqebbs klw"
    assert candidate("acebaypfpclaww n") == "n acebaypfpclaww"
    assert candidate("wjryh vzdepwfurk") == "vzdepwfurk wjryh"
    assert candidate("opksvjhajs") == "opksvjhajs"
    assert candidate(" svuvnxywxfuka") == "svuvnxywxfuka"
    assert candidate("nyychslhmdphbo fgm") == "fgm nyychslhmdphbo"
    assert candidate("oq nkfxifunfjckvtb") == "nkfxifunfjckvtb oq"
    assert candidate("f xggbujzjopki") == "xggbujzjopki f"
    assert candidate("opkhu ddutcjurvvxc") == "ddutcjurvvxc opkhu"
    assert candidate("mfrlawoogamtpzp") == "mfrlawoogamtpzp"
    assert candidate(" dxccdrdugzkbjdnew") == "dxccdrdugzkbjdnew"
    assert candidate("ndkszygjsm") == "ndkszygjsm"
    assert candidate("fakptggdd") == "fakptggdd"
    assert candidate("dlwjimyva") == "dlwjimyva"
    assert candidate("smegeoih ") == "smegeoih"
    assert candidate("sb jluzcaxvopdn") == "jluzcaxvopdn sb"
    assert candidate("fwfkncpxa") == "fwfkncpxa"
    assert candidate(" fdmkznhyjyxsa") == "fdmkznhyjyxsa"
    assert candidate("vjpseribiei") == "vjpseribiei"
    assert candidate("deyuluumyqefez") == "deyuluumyqefez"
    assert candidate("plqjcyyvkntmh") == "plqjcyyvkntmh"
    assert candidate("smkkbhegbcnzuik") == "smkkbhegbcnzuik"
    assert candidate("vsqj hb") == "hb vsqj"
    assert candidate("xhgmmcbm") == "xhgmmcbm"
    assert candidate("b jk vex") == "vex jk b"
    assert candidate("xztizrlsojkfw") == "xztizrlsojkfw"
    assert candidate("slnlzdqsrtyujz") == "slnlzdqsrtyujz"
    assert candidate("eyqdhnnhncwecf") == "eyqdhnnhncwecf"
    assert candidate("gqbwbrnanzm") == "gqbwbrnanzm"
    assert candidate("ijtder") == "ijtder"
    assert candidate(" jtifmwmszew") == "jtifmwmszew"
    assert candidate("iqbjyyxh") == "iqbjyyxh"
    assert candidate("kwbg z cyp") == "cyp z kwbg"
    assert candidate("bzacgkeejw") == "bzacgkeejw"
    assert candidate("loeaajmpal") == "loeaajmpal"
    assert candidate("uyqwdzns ") == "uyqwdzns"
    assert candidate("mfmxpmhhjpejbr") == "mfmxpmhhjpejbr"
    assert candidate("el gsuldv") == "gsuldv el"
    assert candidate("tthylld bkufx") == "bkufx tthylld"
    assert candidate("dxybqmmwyeu") == "dxybqmmwyeu"
    assert candidate("istdzigcye") == "istdzigcye"
    assert candidate("vblryhanippgt") == "vblryhanippgt"
    assert candidate("aagatimpnrdr") == "aagatimpnrdr"
    assert candidate("n dwhcrrciaqj") == "dwhcrrciaqj n"
    assert candidate("pkqhabosyqba") == "pkqhabosyqba"
    assert candidate("luhkfsq") == "luhkfsq"
    assert candidate("nlza xtm") == "xtm nlza"
    assert candidate("lekdguw") == "lekdguw"
    assert candidate("cbg fs") == "fs cbg"
    assert candidate("vzdejlp") == "vzdejlp"

if __name__ == '__main__':
    check(reverse_words)