from case_MBPP_014 import is_woodall


def check(candidate):
    assert candidate(383) == True
    assert candidate(254) == False
    assert candidate(200) == False
    assert candidate(381) == False
    assert candidate(379) == False
    assert candidate(388) == False
    assert candidate(382) == False
    assert candidate(385) == False
    assert candidate(387) == False
    assert candidate(387) == False
    assert candidate(387) == False
    assert candidate(385) == False
    assert candidate(384) == False
    assert candidate(379) == False
    assert candidate(384) == False
    assert candidate(382) == False
    assert candidate(380) == False
    assert candidate(388) == False
    assert candidate(386) == False
    assert candidate(378) == False
    assert candidate(383) == True
    assert candidate(384) == False
    assert candidate(385) == False
    assert candidate(381) == False
    assert candidate(378) == False
    assert candidate(386) == False
    assert candidate(387) == False
    assert candidate(381) == False
    assert candidate(384) == False
    assert candidate(387) == False
    assert candidate(381) == False
    assert candidate(385) == False
    assert candidate(384) == False
    assert candidate(378) == False
    assert candidate(386) == False
    assert candidate(387) == False
    assert candidate(253) == False
    assert candidate(259) == False
    assert candidate(255) == False
    assert candidate(251) == False
    assert candidate(251) == False
    assert candidate(252) == False
    assert candidate(249) == False
    assert candidate(255) == False
    assert candidate(255) == False
    assert candidate(259) == False
    assert candidate(254) == False
    assert candidate(250) == False
    assert candidate(257) == False
    assert candidate(257) == False
    assert candidate(250) == False
    assert candidate(259) == False
    assert candidate(254) == False
    assert candidate(256) == False
    assert candidate(258) == False
    assert candidate(250) == False
    assert candidate(251) == False
    assert candidate(256) == False
    assert candidate(252) == False
    assert candidate(255) == False
    assert candidate(249) == False
    assert candidate(252) == False
    assert candidate(255) == False
    assert candidate(249) == False
    assert candidate(249) == False
    assert candidate(252) == False
    assert candidate(256) == False
    assert candidate(250) == False
    assert candidate(249) == False
    assert candidate(195) == False
    assert candidate(203) == False
    assert candidate(198) == False
    assert candidate(204) == False
    assert candidate(202) == False
    assert candidate(195) == False
    assert candidate(201) == False
    assert candidate(198) == False
    assert candidate(205) == False
    assert candidate(200) == False
    assert candidate(201) == False
    assert candidate(199) == False
    assert candidate(204) == False
    assert candidate(205) == False
    assert candidate(202) == False
    assert candidate(204) == False
    assert candidate(203) == False
    assert candidate(199) == False
    assert candidate(201) == False
    assert candidate(201) == False
    assert candidate(200) == False
    assert candidate(200) == False
    assert candidate(199) == False
    assert candidate(195) == False
    assert candidate(201) == False
    assert candidate(196) == False
    assert candidate(197) == False
    assert candidate(195) == False
    assert candidate(198) == False
    assert candidate(197) == False
    assert candidate(201) == False
    assert candidate(199) == False
    assert candidate(196) == False

if __name__ == '__main__':
    check(is_woodall)