from case_MBPP_206 import group_tuples


def check(candidate):
    assert candidate([('x', 'y'), ('x', 'z'), ('w', 't')]) == [('x', 'y', 'z'), ('w', 't')]
    assert candidate([('a', 'b'), ('a', 'c'), ('d', 'e')]) == [('a', 'b', 'c'), ('d', 'e')]
    assert candidate([('f', 'g'), ('f', 'g'), ('h', 'i')]) == [('f', 'g', 'g'), ('h', 'i')]
    assert candidate([('w', 'u'), ('s', 'v'), ('f', 'r')]) == [('w', 'u'), ('s', 'v'), ('f', 'r')]
    assert candidate([('i', 'y'), ('x', 'e'), ('c', 'v')]) == [('i', 'y'), ('x', 'e'), ('c', 'v')]
    assert candidate([('t', 'b'), ('n', 'a'), ('m', 'e')]) == [('t', 'b'), ('n', 'a'), ('m', 'e')]
    assert candidate([('s', 't'), ('w', 'v'), ('q', 's')]) == [('s', 't'), ('w', 'v'), ('q', 's')]
    assert candidate([('x', 'l'), ('h', 'y'), ('i', 'r')]) == [('x', 'l'), ('h', 'y'), ('i', 'r')]
    assert candidate([('c', 'b'), ('l', 'c'), ('i', 'w')]) == [('c', 'b'), ('l', 'c'), ('i', 'w')]
    assert candidate([('c', 'd'), ('s', 'l'), ('z', 'm')]) == [('c', 'd'), ('s', 'l'), ('z', 'm')]
    assert candidate([('r', 'k'), ('c', 'o'), ('b', 'w')]) == [('r', 'k'), ('c', 'o'), ('b', 'w')]
    assert candidate([('i', 'f'), ('w', 'n'), ('z', 'q')]) == [('i', 'f'), ('w', 'n'), ('z', 'q')]
    assert candidate([('f', 'z'), ('l', 'l'), ('r', 'q')]) == [('f', 'z'), ('l', 'l'), ('r', 'q')]
    assert candidate([('k', 't'), ('c', 'n'), ('b', 'w')]) == [('k', 't'), ('c', 'n'), ('b', 'w')]
    assert candidate([('a', 'z'), ('o', 'w'), ('r', 'v')]) == [('a', 'z'), ('o', 'w'), ('r', 'v')]
    assert candidate([('m', 'r'), ('b', 'o'), ('h', 'k')]) == [('m', 'r'), ('b', 'o'), ('h', 'k')]
    assert candidate([('s', 'j'), ('x', 'r'), ('b', 'i')]) == [('s', 'j'), ('x', 'r'), ('b', 'i')]
    assert candidate([('g', 'h'), ('i', 'd'), ('m', 'o')]) == [('g', 'h'), ('i', 'd'), ('m', 'o')]
    assert candidate([('u', 'h'), ('w', 'k'), ('m', 'r')]) == [('u', 'h'), ('w', 'k'), ('m', 'r')]
    assert candidate([('m', 'b'), ('t', 'v'), ('w', 'i')]) == [('m', 'b'), ('t', 'v'), ('w', 'i')]
    assert candidate([('t', 'q'), ('j', 'c'), ('l', 'y')]) == [('t', 'q'), ('j', 'c'), ('l', 'y')]
    assert candidate([('x', 't'), ('e', 's'), ('b', 'v')]) == [('x', 't'), ('e', 's'), ('b', 'v')]
    assert candidate([('y', 'd'), ('v', 'a'), ('e', 'c')]) == [('y', 'd'), ('v', 'a'), ('e', 'c')]
    assert candidate([('a', 's'), ('o', 'e'), ('m', 'r')]) == [('a', 's'), ('o', 'e'), ('m', 'r')]
    assert candidate([('c', 'r'), ('r', 't'), ('d', 'u')]) == [('c', 'r'), ('r', 't'), ('d', 'u')]
    assert candidate([('v', 'z'), ('h', 'u'), ('x', 'd')]) == [('v', 'z'), ('h', 'u'), ('x', 'd')]
    assert candidate([('v', 't'), ('v', 'm'), ('l', 'q')]) == [('v', 't', 'm'), ('l', 'q')]
    assert candidate([('v', 'l'), ('l', 'w'), ('d', 'b')]) == [('v', 'l'), ('l', 'w'), ('d', 'b')]
    assert candidate([('f', 'd'), ('n', 'h'), ('m', 'n')]) == [('f', 'd'), ('n', 'h'), ('m', 'n')]
    assert candidate([('x', 'a'), ('n', 'v'), ('t', 'j')]) == [('x', 'a'), ('n', 'v'), ('t', 'j')]
    assert candidate([('w', 'c'), ('x', 'e'), ('r', 'v')]) == [('w', 'c'), ('x', 'e'), ('r', 'v')]
    assert candidate([('u', 'r'), ('o', 'v'), ('y', 'n')]) == [('u', 'r'), ('o', 'v'), ('y', 'n')]
    assert candidate([('g', 'p'), ('d', 'm'), ('a', 'd')]) == [('g', 'p'), ('d', 'm'), ('a', 'd')]
    assert candidate([('m', 'm'), ('g', 'e'), ('p', 'f')]) == [('m', 'm'), ('g', 'e'), ('p', 'f')]
    assert candidate([('a', 'c'), ('d', 'e'), ('l', 'n')]) == [('a', 'c'), ('d', 'e'), ('l', 'n')]
    assert candidate([('c', 'g'), ('r', 'p'), ('m', 'x')]) == [('c', 'g'), ('r', 'p'), ('m', 'x')]
    assert candidate([('d', 'r'), ('y', 'v'), ('q', 'b')]) == [('d', 'r'), ('y', 'v'), ('q', 'b')]
    assert candidate([('w', 'j'), ('w', 'o'), ('d', 'e')]) == [('w', 'j', 'o'), ('d', 'e')]
    assert candidate([('x', 's'), ('i', 'w'), ('i', 'f')]) == [('x', 's'), ('i', 'w', 'f')]
    assert candidate([('z', 'o'), ('b', 'b'), ('c', 'b')]) == [('z', 'o'), ('b', 'b'), ('c', 'b')]
    assert candidate([('h', 'd'), ('l', 'e'), ('p', 'y')]) == [('h', 'd'), ('l', 'e'), ('p', 'y')]
    assert candidate([('m', 'u'), ('k', 'b'), ('x', 'v')]) == [('m', 'u'), ('k', 'b'), ('x', 'v')]
    assert candidate([('o', 'd'), ('n', 'n'), ('g', 'o')]) == [('o', 'd'), ('n', 'n'), ('g', 'o')]
    assert candidate([('j', 'o'), ('v', 'q'), ('o', 'p')]) == [('j', 'o'), ('v', 'q'), ('o', 'p')]
    assert candidate([('i', 'a'), ('c', 'e'), ('s', 'j')]) == [('i', 'a'), ('c', 'e'), ('s', 'j')]
    assert candidate([('a', 'i'), ('d', 'u'), ('b', 'o')]) == [('a', 'i'), ('d', 'u'), ('b', 'o')]
    assert candidate([('e', 'g'), ('v', 't'), ('a', 'c')]) == [('e', 'g'), ('v', 't'), ('a', 'c')]
    assert candidate([('e', 'f'), ('w', 'o'), ('u', 'x')]) == [('e', 'f'), ('w', 'o'), ('u', 'x')]
    assert candidate([('n', 'f'), ('k', 'v'), ('i', 'g')]) == [('n', 'f'), ('k', 'v'), ('i', 'g')]
    assert candidate([('u', 'a'), ('q', 'i'), ('o', 'z')]) == [('u', 'a'), ('q', 'i'), ('o', 'z')]
    assert candidate([('l', 'b'), ('u', 'd'), ('n', 'y')]) == [('l', 'b'), ('u', 'd'), ('n', 'y')]
    assert candidate([('l', 'o'), ('w', 'e'), ('s', 'u')]) == [('l', 'o'), ('w', 'e'), ('s', 'u')]
    assert candidate([('h', 'w'), ('u', 't'), ('f', 'k')]) == [('h', 'w'), ('u', 't'), ('f', 'k')]
    assert candidate([('h', 'q'), ('s', 'a'), ('t', 'd')]) == [('h', 'q'), ('s', 'a'), ('t', 'd')]
    assert candidate([('k', 'n'), ('k', 'l'), ('q', 'j')]) == [('k', 'n', 'l'), ('q', 'j')]
    assert candidate([('d', 'e'), ('q', 'q'), ('q', 'l')]) == [('d', 'e'), ('q', 'q', 'l')]
    assert candidate([('l', 'r'), ('s', 'p'), ('d', 'l')]) == [('l', 'r'), ('s', 'p'), ('d', 'l')]
    assert candidate([('s', 'v'), ('b', 'w'), ('x', 'm')]) == [('s', 'v'), ('b', 'w'), ('x', 'm')]
    assert candidate([('d', 'd'), ('z', 'g'), ('k', 'm')]) == [('d', 'd'), ('z', 'g'), ('k', 'm')]
    assert candidate([('u', 'g'), ('d', 'v'), ('l', 'o')]) == [('u', 'g'), ('d', 'v'), ('l', 'o')]
    assert candidate([('l', 'd'), ('n', 'b'), ('q', 'x')]) == [('l', 'd'), ('n', 'b'), ('q', 'x')]
    assert candidate([('f', 'e'), ('f', 'z'), ('w', 'g')]) == [('f', 'e', 'z'), ('w', 'g')]
    assert candidate([('r', 'k'), ('z', 'i'), ('v', 'c')]) == [('r', 'k'), ('z', 'i'), ('v', 'c')]
    assert candidate([('a', 'w'), ('v', 'd'), ('w', 'y')]) == [('a', 'w'), ('v', 'd'), ('w', 'y')]
    assert candidate([('m', 'b'), ('j', 'k'), ('s', 'i')]) == [('m', 'b'), ('j', 'k'), ('s', 'i')]
    assert candidate([('v', 'x'), ('n', 'k'), ('a', 'd')]) == [('v', 'x'), ('n', 'k'), ('a', 'd')]
    assert candidate([('p', 'm'), ('v', 'd'), ('i', 'k')]) == [('p', 'm'), ('v', 'd'), ('i', 'k')]
    assert candidate([('y', 'x'), ('y', 'l'), ('p', 'i')]) == [('y', 'x', 'l'), ('p', 'i')]
    assert candidate([('s', 'n'), ('w', 'r'), ('i', 'b')]) == [('s', 'n'), ('w', 'r'), ('i', 'b')]
    assert candidate([('z', 'u'), ('w', 'n'), ('j', 'd')]) == [('z', 'u'), ('w', 'n'), ('j', 'd')]
    assert candidate([('u', 'q'), ('e', 'j'), ('b', 'x')]) == [('u', 'q'), ('e', 'j'), ('b', 'x')]
    assert candidate([('n', 'a'), ('h', 'i'), ('x', 'u')]) == [('n', 'a'), ('h', 'i'), ('x', 'u')]
    assert candidate([('x', 'h'), ('u', 'p'), ('z', 'b')]) == [('x', 'h'), ('u', 'p'), ('z', 'b')]
    assert candidate([('b', 'g'), ('l', 'g'), ('x', 'v')]) == [('b', 'g'), ('l', 'g'), ('x', 'v')]
    assert candidate([('n', 'n'), ('f', 'n'), ('t', 'v')]) == [('n', 'n'), ('f', 'n'), ('t', 'v')]
    assert candidate([('b', 'd'), ('p', 'd'), ('s', 'c')]) == [('b', 'd'), ('p', 'd'), ('s', 'c')]
    assert candidate([('i', 'w'), ('d', 'w'), ('r', 'o')]) == [('i', 'w'), ('d', 'w'), ('r', 'o')]
    assert candidate([('g', 'd'), ('s', 'r'), ('x', 'f')]) == [('g', 'd'), ('s', 'r'), ('x', 'f')]
    assert candidate([('h', 'e'), ('m', 'f'), ('o', 'i')]) == [('h', 'e'), ('m', 'f'), ('o', 'i')]
    assert candidate([('e', 't'), ('o', 'n'), ('a', 'q')]) == [('e', 't'), ('o', 'n'), ('a', 'q')]
    assert candidate([('b', 'y'), ('j', 'f'), ('b', 'a')]) == [('b', 'y', 'a'), ('j', 'f')]
    assert candidate([('m', 'x'), ('l', 'y'), ('a', 'o')]) == [('m', 'x'), ('l', 'y'), ('a', 'o')]
    assert candidate([('n', 't'), ('h', 'o'), ('n', 'f')]) == [('n', 't', 'f'), ('h', 'o')]
    assert candidate([('p', 'd'), ('k', 'a'), ('n', 'm')]) == [('p', 'd'), ('k', 'a'), ('n', 'm')]
    assert candidate([('j', 's'), ('l', 'f'), ('s', 'r')]) == [('j', 's'), ('l', 'f'), ('s', 'r')]
    assert candidate([('p', 'q'), ('b', 'z'), ('g', 'h')]) == [('p', 'q'), ('b', 'z'), ('g', 'h')]
    assert candidate([('t', 'w'), ('x', 'e'), ('o', 'r')]) == [('t', 'w'), ('x', 'e'), ('o', 'r')]
    assert candidate([('h', 'e'), ('n', 'o'), ('j', 'h')]) == [('h', 'e'), ('n', 'o'), ('j', 'h')]
    assert candidate([('c', 'o'), ('x', 'a'), ('e', 'p')]) == [('c', 'o'), ('x', 'a'), ('e', 'p')]
    assert candidate([('h', 'h'), ('r', 'n'), ('a', 'd')]) == [('h', 'h'), ('r', 'n'), ('a', 'd')]
    assert candidate([('e', 'y'), ('l', 'n'), ('j', 'r')]) == [('e', 'y'), ('l', 'n'), ('j', 'r')]
    assert candidate([('m', 'l'), ('a', 'z'), ('o', 'm')]) == [('m', 'l'), ('a', 'z'), ('o', 'm')]
    assert candidate([('d', 'i'), ('m', 'p'), ('j', 'h')]) == [('d', 'i'), ('m', 'p'), ('j', 'h')]
    assert candidate([('y', 'o'), ('u', 'y'), ('m', 'k')]) == [('y', 'o'), ('u', 'y'), ('m', 'k')]
    assert candidate([('s', 'i'), ('g', 'm'), ('i', 'j')]) == [('s', 'i'), ('g', 'm'), ('i', 'j')]
    assert candidate([('t', 'u'), ('u', 'e'), ('z', 'l')]) == [('t', 'u'), ('u', 'e'), ('z', 'l')]
    assert candidate([('l', 'u'), ('k', 'i'), ('a', 'n')]) == [('l', 'u'), ('k', 'i'), ('a', 'n')]
    assert candidate([('l', 'j'), ('i', 's'), ('t', 'b')]) == [('l', 'j'), ('i', 's'), ('t', 'b')]
    assert candidate([('g', 'u'), ('m', 'x'), ('v', 'd')]) == [('g', 'u'), ('m', 'x'), ('v', 'd')]
    assert candidate([('f', 'y'), ('p', 'k'), ('k', 'd')]) == [('f', 'y'), ('p', 'k'), ('k', 'd')]
    assert candidate([('s', 'q'), ('j', 'h'), ('p', 'c')]) == [('s', 'q'), ('j', 'h'), ('p', 'c')]
    assert candidate([('u', 'b'), ('u', 'f'), ('n', 'i')]) == [('u', 'b', 'f'), ('n', 'i')]

if __name__ == '__main__':
    check(group_tuples)