from case_MBPP_116 import number_of_substrings


def check(candidate):
    assert candidate("abc") == 6
    assert candidate("abcd") == 10
    assert candidate("abcde") == 15
    assert candidate("adou") == 10
    assert candidate("caqo") == 10
    assert candidate("zsbgso") == 21
    assert candidate("vizyxnw") == 28
    assert candidate("wnmg") == 10
    assert candidate("iecmba") == 21
    assert candidate("alqos") == 15
    assert candidate("sxpwac") == 21
    assert candidate("ccheuce") == 28
    assert candidate("pwffxwzzv") == 45
    assert candidate("xzrd") == 10
    assert candidate("kbdjc") == 15
    assert candidate("utomxn") == 21
    assert candidate("bmy") == 6
    assert candidate("corybr") == 21
    assert candidate("kpxyhijn") == 36
    assert candidate("nkfdb") == 15
    assert candidate("wehleaayd") == 45
    assert candidate("hrawqihk") == 36
    assert candidate("kkb") == 6
    assert candidate("hjgh") == 10
    assert candidate("lmrzh") == 15
    assert candidate("ttcexzgqs") == 45
    assert candidate("anwrxa") == 21
    assert candidate("isizcmv") == 28
    assert candidate("yjf") == 6
    assert candidate("cewdnocy") == 36
    assert candidate("qdv") == 6
    assert candidate("hurqt") == 15
    assert candidate("xdalp") == 15
    assert candidate("nsnptggbo") == 45
    assert candidate("krty") == 10
    assert candidate("ogt") == 6
    assert candidate("rxtig") == 15
    assert candidate("jbornjuba") == 45
    assert candidate("dtwpit") == 21
    assert candidate("bpxh") == 10
    assert candidate("iatzbwtwf") == 45
    assert candidate("cyfazw") == 21
    assert candidate("azrxdgebo") == 45
    assert candidate("pcbm") == 10
    assert candidate("luv") == 6
    assert candidate("ldqspjrql") == 45
    assert candidate("eqnauql") == 28
    assert candidate("dicroev") == 28
    assert candidate("jmclfajqj") == 45
    assert candidate("rttimi") == 21
    assert candidate("vlrap") == 15
    assert candidate("vurxalrcb") == 45
    assert candidate("jio") == 6
    assert candidate("fyh") == 6
    assert candidate("baju") == 10
    assert candidate("cyymawaf") == 36
    assert candidate("gthu") == 10
    assert candidate("yat") == 6
    assert candidate("oras") == 10
    assert candidate("iutosomxt") == 45
    assert candidate("xsf") == 6
    assert candidate("pnasjdnhi") == 45
    assert candidate("trcyvqwu") == 36
    assert candidate("teeoc") == 15
    assert candidate("kcqntdpv") == 36
    assert candidate("emyskoe") == 28
    assert candidate("sfksgiptr") == 45
    assert candidate("pdtlpx") == 21
    assert candidate("qcq") == 6
    assert candidate("sfvo") == 10
    assert candidate("uvrqmlnwc") == 45
    assert candidate("nhrn") == 10
    assert candidate("onondgkwq") == 45
    assert candidate("htj") == 6
    assert candidate("xcyvpqivu") == 45
    assert candidate("gmk") == 6
    assert candidate("hbxjcb") == 21
    assert candidate("abmtxw") == 21
    assert candidate("cwgpdkw") == 28
    assert candidate("ucsbznn") == 28
    assert candidate("nwe") == 6
    assert candidate("uwwfbeaay") == 45
    assert candidate("hoixzuj") == 28
    assert candidate("xpnskmvq") == 36
    assert candidate("rglnwdg") == 28
    assert candidate("lrtnun") == 21
    assert candidate("nchhfl") == 21
    assert candidate("yhyjagiqz") == 45
    assert candidate("ysw") == 6
    assert candidate("tztxwmgcx") == 45
    assert candidate("ytfnwcmze") == 45
    assert candidate("tusnpgv") == 28
    assert candidate("rrdnt") == 15
    assert candidate("uyjvsujt") == 36
    assert candidate("tgqkatpb") == 36
    assert candidate("awfvwtkq") == 36
    assert candidate("gqdtodbl") == 36
    assert candidate("xzhay") == 15
    assert candidate("pqaby") == 15
    assert candidate("jtzt") == 10
    assert candidate("hlg") == 6
    assert candidate("gjjj") == 10

if __name__ == '__main__':
    check(number_of_substrings)