from case_MBPP_375 import min_k


def check(candidate):
    assert candidate([('Manjeet', 10), ('Akshat', 4), ('Akash', 2), ('Nikhil', 8)], 2) == [('Akash', 2), ('Akshat', 4)]
    assert candidate([('Sanjeev', 11), ('Angat', 5), ('Akash', 3), ('Nepin', 9)], 3) == [('Akash', 3), ('Angat', 5), ('Nepin', 9)]
    assert candidate([('tanmay', 14), ('Amer', 11), ('Ayesha', 9), ('SKD', 16)], 1) == [('Ayesha', 9)]
    assert candidate([('RbIyTB', 7), ('afQBBtcAunI', 5), ('sSx', 7), ('iDVqlJvlL', 5)], 2) == [('afQBBtcAunI', 5), ('iDVqlJvlL', 5)]
    assert candidate([('KcGgI', 5), ('JjlvhisJZ', 2), ('ErxKt', 5), ('wjo', 4)], 1) == [('JjlvhisJZ', 2)]
    assert candidate([('TVNUTs', 14), ('yqMSpMJ', 9), ('zbqyGgf', 4), ('HGoxBS', 5)], 3) == [('zbqyGgf', 4), ('HGoxBS', 5), ('yqMSpMJ', 9)]
    assert candidate([('NKtmwkpgknNf', 10), ('AlKioD', 7), ('QjX', 2), ('SnwkbmaSGr', 3)], 2) == [('QjX', 2), ('SnwkbmaSGr', 3)]
    assert candidate([('pqQpNnTLpxK', 8), ('ziLwmxgT', 5), ('InZG', 6), ('iiNEYeeodmw', 13)], 1) == [('ziLwmxgT', 5)]
    assert candidate([('IkzAHAMMOsfQ', 7), ('CqqPoohYqAh', 7), ('SSDKwj', 4), ('wTEjEnmwPt', 8)], 6) == [('SSDKwj', 4), ('IkzAHAMMOsfQ', 7), ('CqqPoohYqAh', 7), ('wTEjEnmwPt', 8)]
    assert candidate([('svX', 8), ('iXOhkxlmttI', 3), ('RvOHtVeo', 3), ('OlykPqR', 10)], 5) == [('iXOhkxlmttI', 3), ('RvOHtVeo', 3), ('svX', 8), ('OlykPqR', 10)]
    assert candidate([('ygsQuEh', 7), ('dyeGqrhXjGij', 3), ('WTLB', 4), ('lRyjP', 12)], 6) == [('dyeGqrhXjGij', 3), ('WTLB', 4), ('ygsQuEh', 7), ('lRyjP', 12)]
    assert candidate([('IsnE', 12), ('AcUSgTArhaQx', 3), ('gLtErwYkp', 6), ('dlVXb', 10)], 3) == [('AcUSgTArhaQx', 3), ('gLtErwYkp', 6), ('dlVXb', 10)]
    assert candidate([('nehvDW', 9), ('QzXTYtIAa', 8), ('VFotMmAvj', 7), ('uVLvNPaxOrRl', 9)], 5) == [('VFotMmAvj', 7), ('QzXTYtIAa', 8), ('nehvDW', 9), ('uVLvNPaxOrRl', 9)]
    assert candidate([('qFBiCHdKny', 14), ('zdkUbY', 2), ('UWzOAJrgp', 1), ('lNQySDW', 10)], 7) == [('UWzOAJrgp', 1), ('zdkUbY', 2), ('lNQySDW', 10), ('qFBiCHdKny', 14)]
    assert candidate([('oOys', 14), ('dBcwkDXwvUcE', 8), ('xolIbPUR', 7), ('pmIRmfG', 6)], 3) == [('pmIRmfG', 6), ('xolIbPUR', 7), ('dBcwkDXwvUcE', 8)]
    assert candidate([('QgPX', 9), ('bBFtMb', 1), ('iVbBoBJ', 7), ('KRmZS', 9)], 4) == [('bBFtMb', 1), ('iVbBoBJ', 7), ('QgPX', 9), ('KRmZS', 9)]
    assert candidate([('RczfioETzzbY', 6), ('gFMhCybPt', 9), ('FbrKWSA', 5), ('HIwjLIr', 9)], 2) == [('FbrKWSA', 5), ('RczfioETzzbY', 6)]
    assert candidate([('tcUYsVEH', 14), ('pWWoXjvR', 4), ('UNm', 3), ('JBEW', 12)], 3) == [('UNm', 3), ('pWWoXjvR', 4), ('JBEW', 12)]
    assert candidate([('Fsa', 5), ('gGq', 9), ('bhWLD', 6), ('odW', 6)], 3) == [('Fsa', 5), ('bhWLD', 6), ('odW', 6)]
    assert candidate([('dYHCMtDRkHty', 11), ('buyh', 3), ('spi', 2), ('ChJwbevL', 10)], 5) == [('spi', 2), ('buyh', 3), ('ChJwbevL', 10), ('dYHCMtDRkHty', 11)]
    assert candidate([('MJNEKLdb', 5), ('cjQT', 8), ('YDMTNet', 1), ('tuVnFFfvF', 7)], 6) == [('YDMTNet', 1), ('MJNEKLdb', 5), ('tuVnFFfvF', 7), ('cjQT', 8)]
    assert candidate([('YZDNO', 12), ('YNZLjietHF', 8), ('BKSdtocIv', 3), ('ePKMYjBiLz', 8)], 1) == [('BKSdtocIv', 3)]
    assert candidate([('hVzqFMajYwqc', 11), ('ThSWkINSzyez', 2), ('NEdbqt', 6), ('CaeeU', 13)], 3) == [('ThSWkINSzyez', 2), ('NEdbqt', 6), ('hVzqFMajYwqc', 11)]
    assert candidate([('WYtVvoTHMl', 14), ('zWVFHCezs', 2), ('dGjkHzwD', 3), ('rpOLnzicQ', 8)], 3) == [('zWVFHCezs', 2), ('dGjkHzwD', 3), ('rpOLnzicQ', 8)]
    assert candidate([('JNuW', 15), ('soeYGonagVZo', 2), ('AIWNGQzS', 2), ('xxSuHyUj', 13)], 1) == [('soeYGonagVZo', 2)]
    assert candidate([('vtGJfukspqJU', 7), ('QtxgZDGpEDdP', 3), ('aVTpwN', 6), ('OUJhGgyVG', 11)], 6) == [('QtxgZDGpEDdP', 3), ('aVTpwN', 6), ('vtGJfukspqJU', 7), ('OUJhGgyVG', 11)]
    assert candidate([('muvmfis', 8), ('PnXqocesMsd', 8), ('sBHQiw', 4), ('jkmzdo', 9)], 5) == [('sBHQiw', 4), ('muvmfis', 8), ('PnXqocesMsd', 8), ('jkmzdo', 9)]
    assert candidate([('SFpQQOTOhO', 11), ('fYJrPty', 8), ('KmbGyMmI', 6), ('wkyKNU', 6)], 6) == [('KmbGyMmI', 6), ('wkyKNU', 6), ('fYJrPty', 8), ('SFpQQOTOhO', 11)]
    assert candidate([('IfKMBMFN', 6), ('lBu', 5), ('SRThvT', 5), ('sDMTvvchDxh', 4)], 6) == [('sDMTvvchDxh', 4), ('lBu', 5), ('SRThvT', 5), ('IfKMBMFN', 6)]
    assert candidate([('xVBNkvA', 13), ('rGxpSEbPCSW', 5), ('TbWF', 5), ('QEp', 5)], 4) == [('rGxpSEbPCSW', 5), ('TbWF', 5), ('QEp', 5), ('xVBNkvA', 13)]
    assert candidate([('DzFKxmpXEM', 9), ('MSWIiEzdRHX', 1), ('PLaPL', 3), ('YvsZ', 12)], 6) == [('MSWIiEzdRHX', 1), ('PLaPL', 3), ('DzFKxmpXEM', 9), ('YvsZ', 12)]
    assert candidate([('xHxAujZSd', 10), ('etUP', 7), ('DDOWo', 6), ('zaiXZ', 12)], 4) == [('DDOWo', 6), ('etUP', 7), ('xHxAujZSd', 10), ('zaiXZ', 12)]
    assert candidate([('MoHGEullsph', 9), ('gqmdynAYfpRM', 1), ('icJKPsUTC', 2), ('prpwwf', 3)], 2) == [('gqmdynAYfpRM', 1), ('icJKPsUTC', 2)]
    assert candidate([('ByxvXLxTRbRE', 10), ('acV', 8), ('SQaHr', 7), ('dOahHjX', 11)], 2) == [('SQaHr', 7), ('acV', 8)]
    assert candidate([('BuUNwTGfHLQZ', 11), ('ZMAm', 6), ('rEq', 5), ('wgwZMWmW', 13)], 3) == [('rEq', 5), ('ZMAm', 6), ('BuUNwTGfHLQZ', 11)]
    assert candidate([('XQttCC', 9), ('qtPIpTLejD', 3), ('fIxarTVy', 1), ('sRBAQixwSO', 3)], 5) == [('fIxarTVy', 1), ('qtPIpTLejD', 3), ('sRBAQixwSO', 3), ('XQttCC', 9)]
    assert candidate([('Dphr', 15), ('oHCRljs', 4), ('UMOUgPc', 7), ('HQZjyU', 13)], 6) == [('oHCRljs', 4), ('UMOUgPc', 7), ('HQZjyU', 13), ('Dphr', 15)]
    assert candidate([('ymMuqZz', 9), ('rQW', 6), ('lNhWCd', 7), ('IxQarKChz', 5)], 7) == [('IxQarKChz', 5), ('rQW', 6), ('lNhWCd', 7), ('ymMuqZz', 9)]
    assert candidate([('xkbLVVMlwk', 9), ('AsrmM', 4), ('QGxqU', 7), ('VtKvtV', 10)], 3) == [('AsrmM', 4), ('QGxqU', 7), ('xkbLVVMlwk', 9)]
    assert candidate([('MeFLPRXsHM', 12), ('DLuNA', 8), ('pJikZH', 5), ('FDDpvzH', 7)], 1) == [('pJikZH', 5)]
    assert candidate([('gTjJL', 16), ('PqLdY', 6), ('CQwfkMF', 4), ('kYE', 10)], 1) == [('CQwfkMF', 4)]
    assert candidate([('nstngIsTcAl', 13), ('kYSMyc', 8), ('Wlvv', 5), ('eQw', 6)], 1) == [('Wlvv', 5)]
    assert candidate([('snNMLou', 10), ('Amb', 4), ('ICyJZkk', 4), ('kmOydH', 12)], 4) == [('Amb', 4), ('ICyJZkk', 4), ('snNMLou', 10), ('kmOydH', 12)]
    assert candidate([('jCwhTQuZ', 11), ('PsAJSpgy', 3), ('sbJ', 6), ('xSvrVSZud', 5)], 4) == [('PsAJSpgy', 3), ('xSvrVSZud', 5), ('sbJ', 6), ('jCwhTQuZ', 11)]
    assert candidate([('jMEsrMrNJ', 15), ('hjYoN', 4), ('vbz', 2), ('vDHye', 10)], 8) == [('vbz', 2), ('hjYoN', 4), ('vDHye', 10), ('jMEsrMrNJ', 15)]
    assert candidate([('hYRvNXUkYQO', 9), ('oGgUKWZ', 6), ('VnV', 8), ('UtP', 4)], 7) == [('UtP', 4), ('oGgUKWZ', 6), ('VnV', 8), ('hYRvNXUkYQO', 9)]
    assert candidate([('FOrZFvCx', 8), ('fhMRPiBcz', 2), ('NjSOE', 5), ('Pvg', 4)], 2) == [('fhMRPiBcz', 2), ('Pvg', 4)]
    assert candidate([('BBZFlnlkphS', 16), ('hhYEsI', 9), ('GmaklmF', 4), ('TMDqcIBeY', 9)], 3) == [('GmaklmF', 4), ('hhYEsI', 9), ('TMDqcIBeY', 9)]
    assert candidate([('pRiohidCRYO', 13), ('ZjuWqekk', 4), ('PRkw', 6), ('xlKL', 6)], 6) == [('ZjuWqekk', 4), ('PRkw', 6), ('xlKL', 6), ('pRiohidCRYO', 13)]
    assert candidate([('eUcwKy', 6), ('Ryaytyltk', 1), ('KyXjUDZUm', 3), ('ORY', 7)], 8) == [('Ryaytyltk', 1), ('KyXjUDZUm', 3), ('eUcwKy', 6), ('ORY', 7)]
    assert candidate([('PlAnkLNnsoSi', 10), ('haCNyh', 5), ('gqNb', 3), ('tFyaCPM', 11)], 1) == [('gqNb', 3)]
    assert candidate([('onvhLK', 15), ('uEfxHvNdu', 3), ('SgKHESvlL', 8), ('WdOZZg', 14)], 2) == [('uEfxHvNdu', 3), ('SgKHESvlL', 8)]
    assert candidate([('mvDkOjaGOLRU', 10), ('xQxkk', 4), ('kEsmqspK', 2), ('IwL', 14)], 8) == [('kEsmqspK', 2), ('xQxkk', 4), ('mvDkOjaGOLRU', 10), ('IwL', 14)]
    assert candidate([('aNsRtAvWi', 10), ('KijUAFfs', 2), ('fbVADwaw', 3), ('uxyole', 5)], 1) == [('KijUAFfs', 2)]
    assert candidate([('deKA', 13), ('LwXJ', 10), ('EPUqJeIe', 3), ('pwRvJBGQI', 7)], 1) == [('EPUqJeIe', 3)]
    assert candidate([('YDoZjbKcaTb', 11), ('DVUZUUzX', 10), ('nAbmL', 4), ('CgIdCuG', 13)], 4) == [('nAbmL', 4), ('DVUZUUzX', 10), ('YDoZjbKcaTb', 11), ('CgIdCuG', 13)]
    assert candidate([('DFHuDLgMA', 8), ('ckZxjZj', 8), ('iUVJI', 4), ('WzfckBi', 4)], 5) == [('iUVJI', 4), ('WzfckBi', 4), ('DFHuDLgMA', 8), ('ckZxjZj', 8)]
    assert candidate([('FPKvJVDieb', 16), ('Mvjunj', 4), ('IxvnGItc', 5), ('XvOhUyF', 14)], 5) == [('Mvjunj', 4), ('IxvnGItc', 5), ('XvOhUyF', 14), ('FPKvJVDieb', 16)]
    assert candidate([('LRkskfEHkQsm', 13), ('IdOglFJ', 8), ('aTanw', 4), ('JZDpuV', 11)], 2) == [('aTanw', 4), ('IdOglFJ', 8)]
    assert candidate([('EZMYPvC', 9), ('LgZJjd', 2), ('pLtomnHm', 3), ('neoHc', 13)], 8) == [('LgZJjd', 2), ('pLtomnHm', 3), ('EZMYPvC', 9), ('neoHc', 13)]
    assert candidate([('RTBtkLxOYry', 13), ('cgvRofaUy', 10), ('kfgnx', 1), ('MeWtsRxY', 7)], 6) == [('kfgnx', 1), ('MeWtsRxY', 7), ('cgvRofaUy', 10), ('RTBtkLxOYry', 13)]
    assert candidate([('FLw', 12), ('eoRlkcfs', 5), ('sjcyddya', 7), ('bVVcsx', 12)], 8) == [('eoRlkcfs', 5), ('sjcyddya', 7), ('FLw', 12), ('bVVcsx', 12)]
    assert candidate([('TIE', 10), ('klCkQ', 8), ('oBui', 1), ('XQqvcC', 5)], 4) == [('oBui', 1), ('XQqvcC', 5), ('klCkQ', 8), ('TIE', 10)]
    assert candidate([('dUMsgf', 16), ('DkNR', 8), ('JFUZLiD', 7), ('pae', 12)], 1) == [('JFUZLiD', 7)]
    assert candidate([('qbWYTeVudGi', 16), ('PNag', 6), ('GZHXan', 5), ('ZEBACkSYj', 7)], 6) == [('GZHXan', 5), ('PNag', 6), ('ZEBACkSYj', 7), ('qbWYTeVudGi', 16)]
    assert candidate([('kTVGCiC', 13), ('oEdDsrFT', 8), ('JclnO', 8), ('euiGGYnkN', 6)], 5) == [('euiGGYnkN', 6), ('oEdDsrFT', 8), ('JclnO', 8), ('kTVGCiC', 13)]
    assert candidate([('YRGOBlbz', 16), ('htljPrA', 7), ('BRZTr', 1), ('dqH', 10)], 2) == [('BRZTr', 1), ('htljPrA', 7)]
    assert candidate([('xHGVKuyvOo', 6), ('dOYEFx', 6), ('ceaqNv', 8), ('WZeStYTy', 12)], 6) == [('xHGVKuyvOo', 6), ('dOYEFx', 6), ('ceaqNv', 8), ('WZeStYTy', 12)]
    assert candidate([('EZqliKkx', 14), ('OXDBDmhsd', 6), ('zUdMda', 4), ('TEiFXixK', 7)], 4) == [('zUdMda', 4), ('OXDBDmhsd', 6), ('TEiFXixK', 7), ('EZqliKkx', 14)]
    assert candidate([('odhrxltby', 10), ('AoGYrBS', 10), ('cKeJrZsnbfY', 5), ('GNNWGC', 21)], 4) == [('cKeJrZsnbfY', 5), ('odhrxltby', 10), ('AoGYrBS', 10), ('GNNWGC', 21)]
    assert candidate([('vwkns', 14), ('hfDyEOO', 11), ('yhLR', 6), ('UERL', 11)], 4) == [('yhLR', 6), ('hfDyEOO', 11), ('UERL', 11), ('vwkns', 14)]
    assert candidate([('zymqmuppxx', 13), ('uhrI', 13), ('svBFir', 10), ('SKYWI', 12)], 1) == [('svBFir', 10)]
    assert candidate([('xqrucmh', 11), ('MLLBJr', 10), ('YvtZJs', 11), ('ZZMS', 19)], 6) == [('MLLBJr', 10), ('xqrucmh', 11), ('YvtZJs', 11), ('ZZMS', 19)]
    assert candidate([('glytxkmu', 16), ('iODozF', 16), ('lyJCnLZGCP', 10), ('HUK', 11)], 2) == [('lyJCnLZGCP', 10), ('HUK', 11)]
    assert candidate([('nkisdxfimcx', 18), ('HPflV', 10), ('TyoxvP', 9), ('WUZFLH', 13)], 4) == [('TyoxvP', 9), ('HPflV', 10), ('WUZFLH', 13), ('nkisdxfimcx', 18)]
    assert candidate([('fubekvw', 13), ('tbPycb', 8), ('faYmycaZBsF', 4), ('DPWNWYPNN', 12)], 4) == [('faYmycaZBsF', 4), ('tbPycb', 8), ('DPWNWYPNN', 12), ('fubekvw', 13)]
    assert candidate([('kquzreiygdbk', 18), ('azWmeb', 11), ('rpYuVjfjYp', 10), ('DRHOQLCF', 11)], 4) == [('rpYuVjfjYp', 10), ('azWmeb', 11), ('DRHOQLCF', 11), ('kquzreiygdbk', 18)]
    assert candidate([('nzosjzuxfba', 14), ('gVr', 6), ('uksjLnl', 5), ('WVMCXP', 11)], 6) == [('uksjLnl', 5), ('gVr', 6), ('WVMCXP', 11), ('nzosjzuxfba', 14)]
    assert candidate([('hdqevwjzl', 16), ('Jwd', 14), ('qWMmyjTmsbdK', 6), ('TNQQO', 11)], 2) == [('qWMmyjTmsbdK', 6), ('TNQQO', 11)]
    assert candidate([('wapmbbmyvpp', 19), ('TGJUC', 6), ('GMNmhQsYBdP', 13), ('FCFFFW', 20)], 6) == [('TGJUC', 6), ('GMNmhQsYBdP', 13), ('wapmbbmyvpp', 19), ('FCFFFW', 20)]
    assert candidate([('zgdn', 19), ('rny', 7), ('MlTn', 10), ('XQDIPS', 15)], 6) == [('rny', 7), ('MlTn', 10), ('XQDIPS', 15), ('zgdn', 19)]
    assert candidate([('egyrl', 11), ('zdWCQ', 7), ('HssvOFnAysLM', 14), ('QOCNJJQP', 21)], 2) == [('zdWCQ', 7), ('egyrl', 11)]
    assert candidate([('rwrlrdjdoot', 11), ('cxjxTP', 13), ('YeuusaVuZoq', 12), ('UMPICFJZG', 12)], 1) == [('rwrlrdjdoot', 11)]
    assert candidate([('txbpgsu', 11), ('MmIEZQr', 12), ('Dis', 5), ('UBTZN', 18)], 1) == [('Dis', 5)]
    assert candidate([('sitvv', 18), ('HtgKGZhLA', 6), ('Hib', 14), ('WNOMAXBD', 20)], 1) == [('HtgKGZhLA', 6)]
    assert candidate([('jgfyde', 12), ('uyyBnilv', 7), ('vYPX', 9), ('IZQ', 14)], 4) == [('uyyBnilv', 7), ('vYPX', 9), ('jgfyde', 12), ('IZQ', 14)]
    assert candidate([('xmuhfbo', 9), ('WiCTHux', 12), ('CnNBfBV', 11), ('JGASH', 21)], 5) == [('xmuhfbo', 9), ('CnNBfBV', 11), ('WiCTHux', 12), ('JGASH', 21)]
    assert candidate([('cofudvl', 16), ('YRgE', 12), ('JKcVXQ', 8), ('ZRYUIS', 19)], 5) == [('JKcVXQ', 8), ('YRgE', 12), ('cofudvl', 16), ('ZRYUIS', 19)]
    assert candidate([('frximti', 10), ('UNu', 9), ('AxbbkOcw', 14), ('EZF', 14)], 1) == [('UNu', 9)]
    assert candidate([('tumylzayrb', 19), ('pgezGqqD', 12), ('ewO', 6), ('PAV', 16)], 2) == [('ewO', 6), ('pgezGqqD', 12)]
    assert candidate([('lortjrlpjien', 17), ('SUBq', 7), ('BEKMTUu', 12), ('YCROAV', 16)], 3) == [('SUBq', 7), ('BEKMTUu', 12), ('YCROAV', 16)]
    assert candidate([('bicocwqdjbg', 15), ('aqA', 15), ('opbrvnd', 14), ('QVG', 19)], 6) == [('opbrvnd', 14), ('bicocwqdjbg', 15), ('aqA', 15), ('QVG', 19)]
    assert candidate([('urpmr', 17), ('prxp', 12), ('ctEptqEhMkx', 12), ('VFYR', 17)], 3) == [('prxp', 12), ('ctEptqEhMkx', 12), ('urpmr', 17)]
    assert candidate([('ojxsf', 13), ('WLapvuCZc', 9), ('lVmxuxl', 10), ('XBWZMSCM', 12)], 5) == [('WLapvuCZc', 9), ('lVmxuxl', 10), ('XBWZMSCM', 12), ('ojxsf', 13)]
    assert candidate([('vqei', 10), ('oFQfUfZ', 10), ('vWFdWMIQIVja', 4), ('JXDJUML', 11)], 5) == [('vWFdWMIQIVja', 4), ('vqei', 10), ('oFQfUfZ', 10), ('JXDJUML', 11)]
    assert candidate([('zmbmucyawl', 19), ('oBSLsl', 8), ('dMC', 5), ('PFJDVNS', 14)], 1) == [('dMC', 5)]
    assert candidate([('xjmtpubqleic', 13), ('IfLch', 10), ('biO', 11), ('UFCUNSM', 17)], 6) == [('IfLch', 10), ('biO', 11), ('xjmtpubqleic', 13), ('UFCUNSM', 17)]
    assert candidate([('qhalrxbivb', 9), ('AAOJ', 9), ('KNE', 11), ('RJDYORKD', 16)], 5) == [('qhalrxbivb', 9), ('AAOJ', 9), ('KNE', 11), ('RJDYORKD', 16)]
    assert candidate([('giddosqxrih', 16), ('DYmY', 12), ('ryfdHNqYfVNH', 10), ('YSPAG', 20)], 4) == [('ryfdHNqYfVNH', 10), ('DYmY', 12), ('giddosqxrih', 16), ('YSPAG', 20)]
    assert candidate([('mue', 14), ('rdcJG', 11), ('SEsTqJfwEbPp', 7), ('JRXGHL', 15)], 3) == [('SEsTqJfwEbPp', 7), ('rdcJG', 11), ('mue', 14)]
    assert candidate([('iruqm', 13), ('yLZmPXRPF', 8), ('ZeeP', 7), ('MHTJOGU', 21)], 5) == [('ZeeP', 7), ('yLZmPXRPF', 8), ('iruqm', 13), ('MHTJOGU', 21)]
    assert candidate([('vsuy', 15), ('Jbe', 10), ('dZzaolVaAa', 6), ('VORSC', 18)], 3) == [('dZzaolVaAa', 6), ('Jbe', 10), ('vsuy', 15)]

if __name__ == '__main__':
    check(min_k)