from case_MBPP_096 import count_char_position


def check(candidate):
    assert candidate("xbcefg") == 2
    assert candidate("ABcED") == 3
    assert candidate("AbgdeF") == 5
    assert candidate("aggaxslltv") == 1
    assert candidate("ufezvleou") == 0
    assert candidate("uhjzvhelu") == 0
    assert candidate("ufeixqasf") == 0
    assert candidate("yltyzb") == 0
    assert candidate("tbqdyfz") == 3
    assert candidate("bhwwe") == 1
    assert candidate("jjpqkxprtc") == 0
    assert candidate("effmlyekb") == 0
    assert candidate("imc") == 1
    assert candidate("txjddqd") == 1
    assert candidate("jmt") == 0
    assert candidate("kkaddiruqgc") == 1
    assert candidate("zkh") == 0
    assert candidate("pppwzsmbzvcz") == 0
    assert candidate("xpnyarfvr") == 0
    assert candidate("rsurphmg") == 0
    assert candidate("gzeuehwx") == 1
    assert candidate("nwkvb") == 0
    assert candidate("wtfnqx") == 0
    assert candidate("pjkq") == 0
    assert candidate("maxvbu") == 0
    assert candidate("iis") == 0
    assert candidate("smvubgaivbmp") == 0
    assert candidate("spknbou") == 0
    assert candidate("bxtxoemm") == 0
    assert candidate("dcbameluwrr") == 0
    assert candidate("qzlcnfh") == 1
    assert candidate("kcu") == 0
    assert candidate("ugjpooaa") == 0
    assert candidate("ivxycq") == 0
    assert candidate("dvtjvawjof") == 0
    assert candidate("pujuzs") == 0
    assert candidate("fEDASEIS") == 0
    assert candidate("aaLzYcVYY") == 1
    assert candidate("AuhSHdY") == 1
    assert candidate("EnUZYwr") == 0
    assert candidate("nhIpxrn") == 0
    assert candidate("giS") == 0
    assert candidate("cRtBdu") == 0
    assert candidate("fzvdX") == 1
    assert candidate("lMj") == 0
    assert candidate("rKz") == 0
    assert candidate("xclUN") == 0
    assert candidate("vCoS") == 0
    assert candidate("NkcVjUh") == 1
    assert candidate("RFTDWCC") == 1
    assert candidate("qZUlNjax") == 0
    assert candidate("rjITNpmZv") == 0
    assert candidate("VAqJqXKuQ") == 0
    assert candidate("itLtZ") == 0
    assert candidate("JGZrhoImQ") == 0
    assert candidate("sbkoMAhRi") == 2
    assert candidate("TqzHcjo") == 0
    assert candidate("IxefNmFjp") == 0
    assert candidate("ZgMnkk") == 0
    assert candidate("IcMDAcCM") == 1
    assert candidate("JfaI") == 0
    assert candidate("dKnVb") == 0
    assert candidate("wGjRPi") == 0
    assert candidate("PoXz") == 0
    assert candidate("mktgIeJ") == 0
    assert candidate("kPXJXR") == 0
    assert candidate("pTqZGnX") == 0
    assert candidate("eTsBGNgV") == 1
    assert candidate("kPaWoR") == 0
    assert candidate("YjIMyZQWj") == 0
    assert candidate("Bso") == 0
    assert candidate("RpTtqO") == 0
    assert candidate("MBN") == 1
    assert candidate("oiwPwB") == 0
    assert candidate("yINh") == 0
    assert candidate("CBaVSb") == 1
    assert candidate("xZZ") == 0
    assert candidate("HMru") == 0
    assert candidate("HLobUnNVEk") == 0
    assert candidate("muDKrrlqsaKa") == 1
    assert candidate("BcsfJ") == 0
    assert candidate("ansvv") == 1
    assert candidate("rqOd") == 1
    assert candidate("nLJID") == 0
    assert candidate("QFBsNFN") == 1
    assert candidate("JHiVG") == 0
    assert candidate("TIX") == 0
    assert candidate("SngggwR") == 0
    assert candidate("TBl") == 1
    assert candidate("GJec") == 0
    assert candidate("lFoZcLPIgx") == 0
    assert candidate("CDFFjTWt") == 0
    assert candidate("vbF") == 1
    assert candidate("sxUdj") == 1
    assert candidate("wljD") == 1
    assert candidate("hpD") == 0
    assert candidate("qvbXFX") == 0
    assert candidate("SiFgXpCYA") == 0
    assert candidate("YbKnEsUT") == 2
    assert candidate("JHX") == 0
    assert candidate("zlmORm") == 0
    assert candidate("vdCwpqVYKGz") == 1

if __name__ == '__main__':
    check(count_char_position)