from case_MBPP_278 import sort_sublists


def check(candidate):
    assert candidate([['green', 'orange'], ['black', 'white'], ['white', 'black', 'orange']])==[['green', 'orange'], ['black', 'white'], ['black', 'orange', 'white']]
    assert candidate([['green', 'orange'], ['black'], ['green', 'orange'], ['white']])==[['green', 'orange'], ['black'], ['green', 'orange'], ['white']]
    assert candidate([['a','b'],['d','c'],['g','h'] , ['f','e']])==[['a', 'b'], ['c', 'd'], ['g', 'h'], ['e', 'f']]
    assert candidate([['cqdytzzq', 'yqlomvjyyg'], ['swfwly', 'rvngs'], ['pffunyu', 'ifwhyhziq', 'nonhw']]) == [['cqdytzzq', 'yqlomvjyyg'], ['rvngs', 'swfwly'], ['ifwhyhziq', 'nonhw', 'pffunyu']]
    assert candidate([['mxe', 'wgtiwor'], ['ytpkd', 'gouhf'], ['dyt', 'vmj', 'cso']]) == [['mxe', 'wgtiwor'], ['gouhf', 'ytpkd'], ['cso', 'dyt', 'vmj']]
    assert candidate([['kllvd', 'fqbthbtaf'], ['nkeijruo', 'gdp'], ['uuj', 'asac', 'dvglqmnqm']]) == [['fqbthbtaf', 'kllvd'], ['gdp', 'nkeijruo'], ['asac', 'dvglqmnqm', 'uuj']]
    assert candidate([['kfoeih', 'wmgutmsxjae'], ['qipuxlu', 'xfgzxyt'], ['uisertw', 'uxk', 'tfrrxcqfl']]) == [['kfoeih', 'wmgutmsxjae'], ['qipuxlu', 'xfgzxyt'], ['tfrrxcqfl', 'uisertw', 'uxk']]
    assert candidate([['xgg', 'ubzldzmfpt'], ['rvljois', 'equkqsug'], ['rmndva', 'mtedv', 'qbxtmmhgsx']]) == [['ubzldzmfpt', 'xgg'], ['equkqsug', 'rvljois'], ['mtedv', 'qbxtmmhgsx', 'rmndva']]
    assert candidate([['evljccfa', 'qjbume'], ['wrt', 'oupww'], ['dldvgla', 'omli', 'xzwletog']]) == [['evljccfa', 'qjbume'], ['oupww', 'wrt'], ['dldvgla', 'omli', 'xzwletog']]
    assert candidate([['whyfqhms', 'bavtvgpd'], ['pcmxdnapd', 'efxfdcs'], ['negmvlt', 'uxvngpzb', 'fxk']]) == [['bavtvgpd', 'whyfqhms'], ['efxfdcs', 'pcmxdnapd'], ['fxk', 'negmvlt', 'uxvngpzb']]
    assert candidate([['qqpeltkt', 'hnqsldtelr'], ['wauxzcbp', 'fhpuiq'], ['xloseq', 'feplwqz', 'qrwzsibrnyp']]) == [['hnqsldtelr', 'qqpeltkt'], ['fhpuiq', 'wauxzcbp'], ['feplwqz', 'qrwzsibrnyp', 'xloseq']]
    assert candidate([['yuigp', 'pucclvw'], ['rywsaacz', 'fxdnu'], ['rznpklaw', 'rqa', 'bwavb']]) == [['pucclvw', 'yuigp'], ['fxdnu', 'rywsaacz'], ['bwavb', 'rqa', 'rznpklaw']]
    assert candidate([['hazjuusy', 'fktjtjm'], ['qvklgrwpb', 'qsdlgzzf'], ['eoi', 'xfxabcl', 'crrplosi']]) == [['fktjtjm', 'hazjuusy'], ['qsdlgzzf', 'qvklgrwpb'], ['crrplosi', 'eoi', 'xfxabcl']]
    assert candidate([['jgnzoz', 'njue'], ['brz', 'rujkanpxt'], ['nujrgd', 'qchsi', 'nij']]) == [['jgnzoz', 'njue'], ['brz', 'rujkanpxt'], ['nij', 'nujrgd', 'qchsi']]
    assert candidate([['yxij', 'juzs'], ['wrdlrjj', 'xacux'], ['bpyixk', 'zcyl', 'tqbpubz']]) == [['juzs', 'yxij'], ['wrdlrjj', 'xacux'], ['bpyixk', 'tqbpubz', 'zcyl']]
    assert candidate([['nrbb', 'klnkywj'], ['uhtgyz', 'flwvgcs'], ['vdc', 'stbdqe', 'nljrrbqtyh']]) == [['klnkywj', 'nrbb'], ['flwvgcs', 'uhtgyz'], ['nljrrbqtyh', 'stbdqe', 'vdc']]
    assert candidate([['ketr', 'asfgowfpnw'], ['yugdctmn', 'ecuxewpe'], ['zekbug', 'mubstf', 'vzpcjxffx']]) == [['asfgowfpnw', 'ketr'], ['ecuxewpe', 'yugdctmn'], ['mubstf', 'vzpcjxffx', 'zekbug']]
    assert candidate([['ifluasi', 'lpwjikkufx'], ['vjyh', 'lpmt'], ['tlump', 'xcildv', 'lyo']]) == [['ifluasi', 'lpwjikkufx'], ['lpmt', 'vjyh'], ['lyo', 'tlump', 'xcildv']]
    assert candidate([['jqels', 'vvhve'], ['qptkclx', 'xzwcio'], ['qaalt', 'edpzxvul', 'ikngzlwb']]) == [['jqels', 'vvhve'], ['qptkclx', 'xzwcio'], ['edpzxvul', 'ikngzlwb', 'qaalt']]
    assert candidate([['dwihaoih', 'zrjewh'], ['tftpv', 'hcb'], ['wnmra', 'siu', 'bapmzcb']]) == [['dwihaoih', 'zrjewh'], ['hcb', 'tftpv'], ['bapmzcb', 'siu', 'wnmra']]
    assert candidate([['oqw', 'jukyofkwq'], ['xkoqwr', 'ggdn'], ['urelkgfin', 'uzjlbea', 'ffh']]) == [['jukyofkwq', 'oqw'], ['ggdn', 'xkoqwr'], ['ffh', 'urelkgfin', 'uzjlbea']]
    assert candidate([['topeojtxu', 'buk'], ['shasz', 'psoazy'], ['hyo', 'fki', 'bjfecjm']]) == [['buk', 'topeojtxu'], ['psoazy', 'shasz'], ['bjfecjm', 'fki', 'hyo']]
    assert candidate([['lsxafd', 'gmevieprlxl'], ['fwwpxr', 'zmx'], ['ybcjrlkwc', 'ynhkr', 'kqlnf']]) == [['gmevieprlxl', 'lsxafd'], ['fwwpxr', 'zmx'], ['kqlnf', 'ybcjrlkwc', 'ynhkr']]
    assert candidate([['xymuxctx', 'nawr'], ['otnhwvx', 'pykfc'], ['ofgkyptf', 'xvrdsqvmd', 'frpqif']]) == [['nawr', 'xymuxctx'], ['otnhwvx', 'pykfc'], ['frpqif', 'ofgkyptf', 'xvrdsqvmd']]
    assert candidate([['yzai', 'qwwoxhoxsaq'], ['gnwklg', 'laufswbwd'], ['jeyrbld', 'qlrobtkiu', 'jgjexp']]) == [['qwwoxhoxsaq', 'yzai'], ['gnwklg', 'laufswbwd'], ['jeyrbld', 'jgjexp', 'qlrobtkiu']]
    assert candidate([['hjeevkbhm', 'krjabphd'], ['cxpscd', 'oalpisw'], ['hmeanil', 'vuzs', 'jqgj']]) == [['hjeevkbhm', 'krjabphd'], ['cxpscd', 'oalpisw'], ['hmeanil', 'jqgj', 'vuzs']]
    assert candidate([['tebiu', 'xiutpwkhh'], ['wlq', 'mbsru'], ['eekvuqf', 'rxyjtxyqn', 'quhgud']]) == [['tebiu', 'xiutpwkhh'], ['mbsru', 'wlq'], ['eekvuqf', 'quhgud', 'rxyjtxyqn']]
    assert candidate([['tqfki', 'aiozcd'], ['dcds', 'uqtyjurv'], ['ubcaiyso', 'cyevemyl', 'vwjmw']]) == [['aiozcd', 'tqfki'], ['dcds', 'uqtyjurv'], ['cyevemyl', 'ubcaiyso', 'vwjmw']]
    assert candidate([['qwtxsfq', 'ihyxkse'], ['ixcecjvcs', 'bihwaoy'], ['pkb', 'ntwuoeu', 'uynzomy']]) == [['ihyxkse', 'qwtxsfq'], ['bihwaoy', 'ixcecjvcs'], ['ntwuoeu', 'pkb', 'uynzomy']]
    assert candidate([['lccxw', 'kadhryn'], ['ksybqohko', 'enlavqm'], ['kjo', 'xvf', 'zcrlurleego']]) == [['kadhryn', 'lccxw'], ['enlavqm', 'ksybqohko'], ['kjo', 'xvf', 'zcrlurleego']]
    assert candidate([['dlklanail', 'znlh'], ['oxavt', 'wdh'], ['ealfziql', 'jrjhrlhv', 'qqzoevrcz']]) == [['dlklanail', 'znlh'], ['oxavt', 'wdh'], ['ealfziql', 'jrjhrlhv', 'qqzoevrcz']]
    assert candidate([['euybkfxra', 'aoqliae'], ['vwt', 'nfdbddgqb'], ['hwzmvdv', 'yxnstkylh', 'plwk']]) == [['aoqliae', 'euybkfxra'], ['nfdbddgqb', 'vwt'], ['hwzmvdv', 'plwk', 'yxnstkylh']]
    assert candidate([['jbibly', 'wunth'], ['ypfkvpjm', 'egdyag'], ['wpf', 'arhhtclkp', 'dfmgaser']]) == [['jbibly', 'wunth'], ['egdyag', 'ypfkvpjm'], ['arhhtclkp', 'dfmgaser', 'wpf']]
    assert candidate([['kcsnpaq', 'wdgdlultef'], ['devvwo', 'slfnsavk'], ['qbkngrd', 'izldxvg', 'gsliogcvsiev']]) == [['kcsnpaq', 'wdgdlultef'], ['devvwo', 'slfnsavk'], ['gsliogcvsiev', 'izldxvg', 'qbkngrd']]
    assert candidate([['sssmgsdsd', 'vszcl'], ['nodar', 'exukyboq'], ['wxcyqeh', 'qfl', 'qhnvpekgiuk']]) == [['sssmgsdsd', 'vszcl'], ['exukyboq', 'nodar'], ['qfl', 'qhnvpekgiuk', 'wxcyqeh']]
    assert candidate([['thzjwwrct', 'nuklyoxvvkee'], ['bmbvxy', 'rzqsykwy'], ['qklnzt', 'iwqttn', 'mptjmyyj']]) == [['nuklyoxvvkee', 'thzjwwrct'], ['bmbvxy', 'rzqsykwy'], ['iwqttn', 'mptjmyyj', 'qklnzt']]
    assert candidate([['cftxto', 'mufzrciuijv'], ['ogzcjr'], ['idwm', 'tvci'], ['hql']]) == [['cftxto', 'mufzrciuijv'], ['ogzcjr'], ['idwm', 'tvci'], ['hql']]
    assert candidate([['hfpb', 'gdepaeh'], ['prlprbffb'], ['uca', 'lcqomfzy'], ['vprcebpv']]) == [['gdepaeh', 'hfpb'], ['prlprbffb'], ['lcqomfzy', 'uca'], ['vprcebpv']]
    assert candidate([['blq', 'pyjoandcmcd'], ['cay'], ['jcmfyu', 'swteambk'], ['jmihf']]) == [['blq', 'pyjoandcmcd'], ['cay'], ['jcmfyu', 'swteambk'], ['jmihf']]
    assert candidate([['eafcmpplc', 'wvuissqecjd'], ['qpnp'], ['lntdtn', 'spvevxkvb'], ['izoq']]) == [['eafcmpplc', 'wvuissqecjd'], ['qpnp'], ['lntdtn', 'spvevxkvb'], ['izoq']]
    assert candidate([['zjz', 'cefxksoeeoq'], ['lavulyuvs'], ['unwja', 'ermwpdbvdckw'], ['yglvkz']]) == [['cefxksoeeoq', 'zjz'], ['lavulyuvs'], ['ermwpdbvdckw', 'unwja'], ['yglvkz']]
    assert candidate([['nudyq', 'qvilxnb'], ['fravxfph'], ['wbtywpf', 'cta'], ['wrijfi']]) == [['nudyq', 'qvilxnb'], ['fravxfph'], ['cta', 'wbtywpf'], ['wrijfi']]
    assert candidate([['gxsw', 'fdhfu'], ['qbiteuxyl'], ['sgpo', 'ibmnrvgwihqs'], ['dob']]) == [['fdhfu', 'gxsw'], ['qbiteuxyl'], ['ibmnrvgwihqs', 'sgpo'], ['dob']]
    assert candidate([['yvpez', 'kbjmu'], ['dwam'], ['rmtuwrd', 'phbfqozpqa'], ['qgd']]) == [['kbjmu', 'yvpez'], ['dwam'], ['phbfqozpqa', 'rmtuwrd'], ['qgd']]
    assert candidate([['dvrqqgtib', 'nvxv'], ['iaknz'], ['ierlmi', 'sczc'], ['fzx']]) == [['dvrqqgtib', 'nvxv'], ['iaknz'], ['ierlmi', 'sczc'], ['fzx']]
    assert candidate([['ptplf', 'wet'], ['ggoxx'], ['lmhvkgp', 'nzwczugwve'], ['ilutm']]) == [['ptplf', 'wet'], ['ggoxx'], ['lmhvkgp', 'nzwczugwve'], ['ilutm']]
    assert candidate([['ponj', 'ukyhui'], ['hbn'], ['szf', 'ovglhorv'], ['ghyjljcf']]) == [['ponj', 'ukyhui'], ['hbn'], ['ovglhorv', 'szf'], ['ghyjljcf']]
    assert candidate([['jkhydfdf', 'nttti'], ['ljeapuag'], ['jyifqk', 'ypqbzkantqi'], ['xvonvsdsl']]) == [['jkhydfdf', 'nttti'], ['ljeapuag'], ['jyifqk', 'ypqbzkantqi'], ['xvonvsdsl']]
    assert candidate([['jhhh', 'czquzuqegggz'], ['ksqkb'], ['kbjrias', 'nrxho'], ['zlcujdfdm']]) == [['czquzuqegggz', 'jhhh'], ['ksqkb'], ['kbjrias', 'nrxho'], ['zlcujdfdm']]
    assert candidate([['uvpjgp', 'wkcsklklammh'], ['imflavx'], ['ynvqdr', 'italyier'], ['esyg']]) == [['uvpjgp', 'wkcsklklammh'], ['imflavx'], ['italyier', 'ynvqdr'], ['esyg']]
    assert candidate([['dqxmby', 'jdpjgjf'], ['obabwjpkb'], ['wttmx', 'ddmeretosvly'], ['sqnypi']]) == [['dqxmby', 'jdpjgjf'], ['obabwjpkb'], ['ddmeretosvly', 'wttmx'], ['sqnypi']]
    assert candidate([['pjhzvdpc', 'nfkpfyvv'], ['mpppudz'], ['inwtnvre', 'tpbg'], ['agxhvfnou']]) == [['nfkpfyvv', 'pjhzvdpc'], ['mpppudz'], ['inwtnvre', 'tpbg'], ['agxhvfnou']]
    assert candidate([['nudeypnds', 'yoqsszbj'], ['ezer'], ['vzbavfhcr', 'hgk'], ['lcliyaf']]) == [['nudeypnds', 'yoqsszbj'], ['ezer'], ['hgk', 'vzbavfhcr'], ['lcliyaf']]
    assert candidate([['pepnvi', 'neupafkiw'], ['ujlji'], ['qeqz', 'popg'], ['thmya']]) == [['neupafkiw', 'pepnvi'], ['ujlji'], ['popg', 'qeqz'], ['thmya']]
    assert candidate([['hfrdlh', 'jxzcy'], ['xyrqhtlv'], ['gdamtb', 'ewtxvureg'], ['tcpfqwcht']]) == [['hfrdlh', 'jxzcy'], ['xyrqhtlv'], ['ewtxvureg', 'gdamtb'], ['tcpfqwcht']]
    assert candidate([['dtvalblyt', 'pnpbugfzfj'], ['udnjk'], ['lcovk', 'liaunyjhmnth'], ['upcp']]) == [['dtvalblyt', 'pnpbugfzfj'], ['udnjk'], ['lcovk', 'liaunyjhmnth'], ['upcp']]
    assert candidate([['gmngeep', 'ensafgvkbec'], ['nfaizlfs'], ['aqw', 'uejqmdf'], ['ackftcsm']]) == [['ensafgvkbec', 'gmngeep'], ['nfaizlfs'], ['aqw', 'uejqmdf'], ['ackftcsm']]
    assert candidate([['acie', 'xrfvxqq'], ['wycxjzj'], ['dgastjjg', 'lglq'], ['wegmglc']]) == [['acie', 'xrfvxqq'], ['wycxjzj'], ['dgastjjg', 'lglq'], ['wegmglc']]
    assert candidate([['urcfb', 'hrs'], ['clq'], ['lbnx', 'omed'], ['gau']]) == [['hrs', 'urcfb'], ['clq'], ['lbnx', 'omed'], ['gau']]
    assert candidate([['gijuztsi', 'xjpvlnbsdop'], ['dfxapwmz'], ['djuihswwd', 'zynfj'], ['emiqpa']]) == [['gijuztsi', 'xjpvlnbsdop'], ['dfxapwmz'], ['djuihswwd', 'zynfj'], ['emiqpa']]
    assert candidate([['rrosg', 'zalz'], ['ooggxom'], ['bpytvkq', 'pgcw'], ['uqayotc']]) == [['rrosg', 'zalz'], ['ooggxom'], ['bpytvkq', 'pgcw'], ['uqayotc']]
    assert candidate([['pjnmepwc', 'dsgqqmvj'], ['xvtaidh'], ['miplwvrw', 'zixwxbflj'], ['achekmd']]) == [['dsgqqmvj', 'pjnmepwc'], ['xvtaidh'], ['miplwvrw', 'zixwxbflj'], ['achekmd']]
    assert candidate([['oexq', 'wrxbfnjmamw'], ['tbes'], ['jbuf', 'vnvha'], ['bamilaus']]) == [['oexq', 'wrxbfnjmamw'], ['tbes'], ['jbuf', 'vnvha'], ['bamilaus']]
    assert candidate([['snx', 'cpgaavsyhtk'], ['etqip'], ['ydak', 'vbghxaclj'], ['wvuimj']]) == [['cpgaavsyhtk', 'snx'], ['etqip'], ['vbghxaclj', 'ydak'], ['wvuimj']]
    assert candidate([['voxcrjy', 'dvcboc'], ['rvdqyll'], ['cxybgyjf', 'gdl'], ['mzwszlmhi']]) == [['dvcboc', 'voxcrjy'], ['rvdqyll'], ['cxybgyjf', 'gdl'], ['mzwszlmhi']]
    assert candidate([['luv', 'thwvm'], ['rxxs'], ['hdx', 'tcobuabi'], ['ubprkfjaw']]) == [['luv', 'thwvm'], ['rxxs'], ['hdx', 'tcobuabi'], ['ubprkfjaw']]
    assert candidate([['sipbn', 'vhqy'], ['stabax'], ['ktriloq', 'jzi'], ['rqzdnfvz']]) == [['sipbn', 'vhqy'], ['stabax'], ['jzi', 'ktriloq'], ['rqzdnfvz']]
    assert candidate([['vclx', 'jywp'], ['ziebkrqo'], ['rzbtu', 'exbqt'], ['mnxqyicy']]) == [['jywp', 'vclx'], ['ziebkrqo'], ['exbqt', 'rzbtu'], ['mnxqyicy']]
    assert candidate([['fmr', 'ucf'], ['yzq'], ['ivf', 'dsyqhiue'], ['vrkcr']]) == [['fmr', 'ucf'], ['yzq'], ['dsyqhiue', 'ivf'], ['vrkcr']]
    assert candidate([['f', 'j'], ['g', 'm'], ['b', 'r'], ['o', 'h']]) == [['f', 'j'], ['g', 'm'], ['b', 'r'], ['h', 'o']]
    assert candidate([['w', 'm'], ['g', 't'], ['g', 't'], ['s', 'r']]) == [['m', 'w'], ['g', 't'], ['g', 't'], ['r', 's']]
    assert candidate([['d', 'm'], ['l', 'x'], ['x', 'p'], ['m', 'e']]) == [['d', 'm'], ['l', 'x'], ['p', 'x'], ['e', 'm']]
    assert candidate([['o', 'd'], ['d', 'k'], ['p', 'w'], ['a', 's']]) == [['d', 'o'], ['d', 'k'], ['p', 'w'], ['a', 's']]
    assert candidate([['j', 'c'], ['a', 'h'], ['a', 'p'], ['l', 'n']]) == [['c', 'j'], ['a', 'h'], ['a', 'p'], ['l', 'n']]
    assert candidate([['r', 'v'], ['l', 't'], ['q', 'b'], ['h', 'd']]) == [['r', 'v'], ['l', 't'], ['b', 'q'], ['d', 'h']]
    assert candidate([['x', 'l'], ['l', 'e'], ['j', 'i'], ['f', 'x']]) == [['l', 'x'], ['e', 'l'], ['i', 'j'], ['f', 'x']]
    assert candidate([['h', 'l'], ['z', 'a'], ['t', 'c'], ['q', 'l']]) == [['h', 'l'], ['a', 'z'], ['c', 't'], ['l', 'q']]
    assert candidate([['z', 'y'], ['n', 'a'], ['h', 'a'], ['m', 'a']]) == [['y', 'z'], ['a', 'n'], ['a', 'h'], ['a', 'm']]
    assert candidate([['w', 'z'], ['f', 'e'], ['z', 'j'], ['o', 'i']]) == [['w', 'z'], ['e', 'f'], ['j', 'z'], ['i', 'o']]
    assert candidate([['y', 'o'], ['j', 'w'], ['c', 'c'], ['x', 'p']]) == [['o', 'y'], ['j', 'w'], ['c', 'c'], ['p', 'x']]
    assert candidate([['d', 'y'], ['v', 'w'], ['n', 'g'], ['d', 'c']]) == [['d', 'y'], ['v', 'w'], ['g', 'n'], ['c', 'd']]
    assert candidate([['m', 'i'], ['i', 'm'], ['d', 'q'], ['u', 's']]) == [['i', 'm'], ['i', 'm'], ['d', 'q'], ['s', 'u']]
    assert candidate([['q', 'b'], ['h', 'b'], ['p', 'z'], ['a', 'n']]) == [['b', 'q'], ['b', 'h'], ['p', 'z'], ['a', 'n']]
    assert candidate([['m', 'l'], ['j', 'r'], ['h', 'd'], ['j', 'l']]) == [['l', 'm'], ['j', 'r'], ['d', 'h'], ['j', 'l']]
    assert candidate([['a', 'l'], ['n', 'k'], ['v', 'e'], ['g', 'o']]) == [['a', 'l'], ['k', 'n'], ['e', 'v'], ['g', 'o']]
    assert candidate([['x', 'x'], ['f', 'g'], ['e', 'h'], ['y', 'h']]) == [['x', 'x'], ['f', 'g'], ['e', 'h'], ['h', 'y']]
    assert candidate([['e', 'p'], ['x', 'p'], ['y', 'k'], ['i', 'n']]) == [['e', 'p'], ['p', 'x'], ['k', 'y'], ['i', 'n']]
    assert candidate([['s', 'm'], ['s', 't'], ['a', 'g'], ['m', 'i']]) == [['m', 's'], ['s', 't'], ['a', 'g'], ['i', 'm']]
    assert candidate([['k', 'c'], ['c', 't'], ['y', 'e'], ['e', 'v']]) == [['c', 'k'], ['c', 't'], ['e', 'y'], ['e', 'v']]
    assert candidate([['w', 'd'], ['w', 'b'], ['g', 'i'], ['j', 'm']]) == [['d', 'w'], ['b', 'w'], ['g', 'i'], ['j', 'm']]
    assert candidate([['x', 'm'], ['w', 'l'], ['d', 't'], ['y', 'd']]) == [['m', 'x'], ['l', 'w'], ['d', 't'], ['d', 'y']]
    assert candidate([['h', 's'], ['d', 'd'], ['i', 'z'], ['w', 'f']]) == [['h', 's'], ['d', 'd'], ['i', 'z'], ['f', 'w']]
    assert candidate([['w', 't'], ['k', 'b'], ['r', 'n'], ['u', 'y']]) == [['t', 'w'], ['b', 'k'], ['n', 'r'], ['u', 'y']]
    assert candidate([['r', 'y'], ['e', 'y'], ['i', 'm'], ['m', 'e']]) == [['r', 'y'], ['e', 'y'], ['i', 'm'], ['e', 'm']]
    assert candidate([['j', 'o'], ['q', 'f'], ['y', 'i'], ['x', 'p']]) == [['j', 'o'], ['f', 'q'], ['i', 'y'], ['p', 'x']]
    assert candidate([['s', 'x'], ['b', 't'], ['s', 'c'], ['d', 's']]) == [['s', 'x'], ['b', 't'], ['c', 's'], ['d', 's']]
    assert candidate([['z', 'z'], ['c', 't'], ['m', 'q'], ['m', 'w']]) == [['z', 'z'], ['c', 't'], ['m', 'q'], ['m', 'w']]
    assert candidate([['m', 'u'], ['i', 'x'], ['f', 'x'], ['d', 't']]) == [['m', 'u'], ['i', 'x'], ['f', 'x'], ['d', 't']]
    assert candidate([['g', 'b'], ['s', 's'], ['d', 'h'], ['o', 'h']]) == [['b', 'g'], ['s', 's'], ['d', 'h'], ['h', 'o']]
    assert candidate([['y', 'f'], ['f', 'o'], ['e', 'j'], ['d', 'a']]) == [['f', 'y'], ['f', 'o'], ['e', 'j'], ['a', 'd']]
    assert candidate([['p', 'l'], ['k', 'i'], ['j', 'd'], ['m', 'l']]) == [['l', 'p'], ['i', 'k'], ['d', 'j'], ['l', 'm']]
    assert candidate([['j', 't'], ['o', 'g'], ['g', 't'], ['s', 'c']]) == [['j', 't'], ['g', 'o'], ['g', 't'], ['c', 's']]

if __name__ == '__main__':
    check(sort_sublists)