from case_MBPP_037 import get_Char


def check(candidate):
    assert candidate("abc") == "f"
    assert candidate("gfg") == "t"
    assert candidate("ab") == "c"
    assert candidate("hhte") == "o"
    assert candidate("wktkgh") == "b"
    assert candidate("ifimlgvol") == "a"
    assert candidate("iviaaln") == "p"
    assert candidate("qhlxdmgs") == 122
    assert candidate("ldrfywxf") == "n"
    assert candidate("jfejwdqx") == "u"
    assert candidate("onl") == "o"
    assert candidate("vchn") == "u"
    assert candidate("fbjteo") == f
    assert candidate("skcqwtmz") == "b"
    assert candidate("umauoxbri") == "t"
    assert candidate("xlz") == j
    assert candidate("rxzgw") == "t"
    assert candidate("wnssyjmr") == "k"
    assert candidate("kmx") == "v"
    assert candidate("myihnnj") == "o"
    assert candidate("dhtbtexm") == "r"
    assert candidate("std") == "q"
    assert candidate("pxzdx") == "p"
    assert candidate("acn") == "r"
    assert candidate("she") == f
    assert candidate("xsygcz") == 122
    assert candidate("jcrjjyfz") == "d"
    assert candidate("ausg") == "v"
    assert candidate("zskwzhqyo") == "n"
    assert candidate("rrneeyp") == "w"
    assert candidate("qqrjxmv") == "q"
    assert candidate("ikpc") == "m"
    assert candidate("cnltzkus") == "v"
    assert candidate("pupze") == f
    assert candidate("nloqebjr") == "o"
    assert candidate("kzkg") == "c"
    assert candidate("gzcaic") == "w"
    assert candidate("flvt") == "h"
    assert candidate("qcc") == "w"
    assert candidate("tihdegwzt") == "r"
    assert candidate("slrmxe") == "m"
    assert candidate("cntjhsopo") == "p"
    assert candidate("lnvegdqlv") == "k"
    assert candidate("obl") == "c"
    assert candidate("iztvb") == "a"
    assert candidate("jay") == j
    assert candidate("kgxoywqz") == "r"
    assert candidate("fzg") == "m"
    assert candidate("egzjzmvcx") == f
    assert candidate("acpxpktnm") == "n"
    assert candidate("tlb") == "h"
    assert candidate("whfbfrr") == "c"
    assert candidate("mxdmsgezb") == i
    assert candidate("yyq") == "o"
    assert candidate("cnkvtt") == "l"
    assert candidate("yxmclmtmv") == "o"
    assert candidate("khgsrwpf") == "d"
    assert candidate("eznw") == "p"
    assert candidate("erl") == i
    assert candidate("nvjr") == "l"
    assert candidate("ors") == 122
    assert candidate("bxery") == "v"
    assert candidate("ucbelzaa") == "s"
    assert candidate("hzxsio") == "w"
    assert candidate("lmaipclk") == "y"
    assert candidate("uzqs") == "e"
    assert candidate("hrlcwqvt") == "s"
    assert candidate("cqtpeltin") == "l"
    assert candidate("slfxbno") == "n"
    assert candidate("tblx") == f
    assert candidate("lxwj") == "q"
    assert candidate("tyg") == 122
    assert candidate("jihysj") == "c"
    assert candidate("jke") == 122
    assert candidate("whiym") == 122
    assert candidate("pkota") == "k"
    assert candidate("akwvb") == "g"
    assert candidate("dxo") == "q"
    assert candidate("gxolu") == "a"
    assert candidate("bwnr") == "e"
    assert candidate("mklu") == "e"
    assert candidate("njt") == "r"
    assert candidate("ogdx") == "x"
    assert candidate("ifrv") == "c"
    assert candidate("ytq") == j
    assert candidate("kura") == "y"
    assert candidate("ipywht") == "w"
    assert candidate("ehvh") == "q"
    assert candidate("kbasq") == "x"
    assert candidate("tqql") == "n"
    assert candidate("jjys") == "l"
    assert candidate("jiguot") == "d"
    assert candidate("zln") == 122
    assert candidate("rsttxs") == "p"
    assert candidate("uyeq") == "p"
    assert candidate("dizip") == "l"
    assert candidate("uxx") == "q"
    assert candidate("ppvmys") == "g"
    assert candidate("ely") == "p"
    assert candidate("wej") == "l"
    assert candidate("ubjg") == "n"
    assert candidate("jfa") == "q"

if __name__ == '__main__':
    check(get_Char)