from case_MBPP_028 import get_equal


def check(candidate):
    assert candidate([(11, 22, 33), (44, 55, 66)], 3) == 'All tuples have same length'
    assert candidate([(1, 2, 3), (4, 5, 6, 7)], 3) == 'All tuples do not have same length'
    assert candidate([(1, 2), (3, 4)], 2) == 'All tuples have same length'
    assert candidate([(12, 19, 29), (40, 57, 66)], 4) == "All tuples do not have same length"
    assert candidate([(11, 22, 38), (49, 54, 65)], 2) == "All tuples do not have same length"
    assert candidate([(11, 23, 31), (43, 56, 71)], 3) == "All tuples have same length"
    assert candidate([(13, 26, 36), (49, 52, 70)], 5) == "All tuples do not have same length"
    assert candidate([(12, 27, 37), (49, 56, 64)], 8) == "All tuples do not have same length"
    assert candidate([(9, 17, 38), (40, 52, 68)], 4) == "All tuples do not have same length"
    assert candidate([(14, 25, 32), (43, 59, 61)], 6) == "All tuples do not have same length"
    assert candidate([(16, 21, 34), (43, 51, 67)], 4) == "All tuples do not have same length"
    assert candidate([(6, 21, 33), (48, 60, 68)], 7) == "All tuples do not have same length"
    assert candidate([(12, 20, 32), (43, 56, 66)], 5) == "All tuples do not have same length"
    assert candidate([(8, 18, 33), (48, 50, 66)], 6) == "All tuples do not have same length"
    assert candidate([(11, 26, 33), (42, 57, 71)], 4) == "All tuples do not have same length"
    assert candidate([(16, 26, 36), (46, 53, 63)], 5) == "All tuples do not have same length"
    assert candidate([(6, 18, 36), (43, 50, 70)], 8) == "All tuples do not have same length"
    assert candidate([(11, 17, 33), (49, 60, 70)], 7) == "All tuples do not have same length"
    assert candidate([(10, 25, 28), (43, 60, 67)], 8) == "All tuples do not have same length"
    assert candidate([(13, 18, 32), (46, 56, 63)], 5) == "All tuples do not have same length"
    assert candidate([(14, 22, 34), (39, 56, 67)], 7) == "All tuples do not have same length"
    assert candidate([(13, 25, 32), (47, 60, 70)], 1) == "All tuples do not have same length"
    assert candidate([(10, 21, 32), (39, 56, 70)], 7) == "All tuples do not have same length"
    assert candidate([(15, 21, 36), (44, 58, 71)], 2) == "All tuples do not have same length"
    assert candidate([(9, 18, 36), (48, 59, 63)], 3) == "All tuples have same length"
    assert candidate([(12, 22, 35), (48, 53, 68)], 5) == "All tuples do not have same length"
    assert candidate([(15, 17, 31), (47, 60, 63)], 1) == "All tuples do not have same length"
    assert candidate([(15, 18, 30), (46, 60, 68)], 1) == "All tuples do not have same length"
    assert candidate([(11, 22, 37), (40, 52, 70)], 3) == "All tuples have same length"
    assert candidate([(15, 18, 30), (43, 56, 71)], 5) == "All tuples do not have same length"
    assert candidate([(12, 20, 36), (39, 51, 61)], 5) == "All tuples do not have same length"
    assert candidate([(15, 19, 28), (41, 52, 62)], 8) == "All tuples do not have same length"
    assert candidate([(12, 22, 34), (48, 56, 65)], 1) == "All tuples do not have same length"
    assert candidate([(9, 18, 29), (48, 51, 63)], 7) == "All tuples do not have same length"
    assert candidate([(15, 22, 33), (43, 54, 69)], 7) == "All tuples do not have same length"
    assert candidate([(8, 19, 36), (47, 60, 63)], 3) == "All tuples have same length"
    assert candidate([(4, 6, 3), (4, 1, 8, 2)], 2) == "All tuples do not have same length"
    assert candidate([(2, 5, 1), (2, 8, 7, 9)], 3) == "All tuples do not have same length"
    assert candidate([(3, 3, 3), (5, 5, 11, 12)], 4) == "All tuples do not have same length"
    assert candidate([(1, 1, 1), (8, 8, 6, 12)], 6) == "All tuples do not have same length"
    assert candidate([(5, 1, 3), (2, 6, 8, 5)], 3) == "All tuples do not have same length"
    assert candidate([(4, 5, 5), (8, 9, 8, 3)], 4) == "All tuples do not have same length"
    assert candidate([(1, 7, 3), (9, 4, 4, 6)], 1) == "All tuples do not have same length"
    assert candidate([(2, 1, 7), (5, 4, 4, 8)], 2) == "All tuples do not have same length"
    assert candidate([(3, 1, 4), (6, 4, 1, 10)], 8) == "All tuples do not have same length"
    assert candidate([(3, 4, 4), (5, 1, 9, 11)], 2) == "All tuples do not have same length"
    assert candidate([(5, 5, 5), (3, 3, 1, 10)], 4) == "All tuples do not have same length"
    assert candidate([(5, 2, 4), (2, 8, 4, 2)], 5) == "All tuples do not have same length"
    assert candidate([(1, 2, 6), (4, 6, 9, 9)], 2) == "All tuples do not have same length"
    assert candidate([(1, 5, 6), (5, 7, 7, 7)], 3) == "All tuples do not have same length"
    assert candidate([(5, 2, 5), (9, 4, 5, 4)], 4) == "All tuples do not have same length"
    assert candidate([(3, 1, 4), (1, 8, 5, 9)], 3) == "All tuples do not have same length"
    assert candidate([(6, 2, 1), (5, 10, 10, 9)], 2) == "All tuples do not have same length"
    assert candidate([(4, 6, 6), (3, 3, 2, 7)], 1) == "All tuples do not have same length"
    assert candidate([(6, 7, 6), (5, 6, 7, 3)], 1) == "All tuples do not have same length"
    assert candidate([(3, 7, 5), (1, 5, 9, 7)], 2) == "All tuples do not have same length"
    assert candidate([(3, 4, 3), (3, 8, 1, 2)], 7) == "All tuples do not have same length"
    assert candidate([(5, 6, 6), (9, 9, 2, 8)], 5) == "All tuples do not have same length"
    assert candidate([(3, 7, 6), (2, 3, 9, 7)], 5) == "All tuples do not have same length"
    assert candidate([(5, 3, 6), (2, 2, 2, 10)], 4) == "All tuples do not have same length"
    assert candidate([(2, 3, 3), (4, 8, 5, 5)], 3) == "All tuples do not have same length"
    assert candidate([(3, 3, 6), (7, 3, 8, 6)], 1) == "All tuples do not have same length"
    assert candidate([(2, 3, 3), (5, 2, 2, 3)], 4) == "All tuples do not have same length"
    assert candidate([(2, 4, 5), (2, 10, 3, 11)], 8) == "All tuples do not have same length"
    assert candidate([(5, 1, 1), (6, 2, 8, 5)], 1) == "All tuples do not have same length"
    assert candidate([(4, 1, 5), (3, 3, 11, 6)], 4) == "All tuples do not have same length"
    assert candidate([(6, 6, 3), (4, 2, 8, 4)], 5) == "All tuples do not have same length"
    assert candidate([(5, 6, 8), (6, 9, 8, 5)], 5) == "All tuples do not have same length"
    assert candidate([(3, 3, 6), (9, 7, 2, 8)], 1) == "All tuples do not have same length"
    assert candidate([(4, 3), (2, 9)], 3) == "All tuples do not have same length"
    assert candidate([(2, 7), (7, 5)], 1) == "All tuples do not have same length"
    assert candidate([(3, 3), (8, 1)], 4) == "All tuples do not have same length"
    assert candidate([(6, 3), (2, 8)], 2) == "All tuples have same length"
    assert candidate([(6, 5), (8, 6)], 1) == "All tuples do not have same length"
    assert candidate([(3, 3), (7, 2)], 1) == "All tuples do not have same length"
    assert candidate([(2, 5), (6, 4)], 6) == "All tuples do not have same length"
    assert candidate([(6, 6), (5, 2)], 7) == "All tuples do not have same length"
    assert candidate([(6, 5), (5, 6)], 4) == "All tuples do not have same length"
    assert candidate([(1, 5), (1, 6)], 4) == "All tuples do not have same length"
    assert candidate([(2, 6), (2, 7)], 2) == "All tuples have same length"
    assert candidate([(2, 3), (4, 6)], 7) == "All tuples do not have same length"
    assert candidate([(3, 7), (3, 1)], 3) == "All tuples do not have same length"
    assert candidate([(5, 2), (4, 1)], 3) == "All tuples do not have same length"
    assert candidate([(2, 4), (1, 6)], 1) == "All tuples do not have same length"
    assert candidate([(6, 5), (8, 6)], 7) == "All tuples do not have same length"
    assert candidate([(4, 5), (2, 9)], 6) == "All tuples do not have same length"
    assert candidate([(5, 6), (2, 4)], 1) == "All tuples do not have same length"
    assert candidate([(6, 6), (5, 2)], 5) == "All tuples do not have same length"
    assert candidate([(5, 4), (6, 9)], 3) == "All tuples do not have same length"
    assert candidate([(2, 5), (7, 3)], 4) == "All tuples do not have same length"
    assert candidate([(5, 1), (8, 8)], 5) == "All tuples do not have same length"
    assert candidate([(6, 4), (3, 7)], 7) == "All tuples do not have same length"
    assert candidate([(3, 5), (8, 8)], 7) == "All tuples do not have same length"
    assert candidate([(3, 7), (1, 7)], 4) == "All tuples do not have same length"
    assert candidate([(2, 6), (1, 1)], 7) == "All tuples do not have same length"
    assert candidate([(4, 7), (3, 3)], 4) == "All tuples do not have same length"
    assert candidate([(6, 3), (5, 2)], 7) == "All tuples do not have same length"
    assert candidate([(3, 2), (4, 5)], 5) == "All tuples do not have same length"
    assert candidate([(3, 1), (1, 4)], 6) == "All tuples do not have same length"
    assert candidate([(1, 3), (1, 5)], 2) == "All tuples have same length"
    assert candidate([(3, 6), (2, 2)], 4) == "All tuples do not have same length"
    assert candidate([(6, 4), (6, 4)], 7) == "All tuples do not have same length"

if __name__ == '__main__':
    check(get_equal)