from case_MBPP_004 import find_char_long


def check(candidate):
    assert candidate('Please move back to stream') == ['Please', 'move', 'back', 'stream']
    assert candidate('Jing Eco and Tech') == ['Jing', 'Tech']
    assert candidate('Jhingai wulu road Zone 3') == ['Jhingai', 'wulu', 'road', 'Zone']
    assert candidate(" BGBKxLZVVthfphWmiQlSzrk") == ['BGBKxLZVVthfphWmiQlSzrk']
    assert candidate("oamnvNIOEluWpxgZjQMgjU") == ['oamnvNIOEluWpxgZjQMgjU']
    assert candidate("sSAFCZAXyXogXCyFvSVPSokK") == ['sSAFCZAXyXogXCyFvSVPSokK']
    assert candidate("iMfssAbLsbTESTfMgSAulTql") == ['iMfssAbLsbTESTfMgSAulTql']
    assert candidate("kSPCWfEtMHhPiBiBSoDvv") == ['kSPCWfEtMHhPiBiBSoDvv']
    assert candidate("DMqMVHYDsSAWWyKW ndNmUsLUYv") == ['DMqMVHYDsSAWWyKW', 'ndNmUsLUYv']
    assert candidate("GdWBslQdRIsZ pxW Ofysf") == ['GdWBslQdRIsZ', 'Ofysf']
    assert candidate("gLLpeKctHMWjkxjTRsCus") == ['gLLpeKctHMWjkxjTRsCus']
    assert candidate("QXrgeewOnbwmcFUQvqgJAic") == ['QXrgeewOnbwmcFUQvqgJAic']
    assert candidate("ryioUEshBzmGnpDIdOHHJ") == ['ryioUEshBzmGnpDIdOHHJ']
    assert candidate("XnOPHydAzVMZTCQSDKssUcomo") == ['XnOPHydAzVMZTCQSDKssUcomo']
    assert candidate("vpYBYlYpuIzKaHttbXWBrRiOttrz") == ['vpYBYlYpuIzKaHttbXWBrRiOttrz']
    assert candidate("MtxMXTIUVXEFqYpHJnDdLxfYO") == ['MtxMXTIUVXEFqYpHJnDdLxfYO']
    assert candidate("WvmLHJVYZGIDpYoSzFi oT") == ['WvmLHJVYZGIDpYoSzFi']
    assert candidate("yQbwLOngQvQkBIPxPFTKm") == ['yQbwLOngQvQkBIPxPFTKm']
    assert candidate("bcfDiOoWItswdQjAMCjvybetn") == ['bcfDiOoWItswdQjAMCjvybetn']
    assert candidate("zEzrWDnnHQxPCCDAvqgJSzJSiZ") == ['zEzrWDnnHQxPCCDAvqgJSzJSiZ']
    assert candidate("XUMYQigKNsKsyuSXNUxds mCsomL") == ['XUMYQigKNsKsyuSXNUxds', 'mCsomL']
    assert candidate("qudIjtprlcRGtnodTLeqWUqhYDIer") == ['qudIjtprlcRGtnodTLeqWUqhYDIer']
    assert candidate("SyQjtNbykksnaRUwqPi fXa DUn") == ['SyQjtNbykksnaRUwqPi']
    assert candidate("IOT gniYJobPkdtOUlCQ EbJMLeu") == ['gniYJobPkdtOUlCQ', 'EbJMLeu']
    assert candidate("bBjMoMZjEtPuRArhenzwig") == ['bBjMoMZjEtPuRArhenzwig']
    assert candidate("RgiOIGheVJPfpNVhQHeYdvOdyxzUn") == ['RgiOIGheVJPfpNVhQHeYdvOdyxzUn']
    assert candidate("fySkwzWkBMZYQIOHHoubRB") == ['fySkwzWkBMZYQIOHHoubRB']
    assert candidate("VuFUUVThHNlfAqmmmRyvcWAhdx") == ['VuFUUVThHNlfAqmmmRyvcWAhdx']
    assert candidate("TXzjZvYxSKHsXJOcyjtHGttpSAL") == ['TXzjZvYxSKHsXJOcyjtHGttpSAL']
    assert candidate("vYagwqRuUbCSZNKkMYeFKVypKoZlq") == ['vYagwqRuUbCSZNKkMYeFKVypKoZlq']
    assert candidate("voWObMMsZCvwsUvcVuCSVICHxwMmfk") == ['voWObMMsZCvwsUvcVuCSVICHxwMmfk']
    assert candidate("uLKzIMePKMGZumtvTiPcWCrKGPhwh") == ['uLKzIMePKMGZumtvTiPcWCrKGPhwh']
    assert candidate("BFRcHuB VnZvGHnaAOozjBgysw") == ['BFRcHuB', 'VnZvGHnaAOozjBgysw']
    assert candidate("oWBAShXgiCiLtfrWdWqiKH") == ['oWBAShXgiCiLtfrWdWqiKH']
    assert candidate("IssAlvUbCFrGVcpqKuS fZ") == ['IssAlvUbCFrGVcpqKuS']
    assert candidate("ibtxsjUuPbNwztOffYsuWt") == ['ibtxsjUuPbNwztOffYsuWt']
    assert candidate("cBGFZguckCiSAUYoPRRm") == ['cBGFZguckCiSAUYoPRRm']
    assert candidate("CMcrqzrgCBLotDzriXfmf") == ['CMcrqzrgCBLotDzriXfmf']
    assert candidate("cSIYINRSskeZdCMh") == ['cSIYINRSskeZdCMh']
    assert candidate("OlmGgybIpGPtPDrxZsV") == ['OlmGgybIpGPtPDrxZsV']
    assert candidate("XqtuZsSyY AhoC mg") == ['XqtuZsSyY', 'AhoC']
    assert candidate("WYILarumXpvEAeNcHp") == ['WYILarumXpvEAeNcHp']
    assert candidate("QbCEnZJtyqCBCxoiWrzY") == ['QbCEnZJtyqCBCxoiWrzY']
    assert candidate("bBxvbvtObdnWDNkqOet") == ['bBxvbvtObdnWDNkqOet']
    assert candidate("MUiSyjXXtDDuchY") == ['MUiSyjXXtDDuchY']
    assert candidate("ekYCiJJHOkfxEkSoRnVYj") == ['ekYCiJJHOkfxEkSoRnVYj']
    assert candidate("kMAz ESSibVUVDzFe") == ['kMAz', 'ESSibVUVDzFe']
    assert candidate("OxVgakvaDUCVyO") == ['OxVgakvaDUCVyO']
    assert candidate("ljtXwUgoFdVgXnA") == ['ljtXwUgoFdVgXnA']
    assert candidate("XMqBLEJAPTUbhrupv") == ['XMqBLEJAPTUbhrupv']
    assert candidate("mrEr CZHOOH ") == ['mrEr', 'CZHOOH']
    assert candidate("RW aYlcLwlnQEHdNnlHt") == ['aYlcLwlnQEHdNnlHt']
    assert candidate("MhhdfeFEWjtdt") == ['MhhdfeFEWjtdt']
    assert candidate("RDpF QfPcZoQs") == ['RDpF', 'QfPcZoQs']
    assert candidate("ndJvdTjHhtCI") == ['ndJvdTjHhtCI']
    assert candidate("aOsuOMxYiRZAdzWgWbx") == ['aOsuOMxYiRZAdzWgWbx']
    assert candidate("faZRcFXwrFLtmbfqj") == ['faZRcFXwrFLtmbfqj']
    assert candidate("RGmDjHYQVEtX") == ['RGmDjHYQVEtX']
    assert candidate("ScyqmPCFPTnRpXJxyvJP") == ['ScyqmPCFPTnRpXJxyvJP']
    assert candidate("fLgAvYkrzHDP") == ['fLgAvYkrzHDP']
    assert candidate("yqwdggznmFmSRdftt") == ['yqwdggznmFmSRdftt']
    assert candidate("GatHmsxjDGF SdVk") == ['GatHmsxjDGF', 'SdVk']
    assert candidate("sYWVPMJsrIMzGZR Yb") == ['sYWVPMJsrIMzGZR']
    assert candidate(" ADjwOiAWjTln ") == ['ADjwOiAWjTln']
    assert candidate("kLWtMQNjpnPMU") == ['kLWtMQNjpnPMU']
    assert candidate("veWSCrvwgmWogCZGv") == ['veWSCrvwgmWogCZGv']
    assert candidate("VuHyLuVXNCEIyCJmwnXC") == ['VuHyLuVXNCEIyCJmwnXC']
    assert candidate("RYKFMhSoROfdWIGH") == ['RYKFMhSoROfdWIGH']
    assert candidate("WsLHAYwhNOSHVGNDCv") == ['WsLHAYwhNOSHVGNDCv']
    assert candidate("bmCMVkuUtWFfYmsY4gFC1YUjYX6") == ['bmCMVkuUtWFfYmsY4gFC1YUjYX6']
    assert candidate("KoiP5tipiG5QlacNMb85k3T") == ['KoiP5tipiG5QlacNMb85k3T']
    assert candidate("iMrfyQgsFrmLHC mP3mdqrLVz") == ['iMrfyQgsFrmLHC', 'mP3mdqrLVz']
    assert candidate("6NiziL5Z4m4514ctvbYX3VxtB1cN") == ['6NiziL5Z4m4514ctvbYX3VxtB1cN']
    assert candidate("RwjqCngF2 bD5wb 8WqE5xXViiiL") == ['RwjqCngF2', 'bD5wb', '8WqE5xXViiiL']
    assert candidate("O4jDlqmnCyVFco8RNsaIeeXvJciot") == ['O4jDlqmnCyVFco8RNsaIeeXvJciot']
    assert candidate("kyhvz7qJomhxxSS3vu ZNL") == ['kyhvz7qJomhxxSS3vu']
    assert candidate("ggQudeSwAEr6n88igRT9py7ZuJ") == ['ggQudeSwAEr6n88igRT9py7ZuJ']
    assert candidate("gKMiRILsylpickrxtCOHhnBhB ") == ['gKMiRILsylpickrxtCOHhnBhB']
    assert candidate("2RQhS3holFQbf1WVTon8loqidM") == ['2RQhS3holFQbf1WVTon8loqidM']
    assert candidate("9JSvLjie4UCPUYH 2ZL2ydwun") == ['9JSvLjie4UCPUYH', '2ZL2ydwun']
    assert candidate("evBxZWXd6mWPU8dL97gzf") == ['evBxZWXd6mWPU8dL97gzf']
    assert candidate("4tgLUTNhQeT2xuaeGk96rXP") == ['4tgLUTNhQeT2xuaeGk96rXP']
    assert candidate("5Dj0NMcqk Dtu5enQ42RnDKdBcOX") == ['5Dj0NMcqk', 'Dtu5enQ42RnDKdBcOX']
    assert candidate(" Zsd4OxG8uostqSAYeQzs6jf") == ['Zsd4OxG8uostqSAYeQzs6jf']
    assert candidate("ty1pSwdTDkRLeh0inWf q") == ['ty1pSwdTDkRLeh0inWf']
    assert candidate("nEzuAjwEnAxa6q9HChSwj8 gJMmM") == ['nEzuAjwEnAxa6q9HChSwj8', 'gJMmM']
    assert candidate("Y4zHrho2ouwMyW830JSFp") == ['Y4zHrho2ouwMyW830JSFp']
    assert candidate("YIi7EhQTOvmI0sL0tASvJeiNYRmfw") == ['YIi7EhQTOvmI0sL0tASvJeiNYRmfw']
    assert candidate("rggZeq1Q0 cwEmit5FlgCI ") == ['rggZeq1Q0', 'cwEmit5FlgCI']
    assert candidate("KkxFPRfGyaj1xti6kigB5s") == ['KkxFPRfGyaj1xti6kigB5s']
    assert candidate("NkIxwu2l7xaIXuZCGG unRhU1S") == ['NkIxwu2l7xaIXuZCGG', 'unRhU1S']
    assert candidate("mq7w8BQtAKp8jlMJTgo8DgkYeR5xJp") == ['mq7w8BQtAKp8jlMJTgo8DgkYeR5xJp']
    assert candidate("Wejmw4AUuyKLxwvEa4u3Z8hF") == ['Wejmw4AUuyKLxwvEa4u3Z8hF']
    assert candidate("y4MDozGfjTAN 32vA91SJpU") == ['y4MDozGfjTAN', '32vA91SJpU']
    assert candidate("jErEXzWh T I3F3s1YgQ9ZRyy") == ['jErEXzWh', 'I3F3s1YgQ9ZRyy']
    assert candidate("NBb6QuYgC0sFvvt0faDsu") == ['NBb6QuYgC0sFvvt0faDsu']
    assert candidate("EZl4C3z1r8AI8SUN37UK4J") == ['EZl4C3z1r8AI8SUN37UK4J']
    assert candidate("kPG1vOyH9c07X9yv88JyY aIfB6") == ['kPG1vOyH9c07X9yv88JyY', 'aIfB6']
    assert candidate(" 3HzHRB4mh2NVCmfO9vgWfzp") == ['3HzHRB4mh2NVCmfO9vgWfzp']
    assert candidate("JfN9mdKj3Kfv29rMNswWJYpfW3WTi") == ['JfN9mdKj3Kfv29rMNswWJYpfW3WTi']
    assert candidate("ui7 OLqnKFX1RZHlShM7 6") == ['OLqnKFX1RZHlShM7']
    assert candidate("z4k9ubpb1KgR5kyVxne8b") == ['z4k9ubpb1KgR5kyVxne8b']

if __name__ == '__main__':
    check(find_char_long)