from case_MBPP_181 import find_lucas


def check(candidate):
    assert candidate(9) == 76
    assert candidate(4) == 7
    assert candidate(3) == 4
    assert candidate(11) == 199
    assert candidate(10) == 123
    assert candidate(6) == 18
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(10) == 123
    assert candidate(4) == 7
    assert candidate(7) == 29
    assert candidate(13) == 521
    assert candidate(12) == 322
    assert candidate(11) == 199
    assert candidate(12) == 322
    assert candidate(8) == 47
    assert candidate(9) == 76
    assert candidate(6) == 18
    assert candidate(10) == 123
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(8) == 47
    assert candidate(4) == 7
    assert candidate(8) == 47
    assert candidate(7) == 29
    assert candidate(5) == 11
    assert candidate(5) == 11
    assert candidate(13) == 521
    assert candidate(14) == 843
    assert candidate(4) == 7
    assert candidate(5) == 11
    assert candidate(9) == 76
    assert candidate(5) == 11
    assert candidate(6) == 18
    assert candidate(14) == 843
    assert candidate(8) == 47
    assert candidate(1) == 1
    assert candidate(9) == 76
    assert candidate(4) == 7
    assert candidate(8) == 47
    assert candidate(1) == 1
    assert candidate(4) == 7
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(1) == 1
    assert candidate(4) == 7
    assert candidate(1) == 1
    assert candidate(8) == 47
    assert candidate(4) == 7
    assert candidate(1) == 1
    assert candidate(4) == 7
    assert candidate(6) == 18
    assert candidate(2) == 3
    assert candidate(2) == 3
    assert candidate(4) == 7
    assert candidate(2) == 3
    assert candidate(3) == 4
    assert candidate(8) == 47
    assert candidate(2) == 3
    assert candidate(5) == 11
    assert candidate(9) == 76
    assert candidate(3) == 4
    assert candidate(2) == 3
    assert candidate(8) == 47
    assert candidate(5) == 11
    assert candidate(7) == 29
    assert candidate(5) == 11
    assert candidate(8) == 47
    assert candidate(5) == 11
    assert candidate(2) == 3
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(4) == 7
    assert candidate(8) == 47
    assert candidate(3) == 4
    assert candidate(1) == 1
    assert candidate(6) == 18
    assert candidate(5) == 11
    assert candidate(3) == 4
    assert candidate(3) == 4
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(2) == 3
    assert candidate(3) == 4
    assert candidate(3) == 4
    assert candidate(8) == 47
    assert candidate(5) == 11
    assert candidate(3) == 4
    assert candidate(1) == 1
    assert candidate(4) == 7
    assert candidate(8) == 47
    assert candidate(5) == 11
    assert candidate(5) == 11
    assert candidate(7) == 29
    assert candidate(6) == 18
    assert candidate(8) == 47
    assert candidate(7) == 29
    assert candidate(7) == 29
    assert candidate(8) == 47
    assert candidate(8) == 47
    assert candidate(8) == 47
    assert candidate(4) == 7

if __name__ == '__main__':
    check(find_lucas)