from case_MBPP_001 import is_not_prime


def check(candidate):
    assert candidate(2) == False
    assert candidate(10) == True
    assert candidate(35) == True
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(3) == False
    assert candidate(4) == True
    assert candidate(5) == False
    assert candidate(6) == True
    assert candidate(2) == False
    assert candidate(5) == False
    assert candidate(4) == True
    assert candidate(6) == True
    assert candidate(7) == False
    assert candidate(2) == False
    assert candidate(2) == False
    assert candidate(5) == False
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(2) == False
    assert candidate(1) == False
    assert candidate(6) == True
    assert candidate(2) == False
    assert candidate(7) == False
    assert candidate(3) == False
    assert candidate(6) == True
    assert candidate(3) == False
    assert candidate(1) == False
    assert candidate(1) == False
    assert candidate(1) == False
    assert candidate(6) == True
    assert candidate(2) == False
    assert candidate(3) == False
    assert candidate(7) == False
    assert candidate(6) == True
    assert candidate(6) == True
    assert candidate(10) == True
    assert candidate(5) == False
    assert candidate(11) == False
    assert candidate(5) == False
    assert candidate(14) == True
    assert candidate(11) == False
    assert candidate(7) == False
    assert candidate(14) == True
    assert candidate(10) == True
    assert candidate(8) == True
    assert candidate(9) == True
    assert candidate(6) == True
    assert candidate(5) == False
    assert candidate(13) == False
    assert candidate(13) == False
    assert candidate(14) == True
    assert candidate(5) == False
    assert candidate(14) == True
    assert candidate(11) == False
    assert candidate(15) == True
    assert candidate(6) == True
    assert candidate(7) == False
    assert candidate(11) == False
    assert candidate(15) == True
    assert candidate(6) == True
    assert candidate(9) == True
    assert candidate(12) == True
    assert candidate(15) == True
    assert candidate(7) == False
    assert candidate(9) == True
    assert candidate(12) == True
    assert candidate(15) == True
    assert candidate(10) == True
    assert candidate(40) == True
    assert candidate(36) == True
    assert candidate(31) == False
    assert candidate(40) == True
    assert candidate(36) == True
    assert candidate(34) == True
    assert candidate(35) == True
    assert candidate(31) == False
    assert candidate(30) == True
    assert candidate(39) == True
    assert candidate(30) == True
    assert candidate(35) == True
    assert candidate(31) == False
    assert candidate(37) == False
    assert candidate(30) == True
    assert candidate(31) == False
    assert candidate(35) == True
    assert candidate(39) == True
    assert candidate(32) == True
    assert candidate(36) == True
    assert candidate(39) == True
    assert candidate(32) == True
    assert candidate(30) == True
    assert candidate(38) == True
    assert candidate(36) == True
    assert candidate(30) == True
    assert candidate(34) == True
    assert candidate(33) == True
    assert candidate(30) == True
    assert candidate(34) == True
    assert candidate(31) == False
    assert candidate(40) == True
    assert candidate(34) == True

if __name__ == '__main__':
    check(is_not_prime)