from case_MBPP_354 import replace_specialchar


def check(candidate):
    assert candidate('Python language, Programming language.')==('Python:language::Programming:language:')
    assert candidate('a b c,d e f')==('a:b:c:d:e:f')
    assert candidate('ram reshma,ram rahim')==('ram:reshma:ram:rahim')
    assert candidate("lCzCRMK.LzmTnDVvfXIgVQu FEcCOQzZQhPFAa") == "lCzCRMK:LzmTnDVvfXIgVQu:FEcCOQzZQhPFAa"
    assert candidate("P. uRMXzvcl.hrYwlV.ysmGNDfxyAkZxZikux") == "P::uRMXzvcl:hrYwlV:ysmGNDfxyAkZxZikux"
    assert candidate("ty EIUQzAHlewDvGrrICLNEleYSxhF.eOAhSokg") == "ty:EIUQzAHlewDvGrrICLNEleYSxhF:eOAhSokg"
    assert candidate(" uYcUUhjaZwRqBHyoEEnZofi.rwRxjaXwfFwdVvT") == ":uYcUUhjaZwRqBHyoEEnZofi:rwRxjaXwfFwdVvT"
    assert candidate("bz,kWJlqtlyGSGVnuWTtum.WjYJElomSh lIUbn") == "bz:kWJlqtlyGSGVnuWTtum:WjYJElomSh:lIUbn"
    assert candidate("XeOzQEzhp,QHJi,lxSTk rdhKjMBpkvvwOE") == "XeOzQEzhp:QHJi:lxSTk:rdhKjMBpkvvwOE"
    assert candidate("jum.kmrtILSSJrSUgqcddVH,hDffdXlSGKPr") == "jum:kmrtILSSJrSUgqcddVH:hDffdXlSGKPr"
    assert candidate("EWhrhMElLsvCQWjOqAbqaK lLerqBAyY.QF GSJm") == "EWhrhMElLsvCQWjOqAbqaK:lLerqBAyY:QF:GSJm"
    assert candidate("lHurcVQhNSPSn,AyOcncubF.bzCj.KmNC qzVTlu") == "lHurcVQhNSPSn:AyOcncubF:bzCj:KmNC:qzVTlu"
    assert candidate("cwLcuGNKNKiYvLgD bgsgBSbxwDaB.JuXanwPpClAU") == "cwLcuGNKNKiYvLgD:bgsgBSbxwDaB:JuXanwPpClAU"
    assert candidate("qQZLmfIkhtssHvyObdev,fWSDSroInFxnNHMMV") == "qQZLmfIkhtssHvyObdev:fWSDSroInFxnNHMMV"
    assert candidate("iiyCOuuqDdueQzEXtjOJM t.vabxkkgAcXXtdFb") == "iiyCOuuqDdueQzEXtjOJM:t:vabxkkgAcXXtdFb"
    assert candidate(" jhitjoIiXXtpDGHLZKAtqlKXInbABUvPrSiS") == ":jhitjoIiXXtpDGHLZKAtqlKXInbABUvPrSiS"
    assert candidate("aeBefEwbWRGpCGDKzj,yvAhxMiQZYJdTmUvYknXyOn") == "aeBefEwbWRGpCGDKzj:yvAhxMiQZYJdTmUvYknXyOn"
    assert candidate("rswJenQCeaKozQXYmcrnqHOUOqSWtDEGh") == "rswJenQCeaKozQXYmcrnqHOUOqSWtDEGh"
    assert candidate("DoxjGgayMnF qAk.EEVFzewMbik.nGvjmmDsPDdbh") == "DoxjGgayMnF:qAk:EEVFzewMbik:nGvjmmDsPDdbh"
    assert candidate(".YxQAThWcG. dPRPfuhYnnFyAi,CUhgvsiFiw") == ":YxQAThWcG::dPRPfuhYnnFyAi:CUhgvsiFiw"
    assert candidate("VwasvfZzrLJuGqercDSWejoKwebWkigLBerba") == "VwasvfZzrLJuGqercDSWejoKwebWkigLBerba"
    assert candidate(",ogDBJugjhLfZ,ecwm.dfPfMTEwiqEBDkpNThUIV") == ":ogDBJugjhLfZ:ecwm:dfPfMTEwiqEBDkpNThUIV"
    assert candidate("zOMBeVURNIYTulTNgzdnFxWhupXLBLX,,Mo,XfFMUZ") == "zOMBeVURNIYTulTNgzdnFxWhupXLBLX::Mo:XfFMUZ"
    assert candidate("nJUc.lOBsTrZYUkYIcppGGONme,YoCZlixUIxnl") == "nJUc:lOBsTrZYUkYIcppGGONme:YoCZlixUIxnl"
    assert candidate("nsimfWckBcfFCxQMSdTYCBSyCwCXRpxTkbZ") == "nsimfWckBcfFCxQMSdTYCBSyCwCXRpxTkbZ"
    assert candidate("hdUexDaOGOrEA.wezXTX,PPdESJdUuFDt") == "hdUexDaOGOrEA:wezXTX:PPdESJdUuFDt"
    assert candidate("QAXXmeZfKQukHGeHYfRxjYXmCCBuqdESVvXHDMJy") == "QAXXmeZfKQukHGeHYfRxjYXmCCBuqdESVvXHDMJy"
    assert candidate("fgiPjFItEoCRwLxMpWtqbLSSJJOhwbqgmiStlujm") == "fgiPjFItEoCRwLxMpWtqbLSSJJOhwbqgmiStlujm"
    assert candidate("JlYV okRroxFzHDDkFwbytTKfwpYyKeNS qpEa ") == "JlYV:okRroxFzHDDkFwbytTKfwpYyKeNS:qpEa:"
    assert candidate("aVlhtlvtpfKSdzbJznUSEwYRlijwEkg..") == "aVlhtlvtpfKSdzbJznUSEwYRlijwEkg::"
    assert candidate("aykpAUHoVPJrA.ihUrOmuSbdJGbcXeHMrpND") == "aykpAUHoVPJrA:ihUrOmuSbdJGbcXeHMrpND"
    assert candidate("YjKdSQZprSUK.DrsKFvalUeOwYElqOkjpRMc") == "YjKdSQZprSUK:DrsKFvalUeOwYElqOkjpRMc"
    assert candidate("QQagFKCile.qyeypEjUliTKiVtmrgpNFL.H") == "QQagFKCile:qyeypEjUliTKiVtmrgpNFL:H"
    assert candidate("ofsYhKWMFZIhvKyXQuINhRbVdWrHsFnGt.jBESR") == "ofsYhKWMFZIhvKyXQuINhRbVdWrHsFnGt:jBESR"
    assert candidate("KaeoSWQ,.yRNFZTHnYOZhaacPyj GgEtZkJCSR") == "KaeoSWQ::yRNFZTHnYOZhaacPyj:GgEtZkJCSR"
    assert candidate("UPAncfxJjHfyNyoVTjmWKh VYDOXhsDHskrwo.cU") == "UPAncfxJjHfyNyoVTjmWKh:VYDOXhsDHskrwo:cU"
    assert candidate("qvblqnbdayienr") == "qvblqnbdayienr"
    assert candidate(" mziqzwwu  z") == ":mziqzwwu::z"
    assert candidate("alsni,bnmqrht") == "alsni:bnmqrht"
    assert candidate("wvnawfzklqznlw") == "wvnawfzklqznlw"
    assert candidate("entdztpuiztof") == "entdztpuiztof"
    assert candidate("dcwcbwsmtozobdw") == "dcwcbwsmtozobdw"
    assert candidate("kfdyawm xdgk") == "kfdyawm:xdgk"
    assert candidate("mqaxxj") == "mqaxxj"
    assert candidate("l bgxqu") == "l:bgxqu"
    assert candidate("mzkf fnydqg") == "mzkf:fnydqg"
    assert candidate("iwtinuhlk ") == "iwtinuhlk:"
    assert candidate("mvrdrqf,") == "mvrdrqf:"
    assert candidate("nkis,stmtmchq") == "nkis:stmtmchq"
    assert candidate("oxnjrv") == "oxnjrv"
    assert candidate("thgcizyhp") == "thgcizyhp"
    assert candidate("qxghuafuurmc") == "qxghuafuurmc"
    assert candidate("nepyykilivr") == "nepyykilivr"
    assert candidate("edmolxjya") == "edmolxjya"
    assert candidate("whcnlmabilygcx") == "whcnlmabilygcx"
    assert candidate("rnjwdybpfwm") == "rnjwdybpfwm"
    assert candidate("lmjgwimqz  b") == "lmjgwimqz::b"
    assert candidate("kh,gzbhqcvgeda") == "kh:gzbhqcvgeda"
    assert candidate("ztdtejkgtmg mtu") == "ztdtejkgtmg:mtu"
    assert candidate("eueqjay a") == "eueqjay:a"
    assert candidate("lr,cuke") == "lr:cuke"
    assert candidate("zekpyiueezn") == "zekpyiueezn"
    assert candidate("lzqqhedfm") == "lzqqhedfm"
    assert candidate("akltqzsrot ") == "akltqzsrot:"
    assert candidate("fkrpekpf xplc") == "fkrpekpf:xplc"
    assert candidate("az,b,no hgwwdwm") == "az:b:no:hgwwdwm"
    assert candidate("fjhgo,cudx,") == "fjhgo:cudx:"
    assert candidate(" ckf,kevyiwcvaz") == ":ckf:kevyiwcvaz"
    assert candidate("zjirmxlu") == "zjirmxlu"
    assert candidate("kfxasluwzgruezinou") == "kfxasluwzgruezinou"
    assert candidate("isx baqwdxn,bxc") == "isx:baqwdxn:bxc"
    assert candidate("pujrikmhxoxxxymqhfojppip") == "pujrikmhxoxxxymqhfojppip"
    assert candidate("vblorrpypaviafnb") == "vblorrpypaviafnb"
    assert candidate("qq w,tyzuctgggaqelklmncf") == "qq:w:tyzuctgggaqelklmncf"
    assert candidate("tzkfbllrgdxnabwl") == "tzkfbllrgdxnabwl"
    assert candidate("rlplvtcygahvv,z") == "rlplvtcygahvv:z"
    assert candidate("vxtnbabnzdpybx,utfrgnh") == "vxtnbabnzdpybx:utfrgnh"
    assert candidate("kmqxxjsuft ipvevjez") == "kmqxxjsuft:ipvevjez"
    assert candidate("jvqnqghzyldxbkzkl,") == "jvqnqghzyldxbkzkl:"
    assert candidate("obtarmpskzcdidvyberd") == "obtarmpskzcdidvyberd"
    assert candidate("jwod,,blahfuztkqzv") == "jwod::blahfuztkqzv"
    assert candidate("g ,hgdrfajzh,opdg") == "g::hgdrfajzh:opdg"
    assert candidate("jtrepglcjarewde,s") == "jtrepglcjarewde:s"
    assert candidate("ziitiolwtambosv") == "ziitiolwtambosv"
    assert candidate("b yinhlnpomyqfuunockizb") == "b:yinhlnpomyqfuunockizb"
    assert candidate("uufcfyixrotxtiw") == "uufcfyixrotxtiw"
    assert candidate("w,xdkyijhtxtvheeaqlv") == "w:xdkyijhtxtvheeaqlv"
    assert candidate("monvclxrkmeekvgsydb") == "monvclxrkmeekvgsydb"
    assert candidate("zv,sbbdcrviykonsj,mpgnwd") == "zv:sbbdcrviykonsj:mpgnwd"
    assert candidate("dkfwjuetcnwkkicnm") == "dkfwjuetcnwkkicnm"
    assert candidate("igqbe w  bxdrcqc ej") == "igqbe:w::bxdrcqc:ej"
    assert candidate("fhhhcyyzkchlx,hnsjzhe") == "fhhhcyyzkchlx:hnsjzhe"
    assert candidate("boewmqhbotrdhbvryuvuwuj") == "boewmqhbotrdhbvryuvuwuj"
    assert candidate("jqgbyfkqvzd rkjbm") == "jqgbyfkqvzd:rkjbm"
    assert candidate("kzawhybq jnhoimudkb") == "kzawhybq:jnhoimudkb"
    assert candidate("wkunnkedvvuzoilndnbahw") == "wkunnkedvvuzoilndnbahw"
    assert candidate("junbslpgbvyfwjbysihnx,s") == "junbslpgbvyfwjbysihnx:s"
    assert candidate("wscqkihfkxy,cbpyn ,c,ox") == "wscqkihfkxy:cbpyn::c:ox"
    assert candidate("ugamtvvspj,eigd") == "ugamtvvspj:eigd"
    assert candidate("z ncvpxmtpacwuyp,b,x") == "z:ncvpxmtpacwuyp:b:x"
    assert candidate("dsssro,lvxxljhs") == "dsssro:lvxxljhs"
    assert candidate("yamk  igpnjiwsnjbpd fk") == "yamk::igpnjiwsnjbpd:fk"

if __name__ == '__main__':
    check(replace_specialchar)