from case_MBPP_034 import word_len


def check(candidate):
    assert candidate("Hadoop") == False
    assert candidate("great") == True
    assert candidate("structure") == True
    assert candidate("kGKTbhZoZUz") == True
    assert candidate("poAJmXvi") == False
    assert candidate("pHVCpqRlg") == True
    assert candidate("tmd") == True
    assert candidate("eHz") == True
    assert candidate("pApTiTyXPI") == False
    assert candidate("gLNXoAcqV") == True
    assert candidate("eyoH") == False
    assert candidate("GlLutVZmf") == True
    assert candidate("zvdCGMeApvb") == True
    assert candidate("MQOIBz") == False
    assert candidate("wXwyAPHJV") == True
    assert candidate("HNiLcvBp") == False
    assert candidate("UAUJf") == True
    assert candidate("pJdFTNnl") == False
    assert candidate("TbqQUNirrPM") == True
    assert candidate("pbtYEF") == False
    assert candidate("upesUAjl") == False
    assert candidate("HseKlJzv") == False
    assert candidate("Hrx") == True
    assert candidate("JtGPQpm") == True
    assert candidate("qvBjNsZvz") == True
    assert candidate("rjIzJmCsvU") == False
    assert candidate("kYFAfzXeCE") == False
    assert candidate("CEFGdHD") == True
    assert candidate("klSFyIgvUNGa") == False
    assert candidate("lfuZSwgUpErH") == False
    assert candidate("IhAogIqdW") == True
    assert candidate("ctJjzIBN") == False
    assert candidate("HSUUTFyiH") == True
    assert candidate("nno") == True
    assert candidate("PlPR") == False
    assert candidate("aSGAUSi") == True
    assert candidate("ixzuykzwu") == True
    assert candidate("rwv") == True
    assert candidate("wpndioe") == True
    assert candidate("jfvyym") == False
    assert candidate("ddelqqe") == True
    assert candidate("eceudxu") == True
    assert candidate("lywqwwzq") == False
    assert candidate("scn") == True
    assert candidate("bfl") == True
    assert candidate("ejeeci") == False
    assert candidate("dxk") == True
    assert candidate("taj") == True
    assert candidate("gdipntrk") == False
    assert candidate("yfjobpca") == False
    assert candidate("wbq") == True
    assert candidate("nga") == True
    assert candidate("wjlen") == True
    assert candidate("ihjcr") == True
    assert candidate("snjaprq") == True
    assert candidate("rqmtt") == True
    assert candidate("keqovbkw") == False
    assert candidate("tna") == True
    assert candidate("kijuozju") == False
    assert candidate("sqytprkw") == False
    assert candidate("ohdres") == False
    assert candidate("uno") == True
    assert candidate("dci") == True
    assert candidate("hjhcad") == False
    assert candidate("ulsswm") == False
    assert candidate("gemxip") == False
    assert candidate("paief") == True
    assert candidate("oqa") == True
    assert candidate("oshfyyjv") == False
    assert candidate("lkpcidca") == False
    assert candidate("fzzsrml") == True
    assert candidate("tlezzmav") == False
    assert candidate("lsanupsvlv") == False
    assert candidate("gckyxnu") == True
    assert candidate("wtdszjzcjoljfp") == False
    assert candidate("jlxzlcegpzilfb") == False
    assert candidate("abcvhapotaq") == True
    assert candidate("okxfdviyo") == True
    assert candidate("ihyxjgu") == True
    assert candidate("pngnfndjog") == False
    assert candidate("xzsalkhniwxxb") == True
    assert candidate("ysmoipdesfqk") == False
    assert candidate("wpbobysnkks") == True
    assert candidate("kyqryozuwaw") == True
    assert candidate("kmckgswbu") == True
    assert candidate("qihveydwrbuqms") == False
    assert candidate("dxpwpwzc") == False
    assert candidate("lyafogqnvfk") == True
    assert candidate("knjdyt") == False
    assert candidate("tnowjqi") == True
    assert candidate("srbsmygyq") == True
    assert candidate("lgwjkec") == True
    assert candidate("xgypzc") == False
    assert candidate("ogngdhhpv") == True
    assert candidate("npfktfhvpjrqkdl") == True
    assert candidate("ngvjaemhrbkkpe") == False
    assert candidate("tzkibftv") == False
    assert candidate("mppybawtb") == True
    assert candidate("fwugllwnshfry") == True
    assert candidate("mgzlwbhdmt") == False
    assert candidate("daitrhkcpu") == False
    assert candidate("opnbeymrepb") == True

if __name__ == '__main__':
    check(word_len)