from case_MBPP_177 import string_to_tuple


def check(candidate):
    assert candidate("python 3.0")==('p', 'y', 't', 'h', 'o', 'n', '3', '.', '0')
    assert candidate("item1")==('i', 't', 'e', 'm', '1')
    assert candidate("15.10")==('1', '5', '.', '1', '0')
    assert candidate("lzsz6n8s0v4hql") == ('l', 'z', 's', 'z', '6', 'n', '8', 's', '0', 'v', '4', 'h', 'q', 'l')
    assert candidate("h567ysby7u7") == ('h', '5', '6', '7', 'y', 's', 'b', 'y', '7', 'u', '7')
    assert candidate("w8 06lx3 ") == ('w', '8', '0', '6', 'l', 'x', '3')
    assert candidate("m7nbeqzj3mt") == ('m', '7', 'n', 'b', 'e', 'q', 'z', 'j', '3', 'm', 't')
    assert candidate("p34upaj07tizc") == ('p', '3', '4', 'u', 'p', 'a', 'j', '0', '7', 't', 'i', 'z', 'c')
    assert candidate("vgt042sh7ct") == ('v', 'g', 't', '0', '4', '2', 's', 'h', '7', 'c', 't')
    assert candidate("2e gu8d2w1fw8wk") == ('2', 'e', 'g', 'u', '8', 'd', '2', 'w', '1', 'f', 'w', '8', 'w', 'k')
    assert candidate("2si0..yjso82") == ('2', 's', 'i', '0', '.', '.', 'y', 'j', 's', 'o', '8', '2')
    assert candidate("qg6vg7rkx6f") == ('q', 'g', '6', 'v', 'g', '7', 'r', 'k', 'x', '6', 'f')
    assert candidate("b3na2xxqqoed") == ('b', '3', 'n', 'a', '2', 'x', 'x', 'q', 'q', 'o', 'e', 'd')
    assert candidate("3yvs.fyqcu5p") == ('3', 'y', 'v', 's', '.', 'f', 'y', 'q', 'c', 'u', '5', 'p')
    assert candidate("u8dbzotkl6") == ('u', '8', 'd', 'b', 'z', 'o', 't', 'k', 'l', '6')
    assert candidate("yztn9hl49if5ket") == ('y', 'z', 't', 'n', '9', 'h', 'l', '4', '9', 'i', 'f', '5', 'k', 'e', 't')
    assert candidate("9ix53mwd") == ('9', 'i', 'x', '5', '3', 'm', 'w', 'd')
    assert candidate("isprtq") == ('i', 's', 'p', 'r', 't', 'q')
    assert candidate("131do39 vdsjm5d") == ('1', '3', '1', 'd', 'o', '3', '9', 'v', 'd', 's', 'j', 'm', '5', 'd')
    assert candidate("x4oz14ks0c") == ('x', '4', 'o', 'z', '1', '4', 'k', 's', '0', 'c')
    assert candidate("p33p3y ") == ('p', '3', '3', 'p', '3', 'y')
    assert candidate("5omxxsrrq") == ('5', 'o', 'm', 'x', 'x', 's', 'r', 'r', 'q')
    assert candidate("epl6aw48sgu2me") == ('e', 'p', 'l', '6', 'a', 'w', '4', '8', 's', 'g', 'u', '2', 'm', 'e')
    assert candidate(".okc6wp9fj.") == ('.', 'o', 'k', 'c', '6', 'w', 'p', '9', 'f', 'j', '.')
    assert candidate("iu04jdq3rkwr") == ('i', 'u', '0', '4', 'j', 'd', 'q', '3', 'r', 'k', 'w', 'r')
    assert candidate("t008u.2at7e492") == ('t', '0', '0', '8', 'u', '.', '2', 'a', 't', '7', 'e', '4', '9', '2')
    assert candidate("8d.i7f") == ('8', 'd', '.', 'i', '7', 'f')
    assert candidate("f72wa38lhgka.ad") == ('f', '7', '2', 'w', 'a', '3', '8', 'l', 'h', 'g', 'k', 'a', '.', 'a', 'd')
    assert candidate("6ks7z097jknd") == ('6', 'k', 's', '7', 'z', '0', '9', '7', 'j', 'k', 'n', 'd')
    assert candidate(" zlu471w7 2c9r") == ('z', 'l', 'u', '4', '7', '1', 'w', '7', '2', 'c', '9', 'r')
    assert candidate("gw178kria3us06") == ('g', 'w', '1', '7', '8', 'k', 'r', 'i', 'a', '3', 'u', 's', '0', '6')
    assert candidate("7sp32b1ell") == ('7', 's', 'p', '3', '2', 'b', '1', 'e', 'l', 'l')
    assert candidate("n1bg22th02mzum") == ('n', '1', 'b', 'g', '2', '2', 't', 'h', '0', '2', 'm', 'z', 'u', 'm')
    assert candidate("su tlc35rr8") == ('s', 'u', 't', 'l', 'c', '3', '5', 'r', 'r', '8')
    assert candidate("kqtp7r.xsvrt8") == ('k', 'q', 't', 'p', '7', 'r', '.', 'x', 's', 'v', 'r', 't', '8')
    assert candidate("2zsc0qx.") == ('2', 'z', 's', 'c', '0', 'q', 'x', '.')
    assert candidate("j87q") == ('j', '8', '7', 'q')
    assert candidate("d6ue") == ('d', '6', 'u', 'e')
    assert candidate("hur") == ('h', 'u', 'r')
    assert candidate("cv0") == ('c', 'v', '0')
    assert candidate("9xrbheb") == ('9', 'x', 'r', 'b', 'h', 'e', 'b')
    assert candidate("cvc") == ('c', 'v', 'c')
    assert candidate("q5kyny") == ('q', '5', 'k', 'y', 'n', 'y')
    assert candidate("piz6w") == ('p', 'i', 'z', '6', 'w')
    assert candidate("z5slr2") == ('z', '5', 's', 'l', 'r', '2')
    assert candidate("apa1") == ('a', 'p', 'a', '1')
    assert candidate("pjp1nw7") == ('p', 'j', 'p', '1', 'n', 'w', '7')
    assert candidate("8jptp4tc") == ('8', 'j', 'p', 't', 'p', '4', 't', 'c')
    assert candidate("k46hkhw") == ('k', '4', '6', 'h', 'k', 'h', 'w')
    assert candidate("oio542pt") == ('o', 'i', 'o', '5', '4', '2', 'p', 't')
    assert candidate("udo") == ('u', 'd', 'o')
    assert candidate("r14karhk") == ('r', '1', '4', 'k', 'a', 'r', 'h', 'k')
    assert candidate("q6rp2") == ('q', '6', 'r', 'p', '2')
    assert candidate("yrydu5u") == ('y', 'r', 'y', 'd', 'u', '5', 'u')
    assert candidate("tt28hqwd") == ('t', 't', '2', '8', 'h', 'q', 'w', 'd')
    assert candidate("7ueocsg") == ('7', 'u', 'e', 'o', 'c', 's', 'g')
    assert candidate("2nva") == ('2', 'n', 'v', 'a')
    assert candidate("w8f0gwctm") == ('w', '8', 'f', '0', 'g', 'w', 'c', 't', 'm')
    assert candidate("ud5ct") == ('u', 'd', '5', 'c', 't')
    assert candidate("4ujxaw") == ('4', 'u', 'j', 'x', 'a', 'w')
    assert candidate("kqua5cg") == ('k', 'q', 'u', 'a', '5', 'c', 'g')
    assert candidate("zgaljxa") == ('z', 'g', 'a', 'l', 'j', 'x', 'a')
    assert candidate("3e0pwinzi") == ('3', 'e', '0', 'p', 'w', 'i', 'n', 'z', 'i')
    assert candidate("rln92") == ('r', 'l', 'n', '9', '2')
    assert candidate("2wp1f") == ('2', 'w', 'p', '1', 'f')
    assert candidate("08v") == ('0', '8', 'v')
    assert candidate("sssbsb") == ('s', 's', 's', 'b', 's', 'b')
    assert candidate("43vl") == ('4', '3', 'v', 'l')
    assert candidate("aho5") == ('a', 'h', 'o', '5')
    assert candidate("686354361") == ('6', '8', '6', '3', '5', '4', '3', '6', '1')
    assert candidate("312297095") == ('3', '1', '2', '2', '9', '7', '0', '9', '5')
    assert candidate("85072") == ('8', '5', '0', '7', '2')
    assert candidate("6.2500") == ('6', '.', '2', '5', '0', '0')
    assert candidate("99980.1") == ('9', '9', '9', '8', '0', '.', '1')
    assert candidate("28969168") == ('2', '8', '9', '6', '9', '1', '6', '8')
    assert candidate("880") == ('8', '8', '0')
    assert candidate(".2139804") == ('.', '2', '1', '3', '9', '8', '0', '4')
    assert candidate("554.") == ('5', '5', '4', '.')
    assert candidate("294069") == ('2', '9', '4', '0', '6', '9')
    assert candidate("1..043.") == ('1', '.', '.', '0', '4', '3', '.')
    assert candidate("549") == ('5', '4', '9')
    assert candidate("33828.") == ('3', '3', '8', '2', '8', '.')
    assert candidate("41348572") == ('4', '1', '3', '4', '8', '5', '7', '2')
    assert candidate("368") == ('3', '6', '8')
    assert candidate("166111116") == ('1', '6', '6', '1', '1', '1', '1', '1', '6')
    assert candidate(".17") == ('.', '1', '7')
    assert candidate("429489") == ('4', '2', '9', '4', '8', '9')
    assert candidate("83375720") == ('8', '3', '3', '7', '5', '7', '2', '0')
    assert candidate("9103") == ('9', '1', '0', '3')
    assert candidate("947") == ('9', '4', '7')
    assert candidate("541422") == ('5', '4', '1', '4', '2', '2')
    assert candidate(".2501.601") == ('.', '2', '5', '0', '1', '.', '6', '0', '1')
    assert candidate("2.427081") == ('2', '.', '4', '2', '7', '0', '8', '1')
    assert candidate("25.27") == ('2', '5', '.', '2', '7')
    assert candidate("965") == ('9', '6', '5')
    assert candidate("526193708") == ('5', '2', '6', '1', '9', '3', '7', '0', '8')
    assert candidate("81330.9") == ('8', '1', '3', '3', '0', '.', '9')
    assert candidate("1618") == ('1', '6', '1', '8')
    assert candidate("3.3506681") == ('3', '.', '3', '5', '0', '6', '6', '8', '1')
    assert candidate("5245") == ('5', '2', '4', '5')
    assert candidate("2809") == ('2', '8', '0', '9')
    assert candidate("655.96085") == ('6', '5', '5', '.', '9', '6', '0', '8', '5')

if __name__ == '__main__':
    check(string_to_tuple)