from case_MBPP_274 import split


def check(candidate):
    assert candidate('python') == ['p','y','t','h','o','n']
    assert candidate('Name') == ['N','a','m','e']
    assert candidate('program') == ['p','r','o','g','r','a','m']
    assert candidate("emw") == ['e', 'm', 'w']
    assert candidate("mfjwlp") == ['m', 'f', 'j', 'w', 'l', 'p']
    assert candidate("bckqgo") == ['b', 'c', 'k', 'q', 'g', 'o']
    assert candidate("jkbj") == ['j', 'k', 'b', 'j']
    assert candidate("qsadjbsgvs") == ['q', 's', 'a', 'd', 'j', 'b', 's', 'g', 'v', 's']
    assert candidate("iidpjq") == ['i', 'i', 'd', 'p', 'j', 'q']
    assert candidate("fqjhpzc") == ['f', 'q', 'j', 'h', 'p', 'z', 'c']
    assert candidate("pzq") == ['p', 'z', 'q']
    assert candidate("ctci") == ['c', 't', 'c', 'i']
    assert candidate("jkvfwxv") == ['j', 'k', 'v', 'f', 'w', 'x', 'v']
    assert candidate("uomn") == ['u', 'o', 'm', 'n']
    assert candidate("kcc") == ['k', 'c', 'c']
    assert candidate("ftr") == ['f', 't', 'r']
    assert candidate("nfliwr") == ['n', 'f', 'l', 'i', 'w', 'r']
    assert candidate("wshqznrs") == ['w', 's', 'h', 'q', 'z', 'n', 'r', 's']
    assert candidate("ebgdysmi") == ['e', 'b', 'g', 'd', 'y', 's', 'm', 'i']
    assert candidate("hcymorjwbea") == ['h', 'c', 'y', 'm', 'o', 'r', 'j', 'w', 'b', 'e', 'a']
    assert candidate("ahuxo") == ['a', 'h', 'u', 'x', 'o']
    assert candidate("pnihjxnoe") == ['p', 'n', 'i', 'h', 'j', 'x', 'n', 'o', 'e']
    assert candidate("uny") == ['u', 'n', 'y']
    assert candidate("tsjrcc") == ['t', 's', 'j', 'r', 'c', 'c']
    assert candidate("qlkilmdcw") == ['q', 'l', 'k', 'i', 'l', 'm', 'd', 'c', 'w']
    assert candidate("fvextrntpo") == ['f', 'v', 'e', 'x', 't', 'r', 'n', 't', 'p', 'o']
    assert candidate("vuiprgpd") == ['v', 'u', 'i', 'p', 'r', 'g', 'p', 'd']
    assert candidate("nsqpc") == ['n', 's', 'q', 'p', 'c']
    assert candidate("cynvbxmej") == ['c', 'y', 'n', 'v', 'b', 'x', 'm', 'e', 'j']
    assert candidate("evjsdgq") == ['e', 'v', 'j', 's', 'd', 'g', 'q']
    assert candidate("adihl") == ['a', 'd', 'i', 'h', 'l']
    assert candidate("smmqznmrifmw") == ['s', 'm', 'm', 'q', 'z', 'n', 'm', 'r', 'i', 'f', 'm', 'w']
    assert candidate("tcnhyjjfvooy") == ['t', 'c', 'n', 'h', 'y', 'j', 'j', 'f', 'v', 'o', 'o', 'y']
    assert candidate("gzkw") == ['g', 'z', 'k', 'w']
    assert candidate("ymcdlptupry") == ['y', 'm', 'c', 'd', 'l', 'p', 't', 'u', 'p', 'r', 'y']
    assert candidate("uybaabarle") == ['u', 'y', 'b', 'a', 'a', 'b', 'a', 'r', 'l', 'e']
    assert candidate("cnPyFe") == ['c', 'n', 'P', 'y', 'F', 'e']
    assert candidate("cKdsJwzz") == ['c', 'K', 'd', 's', 'J', 'w', 'z', 'z']
    assert candidate("NjR") == ['N', 'j', 'R']
    assert candidate("ASAgST") == ['A', 'S', 'A', 'g', 'S', 'T']
    assert candidate("yIWkUrjS") == ['y', 'I', 'W', 'k', 'U', 'r', 'j', 'S']
    assert candidate("lHIDPb") == ['l', 'H', 'I', 'D', 'P', 'b']
    assert candidate("xeHwqM") == ['x', 'e', 'H', 'w', 'q', 'M']
    assert candidate("SNf") == ['S', 'N', 'f']
    assert candidate("kbB") == ['k', 'b', 'B']
    assert candidate("ZupqtwDN") == ['Z', 'u', 'p', 'q', 't', 'w', 'D', 'N']
    assert candidate("ZMZph") == ['Z', 'M', 'Z', 'p', 'h']
    assert candidate("PSLgQOqps") == ['P', 'S', 'L', 'g', 'Q', 'O', 'q', 'p', 's']
    assert candidate("ZErpwb") == ['Z', 'E', 'r', 'p', 'w', 'b']
    assert candidate("pEQZCqS") == ['p', 'E', 'Q', 'Z', 'C', 'q', 'S']
    assert candidate("GKT") == ['G', 'K', 'T']
    assert candidate("kZgocSmPi") == ['k', 'Z', 'g', 'o', 'c', 'S', 'm', 'P', 'i']
    assert candidate("snlybdHbV") == ['s', 'n', 'l', 'y', 'b', 'd', 'H', 'b', 'V']
    assert candidate("TqQsixwq") == ['T', 'q', 'Q', 's', 'i', 'x', 'w', 'q']
    assert candidate("ialpepZ") == ['i', 'a', 'l', 'p', 'e', 'p', 'Z']
    assert candidate("kFNM") == ['k', 'F', 'N', 'M']
    assert candidate("pFq") == ['p', 'F', 'q']
    assert candidate("Ddzd") == ['D', 'd', 'z', 'd']
    assert candidate("lcU") == ['l', 'c', 'U']
    assert candidate("iFmYST") == ['i', 'F', 'm', 'Y', 'S', 'T']
    assert candidate("VTKfcYC") == ['V', 'T', 'K', 'f', 'c', 'Y', 'C']
    assert candidate("sRYDo") == ['s', 'R', 'Y', 'D', 'o']
    assert candidate("UNo") == ['U', 'N', 'o']
    assert candidate("DezffBka") == ['D', 'e', 'z', 'f', 'f', 'B', 'k', 'a']
    assert candidate("HDeMJw") == ['H', 'D', 'e', 'M', 'J', 'w']
    assert candidate("JmXtLWE") == ['J', 'm', 'X', 't', 'L', 'W', 'E']
    assert candidate("lLZvOn") == ['l', 'L', 'Z', 'v', 'O', 'n']
    assert candidate("NgbK") == ['N', 'g', 'b', 'K']
    assert candidate("WFS") == ['W', 'F', 'S']
    assert candidate("ybc") == ['y', 'b', 'c']
    assert candidate("qootvxflael") == ['q', 'o', 'o', 't', 'v', 'x', 'f', 'l', 'a', 'e', 'l']
    assert candidate("gszgdxsir") == ['g', 's', 'z', 'g', 'd', 'x', 's', 'i', 'r']
    assert candidate("gwkobfb") == ['g', 'w', 'k', 'o', 'b', 'f', 'b']
    assert candidate("hjbxgsawe") == ['h', 'j', 'b', 'x', 'g', 's', 'a', 'w', 'e']
    assert candidate("thjpykke") == ['t', 'h', 'j', 'p', 'y', 'k', 'k', 'e']
    assert candidate("tdot") == ['t', 'd', 'o', 't']
    assert candidate("vvb") == ['v', 'v', 'b']
    assert candidate("uthixmdzqjok") == ['u', 't', 'h', 'i', 'x', 'm', 'd', 'z', 'q', 'j', 'o', 'k']
    assert candidate("srveqcpayt") == ['s', 'r', 'v', 'e', 'q', 'c', 'p', 'a', 'y', 't']
    assert candidate("ikzhmlkqyzz") == ['i', 'k', 'z', 'h', 'm', 'l', 'k', 'q', 'y', 'z', 'z']
    assert candidate("lumfxdbvxp") == ['l', 'u', 'm', 'f', 'x', 'd', 'b', 'v', 'x', 'p']
    assert candidate("wyptzemze") == ['w', 'y', 'p', 't', 'z', 'e', 'm', 'z', 'e']
    assert candidate("ppp") == ['p', 'p', 'p']
    assert candidate("zensjookyop") == ['z', 'e', 'n', 's', 'j', 'o', 'o', 'k', 'y', 'o', 'p']
    assert candidate("ndnd") == ['n', 'd', 'n', 'd']
    assert candidate("mckyx") == ['m', 'c', 'k', 'y', 'x']
    assert candidate("zjemvrdy") == ['z', 'j', 'e', 'm', 'v', 'r', 'd', 'y']
    assert candidate("bmco") == ['b', 'm', 'c', 'o']
    assert candidate("xymlm") == ['x', 'y', 'm', 'l', 'm']
    assert candidate("nzwlx") == ['n', 'z', 'w', 'l', 'x']
    assert candidate("kdj") == ['k', 'd', 'j']
    assert candidate("mxhqoc") == ['m', 'x', 'h', 'q', 'o', 'c']
    assert candidate("yrsxnjj") == ['y', 'r', 's', 'x', 'n', 'j', 'j']
    assert candidate("ocffsdmv") == ['o', 'c', 'f', 'f', 's', 'd', 'm', 'v']
    assert candidate("ibxzwtphzwn") == ['i', 'b', 'x', 'z', 'w', 't', 'p', 'h', 'z', 'w', 'n']
    assert candidate("nmubtngsd") == ['n', 'm', 'u', 'b', 't', 'n', 'g', 's', 'd']
    assert candidate("vmhapqneqshe") == ['v', 'm', 'h', 'a', 'p', 'q', 'n', 'e', 'q', 's', 'h', 'e']
    assert candidate("rvjola") == ['r', 'v', 'j', 'o', 'l', 'a']
    assert candidate("kybtzyqe") == ['k', 'y', 'b', 't', 'z', 'y', 'q', 'e']
    assert candidate("mxuyhy") == ['m', 'x', 'u', 'y', 'h', 'y']
    assert candidate("qcjmoa") == ['q', 'c', 'j', 'm', 'o', 'a']
    assert candidate("xezddibiie") == ['x', 'e', 'z', 'd', 'd', 'i', 'b', 'i', 'i', 'e']

if __name__ == '__main__':
    check(split)