from case_MBPP_080 import tup_string


def check(candidate):
    assert candidate(('e', 'x', 'e', 'r', 'c', 'i', 's', 'e', 's'))==("exercises")
    assert candidate(('p','y','t','h','o','n'))==("python")
    assert candidate(('p','r','o','g','r','a','m'))==("program")
    assert candidate(('h', 'g', 'd', 'y', 'a', 'e', 'g', 't', 'g')) == "hgdyaegtg"
    assert candidate(('k', 'v', 'u', 'v', 'h', 'p', 'd', 'r', 'o')) == "kvuvhpdro"
    assert candidate(('x', 'o', 'm', 'm', 'y', 'j', 'l', 'v', 'j')) == "xommyjlvj"
    assert candidate(('j', 'o', 'z', 'c', 'c', 'u', 'l', 'v', 's')) == "jozcculvs"
    assert candidate(('q', 't', 'q', 'j', 'v', 'd', 'c', 'v', 'u')) == "qtqjvdcvu"
    assert candidate(('z', 'f', 'w', 'y', 'f', 'g', 'o', 'v', 'b')) == "zfwyfgovb"
    assert candidate(('g', 'j', 't', 'p', 'l', 'h', 'c', 'n', 'm')) == "gjtplhcnm"
    assert candidate(('y', 'q', 'q', 'p', 'y', 'q', 'n', 'd', 'u')) == "yqqpyqndu"
    assert candidate(('c', 'a', 'q', 'l', 'r', 'g', 'z', 'l', 'r')) == "caqlrgzlr"
    assert candidate(('s', 't', 'l', 'q', 'p', 'g', 'h', 'p', 'j')) == "stlqpghpj"
    assert candidate(('c', 'h', 'l', 'g', 'g', 'c', 'd', 'a', 'f')) == "chlggcdaf"
    assert candidate(('e', 'o', 'q', 'x', 'x', 'f', 'n', 'd', 'e')) == "eoqxxfnde"
    assert candidate(('m', 'u', 'b', 'm', 'x', 'd', 'j', 'e', 'd')) == "mubmxdjed"
    assert candidate(('h', 'k', 'p', 'd', 'u', 'r', 't', 'x', 'k')) == "hkpdurtxk"
    assert candidate(('z', 'v', 'b', 'd', 'm', 'y', 'i', 'm', 'i')) == "zvbdmyimi"
    assert candidate(('m', 'q', 'j', 'f', 'u', 'l', 'f', 'i', 'f')) == "mqjfulfif"
    assert candidate(('z', 'r', 'u', 'a', 'n', 'c', 'j', 's', 'v')) == "zruancjsv"
    assert candidate(('e', 'f', 'q', 'z', 'c', 'z', 'e', 'g', 'g')) == "efqzczegg"
    assert candidate(('z', 'p', 'j', 'y', 'r', 'z', 'o', 'h', 'c')) == "zpjyrzohc"
    assert candidate(('e', 'd', 'v', 'j', 'x', 'x', 'o', 's', 'l')) == "edvjxxosl"
    assert candidate(('t', 'd', 'm', 'm', 'q', 'o', 'q', 'n', 'x')) == "tdmmqoqnx"
    assert candidate(('k', 'a', 'v', 'z', 'x', 'w', 'z', 'h', 'c')) == "kavzxwzhc"
    assert candidate(('h', 't', 'a', 'e', 'k', 'n', 'q', 'c', 'e')) == "htaeknqce"
    assert candidate(('i', 'v', 't', 'y', 'k', 'l', 'q', 'd', 'y')) == "ivtyklqdy"
    assert candidate(('r', 'g', 'b', 'c', 'k', 'b', 'q', 's', 'g')) == "rgbckbqsg"
    assert candidate(('b', 'q', 's', 'h', 'n', 'w', 'n', 'w', 'j')) == "bqshnwnwj"
    assert candidate(('u', 'k', 'z', 'u', 'l', 'd', 't', 'v', 'y')) == "ukzuldtvy"
    assert candidate(('r', 'd', 'd', 'v', 'y', 'd', 'h', 'q', 't')) == "rddvydhqt"
    assert candidate(('w', 'o', 't', 'j', 'n', 'g', 'q', 'u', 'd')) == "wotjngqud"
    assert candidate(('c', 'x', 'x', 'u', 'w', 'x', 'x', 'q', 'p')) == "cxxuwxxqp"
    assert candidate(('x', 'l', 'n', 'i', 'w', 'j', 'o', 'k', 'd')) == "xlniwjokd"
    assert candidate(('q', 'l', 'g', 'd', 'z', 'i', 'c', 'm', 'y')) == "qlgdzicmy"
    assert candidate(('i', 'e', 'v', 'o', 'q', 'h', 'l', 'n', 'j')) == "ievoqhlnj"
    assert candidate(('w', 'e', 'j', 'i', 'p', 'j')) == "wejipj"
    assert candidate(('p', 'l', 'e', 'w', 'e', 'a')) == "plewea"
    assert candidate(('l', 'h', 's', 'b', 'y', 'w')) == "lhsbyw"
    assert candidate(('r', 'd', 'o', 'u', 'q', 'f')) == "rdouqf"
    assert candidate(('r', 'p', 'x', 'g', 'n', 'j')) == "rpxgnj"
    assert candidate(('v', 'x', 'f', 'k', 'b', 'y')) == "vxfkby"
    assert candidate(('d', 'g', 'm', 'f', 'i', 'e')) == "dgmfie"
    assert candidate(('j', 'a', 'z', 'f', 'i', 'b')) == "jazfib"
    assert candidate(('t', 'n', 'n', 'z', 'c', 'r')) == "tnnzcr"
    assert candidate(('v', 'f', 'h', 'h', 'o', 'i')) == "vfhhoi"
    assert candidate(('r', 'b', 't', 's', 'o', 'w')) == "rbtsow"
    assert candidate(('u', 'y', 'k', 'v', 'l', 'o')) == "uykvlo"
    assert candidate(('q', 'z', 'p', 'p', 'k', 's')) == "qzppks"
    assert candidate(('m', 'n', 'o', 'z', 't', 'h')) == "mnozth"
    assert candidate(('i', 'i', 'i', 'w', 's', 'w')) == "iiiwsw"
    assert candidate(('f', 'u', 'k', 'l', 'z', 'z')) == "fuklzz"
    assert candidate(('n', 'd', 'w', 'u', 'i', 'w')) == "ndwuiw"
    assert candidate(('x', 'l', 'm', 'u', 'a', 's')) == "xlmuas"
    assert candidate(('n', 'h', 'k', 'o', 'g', 'x')) == "nhkogx"
    assert candidate(('r', 'p', 'a', 'j', 'q', 't')) == "rpajqt"
    assert candidate(('t', 'e', 'b', 'd', 'x', 'm')) == "tebdxm"
    assert candidate(('i', 'k', 'k', 'g', 'd', 'n')) == "ikkgdn"
    assert candidate(('g', 'c', 'u', 'c', 'r', 'f')) == "gcucrf"
    assert candidate(('g', 'm', 'p', 't', 'o', 'v')) == "gmptov"
    assert candidate(('a', 'e', 'y', 's', 'p', 'z')) == "aeyspz"
    assert candidate(('e', 'j', 'y', 'q', 'w', 'g')) == "ejyqwg"
    assert candidate(('v', 'b', 'i', 'p', 'y', 't')) == "vbipyt"
    assert candidate(('t', 'e', 'h', 'h', 'i', 'h')) == "tehhih"
    assert candidate(('b', 'g', 'z', 'b', 'p', 'm')) == "bgzbpm"
    assert candidate(('p', 'v', 'k', 'p', 'v', 'd')) == "pvkpvd"
    assert candidate(('n', 'o', 'y', 'g', 'c', 'i')) == "noygci"
    assert candidate(('t', 'k', 'i', 'z', 't', 's')) == "tkizts"
    assert candidate(('e', 'r', 't', 'i', 'z', 's')) == "ertizs"
    assert candidate(('m', 'n', 'x', 'n', 'b', 'j', 's')) == "mnxnbjs"
    assert candidate(('o', 'v', 'j', 'u', 't', 'q', 'a')) == "ovjutqa"
    assert candidate(('d', 'm', 't', 'q', 'y', 's', 'q')) == "dmtqysq"
    assert candidate(('h', 'f', 'z', 'r', 'm', 'p', 'r')) == "hfzrmpr"
    assert candidate(('i', 'p', 'a', 'i', 't', 'k', 'g')) == "ipaitkg"
    assert candidate(('l', 'm', 'r', 'c', 'p', 'y', 'v')) == "lmrcpyv"
    assert candidate(('l', 'c', 't', 'b', 'g', 'b', 'm')) == "lctbgbm"
    assert candidate(('c', 'h', 'a', 'k', 'p', 'p', 'e')) == "chakppe"
    assert candidate(('c', 'k', 't', 'g', 'b', 'x', 'p')) == "cktgbxp"
    assert candidate(('g', 'i', 't', 'o', 'y', 'v', 'o')) == "gitoyvo"
    assert candidate(('i', 's', 'e', 'b', 'h', 'o', 's')) == "isebhos"
    assert candidate(('d', 'c', 'o', 'x', 'b', 'a', 'h')) == "dcoxbah"
    assert candidate(('s', 'g', 'w', 's', 'h', 'j', 'i')) == "sgwshji"
    assert candidate(('o', 'b', 'e', 'a', 'l', 'h', 'j')) == "obealhj"
    assert candidate(('r', 'o', 't', 'j', 'h', 'd', 'v')) == "rotjhdv"
    assert candidate(('h', 'u', 'v', 'x', 'w', 'e', 'k')) == "huvxwek"
    assert candidate(('g', 'p', 'o', 'y', 'n', 'j', 'v')) == "gpoynjv"
    assert candidate(('m', 'j', 'o', 'l', 'x', 'v', 'q')) == "mjolxvq"
    assert candidate(('v', 'u', 'c', 'h', 'g', 'c', 'f')) == "vuchgcf"
    assert candidate(('v', 'r', 'w', 's', 'b', 'q', 'k')) == "vrwsbqk"
    assert candidate(('v', 'g', 'z', 'y', 'i', 's', 'c')) == "vgzyisc"
    assert candidate(('j', 'n', 'l', 'f', 'j', 'v', 'e')) == "jnlfjve"
    assert candidate(('s', 'h', 'b', 't', 'h', 'v', 'y')) == "shbthvy"
    assert candidate(('h', 't', 'a', 'u', 'w', 'e', 'j')) == "htauwej"
    assert candidate(('k', 'c', 'r', 'h', 'd', 'd', 'n')) == "kcrhddn"
    assert candidate(('w', 'k', 'w', 'h', 'p', 'd', 'j')) == "wkwhpdj"
    assert candidate(('h', 'i', 'k', 'u', 'm', 'g', 'h')) == "hikumgh"
    assert candidate(('n', 'm', 'f', 'o', 'n', 'h', 'j')) == "nmfonhj"
    assert candidate(('l', 'k', 'k', 'o', 'n', 'x', 'n')) == "lkkonxn"
    assert candidate(('e', 't', 'p', 'm', 'i', 'y', 'r')) == "etpmiyr"
    assert candidate(('x', 'c', 'q', 'c', 'm', 'c', 'f')) == "xcqcmcf"
    assert candidate(('q', 'u', 'e', 'l', 'u', 'v', 'w')) == "queluvw"
    assert candidate(('v', 'y', 't', 'z', 'm', 'a', 'w')) == "vytzmaw"

if __name__ == '__main__':
    check(tup_string)