from case_MBPP_030 import dif_Square


def check(candidate):
    assert candidate(5) == True
    assert candidate(10) == False
    assert candidate(15) == True
    assert candidate(6) == False
    assert candidate(2) == False
    assert candidate(4) == True
    assert candidate(4) == True
    assert candidate(1) == True
    assert candidate(8) == True
    assert candidate(6) == False
    assert candidate(10) == False
    assert candidate(6) == False
    assert candidate(5) == True
    assert candidate(2) == False
    assert candidate(7) == True
    assert candidate(10) == False
    assert candidate(9) == True
    assert candidate(9) == True
    assert candidate(9) == True
    assert candidate(2) == False
    assert candidate(6) == False
    assert candidate(9) == True
    assert candidate(2) == False
    assert candidate(4) == True
    assert candidate(7) == True
    assert candidate(7) == True
    assert candidate(3) == True
    assert candidate(6) == False
    assert candidate(10) == False
    assert candidate(2) == False
    assert candidate(2) == False
    assert candidate(1) == True
    assert candidate(10) == False
    assert candidate(2) == False
    assert candidate(2) == False
    assert candidate(10) == False
    assert candidate(8) == True
    assert candidate(9) == True
    assert candidate(13) == True
    assert candidate(14) == False
    assert candidate(14) == False
    assert candidate(6) == False
    assert candidate(12) == True
    assert candidate(7) == True
    assert candidate(5) == True
    assert candidate(7) == True
    assert candidate(6) == False
    assert candidate(7) == True
    assert candidate(5) == True
    assert candidate(12) == True
    assert candidate(10) == False
    assert candidate(7) == True
    assert candidate(14) == False
    assert candidate(14) == False
    assert candidate(5) == True
    assert candidate(10) == False
    assert candidate(7) == True
    assert candidate(11) == True
    assert candidate(5) == True
    assert candidate(8) == True
    assert candidate(9) == True
    assert candidate(13) == True
    assert candidate(13) == True
    assert candidate(9) == True
    assert candidate(5) == True
    assert candidate(13) == True
    assert candidate(10) == False
    assert candidate(11) == True
    assert candidate(15) == True
    assert candidate(14) == False
    assert candidate(19) == True
    assert candidate(12) == True
    assert candidate(18) == False
    assert candidate(11) == True
    assert candidate(14) == False
    assert candidate(13) == True
    assert candidate(12) == True
    assert candidate(12) == True
    assert candidate(18) == False
    assert candidate(20) == True
    assert candidate(14) == False
    assert candidate(17) == True
    assert candidate(12) == True
    assert candidate(12) == True
    assert candidate(17) == True
    assert candidate(18) == False
    assert candidate(19) == True
    assert candidate(15) == True
    assert candidate(12) == True
    assert candidate(15) == True
    assert candidate(19) == True
    assert candidate(12) == True
    assert candidate(15) == True
    assert candidate(11) == True
    assert candidate(17) == True
    assert candidate(10) == False
    assert candidate(18) == False
    assert candidate(16) == True
    assert candidate(15) == True
    assert candidate(16) == True
    assert candidate(12) == True
    assert candidate(11) == True

if __name__ == '__main__':
    check(dif_Square)