from case_MBPP_395 import count_vowels


def check(candidate):
    assert candidate('bestinstareels') == 7
    assert candidate('partofthejourneyistheend') == 12
    assert candidate('amazonprime') == 5
    assert candidate("umgvcwzrz") == 1
    assert candidate("zigownnyyta") == 4
    assert candidate("iqswjidtbjjltwa") == 4
    assert candidate("sactbbxefnekxf") == 6
    assert candidate("wsliifcoancy") == 4
    assert candidate("suwvppyejthpzaefvj") == 6
    assert candidate("zrbjgjzmzini") == 2
    assert candidate("wtfxjtzsfvj") == 0
    assert candidate("szjuxamhx") == 3
    assert candidate("wfqqvjpckyb") == 0
    assert candidate("kidufotaeewjuk") == 7
    assert candidate("hqmbqlcises") == 3
    assert candidate("cvlewumdicmzpg") == 5
    assert candidate("wcjhpwhsptbzuiuyov") == 3
    assert candidate("gfattonjxxrpoeduk") == 7
    assert candidate("ezyhkycyjhqhnkvzga") == 2
    assert candidate("ognqdpvzlhhrwtw") == 1
    assert candidate("rerhjtnvtnnu") == 3
    assert candidate("oexlxgysululzqyqz") == 4
    assert candidate("rthdlijkfke") == 3
    assert candidate("gbbvqazycqh") == 2
    assert candidate("ybvtsnkaygig") == 4
    assert candidate("bzmzigzforbonitbij") == 9
    assert candidate("epdpzvxslrn") == 1
    assert candidate("idwvspqeltez") == 5
    assert candidate("apsnpkzbqb") == 1
    assert candidate("hkvvvelkd") == 2
    assert candidate("mkoktaaojqmnm") == 4
    assert candidate("eeamurzuleqpztueh") == 7
    assert candidate("qiriwviwznhrk") == 5
    assert candidate("isodbjefqkcwfutu") == 6
    assert candidate("cldswbfucpsjnhxqyp") == 2
    assert candidate("ljitvljddyatiap") == 5
    assert candidate("quqopsroitjivwenhhtlxlxkqkq") == 9
    assert candidate("zlruwwdhcmbwniuvatcobam") == 8
    assert candidate("didzhvrsukqmipvfcbpjprqnt") == 6
    assert candidate("dbmwihgvjbiitqcpqxjwsnlq") == 4
    assert candidate("yebzhjgjehwuloazvvhgtcptemihfp") == 10
    assert candidate("eryrgqprhcvhkgyrkgoedbyg") == 3
    assert candidate("kpoggjsgijcfiptuzonudmsrk") == 10
    assert candidate("gikoxwohyadwcthsuxtkdck") == 9
    assert candidate("dauluqpfmkuwtnotrptvjdbpxqijze") == 10
    assert candidate("swgusxrxgwjqakjglfxtehep") == 7
    assert candidate("wvmlaeijyjwoygmoyutebtvk") == 8
    assert candidate("sdltixaibiqivdvmrxcrndi") == 6
    assert candidate("ltdwjfchaoaphouwzgnzzqm") == 4
    assert candidate("ibfzirnoohzaobrsoegbvihafnf") == 12
    assert candidate("bumtwovqjanyxahmrentfxqwernhsf") == 12
    assert candidate("isvhzjevjpbwequsecdmilpub") == 11
    assert candidate("gijmecxyxqjeytbkpemhwgrnjysis") == 10
    assert candidate("qkdxjscivjtoslnpdiiizso") == 7
    assert candidate("wlyswglvgwlmrjictzkahzxbbewfo") == 7
    assert candidate("rxmylqqwfploflhyepjjbomipgl") == 7
    assert candidate("sjxxbosxmqjqzkkqaqknc") == 4
    assert candidate("yttpnywtsotlntudjrjkrssnnzmua") == 5
    assert candidate("fvogyyqqbownnzopzenlkmjn") == 8
    assert candidate("rfimuanmzixbpwnncsxyutihhomim") == 11
    assert candidate("gjbmnutxbdzxsqvvutcjsnekvcpzsi") == 7
    assert candidate("cvlokdqpdtuzwvjlimysnglrcjoaaf") == 8
    assert candidate("ittconhmowmrtykwcsejtnbc") == 7
    assert candidate("ifygwrkupvaamwaupbtvyiofdenlkh") == 11
    assert candidate("xmxpoqzolaswmlqrmwnrtxgxmkmk") == 5
    assert candidate("llydojmpeuggiedxvxevxwpab") == 10
    assert candidate("soykpuulmhcycyppkghvrj") == 4
    assert candidate("taeguznhxdzghdqbdglpj") == 3
    assert candidate("ryrjwqauqtqouwutkicxdywbl") == 7
    assert candidate("pwxnlhuhhb") == 2
    assert candidate("wgmszvgqx") == 0
    assert candidate("ojgshoerv") == 3
    assert candidate("dcgsrhhf") == 0
    assert candidate("lajfzmioty") == 4
    assert candidate("erdahuubfsuk") == 6
    assert candidate("uwbiua") == 2
    assert candidate("wcnyuepirex") == 4
    assert candidate("bsamopishwh") == 4
    assert candidate("qleyaye") == 3
    assert candidate("vdadjjmeymnf") == 4
    assert candidate("odkeaiwgjvx") == 3
    assert candidate("pdrayexxanxdzyu") == 6
    assert candidate("oqvjhqt") == 1
    assert candidate("nnndtlbwukk") == 2
    assert candidate("gjnbohwafebihy") == 6
    assert candidate("wilhunylhgyb") == 4
    assert candidate("yctuclayrdbf") == 4
    assert candidate("obhtnvbd") == 1
    assert candidate("jrowzpu") == 3
    assert candidate("wawarvfwddh") == 3
    assert candidate("axhfdoroqiciecf") == 6
    assert candidate("xgvpegojrbeuy") == 5
    assert candidate("lrbxdwv") == 0
    assert candidate("uqiieszvsxszjy") == 2
    assert candidate("kpyvlsh") == 0
    assert candidate("uuwmtnagxof") == 5
    assert candidate("opnggoxmnckqeuw") == 5
    assert candidate("zravdf") == 2
    assert candidate("dsnmtirdzuzrf") == 4
    assert candidate("tdduoy") == 2
    assert candidate("zhqddoqnbrc") == 2
    assert candidate("ftfqbfzscpzwa") == 1

if __name__ == '__main__':
    check(count_vowels)