from case_MBPP_068 import string_to_list


def check(candidate):
    assert candidate("python programming")==['python','programming']
    assert candidate("lists tuples strings")==['lists','tuples','strings']
    assert candidate("write a program")==['write','a','program']
    assert candidate("cisjjqxcey baawfimfgkrd") == ['cisjjqxcey', 'baawfimfgkrd']
    assert candidate("isfkh ldsbndxsjxaqfuhy") == ['isfkh', 'ldsbndxsjxaqfuhy']
    assert candidate("hrgud vhckxvgyjtlhjz") == ['hrgud', 'vhckxvgyjtlhjz']
    assert candidate("qfwxkikvnzhymkwntqictmm") == ['qfwxkikvnzhymkwntqictmm']
    assert candidate("xnah mgufvjjumxn") == ['xnah', 'mgufvjjumxn']
    assert candidate("bmegkba yhecgvfzhye") == ['bmegkba', 'yhecgvfzhye']
    assert candidate("zopcvaeutdwhffvpwewxq") == ['zopcvaeutdwhffvpwewxq']
    assert candidate("vwykco rgrikwlsnly") == ['vwykco', 'rgrikwlsnly']
    assert candidate("hjfqeifykx lamwqij") == ['hjfqeifykx', 'lamwqij']
    assert candidate("ghfyk yphhgiunav") == ['ghfyk', 'yphhgiunav']
    assert candidate(" guiolhudbohi dwbr") == ['', 'guiolhudbohi', 'dwbr']
    assert candidate("lzsfulxqo jxnfij") == ['lzsfulxqo', 'jxnfij']
    assert candidate("gzbninfzwvvldji") == ['gzbninfzwvvldji']
    assert candidate("cevnbmgrahdovualuqqbehf") == ['cevnbmgrahdovualuqqbehf']
    assert candidate("sal t qchxlffwwlbq ") == ['sal', 't', 'qchxlffwwlbq', '']
    assert candidate("pktrchshtdl ism") == ['pktrchshtdl', 'ism']
    assert candidate("jfo dbadrmefk iylrckva") == ['jfo', 'dbadrmefk', 'iylrckva']
    assert candidate("jtt ahhnownduyobcbdlvi") == ['jtt', 'ahhnownduyobcbdlvi']
    assert candidate("rgbcyfumfbizvsmplmjjvngp") == ['rgbcyfumfbizvsmplmjjvngp']
    assert candidate("acqkjdlpj fctxzvi") == ['acqkjdlpj', 'fctxzvi']
    assert candidate("vdcibapqnwxuxrgnfigfidr") == ['vdcibapqnwxuxrgnfigfidr']
    assert candidate("gcfrctuspho xnuvg") == ['gcfrctuspho', 'xnuvg']
    assert candidate("yjxmw mfudiutb hkl") == ['yjxmw', 'mfudiutb', 'hkl']
    assert candidate("q hujjubhudrqnflzpnknd") == ['q', 'hujjubhudrqnflzpnknd']
    assert candidate("hdixrzjjwqohvzzahz") == ['hdixrzjjwqohvzzahz']
    assert candidate("zdmivflvsvyltjcielwyv") == ['zdmivflvsvyltjcielwyv']
    assert candidate("nqdlkmyoameggza") == ['nqdlkmyoameggza']
    assert candidate("pfzbllbiwincbheehtomatc") == ['pfzbllbiwincbheehtomatc']
    assert candidate("lnefesdqctltydvnpezva") == ['lnefesdqctltydvnpezva']
    assert candidate("oaixkfcfj  lyax") == ['oaixkfcfj', '', 'lyax']
    assert candidate("krrjyictpzflfpyzaf") == ['krrjyictpzflfpyzaf']
    assert candidate("pagup pbizbigmsjnbhpskm") == ['pagup', 'pbizbigmsjnbhpskm']
    assert candidate("oroibuktegdchgmkv") == ['oroibuktegdchgmkv']
    assert candidate("efvospkdmhlbdjieoofij") == ['efvospkdmhlbdjieoofij']
    assert candidate("zhacsydpwri jppjlpek") == ['zhacsydpwri', 'jppjlpek']
    assert candidate("hspslthryurxqbq") == ['hspslthryurxqbq']
    assert candidate("dlehypzqpvxittayziua") == ['dlehypzqpvxittayziua']
    assert candidate("pwaolxfagueqvdfxu") == ['pwaolxfagueqvdfxu']
    assert candidate("jcsfmxphwa wvygxjoyj") == ['jcsfmxphwa', 'wvygxjoyj']
    assert candidate("cimyotgj pwrcbntfer") == ['cimyotgj', 'pwrcbntfer']
    assert candidate("uxbofvfw qjlofc") == ['uxbofvfw', 'qjlofc']
    assert candidate("nifcjtgeoqtmvfiok") == ['nifcjtgeoqtmvfiok']
    assert candidate("vslthpixtfden  cmrsg") == ['vslthpixtfden', '', 'cmrsg']
    assert candidate("hxhygxavhhgwxruy") == ['hxhygxavhhgwxruy']
    assert candidate("to nwxevudslvrwphpwjhvz") == ['to', 'nwxevudslvrwphpwjhvz']
    assert candidate("rekvzpdmgdhfflmrk fmxv") == ['rekvzpdmgdhfflmrk', 'fmxv']
    assert candidate("enieoxxkgkxiwofrukyzbc") == ['enieoxxkgkxiwofrukyzbc']
    assert candidate("fnxqpdpwvdqueyu") == ['fnxqpdpwvdqueyu']
    assert candidate("hqwgcbjqmdxqkgzngnduuc") == ['hqwgcbjqmdxqkgzngnduuc']
    assert candidate("zuqtuehlvcugxqzh") == ['zuqtuehlvcugxqzh']
    assert candidate("xcuniqsxkyodapwfczzue") == ['xcuniqsxkyodapwfczzue']
    assert candidate("ktuoulzgecnjetvssanmxcxs") == ['ktuoulzgecnjetvssanmxcxs']
    assert candidate("vxrozhfoicjwdlhkttslnk") == ['vxrozhfoicjwdlhkttslnk']
    assert candidate("lqhjmwnevkmftyjfmrn nzeq") == ['lqhjmwnevkmftyjfmrn', 'nzeq']
    assert candidate("xpyxydfvbtvwfvr") == ['xpyxydfvbtvwfvr']
    assert candidate("esvxixwpe fytflxs") == ['esvxixwpe', 'fytflxs']
    assert candidate("ooxpvkmimfmslsv") == ['ooxpvkmimfmslsv']
    assert candidate("etrrvmjjipcqgvfkc") == ['etrrvmjjipcqgvfkc']
    assert candidate("fijfkpuaehflizloqedxfsy") == ['fijfkpuaehflizloqedxfsy']
    assert candidate("bgy jpvbqickuecbep") == ['bgy', 'jpvbqickuecbep']
    assert candidate("vfrhko fbdczguj hmzl") == ['vfrhko', 'fbdczguj', 'hmzl']
    assert candidate("gpyc dbwwixgzpl") == ['gpyc', 'dbwwixgzpl']
    assert candidate("xdgblirazralikoa") == ['xdgblirazralikoa']
    assert candidate("npdbulhyrw zldzyxkjrnb") == ['npdbulhyrw', 'zldzyxkjrnb']
    assert candidate("kitoqdzhssxyppiwgiadrazo") == ['kitoqdzhssxyppiwgiadrazo']
    assert candidate("dwu  okzbfrxnkgq") == ['dwu', '', 'okzbfrxnkgq']
    assert candidate("et xpnnvwisnbwmxt") == ['et', 'xpnnvwisnbwmxt']
    assert candidate("iyshjgmopwaua jyqlyae") == ['iyshjgmopwaua', 'jyqlyae']
    assert candidate("zs czycacjrsrnjysk") == ['zs', 'czycacjrsrnjysk']
    assert candidate("gqrmqhwevnxpugd") == ['gqrmqhwevnxpugd']
    assert candidate("hijmncyvmblcmxvcxvwt") == ['hijmncyvmblcmxvcxvwt']
    assert candidate("vb rml d wue") == ['vb', 'rml', 'd', 'wue']
    assert candidate("xj bifcaxgormmg") == ['xj', 'bifcaxgormmg']
    assert candidate("npetqtlljpuglidkgkw") == ['npetqtlljpuglidkgkw']
    assert candidate(" etskmlmtqxjmttuq w") == ['', 'etskmlmtqxjmttuq', 'w']
    assert candidate("jhrpluvrewhecipok") == ['jhrpluvrewhecipok']
    assert candidate("unfsfdghmyglwaexmm") == ['unfsfdghmyglwaexmm']
    assert candidate("wdmzvqtji nctmouiczu") == ['wdmzvqtji', 'nctmouiczu']
    assert candidate("glkxkqdgoxsgy") == ['glkxkqdgoxsgy']
    assert candidate("mubsfdtspeclyciiesd") == ['mubsfdtspeclyciiesd']
    assert candidate("tgiqayzeewugiqwlmsdn") == ['tgiqayzeewugiqwlmsdn']
    assert candidate("d ppjrvnbnqmvsqdh") == ['d', 'ppjrvnbnqmvsqdh']
    assert candidate("ru apass opfat") == ['ru', 'apass', 'opfat']
    assert candidate("cqdkctctvprob") == ['cqdkctctvprob']
    assert candidate("pgflj criggkfhdfjtgy") == ['pgflj', 'criggkfhdfjtgy']
    assert candidate("xbjapimhjaqafor") == ['xbjapimhjaqafor']
    assert candidate("nnngmgdxqiwvovl v g") == ['nnngmgdxqiwvovl', 'v', 'g']
    assert candidate("yrvludlmgghe ghd") == ['yrvludlmgghe', 'ghd']
    assert candidate("tfhfmglqt stw") == ['tfhfmglqt', 'stw']
    assert candidate("l hdjmwqdrwqsyyqh") == ['l', 'hdjmwqdrwqsyyqh']
    assert candidate("pagctjfdlayyzrpbwp") == ['pagctjfdlayyzrpbwp']
    assert candidate("amrflplpqxwpdsdwmdv") == ['amrflplpqxwpdsdwmdv']
    assert candidate("ilmmkdkqfnvjuf") == ['ilmmkdkqfnvjuf']
    assert candidate("uftuqubbhv rix") == ['uftuqubbhv', 'rix']
    assert candidate(" uv ieztyfquvnlu") == ['', 'uv', 'ieztyfquvnlu']
    assert candidate("imsnyracatkxvr") == ['imsnyracatkxvr']
    assert candidate("mcqle msbkr ktrn") == ['mcqle', 'msbkr', 'ktrn']
    assert candidate("zlshhwscfclj ") == ['zlshhwscfclj', '']
    assert candidate("vuxsgfdygqfosl") == ['vuxsgfdygqfosl']

if __name__ == '__main__':
    check(string_to_list)