from case_MBPP_333 import replace_spaces


def check(candidate):
    assert candidate('Jumanji The Jungle') == 'Jumanji_The_Jungle'
    assert candidate('The Avengers') == 'The_Avengers'
    assert candidate('Fast and Furious') == 'Fast_and_Furious'
    assert candidate("fUxFnnPyBCWvQrlU") == "fUxFnnPyBCWvQrlU"
    assert candidate("xiceqEDkoWseXhHQIa") == "xiceqEDkoWseXhHQIa"
    assert candidate("JqJDGe TfBWPVplwYg") == "JqJDGe_TfBWPVplwYg"
    assert candidate("bTBKHnWuJThIRQe") == "bTBKHnWuJThIRQe"
    assert candidate("DBktNUjxAZtZoskeIFMUVwj") == "DBktNUjxAZtZoskeIFMUVwj"
    assert candidate("RBGxjOyHwfAAiAzAi ") == "RBGxjOyHwfAAiAzAi_"
    assert candidate("EZVhFCYUwVsawGZF") == "EZVhFCYUwVsawGZF"
    assert candidate("nTCtZHKHXJDZnsHkQHAdAFEw") == "nTCtZHKHXJDZnsHkQHAdAFEw"
    assert candidate("SFZjBfotwVsEdLMZFKgydcAn") == "SFZjBfotwVsEdLMZFKgydcAn"
    assert candidate("LkwDJDFxJTcqIPdKum") == "LkwDJDFxJTcqIPdKum"
    assert candidate("IUaHiTf VhwNPxzgWREi") == "IUaHiTf_VhwNPxzgWREi"
    assert candidate("jOli noJJpYBEOIL") == "jOli_noJJpYBEOIL"
    assert candidate("efrKHZNKhtGhPMNKysSj") == "efrKHZNKhtGhPMNKysSj"
    assert candidate("bXpcPHhfCmbNsWl XvFPo") == "bXpcPHhfCmbNsWl_XvFPo"
    assert candidate("bijhPpgBmuYffvJLsi") == "bijhPpgBmuYffvJLsi"
    assert candidate("uppPqkyzwxsaFboRlCwxk") == "uppPqkyzwxsaFboRlCwxk"
    assert candidate("hTGgEAtZNSepWVikWCbMnBs") == "hTGgEAtZNSepWVikWCbMnBs"
    assert candidate("ohGZXCN eQvXEdqEgUTyuk") == "ohGZXCN_eQvXEdqEgUTyuk"
    assert candidate("sLSAbBPdvRsWltqN") == "sLSAbBPdvRsWltqN"
    assert candidate("yVALI xeAsbJFckZLyqFtZaN") == "yVALI_xeAsbJFckZLyqFtZaN"
    assert candidate("aLSQjnMCEzRgRXNRpE") == "aLSQjnMCEzRgRXNRpE"
    assert candidate("uw PutcbAPQXQoqHLCU") == "uw_PutcbAPQXQoqHLCU"
    assert candidate("ILYjeyCTmTtIgYpFnPkNfLF") == "ILYjeyCTmTtIgYpFnPkNfLF"
    assert candidate("I UW cYnT ul AjDRJGXbJtq") == "I_UW_cYnT_ul_AjDRJGXbJtq"
    assert candidate("UvyGkOoXOQiAngbFqLyuwkmV") == "UvyGkOoXOQiAngbFqLyuwkmV"
    assert candidate("PScFGSsuOCsvdjghpzUnbNmW") == "PScFGSsuOCsvdjghpzUnbNmW"
    assert candidate("rgtrXMaPipytmqEsXHmojs") == "rgtrXMaPipytmqEsXHmojs"
    assert candidate("hQOywoIsyphCOqm") == "hQOywoIsyphCOqm"
    assert candidate("yqsVC WkcwzvyxCIdOSDmDFX") == "yqsVC_WkcwzvyxCIdOSDmDFX"
    assert candidate("zeTWNxsPiAfLDmhSIAORDpN") == "zeTWNxsPiAfLDmhSIAORDpN"
    assert candidate("yNzQldgIgwyj WAiXs") == "yNzQldgIgwyj_WAiXs"
    assert candidate("qPGsAzbn sFiivVBigMy") == "qPGsAzbn_sFiivVBigMy"
    assert candidate("pUijbBbDSemrJWwuF") == "pUijbBbDSemrJWwuF"
    assert candidate("gCVLqGKpbE") == "gCVLqGKpbE"
    assert candidate("FcFMjrJGPEQqlfVmb") == "FcFMjrJGPEQqlfVmb"
    assert candidate("wfXPMuBeUQG") == "wfXPMuBeUQG"
    assert candidate("hZDaZXWzICZPe") == "hZDaZXWzICZPe"
    assert candidate("aVokpcgbtMhRijaDT") == "aVokpcgbtMhRijaDT"
    assert candidate("aZDlWiDgonCkhZEDN") == "aZDlWiDgonCkhZEDN"
    assert candidate("gSuxACzOiRdOfWMeY") == "gSuxACzOiRdOfWMeY"
    assert candidate("BdbLaEUHv") == "BdbLaEUHv"
    assert candidate("ZbhBDHibjXi") == "ZbhBDHibjXi"
    assert candidate("PLFDfMjIRPd") == "PLFDfMjIRPd"
    assert candidate("ZfHroFfw mqIqYip") == "ZfHroFfw_mqIqYip"
    assert candidate("XBMjisixkbqXbe") == "XBMjisixkbqXbe"
    assert candidate("U  zPDqJXtXMApfl") == "U__zPDqJXtXMApfl"
    assert candidate("GeBjgYxeIMdyZ") == "GeBjgYxeIMdyZ"
    assert candidate("woywaLJQjZqb") == "woywaLJQjZqb"
    assert candidate(" JUPKVZUcCXGUkoQa") == "_JUPKVZUcCXGUkoQa"
    assert candidate("Oof uJZFLOqnuACCPK") == "Oof_uJZFLOqnuACCPK"
    assert candidate("uNfGgZnOVpFUmIHGl") == "uNfGgZnOVpFUmIHGl"
    assert candidate("zixSQdjHJ cTUutjvw") == "zixSQdjHJ_cTUutjvw"
    assert candidate("yWjzUqdzoMqXrry") == "yWjzUqdzoMqXrry"
    assert candidate("txyhrFQnfrSluYuaS") == "txyhrFQnfrSluYuaS"
    assert candidate("qBzKWIXEKinTdlp") == "qBzKWIXEKinTdlp"
    assert candidate("jkGXWppJpppBfee") == "jkGXWppJpppBfee"
    assert candidate("ddh TniNvbgptuLr") == "ddh_TniNvbgptuLr"
    assert candidate("RKmAfuSZedFz") == "RKmAfuSZedFz"
    assert candidate(" nZxFzWoScsgmsydU") == "_nZxFzWoScsgmsydU"
    assert candidate("zFVJBlySa ByE") == "zFVJBlySa_ByE"
    assert candidate("UCFo eEslq") == "UCFo_eEslq"
    assert candidate("mlOZMKrxG") == "mlOZMKrxG"
    assert candidate("OHFfQptzUMENIpHTRN") == "OHFfQptzUMENIpHTRN"
    assert candidate("KdHMBUKVIxcZoyx") == "KdHMBUKVIxcZoyx"
    assert candidate("sYYRItkKGQFTdrCy") == "sYYRItkKGQFTdrCy"
    assert candidate("XHL JJibe") == "XHL_JJibe"
    assert candidate("jxxlbbWLCbNA") == "jxxlbbWLCbNA"
    assert candidate("miUxGUcQzdGwdmJJvk") == "miUxGUcQzdGwdmJJvk"
    assert candidate("okqMlesMSclPNr") == "okqMlesMSclPNr"
    assert candidate("eeiWUAftZZYcudH") == "eeiWUAftZZYcudH"
    assert candidate("ovKRFxxIcByrJpHMW") == "ovKRFxxIcByrJpHMW"
    assert candidate("tmZ LEeXAsP XkxKW") == "tmZ_LEeXAsP_XkxKW"
    assert candidate("pNllZgisQYZI") == "pNllZgisQYZI"
    assert candidate("gM abkQTcoCGdt") == "gM_abkQTcoCGdt"
    assert candidate("UGzwdZIWIbeSJIHVAra") == "UGzwdZIWIbeSJIHVAra"
    assert candidate("GjORscqWEWCLcMC hniY") == "GjORscqWEWCLcMC_hniY"
    assert candidate("zegqwMEjltqOWb") == "zegqwMEjltqOWb"
    assert candidate("EOSMNcKatWa vOB") == "EOSMNcKatWa_vOB"
    assert candidate("ZSBIgbmjRpDObzc") == "ZSBIgbmjRpDObzc"
    assert candidate("eergXZuyKZPGsGR") == "eergXZuyKZPGsGR"
    assert candidate("BnDa VVXwPOb") == "BnDa_VVXwPOb"
    assert candidate("bMiwQIZzqIGGnmmyBO ") == "bMiwQIZzqIGGnmmyBO_"
    assert candidate(" FYtZfHCxtlnbF") == "_FYtZfHCxtlnbF"
    assert candidate("JNeRKkRCOwiVARvPAtr") == "JNeRKkRCOwiVARvPAtr"
    assert candidate("tNSJwuqXojKcqTcCPa") == "tNSJwuqXojKcqTcCPa"
    assert candidate("wWIMnLDnwvvIiLOUVlxy") == "wWIMnLDnwvvIiLOUVlxy"
    assert candidate("y aVewwoeQVVxLTn") == "y_aVewwoeQVVxLTn"
    assert candidate("NIhQSEobYUdzftFPZCr ") == "NIhQSEobYUdzftFPZCr_"
    assert candidate("V MoFjyTDPYPWYHpUN") == "V_MoFjyTDPYPWYHpUN"
    assert candidate("qX wRbAfbd xf") == "qX_wRbAfbd_xf"
    assert candidate("GXShzTBbBnozWwwaYBwn") == "GXShzTBbBnozWwwaYBwn"
    assert candidate("xyIvoLTPQvdGgWpZJkza") == "xyIvoLTPQvdGgWpZJkza"
    assert candidate("CQhgkMFknXmdeNHz") == "CQhgkMFknXmdeNHz"
    assert candidate("CQHZNfyVMw OnNTdfh") == "CQHZNfyVMw_OnNTdfh"
    assert candidate("LHvSkkMbRpeQykWfh") == "LHvSkkMbRpeQykWfh"
    assert candidate("RwwIwjgdneLFCSpVla") == "RwwIwjgdneLFCSpVla"
    assert candidate("rlGRYqhUbAuNePWq") == "rlGRYqhUbAuNePWq"
    assert candidate("MdEeJIypeGguEvDD") == "MdEeJIypeGguEvDD"
    assert candidate("gJMksRpjskKXMQchkF") == "gJMksRpjskKXMQchkF"

if __name__ == '__main__':
    check(replace_spaces)