from case_MBPP_022 import subject_marks


def check(candidate):
    assert candidate([('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)])==[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]
    assert candidate([('Telugu',49),('Hindhi',54),('Social',33)])==([('Social',33),('Telugu',49),('Hindhi',54)])
    assert candidate([('Physics',96),('Chemistry',97),('Biology',45)])==([('Biology',45),('Physics',96),('Chemistry',97)])
    assert candidate([('OEoLiruoZyU', 88), ('mIvDiJu', 90), ('gbLBnXfPg', 95), ('UQwGJqSkunwBAQULBfw', 77)]) == [('UQwGJqSkunwBAQULBfw', 77), ('OEoLiruoZyU', 88), ('mIvDiJu', 90), ('gbLBnXfPg', 95)]
    assert candidate([('cPFV', 88), ('CgDf', 88), ('oOzDEneP', 93), ('oDwiNqxTvRUJO', 82)]) == [('oDwiNqxTvRUJO', 82), ('cPFV', 88), ('CgDf', 88), ('oOzDEneP', 93)]
    assert candidate([('bYxQ', 87), ('cAMTrHC', 90), ('Qhow', 95), ('OMMPTxXUNPQXSPdCZ', 77)]) == [('OMMPTxXUNPQXSPdCZ', 77), ('bYxQ', 87), ('cAMTrHC', 90), ('Qhow', 95)]
    assert candidate([('vSicc', 89), ('KyrnfQnQrwc', 92), ('DHxWT', 94), ('wGtStVHIFzXkwdTX vcq', 81)]) == [('wGtStVHIFzXkwdTX vcq', 81), ('vSicc', 89), ('KyrnfQnQrwc', 92), ('DHxWT', 94)]
    assert candidate([('moZPBy', 92), ('iWiL', 92), ('zCaA', 97), ('HLTKhqbEqtCv l', 86)]) == [('HLTKhqbEqtCv l', 86), ('moZPBy', 92), ('iWiL', 92), ('zCaA', 97)]
    assert candidate([('EzxjNgSwlI', 88), ('Wrn', 92), ('DmXkG', 102), ('rEiARNRbOKOooS', 86)]) == [('rEiARNRbOKOooS', 86), ('EzxjNgSwlI', 88), ('Wrn', 92), ('DmXkG', 102)]
    assert candidate([('jMVtNMLssslK', 91), ('rfqGYyl', 88), ('qhaQoY', 94), ('kNFNwaieJFnMNKnEyK', 81)]) == [('kNFNwaieJFnMNKnEyK', 81), ('rfqGYyl', 88), ('jMVtNMLssslK', 91), ('qhaQoY', 94)]
    assert candidate([('FNQAIVe', 85), ('ARlPcNnFbkBL', 92), ('ytPSw', 92), ('fsCNCrgFHQftcH', 84)]) == [('fsCNCrgFHQftcH', 84), ('FNQAIVe', 85), ('ARlPcNnFbkBL', 92), ('ytPSw', 92)]
    assert candidate([('moSpNzAg', 88), ('aREeLPKi', 92), ('PlQdIawnW', 98), ('iNbnbXlXrPtFkOmVv', 84)]) == [('iNbnbXlXrPtFkOmVv', 84), ('moSpNzAg', 88), ('aREeLPKi', 92), ('PlQdIawnW', 98)]
    assert candidate([('ylkiTygWyXE', 89), ('PZfX', 95), ('DYBCbAAka', 94), ('nnNysBfthiRsTF yRbvtX', 79)]) == [('nnNysBfthiRsTF yRbvtX', 79), ('ylkiTygWyXE', 89), ('DYBCbAAka', 94), ('PZfX', 95)]
    assert candidate([('wKeYoleLOZ', 90), ('UZKWtqWCpS', 85), ('PtaXUSICX', 95), ('xcwObYeZRWCjqgkKyBh ', 80)]) == [('xcwObYeZRWCjqgkKyBh ', 80), ('UZKWtqWCpS', 85), ('wKeYoleLOZ', 90), ('PtaXUSICX', 95)]
    assert candidate([('PGqbVWWoVY', 88), ('fuDnsj', 89), ('ZGYyuGx', 92), ('MB D vQCgbThaojch', 77)]) == [('MB D vQCgbThaojch', 77), ('PGqbVWWoVY', 88), ('fuDnsj', 89), ('ZGYyuGx', 92)]
    assert candidate([('uPLoAM', 91), ('wbmNbIKma', 89), ('MFDgyVYM', 98), ('uGXvKtwQYoCx', 81)]) == [('uGXvKtwQYoCx', 81), ('wbmNbIKma', 89), ('uPLoAM', 91), ('MFDgyVYM', 98)]
    assert candidate([('ucBLvKn', 84), ('FoU', 86), ('cvE', 99), ('cDrNAdgrHoWpgeU', 84)]) == [('ucBLvKn', 84), ('cDrNAdgrHoWpgeU', 84), ('FoU', 86), ('cvE', 99)]
    assert candidate([('zgPYQeqfC', 86), ('ZaQR', 89), ('rTgoQ', 95), ('qUdRqRdL kpZsmAlefyX', 82)]) == [('qUdRqRdL kpZsmAlefyX', 82), ('zgPYQeqfC', 86), ('ZaQR', 89), ('rTgoQ', 95)]
    assert candidate([('lxCs', 90), ('gfPcdSz', 87), ('eNS', 101), ('DIiNtXYd XFJJvxao', 80)]) == [('DIiNtXYd XFJJvxao', 80), ('gfPcdSz', 87), ('lxCs', 90), ('eNS', 101)]
    assert candidate([('NaLoACnnqh', 92), ('oHePdMddKN', 86), ('lgRUjr', 98), ('JSZmxYVTfbWzjq', 79)]) == [('JSZmxYVTfbWzjq', 79), ('oHePdMddKN', 86), ('NaLoACnnqh', 92), ('lgRUjr', 98)]
    assert candidate([('TuSZgJDuPF', 84), ('HKYFfg', 88), ('henHT', 100), ('przTdXRYIrNS', 77)]) == [('przTdXRYIrNS', 77), ('TuSZgJDuPF', 84), ('HKYFfg', 88), ('henHT', 100)]
    assert candidate([('NsKzivsRl', 87), ('rekCCLItTPpv', 85), ('nwgEnrgg', 96), ('OevnERBJoXyzIEmyJJ', 77)]) == [('OevnERBJoXyzIEmyJJ', 77), ('rekCCLItTPpv', 85), ('NsKzivsRl', 87), ('nwgEnrgg', 96)]
    assert candidate([('kAGUuwpiH', 93), ('KNQWiuq', 95), ('udrF', 94), ('JmuMCXFAiVYQnIowNx', 80)]) == [('JmuMCXFAiVYQnIowNx', 80), ('kAGUuwpiH', 93), ('udrF', 94), ('KNQWiuq', 95)]
    assert candidate([('zAV', 90), ('YQQOKGNG', 92), ('hdsrLFUV', 100), ('yVTEtRwxxxtb', 86)]) == [('yVTEtRwxxxtb', 86), ('zAV', 90), ('YQQOKGNG', 92), ('hdsrLFUV', 100)]
    assert candidate([('poWpC', 84), ('WNkaCKDjWWC', 95), ('USWKwMg', 92), ('LTPePxXydsRcsTgOA', 81)]) == [('LTPePxXydsRcsTgOA', 81), ('poWpC', 84), ('USWKwMg', 92), ('WNkaCKDjWWC', 95)]
    assert candidate([('yaYDs', 93), ('oWW', 90), ('hllzmI', 95), ('Gwg nxvDuJxlYUbXWZ', 77)]) == [('Gwg nxvDuJxlYUbXWZ', 77), ('oWW', 90), ('yaYDs', 93), ('hllzmI', 95)]
    assert candidate([('UWfZF', 89), ('RplarQ', 87), ('UeHz', 92), ('HjATajU IpIFXtVneA', 77)]) == [('HjATajU IpIFXtVneA', 77), ('RplarQ', 87), ('UWfZF', 89), ('UeHz', 92)]
    assert candidate([('KxMMw', 91), ('QnMUoOp', 90), ('MTrpRQ', 102), ('PqoJUhBVeDzEOTWYDaD', 83)]) == [('PqoJUhBVeDzEOTWYDaD', 83), ('QnMUoOp', 90), ('KxMMw', 91), ('MTrpRQ', 102)]
    assert candidate([('oywUNZcvRO', 87), ('FldXVcvrSEO', 93), ('mED', 94), ('fBO SdVCnkuQtmUy R', 86)]) == [('fBO SdVCnkuQtmUy R', 86), ('oywUNZcvRO', 87), ('FldXVcvrSEO', 93), ('mED', 94)]
    assert candidate([('BWqmGXLyxvjt', 93), ('MJMzsQDxHpjR', 90), ('YeHm', 96), ('uBNnOiEqOEyzkedxq', 87)]) == [('uBNnOiEqOEyzkedxq', 87), ('MJMzsQDxHpjR', 90), ('BWqmGXLyxvjt', 93), ('YeHm', 96)]
    assert candidate([('mqmyD', 83), ('uESRxUfqIco', 92), ('bHOpv', 102), ('oGQYGwOwbLyYdJYvBVG', 80)]) == [('oGQYGwOwbLyYdJYvBVG', 80), ('mqmyD', 83), ('uESRxUfqIco', 92), ('bHOpv', 102)]
    assert candidate([('yUzVsaRsjw', 84), ('DVUuFkb', 95), ('SsHI', 97), ('HybMXjJEYT iHKU', 87)]) == [('yUzVsaRsjw', 84), ('HybMXjJEYT iHKU', 87), ('DVUuFkb', 95), ('SsHI', 97)]
    assert candidate([('lbscVXp', 89), ('UUC', 85), ('ZmWaD', 95), ('IvLMQmoLcuNlXFckZ', 87)]) == [('UUC', 85), ('IvLMQmoLcuNlXFckZ', 87), ('lbscVXp', 89), ('ZmWaD', 95)]
    assert candidate([('ZhyXbryR', 85), ('rhY', 94), ('cOsv', 100), ('mpoQmrChrwjTr', 86)]) == [('ZhyXbryR', 85), ('mpoQmrChrwjTr', 86), ('rhY', 94), ('cOsv', 100)]
    assert candidate([('OnHfebNhx', 86), ('gKoR', 90), ('RqctHtu', 100), ('QgdNILgKjAXwtHx', 82)]) == [('QgdNILgKjAXwtHx', 82), ('OnHfebNhx', 86), ('gKoR', 90), ('RqctHtu', 100)]
    assert candidate([('UDOcqK', 88), ('AenkSWIZYeEn', 86), ('BGhUYXzK', 102), ('yhkNITljovWZuxY', 85)]) == [('yhkNITljovWZuxY', 85), ('AenkSWIZYeEn', 86), ('UDOcqK', 88), ('BGhUYXzK', 102)]
    assert candidate([('BUveqJdXw', 44), ('YNZysJ', 58), ('duDvJokf', 28)]) == [('duDvJokf', 28), ('BUveqJdXw', 44), ('YNZysJ', 58)]
    assert candidate([('GflrCC', 48), ('txR', 55), ('vDjBwolkemV', 30)]) == [('vDjBwolkemV', 30), ('GflrCC', 48), ('txR', 55)]
    assert candidate([('VcHJlTrWUr', 44), ('ehO', 56), ('wWIh', 34)]) == [('wWIh', 34), ('VcHJlTrWUr', 44), ('ehO', 56)]
    assert candidate([('RSooMIj', 46), ('yxGNla', 55), ('qrUT', 37)]) == [('qrUT', 37), ('RSooMIj', 46), ('yxGNla', 55)]
    assert candidate([('gtMRdaf', 49), ('OMDaneQzq', 49), ('iygX', 38)]) == [('iygX', 38), ('gtMRdaf', 49), ('OMDaneQzq', 49)]
    assert candidate([('AthScmnXBGK', 47), ('dPygj', 51), ('jgoXOA', 36)]) == [('jgoXOA', 36), ('AthScmnXBGK', 47), ('dPygj', 51)]
    assert candidate([('BNioszAD', 52), ('PsB', 57), ('tVYQGM', 37)]) == [('tVYQGM', 37), ('BNioszAD', 52), ('PsB', 57)]
    assert candidate([('AhXUeQgJLDa', 50), ('KUQIdub', 50), ('UmHDbaZi', 31)]) == [('UmHDbaZi', 31), ('AhXUeQgJLDa', 50), ('KUQIdub', 50)]
    assert candidate([('YPRAh', 50), ('kzwuFGWmjo', 58), ('PgbEev', 31)]) == [('PgbEev', 31), ('YPRAh', 50), ('kzwuFGWmjo', 58)]
    assert candidate([('OFTCUwYoXNg', 50), ('PjmuKXHV', 56), ('pWUCopIcHhi', 35)]) == [('pWUCopIcHhi', 35), ('OFTCUwYoXNg', 50), ('PjmuKXHV', 56)]
    assert candidate([('mlkjvL', 54), ('NDUYiPH', 55), ('MrDt', 30)]) == [('MrDt', 30), ('mlkjvL', 54), ('NDUYiPH', 55)]
    assert candidate([('bzZRGCCFBLBL', 51), ('ygzLSql', 57), ('tRXkabbokz', 34)]) == [('tRXkabbokz', 34), ('bzZRGCCFBLBL', 51), ('ygzLSql', 57)]
    assert candidate([('JoVBt', 49), ('fQRssRp', 59), ('nrQWdvtCRnIQ', 37)]) == [('nrQWdvtCRnIQ', 37), ('JoVBt', 49), ('fQRssRp', 59)]
    assert candidate([('GxWbDvbp', 50), ('USSVBXtQyeSk', 50), ('aEfpvlH', 37)]) == [('aEfpvlH', 37), ('GxWbDvbp', 50), ('USSVBXtQyeSk', 50)]
    assert candidate([('YGlUqRu', 53), ('RxUUx', 49), ('THNXRUMNIN', 28)]) == [('THNXRUMNIN', 28), ('RxUUx', 49), ('YGlUqRu', 53)]
    assert candidate([('hawpDDrmwS', 50), ('XaOPMqMC', 57), ('ztYN', 33)]) == [('ztYN', 33), ('hawpDDrmwS', 50), ('XaOPMqMC', 57)]
    assert candidate([('PRwnHqrSB', 48), ('LWGyycTr', 58), ('ptDQH', 32)]) == [('ptDQH', 32), ('PRwnHqrSB', 48), ('LWGyycTr', 58)]
    assert candidate([('alPWVrTkePny', 49), ('sUjGzMZu', 54), ('BdxCBrUANL', 35)]) == [('BdxCBrUANL', 35), ('alPWVrTkePny', 49), ('sUjGzMZu', 54)]
    assert candidate([('eSpz', 45), ('XOUdd', 56), ('uegESoGka', 32)]) == [('uegESoGka', 32), ('eSpz', 45), ('XOUdd', 56)]
    assert candidate([('XErMoZfc', 54), ('HEfo', 52), ('ssxfVco', 28)]) == [('ssxfVco', 28), ('HEfo', 52), ('XErMoZfc', 54)]
    assert candidate([('uYI', 50), ('HDbEvRPygPfJ', 51), ('MpbfWtl', 31)]) == [('MpbfWtl', 31), ('uYI', 50), ('HDbEvRPygPfJ', 51)]
    assert candidate([('zMZVJ', 47), ('dfI', 52), ('QrbaSnxLigSi', 28)]) == [('QrbaSnxLigSi', 28), ('zMZVJ', 47), ('dfI', 52)]
    assert candidate([('hmdT', 47), ('QYtlt', 59), ('fXmRtpOgZx', 33)]) == [('fXmRtpOgZx', 33), ('hmdT', 47), ('QYtlt', 59)]
    assert candidate([('BZN', 50), ('oPtEayZEks', 52), ('YafUYsbo', 33)]) == [('YafUYsbo', 33), ('BZN', 50), ('oPtEayZEks', 52)]
    assert candidate([('QVNqZG', 52), ('pyHM', 52), ('vYlzHcPKhKNE', 30)]) == [('vYlzHcPKhKNE', 30), ('QVNqZG', 52), ('pyHM', 52)]
    assert candidate([('yUIFtC', 45), ('iZbILNTi', 55), ('XUI', 31)]) == [('XUI', 31), ('yUIFtC', 45), ('iZbILNTi', 55)]
    assert candidate([('SxyJ', 47), ('pKKKssOcfeTm', 57), ('WYxpXbF', 32)]) == [('WYxpXbF', 32), ('SxyJ', 47), ('pKKKssOcfeTm', 57)]
    assert candidate([('OrKvGbY', 47), ('ToFEweovwFej', 49), ('qfdLEuJ', 36)]) == [('qfdLEuJ', 36), ('OrKvGbY', 47), ('ToFEweovwFej', 49)]
    assert candidate([('PADy', 47), ('ofDiG', 49), ('rHhTxTTd', 37)]) == [('rHhTxTTd', 37), ('PADy', 47), ('ofDiG', 49)]
    assert candidate([('nwsOitNCCR', 47), ('JXruZS', 55), ('aEFiQg', 37)]) == [('aEFiQg', 37), ('nwsOitNCCR', 47), ('JXruZS', 55)]
    assert candidate([('hkDlcOBm', 54), ('YHxLank', 55), ('mQymocYOrYlz', 38)]) == [('mQymocYOrYlz', 38), ('hkDlcOBm', 54), ('YHxLank', 55)]
    assert candidate([('bsFWp', 51), ('PjkcJ', 59), ('CvZjqLSH', 36)]) == [('CvZjqLSH', 36), ('bsFWp', 51), ('PjkcJ', 59)]
    assert candidate([('HckT', 48), ('hPhjf', 58), ('kcH', 36)]) == [('kcH', 36), ('HckT', 48), ('hPhjf', 58)]
    assert candidate([('pVdxaFkBK', 91), ('CLbBrgIuy', 100), ('SHpweXOC', 43)]) == [('SHpweXOC', 43), ('pVdxaFkBK', 91), ('CLbBrgIuy', 100)]
    assert candidate([('GtqtcoYuNS', 96), ('VUXOVpijxrgQy', 99), ('dJwACdcaDnwz', 46)]) == [('dJwACdcaDnwz', 46), ('GtqtcoYuNS', 96), ('VUXOVpijxrgQy', 99)]
    assert candidate([('DdkfXJvQ', 92), ('wVeuLkazwWuFc', 100), ('mOqBtVkvA', 44)]) == [('mOqBtVkvA', 44), ('DdkfXJvQ', 92), ('wVeuLkazwWuFc', 100)]
    assert candidate([('NmwtPiEq', 97), ('MMYdAV', 94), ('qnnREyPdeOhD', 45)]) == [('qnnREyPdeOhD', 45), ('MMYdAV', 94), ('NmwtPiEq', 97)]
    assert candidate([('kQB', 96), ('omSIKuAGKLSqwRp', 93), ('eCFKTKlSH', 42)]) == [('eCFKTKlSH', 42), ('omSIKuAGKLSqwRp', 93), ('kQB', 96)]
    assert candidate([('GNrHbB', 98), ('XzRYRjznfnYDr', 98), ('EivyUc', 40)]) == [('EivyUc', 40), ('GNrHbB', 98), ('XzRYRjznfnYDr', 98)]
    assert candidate([('BJogx', 96), ('UKSjcfajsqj', 98), ('IJIJWMhWFzD', 49)]) == [('IJIJWMhWFzD', 49), ('BJogx', 96), ('UKSjcfajsqj', 98)]
    assert candidate([('kcjmGH', 95), ('jcLyCjJD', 102), ('uEKLvGIy', 44)]) == [('uEKLvGIy', 44), ('kcjmGH', 95), ('jcLyCjJD', 102)]
    assert candidate([('vSYsEINd', 95), ('WILuPFVXzJu', 98), ('xpZzxTaHCjxW', 41)]) == [('xpZzxTaHCjxW', 41), ('vSYsEINd', 95), ('WILuPFVXzJu', 98)]
    assert candidate([('SPiKhnyOGdo', 95), ('aBXRCDLwVsRtfiJ', 97), ('RlxJuCCYmS', 47)]) == [('RlxJuCCYmS', 47), ('SPiKhnyOGdo', 95), ('aBXRCDLwVsRtfiJ', 97)]
    assert candidate([('dLFDpgsSM', 101), ('BAZpJacjMua', 100), ('mrbuUEF', 45)]) == [('mrbuUEF', 45), ('BAZpJacjMua', 100), ('dLFDpgsSM', 101)]
    assert candidate([('aaIHJhnJZjD', 98), ('BnikmIlQM', 95), ('pVRTHYcn', 44)]) == [('pVRTHYcn', 44), ('BnikmIlQM', 95), ('aaIHJhnJZjD', 98)]
    assert candidate([('FgMdY', 99), ('MvlRtygYqQith', 94), ('ZTQYaC', 48)]) == [('ZTQYaC', 48), ('MvlRtygYqQith', 94), ('FgMdY', 99)]
    assert candidate([('JUfvluw', 94), ('YtEwjqgSh', 96), ('rWvHLMJaLAfc', 48)]) == [('rWvHLMJaLAfc', 48), ('JUfvluw', 94), ('YtEwjqgSh', 96)]
    assert candidate([('uFHCmQoDK', 94), ('qcFUWOpBNQJVN', 94), ('CRfuBmlFS', 44)]) == [('CRfuBmlFS', 44), ('uFHCmQoDK', 94), ('qcFUWOpBNQJVN', 94)]
    assert candidate([('oqfRVgLsOfRy', 95), ('lqPNYlaKVoVvwr', 100), ('OMoexuDNmXyf', 50)]) == [('OMoexuDNmXyf', 50), ('oqfRVgLsOfRy', 95), ('lqPNYlaKVoVvwr', 100)]
    assert candidate([('nKAIjaMfIfpM', 101), ('GshcTvsNtt', 95), ('tlvZIkGGe', 44)]) == [('tlvZIkGGe', 44), ('GshcTvsNtt', 95), ('nKAIjaMfIfpM', 101)]
    assert candidate([('gdGoDrOd', 99), ('isdlVID', 98), ('IQyKLWvN', 42)]) == [('IQyKLWvN', 42), ('isdlVID', 98), ('gdGoDrOd', 99)]
    assert candidate([('DoeesZYMQjN', 101), ('FePBRYGkszOFp', 101), ('RqmoEhNm', 47)]) == [('RqmoEhNm', 47), ('DoeesZYMQjN', 101), ('FePBRYGkszOFp', 101)]
    assert candidate([('OllsvohJQa', 96), ('cEYuroelvBaUR', 97), ('jAUsE', 46)]) == [('jAUsE', 46), ('OllsvohJQa', 96), ('cEYuroelvBaUR', 97)]
    assert candidate([('iNdw', 93), ('guVoOYFXevzRXC', 100), ('hnTkhnHqaknw', 43)]) == [('hnTkhnHqaknw', 43), ('iNdw', 93), ('guVoOYFXevzRXC', 100)]
    assert candidate([('IwDd', 100), ('qHifLObg', 95), ('gzwLnKRrS', 49)]) == [('gzwLnKRrS', 49), ('qHifLObg', 95), ('IwDd', 100)]
    assert candidate([('riyoipIVnodh', 96), ('PlTZbszvYCzqhGr', 95), ('ONy', 45)]) == [('ONy', 45), ('PlTZbszvYCzqhGr', 95), ('riyoipIVnodh', 96)]
    assert candidate([('yyaoHcQl', 92), ('xZCgwF', 102), ('EvVBKBT', 41)]) == [('EvVBKBT', 41), ('yyaoHcQl', 92), ('xZCgwF', 102)]
    assert candidate([('abH', 97), ('OdehDjqJ', 101), ('bdRU', 49)]) == [('bdRU', 49), ('abH', 97), ('OdehDjqJ', 101)]
    assert candidate([('uFiB', 96), ('aYmJcaoFr', 98), ('xHDKfbuVB', 48)]) == [('xHDKfbuVB', 48), ('uFiB', 96), ('aYmJcaoFr', 98)]
    assert candidate([('zQJjXNgTLe', 98), ('YEmwQaLNXGgMky', 94), ('JDQJgXiUx', 49)]) == [('JDQJgXiUx', 49), ('YEmwQaLNXGgMky', 94), ('zQJjXNgTLe', 98)]
    assert candidate([('umdIyVhjPo', 92), ('NYBDPfUewHyBUZ', 102), ('zSCcSmThn', 49)]) == [('zSCcSmThn', 49), ('umdIyVhjPo', 92), ('NYBDPfUewHyBUZ', 102)]
    assert candidate([('tHVkb', 94), ('qYcejP', 92), ('wUajcaSDJ', 46)]) == [('wUajcaSDJ', 46), ('qYcejP', 92), ('tHVkb', 94)]
    assert candidate([('YSSMRTsEFK', 100), ('WVqLuUY', 98), ('OzML', 42)]) == [('OzML', 42), ('WVqLuUY', 98), ('YSSMRTsEFK', 100)]
    assert candidate([('ZPoZuFiw', 97), ('UoDABQSvOdkCuV', 95), ('uFslvKYhFn', 47)]) == [('uFslvKYhFn', 47), ('UoDABQSvOdkCuV', 95), ('ZPoZuFiw', 97)]
    assert candidate([('sxlGrTcJ', 96), ('FIqmyf', 94), ('Vhvfhmiu', 42)]) == [('Vhvfhmiu', 42), ('FIqmyf', 94), ('sxlGrTcJ', 96)]
    assert candidate([('oolJEgaEj', 94), ('iMfMjBPS', 92), ('WZnD', 44)]) == [('WZnD', 44), ('iMfMjBPS', 92), ('oolJEgaEj', 94)]

if __name__ == '__main__':
    check(subject_marks)