from case_MBPP_110 import replace_blank


def check(candidate):
    assert candidate("hello people",'@')==("hello@people")
    assert candidate("python program language",'$')==("python$program$language")
    assert candidate("blank space","-")==("blank-space")
    assert candidate('rhvorhoickcyivoqz', '!') == "rhvorhoickcyivoqz"
    assert candidate('zfwcyftlzco vp', '<') == "zfwcyftlzco<vp"
    assert candidate('tocxwapxsme', '~') == "tocxwapxsme"
    assert candidate('ylqnvxdspeforzed', '-') == "ylqnvxdspeforzed"
    assert candidate('todpmlrwycjqvgbek', '#') == "todpmlrwycjqvgbek"
    assert candidate('gkcygfvoagwlqi cr', '>') == "gkcygfvoagwlqi>cr"
    assert candidate('hwo nkyowqjstroa', '?') == "hwo?nkyowqjstroa"
    assert candidate('isdmq jonrohec', ':') == "isdmq:jonrohec"
    assert candidate('em diixpuxcub', '#') == "em#diixpuxcub"
    assert candidate('animkwglxbsz', '%') == "animkwglxbsz"
    assert candidate('zknwsepunftsbs', '/') == "zknwsepunftsbs"
    assert candidate('mrjpvqkheoan tlop', '?') == "mrjpvqkheoan?tlop"
    assert candidate('zojquz hphhpjzsu', '&') == "zojquz&hphhpjzsu"
    assert candidate('dqnbdegckmayw', '#') == "dqnbdegckmayw"
    assert candidate('rxksvslue', '@') == "rxksvslue"
    assert candidate('gmidxpbopi', '~') == "gmidxpbopi"
    assert candidate('eioflukjkpz', '/') == "eioflukjkpz"
    assert candidate('patmbj bxsz', '=') == "patmbj=bxsz"
    assert candidate('ewlrahidh', '+') == "ewlrahidh"
    assert candidate('lpsdoubdqdcbn', '?') == "lpsdoubdqdcbn"
    assert candidate('ikcchilprh ', '^') == "ikcchilprh^"
    assert candidate('vkcqwrysukelckome', '*') == "vkcqwrysukelckome"
    assert candidate('qmeuxoazyiahbq', '-') == "qmeuxoazyiahbq"
    assert candidate('bdamifvadeulij', ':') == "bdamifvadeulij"
    assert candidate('czjpmfwyvqrotskr', '!') == "czjpmfwyvqrotskr"
    assert candidate('pvjr  qtvp', '^') == "pvjr^^qtvp"
    assert candidate(' rlxbwdtnlo', '|') == "|rlxbwdtnlo"
    assert candidate('hjktjbrglsxbkxax', '?') == "hjktjbrglsxbkxax"
    assert candidate('ghmwjcsrwx', ':') == "ghmwjcsrwx"
    assert candidate('vlveyxi azzcwx', '$') == "vlveyxi$azzcwx"
    assert candidate('dieyqjswg', '!') == "dieyqjswg"
    assert candidate('btezfqjpxxezpla', '+') == "btezfqjpxxezpla"
    assert candidate('ftzlmbvfn mq', '>') == "ftzlmbvfn>mq"
    assert candidate('lwuvxjbmanjehiyyvv', '!') == "lwuvxjbmanjehiyyvv"
    assert candidate('nyherrfipnjjuxagjup', '@') == "nyherrfipnjjuxagjup"
    assert candidate('cjszcwbmdckgkasengqehxl', '-') == "cjszcwbmdckgkasengqehxl"
    assert candidate(' nyykbifvzfbltrrafpetwsbhkf', '*') == "*nyykbifvzfbltrrafpetwsbhkf"
    assert candidate('nynkksofjrgondcdxuc', '<') == "nynkksofjrgondcdxuc"
    assert candidate('tnhqiwk rxigybcplotzyykxdoa', '~') == "tnhqiwk~rxigybcplotzyykxdoa"
    assert candidate('uspfuaxnozxutmthhsblvyoow', '~') == "uspfuaxnozxutmthhsblvyoow"
    assert candidate('izi yjxswgapepagjm', '!') == "izi!yjxswgapepagjm"
    assert candidate('snp agiagsayispmcofvmzhd', '!') == "snp!agiagsayispmcofvmzhd"
    assert candidate('gycoykfhmmnkdwzrfdb', '%') == "gycoykfhmmnkdwzrfdb"
    assert candidate('lptawymfwmpm tamufnmcufqnwn', '@') == "lptawymfwmpm@tamufnmcufqnwn"
    assert candidate('lonxgfmqaeuyjtbjvqzxhyhxepq', '#') == "lonxgfmqaeuyjtbjvqzxhyhxepq"
    assert candidate('vio rofq slptvvenwza', '^') == "vio^rofq^slptvvenwza"
    assert candidate('cowdnyjtx fqcwroqrhxvvgcksl', '>') == "cowdnyjtx>fqcwroqrhxvvgcksl"
    assert candidate('ywxaqgdqypyqcf ptrrfv', '@') == "ywxaqgdqypyqcf@ptrrfv"
    assert candidate('msqtv yugbxm bwhltiendzzgwy', '~') == "msqtv~yugbxm~bwhltiendzzgwy"
    assert candidate('wemwqxsixaqylycjthyol dgd', '*') == "wemwqxsixaqylycjthyol*dgd"
    assert candidate('olp wrimjaamxpowctt', '|') == "olp|wrimjaamxpowctt"
    assert candidate('ubhbvy lvablshfkjhwmnlzt', '?') == "ubhbvy?lvablshfkjhwmnlzt"
    assert candidate('bqslbvjlhrmejxhorpa', '=') == "bqslbvjlhrmejxhorpa"
    assert candidate('rskydwqmgsbdbnxmea', '@') == "rskydwqmgsbdbnxmea"
    assert candidate('xwpgrwshalrhvufmzfzq ', '$') == "xwpgrwshalrhvufmzfzq$"
    assert candidate('tyeayqvtdjwvndzzysmengvlvle', '/') == "tyeayqvtdjwvndzzysmengvlvle"
    assert candidate('gssyjhkawapgdbnucawkvmto', ':') == "gssyjhkawapgdbnucawkvmto"
    assert candidate('uvvuobuvdtmawcfozkipeasf', '/') == "uvvuobuvdtmawcfozkipeasf"
    assert candidate('sqkag ykhftoamlklnjus vx', '-') == "sqkag-ykhftoamlklnjus-vx"
    assert candidate('yngcvbj gimwaoeodbxv', '#') == "yngcvbj#gimwaoeodbxv"
    assert candidate('eosguojf udcrpaaugpind', '~') == "eosguojf~udcrpaaugpind"
    assert candidate('qmtrzoklbcflnphqwa', '+') == "qmtrzoklbcflnphqwa"
    assert candidate('rkyjuwyndgrheipuegrcjv', '~') == "rkyjuwyndgrheipuegrcjv"
    assert candidate('w punywsvscirdcuuuw', '|') == "w|punywsvscirdcuuuw"
    assert candidate('xioygemnjlugzkkllnrzs', '|') == "xioygemnjlugzkkllnrzs"
    assert candidate('ickmutyvjmjajgpibhdzxakg', '>') == "ickmutyvjmjajgpibhdzxakg"
    assert candidate('krxqqmivgkd', '=') == "krxqqmivgkd"
    assert candidate('h azxxmwm xhii', '/') == "h/azxxmwm/xhii"
    assert candidate('hntgt rrzf', '@') == "hntgt@rrzf"
    assert candidate('ppjfpella ', '+') == "ppjfpella+"
    assert candidate('nkpwhalumjygo', '^') == "nkpwhalumjygo"
    assert candidate('kcnyoryuoochq', '?') == "kcnyoryuoochq"
    assert candidate('ugvhthl', '^') == "ugvhthl"
    assert candidate(' eswxkbuk', '|') == "|eswxkbuk"
    assert candidate('calz ok', '!') == "calz!ok"
    assert candidate('pucpvvveezxs', '/') == "pucpvvveezxs"
    assert candidate('k sthmnty', '+') == "k+sthmnty"
    assert candidate('uwp otvxao', '%') == "uwp%otvxao"
    assert candidate('cddnjfd', '|') == "cddnjfd"
    assert candidate('czfywhxqsjy', '|') == "czfywhxqsjy"
    assert candidate(' plgzys gp', '-') == "-plgzys-gp"
    assert candidate('gaosacwvso', '&') == "gaosacwvso"
    assert candidate('qeyimerf', '*') == "qeyimerf"
    assert candidate(' zm ivg', '@') == "@zm@ivg"
    assert candidate('pbghedjj k', '#') == "pbghedjj#k"
    assert candidate('tknjzecki', '<') == "tknjzecki"
    assert candidate('wyulhumcbc', '@') == "wyulhumcbc"
    assert candidate('jnfwqrixetmpdg', '@') == "jnfwqrixetmpdg"
    assert candidate('ljakgkcyz', '~') == "ljakgkcyz"
    assert candidate('uhimhlzcsmcxah', '+') == "uhimhlzcsmcxah"
    assert candidate('sbxepi', '@') == "sbxepi"
    assert candidate('pihfbs', '<') == "pihfbs"
    assert candidate('xzwhgovt', '<') == "xzwhgovt"
    assert candidate('rlobomy', '<') == "rlobomy"
    assert candidate('fxrxtditnlgdf ', '~') == "fxrxtditnlgdf~"
    assert candidate('jmhhwhrjp', '<') == "jmhhwhrjp"
    assert candidate('golmjixdc', '*') == "golmjixdc"
    assert candidate('t aaiwcb', '#') == "t#aaiwcb"
    assert candidate('kihoij', '/') == "kihoij"

if __name__ == '__main__':
    check(replace_blank)