from case_MBPP_238 import remove_whitespaces


def check(candidate):
    assert candidate(' Google    Flutter ') == 'GoogleFlutter'
    assert candidate(' Google    Dart ') == 'GoogleDart'
    assert candidate(' iOS    Swift ') == 'iOSSwift'
    assert candidate(" TcFTVmzfTCLevjzZBIAedd") == "TcFTVmzfTCLevjzZBIAedd"
    assert candidate(" wTgRcawFxOwbOgyy") == "wTgRcawFxOwbOgyy"
    assert candidate("jKnIMvSSr YzuqBbjmacU") == "jKnIMvSSrYzuqBbjmacU"
    assert candidate("lSwkIcsVmLYZRGjPMDlZg") == "lSwkIcsVmLYZRGjPMDlZg"
    assert candidate("zVVIDMcwZxoVQoMWyZLJhg") == "zVVIDMcwZxoVQoMWyZLJhg"
    assert candidate("lbvJnZhjdhOdSptHsef") == "lbvJnZhjdhOdSptHsef"
    assert candidate("wQDjZawmsyzkAhH") == "wQDjZawmsyzkAhH"
    assert candidate("RZKsqVBpuoFFXjBgpukY") == "RZKsqVBpuoFFXjBgpukY"
    assert candidate("MfnjLgeyIvybrbeHrBHBqf") == "MfnjLgeyIvybrbeHrBHBqf"
    assert candidate("FmoVMbEpejpNVyA") == "FmoVMbEpejpNVyA"
    assert candidate("rUeizsFTfiYaezi") == "rUeizsFTfiYaezi"
    assert candidate("BAwIHPMfjKvNIUDN") == "BAwIHPMfjKvNIUDN"
    assert candidate("alOFtDlgmqpEBFF") == "alOFtDlgmqpEBFF"
    assert candidate("TeDRVDJPPpKKikbmWblgcFn") == "TeDRVDJPPpKKikbmWblgcFn"
    assert candidate("ajlAKJaWPAfzeIUUgOpMRZj") == "ajlAKJaWPAfzeIUUgOpMRZj"
    assert candidate("WcSFKCxCswQxITnfALuzt ") == "WcSFKCxCswQxITnfALuzt"
    assert candidate("sRXzOauDPTPrfVb") == "sRXzOauDPTPrfVb"
    assert candidate("eRGlRDjdHikiBfA") == "eRGlRDjdHikiBfA"
    assert candidate("TjgXahxSLOxUXZMQOPLkKM") == "TjgXahxSLOxUXZMQOPLkKM"
    assert candidate("kkgzBDkipuWC loaDxsUww") == "kkgzBDkipuWCloaDxsUww"
    assert candidate("GvDoPRMNZyLqkUuIikqTZeFh") == "GvDoPRMNZyLqkUuIikqTZeFh"
    assert candidate("zcCBeDoEGTqscza") == "zcCBeDoEGTqscza"
    assert candidate("DwbXwnDmkZJPyPjaLzc") == "DwbXwnDmkZJPyPjaLzc"
    assert candidate("lRwrZ PaSjsgaMOGT") == "lRwrZPaSjsgaMOGT"
    assert candidate("CLbIlDmMvLyOMUXNtZhapUK") == "CLbIlDmMvLyOMUXNtZhapUK"
    assert candidate("YkANjxZAbhFBStwf") == "YkANjxZAbhFBStwf"
    assert candidate("gaDRczcPCXyQdfvuhAOxCnKr") == "gaDRczcPCXyQdfvuhAOxCnKr"
    assert candidate("jcnQkSSPFrJKGTFrOfB") == "jcnQkSSPFrJKGTFrOfB"
    assert candidate("gjuODOYaikIYaUODEhZaoG") == "gjuODOYaikIYaUODEhZaoG"
    assert candidate("BmXwFeGrmaUnfBrymCGY") == "BmXwFeGrmaUnfBrymCGY"
    assert candidate("hlhFIKxZavvYAYFFebPzBQ ") == "hlhFIKxZavvYAYFFebPzBQ"
    assert candidate("vHYQOgKIOof TouOCoT") == "vHYQOgKIOofTouOCoT"
    assert candidate("wmtyBXguTiHjXqT") == "wmtyBXguTiHjXqT"
    assert candidate("wznyjrkFqByqqDGItREh") == "wznyjrkFqByqqDGItREh"
    assert candidate("DwxYLpBMDwHpHSAVzEt") == "DwxYLpBMDwHpHSAVzEt"
    assert candidate("ZgVdIRBwqJBk") == "ZgVdIRBwqJBk"
    assert candidate("IMRmlmcitcFpAzkC") == "IMRmlmcitcFpAzkC"
    assert candidate("coSJAwWRqocCtjzIeKH") == "coSJAwWRqocCtjzIeKH"
    assert candidate("isNvxXKixZYTRzgp") == "isNvxXKixZYTRzgp"
    assert candidate("bEcYryoZYMiRhBl") == "bEcYryoZYMiRhBl"
    assert candidate("ynwrXbFsdOElHKHVFl jO") == "ynwrXbFsdOElHKHVFljO"
    assert candidate("cbqZtPSHiQzZmlQZ") == "cbqZtPSHiQzZmlQZ"
    assert candidate("UJ JTpiifPbHIlbuJIx") == "UJJTpiifPbHIlbuJIx"
    assert candidate("efTgokGyugWvJQ") == "efTgokGyugWvJQ"
    assert candidate("OFSLaWWFaw BcQ") == "OFSLaWWFawBcQ"
    assert candidate("yeEDhpfFblOtczje") == "yeEDhpfFblOtczje"
    assert candidate("kUycvzmjNTKvfwwGT") == "kUycvzmjNTKvfwwGT"
    assert candidate("jlaePgPapExM") == "jlaePgPapExM"
    assert candidate("BIeoTPjbdzem") == "BIeoTPjbdzem"
    assert candidate(" MPmB lRfCoX") == "MPmBlRfCoX"
    assert candidate("ikenXJlmViJrbZrwYExr") == "ikenXJlmViJrbZrwYExr"
    assert candidate("BMflQkEhy ZYRrxsIl") == "BMflQkEhyZYRrxsIl"
    assert candidate("MrSdFzBwWoquDTKGFPmj") == "MrSdFzBwWoquDTKGFPmj"
    assert candidate("OSZFRnMOCu nOx lZ") == "OSZFRnMOCunOxlZ"
    assert candidate("FQay UyzCCCRowYNGXx") == "FQayUyzCCCRowYNGXx"
    assert candidate("SlXfEcsOnMkpLBmrb") == "SlXfEcsOnMkpLBmrb"
    assert candidate("HnpHkYTKL AEZlIMlFQ") == "HnpHkYTKLAEZlIMlFQ"
    assert candidate("rPxCHzYvOfTMpHL") == "rPxCHzYvOfTMpHL"
    assert candidate("LmrTtwRfVZvOYvUVoh") == "LmrTtwRfVZvOYvUVoh"
    assert candidate("ETJGwDQyPQXYus") == "ETJGwDQyPQXYus"
    assert candidate("tCAhoODBbJcmuEARaTAp") == "tCAhoODBbJcmuEARaTAp"
    assert candidate(" fYOaykAAbPhegj") == "fYOaykAAbPhegj"
    assert candidate("mbyJJaeXysZqukReCS") == "mbyJJaeXysZqukReCS"
    assert candidate("HBDhwmPDmAoJzkcICp") == "HBDhwmPDmAoJzkcICp"
    assert candidate("dtRsawCCVubeTIHTcIUs") == "dtRsawCCVubeTIHTcIUs"
    assert candidate("WKvlYdrMnqfmBocNmCbXm") == "WKvlYdrMnqfmBocNmCbXm"
    assert candidate("XkIULgiy GvrJBun") == "XkIULgiyGvrJBun"
    assert candidate("znJlRkqdQy") == "znJlRkqdQy"
    assert candidate("cOQQaYhQGTEJqxFKm") == "cOQQaYhQGTEJqxFKm"
    assert candidate("wlHKnbDMDPosgTSqj") == "wlHKnbDMDPosgTSqj"
    assert candidate("zSyoBnvtLEPm") == "zSyoBnvtLEPm"
    assert candidate("SKLrLfMDZS") == "SKLrLfMDZS"
    assert candidate("hkdLUDMCBuhF") == "hkdLUDMCBuhF"
    assert candidate(" QeuvRbGBNVI") == "QeuvRbGBNVI"
    assert candidate("iPElhkx RC") == "iPElhkxRC"
    assert candidate("ulOxKGxTR") == "ulOxKGxTR"
    assert candidate("gTzvBHuXgkaCnbCJZV") == "gTzvBHuXgkaCnbCJZV"
    assert candidate("TxjEkKvVWRdGxqK") == "TxjEkKvVWRdGxqK"
    assert candidate("cSoqPJTyHVVKo") == "cSoqPJTyHVVKo"
    assert candidate("akwFdHEXUKatXQJMv") == "akwFdHEXUKatXQJMv"
    assert candidate("WPNJtyWXhHQGx") == "WPNJtyWXhHQGx"
    assert candidate("bcFNmneaNFmhu") == "bcFNmneaNFmhu"
    assert candidate("tdmIzUrhBiBjf") == "tdmIzUrhBiBjf"
    assert candidate("wexUGirsSVWalssC") == "wexUGirsSVWalssC"
    assert candidate("HqIuHnmaGOp") == "HqIuHnmaGOp"
    assert candidate("oVDMOeIAeRlHmVKdh") == "oVDMOeIAeRlHmVKdh"
    assert candidate("HgashlOsLphk") == "HgashlOsLphk"
    assert candidate("nLAjyvTlcVoxce") == "nLAjyvTlcVoxce"
    assert candidate("NoNknsvaSg") == "NoNknsvaSg"
    assert candidate("ENxJThkOfZdQ") == "ENxJThkOfZdQ"
    assert candidate("SnuqxTiFWvOxZLV") == "SnuqxTiFWvOxZLV"
    assert candidate("ORaaLoywoRvas SYyz") == "ORaaLoywoRvasSYyz"
    assert candidate("ZmXHmCdMNBYvF") == "ZmXHmCdMNBYvF"
    assert candidate("PFNSTcjODx BpSi") == "PFNSTcjODxBpSi"
    assert candidate("xdTiiFLWJW") == "xdTiiFLWJW"
    assert candidate("oQXlXXqZWTURhgAph") == "oQXlXXqZWTURhgAph"
    assert candidate("LrsQBaLMiVnMQDw ") == "LrsQBaLMiVnMQDw"
    assert candidate("XKDIFnyNZ") == "XKDIFnyNZ"
    assert candidate("peZMSACltYTzDeh") == "peZMSACltYTzDeh"

if __name__ == '__main__':
    check(remove_whitespaces)