from case_MBPP_041 import merge_dictionaries_three


def check(candidate):
    assert candidate({ "R": "Red", "B": "Black", "P": "Pink" }, { "G": "Green", "W": "White" },{ "O": "Orange", "W": "White", "B": "Black" })=={'B': 'Black', 'R': 'Red', 'P': 'Pink', 'G': 'Green', 'W': 'White', 'O': 'Orange'}
    assert candidate({ "R": "Red", "B": "Black", "P": "Pink" }, { "G": "Green", "W": "White" },{"L":"lavender","B":"Blue"})=={'W': 'White', 'P': 'Pink', 'B': 'Black', 'R': 'Red', 'G': 'Green', 'L': 'lavender'}
    assert candidate({ "R": "Red", "B": "Black", "P": "Pink" },{"L":"lavender","B":"Blue"},{ "G": "Green", "W": "White" })=={'B': 'Black', 'P': 'Pink', 'R': 'Red', 'G': 'Green', 'L': 'lavender', 'W': 'White'}
    assert candidate({'C': 'dTrUJgn', 'P': 'TUZqlp'}, {'V': 'wCBlH', 'Q': 'BcYSjZvqS'}, {'F': 'dGyakiNNLsgm', 'V': 'KqLICQziG', 'C': 'OWqAK'}) == {'F': 'dGyakiNNLsgm', 'V': 'wCBlH', 'C': 'dTrUJgn', 'Q': 'BcYSjZvqS', 'P': 'TUZqlp'}
    assert candidate({'K': 'toJDxzj', 'J': 'IusAq', 'V': 'Wrej'}, {'Q': 'RaBVTuE', 'X': 'dljoJU'}, {'A': 'oasBn', 'U': 'vfZYTLGeF', 'E': 'pHOqwMwJn'}) == {'A': 'oasBn', 'U': 'vfZYTLGeF', 'E': 'pHOqwMwJn', 'Q': 'RaBVTuE', 'X': 'dljoJU', 'K': 'toJDxzj', 'J': 'IusAq', 'V': 'Wrej'}
    assert candidate({'F': 'gbYWIU', 'V': 'YuW'}, {'N': 'NKr', 'O': 'uDGT'}, {'J': 'rUaCrEmI', 'X': 'OZXO', 'B': 'GkV'}) == {'J': 'rUaCrEmI', 'X': 'OZXO', 'B': 'GkV', 'N': 'NKr', 'O': 'uDGT', 'F': 'gbYWIU', 'V': 'YuW'}
    assert candidate({'S': 'ELvMAh', 'F': 'ITe', 'T': 'mVfcTHJ'}, {'W': 'xNdcRAKXT', 'Q': 'zkrUx'}, {'Q': 'VONUqnLFF', 'H': 'tdFoc', 'Z': 'Fnqk'}) == {'Q': 'zkrUx', 'H': 'tdFoc', 'Z': 'Fnqk', 'W': 'xNdcRAKXT', 'S': 'ELvMAh', 'F': 'ITe', 'T': 'mVfcTHJ'}
    assert candidate({'X': 'lQqG', 'S': 'dUabzTwLV', 'M': 'tSEpjqNem'}, {'J': 'YZXw', 'U': 'URhlHoAL'}, {'O': 'EqZY', 'T': 'PAa'}) == {'O': 'EqZY', 'T': 'PAa', 'J': 'YZXw', 'U': 'URhlHoAL', 'X': 'lQqG', 'S': 'dUabzTwLV', 'M': 'tSEpjqNem'}
    assert candidate({'M': 'rzMbrL', 'R': 'MkcXs', 'K': 'ITNNp'}, {'D': 'GhF', 'Q': 'eLzBSkDB'}, {'X': 'kVvzCtm', 'U': 'Meh', 'P': 'lfTLCwXJv'}) == {'X': 'kVvzCtm', 'U': 'Meh', 'P': 'lfTLCwXJv', 'D': 'GhF', 'Q': 'eLzBSkDB', 'M': 'rzMbrL', 'R': 'MkcXs', 'K': 'ITNNp'}
    assert candidate({'O': 'VQrCDHVUG', 'C': 'eTGZpWmjL', 'T': 'hTrJnpF'}, {'Q': 'wwfwXciZb', 'D': 'tjLWyohXQ'}, {'X': 'Fsqg', 'V': 'QvpQ', 'Z': 'uZzxJmtq'}) == {'X': 'Fsqg', 'V': 'QvpQ', 'Z': 'uZzxJmtq', 'Q': 'wwfwXciZb', 'D': 'tjLWyohXQ', 'O': 'VQrCDHVUG', 'C': 'eTGZpWmjL', 'T': 'hTrJnpF'}
    assert candidate({'V': 'fpMTslH', 'A': 'JOhBSYsAR', 'L': 'xHCwos'}, {'G': 'NYOnsm', 'R': 'byujQk'}, {'X': 'PBbkwhoQ', 'C': 'cIkHB'}) == {'X': 'PBbkwhoQ', 'C': 'cIkHB', 'G': 'NYOnsm', 'R': 'byujQk', 'V': 'fpMTslH', 'A': 'JOhBSYsAR', 'L': 'xHCwos'}
    assert candidate({'Q': 'tlTRiqrA', 'X': 'StwpgClr', 'B': 'xJpuBml'}, {'R': 'bdmC', 'V': 'PqrgHsC'}, {'D': 'Vtjx', 'S': 'BeeTSU', 'U': 'twbBG'}) == {'D': 'Vtjx', 'S': 'BeeTSU', 'U': 'twbBG', 'R': 'bdmC', 'V': 'PqrgHsC', 'Q': 'tlTRiqrA', 'X': 'StwpgClr', 'B': 'xJpuBml'}
    assert candidate({'I': 'gBIGQNrn', 'O': 'WsMDw', 'G': 'HHZruCF'}, {'T': 'JUeuxUtZ', 'E': 'BOTqtELA'}, {'X': 'CTrepJ', 'G': 'OwRnIX', 'E': 'WpOaZYHq'}) == {'X': 'CTrepJ', 'G': 'HHZruCF', 'E': 'BOTqtELA', 'T': 'JUeuxUtZ', 'I': 'gBIGQNrn', 'O': 'WsMDw'}
    assert candidate({'H': 'LjQW', 'Y': 'QRZOQk', 'D': 'prg'}, {'T': 'RNzyT', 'Y': 'KflvZMUZH'}, {'G': 'UJKHlkXzr', 'V': 'mWZjnt'}) == {'G': 'UJKHlkXzr', 'V': 'mWZjnt', 'T': 'RNzyT', 'Y': 'QRZOQk', 'H': 'LjQW', 'D': 'prg'}
    assert candidate({'P': 'OhXj', 'G': 'EGjgPeXh', 'Q': 'AXAOapOck'}, {'C': 'qCcwFbGdB', 'M': 'vZwIltm'}, {'I': 'NxqLXMGRc', 'K': 'nCpkh', 'S': 'eSBsK'}) == {'I': 'NxqLXMGRc', 'K': 'nCpkh', 'S': 'eSBsK', 'C': 'qCcwFbGdB', 'M': 'vZwIltm', 'P': 'OhXj', 'G': 'EGjgPeXh', 'Q': 'AXAOapOck'}
    assert candidate({'N': 'NJE', 'F': 'DBq', 'I': 'SOz'}, {'A': 'omXviz', 'B': 'zWRkr'}, {'N': 'KcdKrnV', 'H': 'TtNNPZah', 'P': 'kpHXgpY'}) == {'N': 'NJE', 'H': 'TtNNPZah', 'P': 'kpHXgpY', 'A': 'omXviz', 'B': 'zWRkr', 'F': 'DBq', 'I': 'SOz'}
    assert candidate({'E': 'avRV', 'X': 'WBeWFxVEY', 'W': 'FRA'}, {'O': 'Hotyi', 'S': 'IPjWqh'}, {'J': 'JTkkyq', 'P': 'Uwvh', 'A': 'VjTNgzEtw'}) == {'J': 'JTkkyq', 'P': 'Uwvh', 'A': 'VjTNgzEtw', 'O': 'Hotyi', 'S': 'IPjWqh', 'E': 'avRV', 'X': 'WBeWFxVEY', 'W': 'FRA'}
    assert candidate({'G': 'XDEECw', 'A': 'Uct', 'R': 'BEjtJiziz'}, {'L': 'FQDVhZ', 'S': 'MVpxHjecc'}, {'W': 'KrDoBWyAOkW', 'U': 'HFJ', 'Q': 'jAlsW'}) == {'W': 'KrDoBWyAOkW', 'U': 'HFJ', 'Q': 'jAlsW', 'L': 'FQDVhZ', 'S': 'MVpxHjecc', 'G': 'XDEECw', 'A': 'Uct', 'R': 'BEjtJiziz'}
    assert candidate({'E': 'yjsH', 'T': 'ueO', 'H': 'MDR'}, {'M': 'PnWTJAx', 'E': 'QyV'}, {'P': 'HjuWNVJRc', 'X': 'XkW', 'I': 'zEq'}) == {'P': 'HjuWNVJRc', 'X': 'XkW', 'I': 'zEq', 'M': 'PnWTJAx', 'E': 'yjsH', 'T': 'ueO', 'H': 'MDR'}
    assert candidate({'O': 'hVgV', 'X': 'MiDeeYGsV', 'E': 'EYQndL'}, {'K': 'vcN', 'T': 'vpcaTvt'}, {'T': 'pJiP', 'L': 'VStFq', 'P': 'ImCdbwIP'}) == {'T': 'vpcaTvt', 'L': 'VStFq', 'P': 'ImCdbwIP', 'K': 'vcN', 'O': 'hVgV', 'X': 'MiDeeYGsV', 'E': 'EYQndL'}
    assert candidate({'Q': 'TmrrwI', 'Z': 'BoPrFRiRd'}, {'Y': 'PvXKZ', 'X': 'iJVt'}, {'R': 'tICBRQM', 'U': 'UcoMCsWYb', 'B': 'TEDjs'}) == {'R': 'tICBRQM', 'U': 'UcoMCsWYb', 'B': 'TEDjs', 'Y': 'PvXKZ', 'X': 'iJVt', 'Q': 'TmrrwI', 'Z': 'BoPrFRiRd'}
    assert candidate({'C': 'YhVRtMDDU', 'Q': 'vHpzrhc', 'P': 'IIxor'}, {'J': 'aEIcdvr', 'S': 'GLqVhq'}, {'Q': 'FRw', 'L': 'yRUBIyD', 'H': 'OPnZW'}) == {'Q': 'vHpzrhc', 'L': 'yRUBIyD', 'H': 'OPnZW', 'J': 'aEIcdvr', 'S': 'GLqVhq', 'C': 'YhVRtMDDU', 'P': 'IIxor'}
    assert candidate({'D': 'dEvfbqST', 'A': 'deZJ', 'E': 'RnxXzh'}, {'Q': 'BVenBFao', 'H': 'dgsSpkDB'}, {'V': 'zTnmPrBHbnrG', 'C': 'rnPpoBqv', 'G': 'NmyOGk'}) == {'V': 'zTnmPrBHbnrG', 'C': 'rnPpoBqv', 'G': 'NmyOGk', 'Q': 'BVenBFao', 'H': 'dgsSpkDB', 'D': 'dEvfbqST', 'A': 'deZJ', 'E': 'RnxXzh'}
    assert candidate({'F': 'IBhNcy', 'C': 'yXBMQq', 'E': 'wkRGPh'}, {'C': 'UdSTxNbNU', 'Q': 'qMUyx'}, {'K': 'IpbIYVufYRG', 'Z': 'sjuV'}) == {'K': 'IpbIYVufYRG', 'Z': 'sjuV', 'C': 'yXBMQq', 'Q': 'qMUyx', 'F': 'IBhNcy', 'E': 'wkRGPh'}
    assert candidate({'C': 'iJLqnC', 'J': 'jCmt'}, {'W': 'MHrfjmid', 'L': 'gRALTpnF'}, {'E': 'fYwLeKTIrLj', 'R': 'Vjn', 'B': 'SwRvRLVg'}) == {'E': 'fYwLeKTIrLj', 'R': 'Vjn', 'B': 'SwRvRLVg', 'W': 'MHrfjmid', 'L': 'gRALTpnF', 'C': 'iJLqnC', 'J': 'jCmt'}
    assert candidate({'V': 'aNeioSong', 'B': 'Wqz', 'M': 'QOCP'}, {'R': 'vwmLpLk', 'S': 'whWZPr'}, {'Q': 'QeBb', 'W': 'rlNb', 'U': 'tOLqyUG'}) == {'Q': 'QeBb', 'W': 'rlNb', 'U': 'tOLqyUG', 'R': 'vwmLpLk', 'S': 'whWZPr', 'V': 'aNeioSong', 'B': 'Wqz', 'M': 'QOCP'}
    assert candidate({'F': 'EXZHYCMpT', 'Y': 'aFU', 'V': 'OGgu'}, {'N': 'sHlclDQ', 'H': 'BzOfDW'}, {'Q': 'Klobijzkr', 'U': 'wDBXNk', 'N': 'shKwoAx'}) == {'Q': 'Klobijzkr', 'U': 'wDBXNk', 'N': 'sHlclDQ', 'H': 'BzOfDW', 'F': 'EXZHYCMpT', 'Y': 'aFU', 'V': 'OGgu'}
    assert candidate({'K': 'KCoPWyxc', 'Z': 'sKVbj', 'S': 'WkzdEKdQg'}, {'D': 'YOYamC', 'S': 'nHsHTPk'}, {'D': 'tapaIcYfWGzr', 'R': 'ZDHlzordb', 'F': 'aRz'}) == {'D': 'YOYamC', 'R': 'ZDHlzordb', 'F': 'aRz', 'S': 'WkzdEKdQg', 'K': 'KCoPWyxc', 'Z': 'sKVbj'}
    assert candidate({'C': 'iQPqq', 'M': 'eqpMj', 'Q': 'LGPlw'}, {'H': 'HqAaWRp', 'U': 'haK'}, {'U': 'KAPKSCpVFB', 'H': 'QNoj', 'G': 'igmLmi'}) == {'U': 'haK', 'H': 'HqAaWRp', 'G': 'igmLmi', 'C': 'iQPqq', 'M': 'eqpMj', 'Q': 'LGPlw'}
    assert candidate({'F': 'Sgktc', 'X': 'ELuqLeOaf', 'A': 'KDALfN'}, {'C': 'wgPvgBE', 'Z': 'CZFdZkUVI'}, {'F': 'SQGMtO', 'H': 'jPPtPX', 'U': 'YAzZfE'}) == {'F': 'Sgktc', 'H': 'jPPtPX', 'U': 'YAzZfE', 'C': 'wgPvgBE', 'Z': 'CZFdZkUVI', 'X': 'ELuqLeOaf', 'A': 'KDALfN'}
    assert candidate({'J': 'NxogbBg', 'F': 'jSmNoduI', 'E': 'uOMbt'}, {'U': 'UjOM', 'L': 'ucnOcCIDo'}, {'Y': 'fRMfpOZda', 'F': 'ClXzZGTT', 'Z': 'MSm'}) == {'Y': 'fRMfpOZda', 'F': 'jSmNoduI', 'Z': 'MSm', 'U': 'UjOM', 'L': 'ucnOcCIDo', 'J': 'NxogbBg', 'E': 'uOMbt'}
    assert candidate({'L': 'juWPZZHsz', 'M': 'JVyHUMuA', 'S': 'HKDQSE'}, {'L': 'SaE', 'Q': 'AvMUpnOv'}, {'Y': 'LZWXz', 'R': 'kphUGeCV'}) == {'Y': 'LZWXz', 'R': 'kphUGeCV', 'L': 'juWPZZHsz', 'Q': 'AvMUpnOv', 'M': 'JVyHUMuA', 'S': 'HKDQSE'}
    assert candidate({'J': 'jzD', 'G': 'yIB', 'T': 'wPeAghqkI'}, {'M': 'XRVTmOpK', 'G': 'Owk'}, {'I': 'msT', 'U': 'BCYtVKU'}) == {'I': 'msT', 'U': 'BCYtVKU', 'M': 'XRVTmOpK', 'G': 'yIB', 'J': 'jzD', 'T': 'wPeAghqkI'}
    assert candidate({'D': 'YIfXh', 'I': 'UCXS', 'T': 'SXh'}, {'Q': 'WKUbs', 'X': 'qQPiyYrF'}, {'J': 'DFNJygzBefv', 'V': 'ppK', 'D': 'GNHNvKJZ'}) == {'J': 'DFNJygzBefv', 'V': 'ppK', 'D': 'YIfXh', 'Q': 'WKUbs', 'X': 'qQPiyYrF', 'I': 'UCXS', 'T': 'SXh'}
    assert candidate({'Q': 'PuXkfMi', 'E': 'FDVhA', 'G': 'jRfF'}, {'W': 'JrnZJgT', 'S': 'lON'}, {'J': 'upcgin', 'V': 'xIRXqLGXe', 'I': 'vBDYrw'}) == {'J': 'upcgin', 'V': 'xIRXqLGXe', 'I': 'vBDYrw', 'W': 'JrnZJgT', 'S': 'lON', 'Q': 'PuXkfMi', 'E': 'FDVhA', 'G': 'jRfF'}
    assert candidate({'M': 'eWX', 'V': 'BGGiKfl', 'W': 'AWmxddDh'}, {'J': 'eMHSjVHCB', 'Q': 'XNIiABZJ'}, {'D': 'Bmy', 'I': 'LDuktTAsY'}) == {'D': 'Bmy', 'I': 'LDuktTAsY', 'J': 'eMHSjVHCB', 'Q': 'XNIiABZJ', 'M': 'eWX', 'V': 'BGGiKfl', 'W': 'AWmxddDh'}
    assert candidate({'Y': 'SIZN', 'W': 'wbz', 'H': 'NrSwnWEpZ'}, {'U': 'liJEzWvar', 'G': 'arXkMveVl'}, {'I': 'vdodavhfya', 'U': 'MQYuLXp'}) == {'I': 'vdodavhfya', 'U': 'liJEzWvar', 'G': 'arXkMveVl', 'Y': 'SIZN', 'W': 'wbz', 'H': 'NrSwnWEpZ'}
    assert candidate({'T': 'KeS', 'V': 'Rxb', 'Y': 'riMuJ'}, {'T': 'VOLkHjdOL', 'A': 'JEynWrW'}, {'W': 'gqfdu', 'S': 'tgSOrQH'}) == {'W': 'gqfdu', 'S': 'tgSOrQH', 'T': 'KeS', 'A': 'JEynWrW', 'V': 'Rxb', 'Y': 'riMuJ'}
    assert candidate({'G': 'kYoTgGS', 'N': 'fLzX', 'J': 'jHhFiOvwu'}, {'A': 'uMgBc', 'J': 'GpVcLN'}, {'G': 'lyg', 'K': 'pxbYYnVni'}) == {'G': 'kYoTgGS', 'K': 'pxbYYnVni', 'A': 'uMgBc', 'J': 'jHhFiOvwu', 'N': 'fLzX'}
    assert candidate({'B': 'ZcrfLAU', 'V': 'QYPg', 'T': 'WNGfoNCg'}, {'B': 'fIljJiqq', 'R': 'yHwD'}, {'U': 'sblfwrkhal', 'E': 'uegyNPjOh'}) == {'U': 'sblfwrkhal', 'E': 'uegyNPjOh', 'B': 'ZcrfLAU', 'R': 'yHwD', 'V': 'QYPg', 'T': 'WNGfoNCg'}
    assert candidate({'X': 'lrKdg', 'D': 'Yuqovpvt', 'B': 'PSempQq'}, {'Q': 'WcxYvVnH', 'H': 'RffbagHkq'}, {'P': 'wztxxc', 'Q': 'HDdpjQJiq'}) == {'P': 'wztxxc', 'Q': 'WcxYvVnH', 'H': 'RffbagHkq', 'X': 'lrKdg', 'D': 'Yuqovpvt', 'B': 'PSempQq'}
    assert candidate({'J': 'qcYr', 'I': 'NoYcYF', 'Z': 'gogsQc'}, {'P': 'Vami', 'B': 'DaD'}, {'Q': 'frtprwjrmpuz', 'O': 'zAEnhqs'}) == {'Q': 'frtprwjrmpuz', 'O': 'zAEnhqs', 'P': 'Vami', 'B': 'DaD', 'J': 'qcYr', 'I': 'NoYcYF', 'Z': 'gogsQc'}
    assert candidate({'C': 'TEM', 'R': 'CfM', 'H': 'PoM'}, {'H': 'FieHAASN', 'J': 'Khkt'}, {'M': 'gypmuxvt', 'X': 'pdsBARdK'}) == {'M': 'gypmuxvt', 'X': 'pdsBARdK', 'H': 'PoM', 'J': 'Khkt', 'C': 'TEM', 'R': 'CfM'}
    assert candidate({'L': 'pMu', 'J': 'GpXzvY', 'G': 'OUhN'}, {'A': 'igvnAC', 'G': 'ZIDiKT'}, {'I': 'kafwksvvn', 'P': 'FCS'}) == {'I': 'kafwksvvn', 'P': 'FCS', 'A': 'igvnAC', 'G': 'OUhN', 'L': 'pMu', 'J': 'GpXzvY'}
    assert candidate({'B': 'rKBvtaG', 'Y': 'Rdqh', 'A': 'hnybeHx'}, {'L': 'zjR', 'H': 'rtUlTywT'}, {'C': 'fcnden', 'H': 'MaT'}) == {'C': 'fcnden', 'H': 'rtUlTywT', 'L': 'zjR', 'B': 'rKBvtaG', 'Y': 'Rdqh', 'A': 'hnybeHx'}
    assert candidate({'X': 'dYHCX', 'Y': 'EJNsmgSQ', 'W': 'MksVfq'}, {'Q': 'znJtRsvjm', 'X': 'WIT'}, {'C': 'pgbjpqp', 'H': 'lmknTp'}) == {'C': 'pgbjpqp', 'H': 'lmknTp', 'Q': 'znJtRsvjm', 'X': 'dYHCX', 'Y': 'EJNsmgSQ', 'W': 'MksVfq'}
    assert candidate({'Q': 'EUcR', 'F': 'prx'}, {'O': 'GOXa', 'W': 'hfj'}, {'V': 'daymrou', 'A': 'uljVPQOc'}) == {'V': 'daymrou', 'A': 'uljVPQOc', 'O': 'GOXa', 'W': 'hfj', 'Q': 'EUcR', 'F': 'prx'}
    assert candidate({'Y': 'aCCgQ', 'S': 'reU', 'P': 'HvXGukgZ'}, {'W': 'UfNKageA', 'P': 'WNVVzUp'}, {'I': 'tuz', 'Q': 'qXz'}) == {'I': 'tuz', 'Q': 'qXz', 'W': 'UfNKageA', 'P': 'HvXGukgZ', 'Y': 'aCCgQ', 'S': 'reU'}
    assert candidate({'O': 'cES', 'L': 'SMTEsR', 'V': 'weEuDu'}, {'Q': 'cIkLVH', 'N': 'nrrnBWu'}, {'Z': 'zvbzplrbhdyt', 'S': 'BtQL'}) == {'Z': 'zvbzplrbhdyt', 'S': 'BtQL', 'Q': 'cIkLVH', 'N': 'nrrnBWu', 'O': 'cES', 'L': 'SMTEsR', 'V': 'weEuDu'}
    assert candidate({'M': 'DNAS', 'G': 'yZIgubur', 'T': 'PCAr'}, {'Z': 'Gludx', 'L': 'XAODhLtUl'}, {'X': 'qoichwfcstvw', 'I': 'Qjbuc'}) == {'X': 'qoichwfcstvw', 'I': 'Qjbuc', 'Z': 'Gludx', 'L': 'XAODhLtUl', 'M': 'DNAS', 'G': 'yZIgubur', 'T': 'PCAr'}
    assert candidate({'J': 'bzxYZc', 'A': 'BHxBim', 'S': 'ADoVXHjiH'}, {'Q': 'nVLeRBgux', 'L': 'Svezca'}, {'F': 'trlndyyxuax', 'U': 'qwigFkDg'}) == {'F': 'trlndyyxuax', 'U': 'qwigFkDg', 'Q': 'nVLeRBgux', 'L': 'Svezca', 'J': 'bzxYZc', 'A': 'BHxBim', 'S': 'ADoVXHjiH'}
    assert candidate({'F': 'qiITOtF', 'Q': 'wOxywsA', 'T': 'ACG'}, {'F': 'FbwYRR', 'C': 'JClwRw'}, {'V': 'wieqvujfj', 'F': 'AHCXH'}) == {'V': 'wieqvujfj', 'F': 'qiITOtF', 'C': 'JClwRw', 'Q': 'wOxywsA', 'T': 'ACG'}
    assert candidate({'W': 'Lmada', 'D': 'yHKehBq', 'V': 'Vxf'}, {'O': 'pAknejPZc', 'P': 'QRujgab'}, {'W': 'vek', 'N': 'CaatJIHVu'}) == {'W': 'Lmada', 'N': 'CaatJIHVu', 'O': 'pAknejPZc', 'P': 'QRujgab', 'D': 'yHKehBq', 'V': 'Vxf'}
    assert candidate({'I': 'RHbfjPAj', 'E': 'GLMARdh', 'F': 'rljy'}, {'Q': 'qEgIiUMs', 'L': 'jmj'}, {'H': 'llgrmknbjma', 'B': 'NWGQt'}) == {'H': 'llgrmknbjma', 'B': 'NWGQt', 'Q': 'qEgIiUMs', 'L': 'jmj', 'I': 'RHbfjPAj', 'E': 'GLMARdh', 'F': 'rljy'}
    assert candidate({'Y': 'RitwewkJB', 'B': 'VtIArP', 'H': 'vCOBOLn'}, {'G': 'BrnT', 'T': 'DoG'}, {'Z': 'viyxrqjyx', 'M': 'ihSRMoVh'}) == {'Z': 'viyxrqjyx', 'M': 'ihSRMoVh', 'G': 'BrnT', 'T': 'DoG', 'Y': 'RitwewkJB', 'B': 'VtIArP', 'H': 'vCOBOLn'}
    assert candidate({'B': 'cuwna', 'R': 'kpTyXpX', 'Q': 'SnJdmIej'}, {'A': 'Geo', 'H': 'DTA'}, {'G': 'rvnemoonaodl', 'S': 'rGpD'}) == {'G': 'rvnemoonaodl', 'S': 'rGpD', 'A': 'Geo', 'H': 'DTA', 'B': 'cuwna', 'R': 'kpTyXpX', 'Q': 'SnJdmIej'}
    assert candidate({'J': 'EVoS', 'B': 'MqYTorff', 'E': 'CeluMS'}, {'K': 'URPiR', 'C': 'iInhhS'}, {'Y': 'yeqomej', 'O': 'TgR'}) == {'Y': 'yeqomej', 'O': 'TgR', 'K': 'URPiR', 'C': 'iInhhS', 'J': 'EVoS', 'B': 'MqYTorff', 'E': 'CeluMS'}
    assert candidate({'G': 'VpfcO', 'A': 'JYWI', 'S': 'ASrU'}, {'D': 'MWmPiE', 'Q': 'ogcz'}, {'E': 'uqvmfcev', 'K': 'iAKx'}) == {'E': 'uqvmfcev', 'K': 'iAKx', 'D': 'MWmPiE', 'Q': 'ogcz', 'G': 'VpfcO', 'A': 'JYWI', 'S': 'ASrU'}
    assert candidate({'R': 'zMdLpGLW', 'Q': 'CtOzL'}, {'E': 'ZGx', 'L': 'ZDRAX'}, {'Z': 'nhzu', 'W': 'LRTtMfU'}) == {'Z': 'nhzu', 'W': 'LRTtMfU', 'E': 'ZGx', 'L': 'ZDRAX', 'R': 'zMdLpGLW', 'Q': 'CtOzL'}
    assert candidate({'V': 'QCHqDBX', 'R': 'MhWzVAoS', 'U': 'cJezExK'}, {'V': 'IdF', 'Z': 'GKMjtFmFK'}, {'V': 'vqwdefzlpy', 'X': 'qxJFkZkF'}) == {'V': 'QCHqDBX', 'X': 'qxJFkZkF', 'Z': 'GKMjtFmFK', 'R': 'MhWzVAoS', 'U': 'cJezExK'}
    assert candidate({'P': 'eOaEiJ', 'U': 'GTqooT', 'O': 'tow'}, {'Q': 'HtuQ'}, {'T': 'zdsgcea', 'E': 'QRmyt'}) == {'T': 'zdsgcea', 'E': 'QRmyt', 'Q': 'HtuQ', 'P': 'eOaEiJ', 'U': 'GTqooT', 'O': 'tow'}
    assert candidate({'V': 'CpUGXthG', 'T': 'FhuHeixW', 'I': 'NXuPD'}, {'I': 'LQmyBvjz', 'O': 'VPIBBEgXl'}, {'W': 'xkuturok', 'N': 'MueYcAVzB'}) == {'W': 'xkuturok', 'N': 'MueYcAVzB', 'I': 'NXuPD', 'O': 'VPIBBEgXl', 'V': 'CpUGXthG', 'T': 'FhuHeixW'}
    assert candidate({'L': 'cHJo', 'U': 'lUK'}, {'Z': 'nvSw', 'X': 'iGNV'}, {'Q': 'ljkviz', 'Z': 'irquDsMdX'}) == {'Q': 'ljkviz', 'Z': 'nvSw', 'X': 'iGNV', 'L': 'cHJo', 'U': 'lUK'}
    assert candidate({'K': 'rWNm', 'W': 'lXGmr', 'U': 'gcY'}, {'Y': 'muLCinYd', 'X': 'lFeVvKCfz'}, {'U': 'nwodnhw', 'S': 'OdqVPF'}) == {'U': 'gcY', 'S': 'OdqVPF', 'Y': 'muLCinYd', 'X': 'lFeVvKCfz', 'K': 'rWNm', 'W': 'lXGmr'}
    assert candidate({'Q': 'cgqb', 'W': 'epUInPvwE'}, {'Y': 'QUhkupz', 'H': 'tZqmuIvw'}, {'R': 'fvvg', 'Z': 'dgf'}) == {'R': 'fvvg', 'Z': 'dgf', 'Y': 'QUhkupz', 'H': 'tZqmuIvw', 'Q': 'cgqb', 'W': 'epUInPvwE'}
    assert candidate({'P': 'zkluxWW', 'D': 'bLQhTPl', 'G': 'fiYoba'}, {'E': 'pJkkTXdbr'}, {'A': 'xti', 'X': 'SXHt'}) == {'A': 'xti', 'X': 'SXHt', 'E': 'pJkkTXdbr', 'P': 'zkluxWW', 'D': 'bLQhTPl', 'G': 'fiYoba'}
    assert candidate({'T': 'bCSSBNX', 'Q': 'CvjG', 'M': 'tAPGNNnPC'}, {'O': 'ESsFuOQj', 'J': 'UUxUMDwju'}, {'B': 'qor', 'N': 'qBhzJgz'}) == {'B': 'qor', 'N': 'qBhzJgz', 'O': 'ESsFuOQj', 'J': 'UUxUMDwju', 'T': 'bCSSBNX', 'Q': 'CvjG', 'M': 'tAPGNNnPC'}
    assert candidate({'C': 'pgih', 'D': 'iYEdg', 'K': 'RcgDu'}, {'V': 'IfFnWmuw', 'R': 'qPpPKv'}, {'P': 'nyyemrrwodhz', 'G': 'PYTBwN'}) == {'P': 'nyyemrrwodhz', 'G': 'PYTBwN', 'V': 'IfFnWmuw', 'R': 'qPpPKv', 'C': 'pgih', 'D': 'iYEdg', 'K': 'RcgDu'}
    assert candidate({'L': 'drNM', 'Q': 'QNhUivfP', 'X': 'WnhgBBuq'}, {'K': 'ZYKAop', 'E': 'zbpNh'}, {'N': 'rid', 'F': 'BwuRD'}) == {'N': 'rid', 'F': 'BwuRD', 'K': 'ZYKAop', 'E': 'zbpNh', 'L': 'drNM', 'Q': 'QNhUivfP', 'X': 'WnhgBBuq'}
    assert candidate({'F': 'KAJZf', 'C': 'JsItypOIn', 'G': 'TXaWf'}, {'F': 'sgxqpfb', 'P': 'rma'}, {'L': 'nJIl', 'M': 'HpBZRgXto'}) == {'L': 'nJIl', 'M': 'HpBZRgXto', 'F': 'KAJZf', 'P': 'rma', 'C': 'JsItypOIn', 'G': 'TXaWf'}
    assert candidate({'D': 'yfi', 'I': 'WnWgWu', 'Q': 'ijh'}, {'X': 'idbm', 'K': 'yrhnjnb'}, {'V': 'YWFtct', 'J': 'VrsGRUDG'}) == {'V': 'YWFtct', 'J': 'VrsGRUDG', 'X': 'idbm', 'K': 'yrhnjnb', 'D': 'yfi', 'I': 'WnWgWu', 'Q': 'ijh'}
    assert candidate({'T': 'sGm', 'X': 'qwIxgNETG', 'F': 'JIcWZk'}, {'I': 'jhpn', 'C': 'bRzUaR'}, {'Z': 'bNjAXFe', 'C': 'pXEdJGaw'}) == {'Z': 'bNjAXFe', 'C': 'bRzUaR', 'I': 'jhpn', 'T': 'sGm', 'X': 'qwIxgNETG', 'F': 'JIcWZk'}
    assert candidate({'U': 'FBOslsaFK', 'B': 'EkHQVRGt', 'L': 'piVkslJ'}, {'A': 'gkwgtwiegi', 'S': 'LiPvvODU'}, {'P': 'EljO', 'S': 'efJCkiI'}) == {'P': 'EljO', 'S': 'LiPvvODU', 'A': 'gkwgtwiegi', 'U': 'FBOslsaFK', 'B': 'EkHQVRGt', 'L': 'piVkslJ'}
    assert candidate({'Q': 'EGhEOd', 'T': 'QNZRd', 'X': 'qRZvdi'}, {'M': 'kszhpjnctv', 'H': 'HfIQr'}, {'L': 'IZjAyxBgA', 'G': 'KJEHZy'}) == {'L': 'IZjAyxBgA', 'G': 'KJEHZy', 'M': 'kszhpjnctv', 'H': 'HfIQr', 'Q': 'EGhEOd', 'T': 'QNZRd', 'X': 'qRZvdi'}
    assert candidate({'R': 'Koya', 'G': 'sHBl'}, {'D': 'jqy', 'R': 'UxG'}, {'T': 'slxXt', 'A': 'ycl'}) == {'T': 'slxXt', 'A': 'ycl', 'D': 'jqy', 'R': 'Koya', 'G': 'sHBl'}
    assert candidate({'J': 'lbi', 'M': 'OMpipGRUP', 'E': 'acp'}, {'S': 'gnxnyej', 'W': 'jPeBt'}, {'W': 'QqkMBwM', 'H': 'sSt'}) == {'W': 'jPeBt', 'H': 'sSt', 'S': 'gnxnyej', 'J': 'lbi', 'M': 'OMpipGRUP', 'E': 'acp'}
    assert candidate({'M': 'BobUbZh', 'K': 'OYojMIGJ', 'Z': 'EVaeyuOYY'}, {'N': 'cklf', 'X': 'gsziB'}, {'U': 'BpWJZeI', 'Y': 'YkZAQ'}) == {'U': 'BpWJZeI', 'Y': 'YkZAQ', 'N': 'cklf', 'X': 'gsziB', 'M': 'BobUbZh', 'K': 'OYojMIGJ', 'Z': 'EVaeyuOYY'}
    assert candidate({'L': 'yaIP', 'K': 'Fkg', 'Y': 'oVspcrq'}, {'Z': 'tnavvqr', 'D': 'RarGbd'}, {'T': 'ejBnTF', 'E': 'lSvKKPFc'}) == {'T': 'ejBnTF', 'E': 'lSvKKPFc', 'Z': 'tnavvqr', 'D': 'RarGbd', 'L': 'yaIP', 'K': 'Fkg', 'Y': 'oVspcrq'}
    assert candidate({'M': 'OjEMGSG', 'V': 'DHkZ', 'H': 'zIruarC'}, {'X': 'udkshzhxa', 'V': 'mJXjvOg'}, {'F': 'Tphat', 'S': 'cIMiblF'}) == {'F': 'Tphat', 'S': 'cIMiblF', 'X': 'udkshzhxa', 'V': 'DHkZ', 'M': 'OjEMGSG', 'H': 'zIruarC'}
    assert candidate({'T': 'AcwlxDB', 'U': 'RRlKsPGuo', 'X': 'BaixJ'}, {'O': 'fpkcrv', 'I': 'nLsTAQM'}, {'J': 'OhQCUUJJ', 'Y': 'ijH'}) == {'J': 'OhQCUUJJ', 'Y': 'ijH', 'O': 'fpkcrv', 'I': 'nLsTAQM', 'T': 'AcwlxDB', 'U': 'RRlKsPGuo', 'X': 'BaixJ'}
    assert candidate({'D': 'VDeKcl', 'R': 'NTaYhTrVT', 'Q': 'pAPsHg'}, {'V': 'tvehrybevsx', 'L': 'OBw'}, {'J': 'yYqjsEEc', 'P': 'cewECiPLe'}) == {'J': 'yYqjsEEc', 'P': 'cewECiPLe', 'V': 'tvehrybevsx', 'L': 'OBw', 'D': 'VDeKcl', 'R': 'NTaYhTrVT', 'Q': 'pAPsHg'}
    assert candidate({'W': 'nSqnyUj', 'T': 'zFrPBqpv', 'C': 'vfVkOEdiw'}, {'F': 'udtedzpusora', 'X': 'oLO'}, {'O': 'KGTFXLxbS', 'T': 'frwrIo'}) == {'O': 'KGTFXLxbS', 'T': 'zFrPBqpv', 'F': 'udtedzpusora', 'X': 'oLO', 'W': 'nSqnyUj', 'C': 'vfVkOEdiw'}
    assert candidate({'K': 'OFwrg', 'F': 'qdHT', 'R': 'rZGbDsxNW'}, {'K': 'vbrmuqdequqg', 'D': 'bXzSjy'}, {'N': 'CAVzoh', 'F': 'VuabSflix'}) == {'N': 'CAVzoh', 'F': 'qdHT', 'K': 'OFwrg', 'D': 'bXzSjy', 'R': 'rZGbDsxNW'}
    assert candidate({'J': 'yMJQTzc', 'M': 'dWWKlUWi', 'G': 'tQI'}, {'W': 'jiapnmpvzs', 'I': 'AHr'}, {'E': 'nky', 'A': 'zRcQBDL'}) == {'E': 'nky', 'A': 'zRcQBDL', 'W': 'jiapnmpvzs', 'I': 'AHr', 'J': 'yMJQTzc', 'M': 'dWWKlUWi', 'G': 'tQI'}
    assert candidate({'X': 'hNUZBD', 'M': 'vtynCy', 'L': 'ydPxLDJ'}, {'K': 'fbxatzi', 'M': 'DtyHfIL'}, {'W': 'MkIrt', 'M': 'YEE'}) == {'W': 'MkIrt', 'M': 'vtynCy', 'K': 'fbxatzi', 'X': 'hNUZBD', 'L': 'ydPxLDJ'}
    assert candidate({'F': 'WDui', 'I': 'MOlSIbjAd', 'C': 'JEJwzvBn'}, {'Q': 'nzznzqfytvta', 'L': 'ePWNYPkPh'}, {'L': 'VYPUzDQ', 'H': 'rFMyyaA'}) == {'L': 'ePWNYPkPh', 'H': 'rFMyyaA', 'Q': 'nzznzqfytvta', 'F': 'WDui', 'I': 'MOlSIbjAd', 'C': 'JEJwzvBn'}
    assert candidate({'G': 'Hkahl', 'K': 'YQA', 'N': 'pfxSlhTMk'}, {'I': 'higsnxtdbyep', 'W': 'zxVg'}, {'H': 'bdOqDQhI', 'K': 'bFByHr'}) == {'H': 'bdOqDQhI', 'K': 'YQA', 'I': 'higsnxtdbyep', 'W': 'zxVg', 'G': 'Hkahl', 'N': 'pfxSlhTMk'}
    assert candidate({'B': 'bIBzeK', 'M': 'ClSYRQ', 'H': 'DrrocGEn'}, {'K': 'mvxdebcf', 'L': 'VbIhsliaG'}, {'N': 'bFs', 'L': 'ovfifUbon'}) == {'N': 'bFs', 'L': 'VbIhsliaG', 'K': 'mvxdebcf', 'B': 'bIBzeK', 'M': 'ClSYRQ', 'H': 'DrrocGEn'}
    assert candidate({'Y': 'ppZoHR', 'R': 'PJVe', 'B': 'nnYVyeley'}, {'B': 'lelclaf', 'M': 'UXFgk'}, {'P': 'MzXcVA', 'U': 'PfS'}) == {'P': 'MzXcVA', 'U': 'PfS', 'B': 'nnYVyeley', 'M': 'UXFgk', 'Y': 'ppZoHR', 'R': 'PJVe'}
    assert candidate({'X': 'MBhI', 'F': 'kte', 'U': 'pyrZq'}, {'S': 'wdlbbvyet', 'W': 'zNBVi'}, {'Z': 'lldaKIr', 'D': 'LEatkjYU'}) == {'Z': 'lldaKIr', 'D': 'LEatkjYU', 'S': 'wdlbbvyet', 'W': 'zNBVi', 'X': 'MBhI', 'F': 'kte', 'U': 'pyrZq'}
    assert candidate({'L': 'eUGufN', 'P': 'rErlpVr', 'I': 'KFlElGIG'}, {'K': 'mkn', 'J': 'RNtll'}, {'W': 'CId', 'L': 'LwxHVXgs'}) == {'W': 'CId', 'L': 'eUGufN', 'K': 'mkn', 'J': 'RNtll', 'P': 'rErlpVr', 'I': 'KFlElGIG'}
    assert candidate({'R': 'kHn', 'S': 'VlCqaZBJ', 'X': 'MSkNCtM'}, {'D': 'evswy', 'Y': 'EIkzVdcl'}, {'F': 'xOP', 'C': 'JwaisQz'}) == {'F': 'xOP', 'C': 'JwaisQz', 'D': 'evswy', 'Y': 'EIkzVdcl', 'R': 'kHn', 'S': 'VlCqaZBJ', 'X': 'MSkNCtM'}
    assert candidate({'R': 'zwT', 'S': 'frXXhHH', 'X': 'BvzZRp'}, {'I': 'nlzoro', 'N': 'nVvfVfgz'}, {'B': 'qkyYYWOb', 'W': 'utwFDZTMR'}) == {'B': 'qkyYYWOb', 'W': 'utwFDZTMR', 'I': 'nlzoro', 'N': 'nVvfVfgz', 'R': 'zwT', 'S': 'frXXhHH', 'X': 'BvzZRp'}
    assert candidate({'A': 'zYrVrmuQI', 'Q': 'XXTXyU', 'R': 'WzGVbQv'}, {'E': 'czk', 'B': 'COWGrVD'}, {'Z': 'YDeScGiwb', 'U': 'qMrGLK'}) == {'Z': 'YDeScGiwb', 'U': 'qMrGLK', 'E': 'czk', 'B': 'COWGrVD', 'A': 'zYrVrmuQI', 'Q': 'XXTXyU', 'R': 'WzGVbQv'}
    assert candidate({'W': 'lKuSRiyR', 'P': 'cTafbrh', 'V': 'vxR'}, {'W': 'dvihztlybqba', 'F': 'zTXW'}, {'W': 'xGwDM', 'E': 'uQwxzbg'}) == {'W': 'lKuSRiyR', 'E': 'uQwxzbg', 'F': 'zTXW', 'P': 'cTafbrh', 'V': 'vxR'}
    assert candidate({'Z': 'KBgj', 'K': 'lYuIKpd', 'E': 'rcDsUGflH'}, {'V': 'rrxifijflcn', 'A': 'pAhLr'}, {'S': 'JBDGBo', 'F': 'jkFucK'}) == {'S': 'JBDGBo', 'F': 'jkFucK', 'V': 'rrxifijflcn', 'A': 'pAhLr', 'Z': 'KBgj', 'K': 'lYuIKpd', 'E': 'rcDsUGflH'}
    assert candidate({'B': 'KJnA', 'W': 'npbPwPy', 'R': 'ZCBCRkZ'}, {'N': 'nca', 'C': 'ykQ'}, {'S': 'BlTZBm', 'K': 'DdflQ'}) == {'S': 'BlTZBm', 'K': 'DdflQ', 'N': 'nca', 'C': 'ykQ', 'B': 'KJnA', 'W': 'npbPwPy', 'R': 'ZCBCRkZ'}
    assert candidate({'X': 'osA', 'V': 'zzfDp', 'U': 'FKwUqxa'}, {'Q': 'vczebxgfhfk', 'G': 'PivJtXRc'}, {'J': 'WWuzJQR', 'U': 'Pvmca'}) == {'J': 'WWuzJQR', 'U': 'FKwUqxa', 'Q': 'vczebxgfhfk', 'G': 'PivJtXRc', 'X': 'osA', 'V': 'zzfDp'}
    assert candidate({'O': 'jKGfcw', 'R': 'LIRKU', 'I': 'qSL'}, {'H': 'jndzsw', 'S': 'OSfZAt'}, {'V': 'WRLHqycDY', 'T': 'tiayws'}) == {'V': 'WRLHqycDY', 'T': 'tiayws', 'H': 'jndzsw', 'S': 'OSfZAt', 'O': 'jKGfcw', 'R': 'LIRKU', 'I': 'qSL'}
    assert candidate({'J': 'mnH', 'G': 'OOWpwTvT', 'P': 'EHGFM'}, {'J': 'agd', 'G': 'sICq'}, {'L': 'fmFsoW', 'A': 'wufCatMW'}) == {'L': 'fmFsoW', 'A': 'wufCatMW', 'J': 'mnH', 'G': 'OOWpwTvT', 'P': 'EHGFM'}
    assert candidate({'Q': 'VRNKcdN', 'K': 'dqiALaIuu', 'F': 'iRzBJF'}, {'K': 'bcpoixekdibm', 'B': 'yOCuFPd'}, {'D': 'gyPNjiiA', 'J': 'rglWbqHF'}) == {'D': 'gyPNjiiA', 'J': 'rglWbqHF', 'K': 'dqiALaIuu', 'B': 'yOCuFPd', 'Q': 'VRNKcdN', 'F': 'iRzBJF'}
    assert candidate({'S': 'jeOBr', 'J': 'sYPG', 'C': 'zjw'}, {'D': 'whj', 'R': 'jHLJyErfh'}, {'U': 'NOAdZJQ', 'Q': 'rjnjJmEcY'}) == {'U': 'NOAdZJQ', 'Q': 'rjnjJmEcY', 'D': 'whj', 'R': 'jHLJyErfh', 'S': 'jeOBr', 'J': 'sYPG', 'C': 'zjw'}

if __name__ == '__main__':
    check(merge_dictionaries_three)