from case_MBPP_283 import last_Digit_Factorial


def check(candidate):
    assert candidate(4) == 4
    assert candidate(21) == 0
    assert candidate(30) == 0
    assert candidate(8) == 0
    assert candidate(2) == 2
    assert candidate(7) == 0
    assert candidate(5) == 0
    assert candidate(9) == 0
    assert candidate(9) == 0
    assert candidate(6) == 0
    assert candidate(8) == 0
    assert candidate(5) == 0
    assert candidate(2) == 2
    assert candidate(2) == 2
    assert candidate(6) == 0
    assert candidate(3) == 6
    assert candidate(7) == 0
    assert candidate(9) == 0
    assert candidate(5) == 0
    assert candidate(9) == 0
    assert candidate(4) == 4
    assert candidate(2) == 2
    assert candidate(3) == 6
    assert candidate(3) == 6
    assert candidate(3) == 6
    assert candidate(4) == 4
    assert candidate(7) == 0
    assert candidate(2) == 2
    assert candidate(9) == 0
    assert candidate(1) == 1
    assert candidate(8) == 0
    assert candidate(6) == 0
    assert candidate(6) == 0
    assert candidate(1) == 1
    assert candidate(3) == 6
    assert candidate(4) == 4
    assert candidate(21) == 0
    assert candidate(23) == 0
    assert candidate(20) == 0
    assert candidate(24) == 0
    assert candidate(16) == 0
    assert candidate(20) == 0
    assert candidate(22) == 0
    assert candidate(18) == 0
    assert candidate(17) == 0
    assert candidate(25) == 0
    assert candidate(17) == 0
    assert candidate(18) == 0
    assert candidate(26) == 0
    assert candidate(16) == 0
    assert candidate(25) == 0
    assert candidate(23) == 0
    assert candidate(23) == 0
    assert candidate(16) == 0
    assert candidate(16) == 0
    assert candidate(25) == 0
    assert candidate(24) == 0
    assert candidate(18) == 0
    assert candidate(24) == 0
    assert candidate(22) == 0
    assert candidate(25) == 0
    assert candidate(21) == 0
    assert candidate(17) == 0
    assert candidate(19) == 0
    assert candidate(23) == 0
    assert candidate(23) == 0
    assert candidate(20) == 0
    assert candidate(20) == 0
    assert candidate(24) == 0
    assert candidate(25) == 0
    assert candidate(25) == 0
    assert candidate(29) == 0
    assert candidate(28) == 0
    assert candidate(25) == 0
    assert candidate(25) == 0
    assert candidate(32) == 0
    assert candidate(25) == 0
    assert candidate(35) == 0
    assert candidate(31) == 0
    assert candidate(30) == 0
    assert candidate(29) == 0
    assert candidate(30) == 0
    assert candidate(28) == 0
    assert candidate(33) == 0
    assert candidate(28) == 0
    assert candidate(26) == 0
    assert candidate(26) == 0
    assert candidate(30) == 0
    assert candidate(26) == 0
    assert candidate(32) == 0
    assert candidate(35) == 0
    assert candidate(33) == 0
    assert candidate(33) == 0
    assert candidate(29) == 0
    assert candidate(25) == 0
    assert candidate(33) == 0
    assert candidate(26) == 0
    assert candidate(25) == 0
    assert candidate(26) == 0
    assert candidate(26) == 0
    assert candidate(28) == 0
    assert candidate(27) == 0

if __name__ == '__main__':
    check(last_Digit_Factorial)