from case_MBPP_127 import insert_element


def check(candidate):
    assert candidate(['Red', 'Green', 'Black'] ,'c')==['c', 'Red', 'c', 'Green', 'c', 'Black'] 
    assert candidate(['python', 'java'] ,'program')==['program', 'python', 'program', 'java'] 
    assert candidate(['happy', 'sad'] ,'laugh')==['laugh', 'happy', 'laugh', 'sad'] 
    assert candidate(['TdHHgtU', 'GkmabTTcx', 'KNuxYV'], 'x') == ['x', 'TdHHgtU', 'x', 'GkmabTTcx', 'x', 'KNuxYV']
    assert candidate(['mTHsVG', 'hQJqXOngB', 'hFvEbZOU'], 'n') == ['n', 'mTHsVG', 'n', 'hQJqXOngB', 'n', 'hFvEbZOU']
    assert candidate(['OLeJbZ', 'XCPbBvGVd', 'zcTbO'], 'r') == ['r', 'OLeJbZ', 'r', 'XCPbBvGVd', 'r', 'zcTbO']
    assert candidate(['jWqSCilB', 'ctJYoCq', 'WCuYvJbk'], 'y') == ['y', 'jWqSCilB', 'y', 'ctJYoCq', 'y', 'WCuYvJbk']
    assert candidate(['gBjzbF', 'sVoqFJzB', 'KAwzgTSTA'], 'q') == ['q', 'gBjzbF', 'q', 'sVoqFJzB', 'q', 'KAwzgTSTA']
    assert candidate(['izorZZg', 'rQHWvqHaS', 'Gzae'], 'o') == ['o', 'izorZZg', 'o', 'rQHWvqHaS', 'o', 'Gzae']
    assert candidate(['hzGiftd', 'xgzu', 'Mpxs'], 'y') == ['y', 'hzGiftd', 'y', 'xgzu', 'y', 'Mpxs']
    assert candidate(['eYqIjO', 'xxiu', 'PlcFUVNsX'], 'f') == ['f', 'eYqIjO', 'f', 'xxiu', 'f', 'PlcFUVNsX']
    assert candidate(['FWgD', 'joCNLL', 'IxhhvOPC'], 'u') == ['u', 'FWgD', 'u', 'joCNLL', 'u', 'IxhhvOPC']
    assert candidate(['cxWAob', 'VsgDsc', 'huEdVVWQa'], 'a') == ['a', 'cxWAob', 'a', 'VsgDsc', 'a', 'huEdVVWQa']
    assert candidate(['wcYEVFgMq', 'syNVsG', 'aCAMD'], 'f') == ['f', 'wcYEVFgMq', 'f', 'syNVsG', 'f', 'aCAMD']
    assert candidate(['wtLWftZ', 'FDWC', 'xFfANN'], 'm') == ['m', 'wtLWftZ', 'm', 'FDWC', 'm', 'xFfANN']
    assert candidate(['yZvpKFasW', 'qiuV', 'KnGHiCKIp'], 'n') == ['n', 'yZvpKFasW', 'n', 'qiuV', 'n', 'KnGHiCKIp']
    assert candidate(['eIVtKU', 'fZg', 'FcoXPStv'], 'b') == ['b', 'eIVtKU', 'b', 'fZg', 'b', 'FcoXPStv']
    assert candidate(['jCPXWDwR', 'vVqKL', 'iBK'], 'w') == ['w', 'jCPXWDwR', 'w', 'vVqKL', 'w', 'iBK']
    assert candidate(['eMSI', 'wTlfaWL', 'KBDBWhi'], 'w') == ['w', 'eMSI', 'w', 'wTlfaWL', 'w', 'KBDBWhi']
    assert candidate(['LyziLHr', 'sEANLSJy', 'DDpRzB'], 'k') == ['k', 'LyziLHr', 'k', 'sEANLSJy', 'k', 'DDpRzB']
    assert candidate(['JRCf', 'zCRqRCNP', 'QfDfitXm'], 'x') == ['x', 'JRCf', 'x', 'zCRqRCNP', 'x', 'QfDfitXm']
    assert candidate(['qAzz', 'OZUlv', 'pERJopwR'], 'm') == ['m', 'qAzz', 'm', 'OZUlv', 'm', 'pERJopwR']
    assert candidate(['ARiZvrCvx', 'slSLlCR', 'PapFzrJ'], 'z') == ['z', 'ARiZvrCvx', 'z', 'slSLlCR', 'z', 'PapFzrJ']
    assert candidate(['AAzkZn', 'nwbUCoLqX', 'ByjhW'], 'p') == ['p', 'AAzkZn', 'p', 'nwbUCoLqX', 'p', 'ByjhW']
    assert candidate(['KZFstbo', 'guCipPzM', 'ndkdCVbFf'], 'v') == ['v', 'KZFstbo', 'v', 'guCipPzM', 'v', 'ndkdCVbFf']
    assert candidate(['eySShji', 'EVrTc', 'jIrPcDH'], 'p') == ['p', 'eySShji', 'p', 'EVrTc', 'p', 'jIrPcDH']
    assert candidate(['XZWrdIW', 'PsQSwSCgq', 'RoYpcizc'], 'v') == ['v', 'XZWrdIW', 'v', 'PsQSwSCgq', 'v', 'RoYpcizc']
    assert candidate(['tqOJhsg', 'rkghlE', 'BBgbR'], 't') == ['t', 'tqOJhsg', 't', 'rkghlE', 't', 'BBgbR']
    assert candidate(['xQNoEuwBF', 'AnTX', 'DURWQB'], 'u') == ['u', 'xQNoEuwBF', 'u', 'AnTX', 'u', 'DURWQB']
    assert candidate(['VWtEm', 'XGizdy', 'uZFZA'], 'c') == ['c', 'VWtEm', 'c', 'XGizdy', 'c', 'uZFZA']
    assert candidate(['tVIrwQmE', 'MvIpyD', 'sCBsQM'], 'd') == ['d', 'tVIrwQmE', 'd', 'MvIpyD', 'd', 'sCBsQM']
    assert candidate(['cnEmah', 'tvyXb', 'wMmnGL'], 'v') == ['v', 'cnEmah', 'v', 'tvyXb', 'v', 'wMmnGL']
    assert candidate(['WYhXCa', 'prOBmPBnS', 'wBQsTYH'], 'f') == ['f', 'WYhXCa', 'f', 'prOBmPBnS', 'f', 'wBQsTYH']
    assert candidate(['RyAo', 'dikAKXKO', 'Ogr'], 'g') == ['g', 'RyAo', 'g', 'dikAKXKO', 'g', 'Ogr']
    assert candidate(['pCyPXLvWu', 'XGELfnr', 'xuNPx'], 's') == ['s', 'pCyPXLvWu', 's', 'XGELfnr', 's', 'xuNPx']
    assert candidate(['ILGPRm', 'HYTUI', 'rQTNs'], 'n') == ['n', 'ILGPRm', 'n', 'HYTUI', 'n', 'rQTNs']
    assert candidate(['aqiobcsxolu', 'zraqs'], 'taqmq') == ['taqmq', 'aqiobcsxolu', 'taqmq', 'zraqs']
    assert candidate(['acpyqdqfzu', 'ogfs'], 'uncrma') == ['uncrma', 'acpyqdqfzu', 'uncrma', 'ogfs']
    assert candidate(['zjlmhxztu', 'zqart'], 'tynbyz') == ['tynbyz', 'zjlmhxztu', 'tynbyz', 'zqart']
    assert candidate(['xbl', 'wbrxqna'], 'czddzebz') == ['czddzebz', 'xbl', 'czddzebz', 'wbrxqna']
    assert candidate(['rlctfmqkk', 'arfwu'], 'dfw') == ['dfw', 'rlctfmqkk', 'dfw', 'arfwu']
    assert candidate(['whafanybb', 'zducf'], 'ofn') == ['ofn', 'whafanybb', 'ofn', 'zducf']
    assert candidate(['ykofpsypylwo', 'byuydjx'], 'ifiajhs') == ['ifiajhs', 'ykofpsypylwo', 'ifiajhs', 'byuydjx']
    assert candidate(['khirntwefll', 'cimbno'], 'qsfbmmfyfku') == ['qsfbmmfyfku', 'khirntwefll', 'qsfbmmfyfku', 'cimbno']
    assert candidate(['oktdozdjuskz', 'vzxsi'], 'taonxhhpr') == ['taonxhhpr', 'oktdozdjuskz', 'taonxhhpr', 'vzxsi']
    assert candidate(['lhipxtlf', 'uvrplbm'], 'liulegrica') == ['liulegrica', 'lhipxtlf', 'liulegrica', 'uvrplbm']
    assert candidate(['tmj', 'zshzwyzqh'], 'uyfkyrdhlxjj') == ['uyfkyrdhlxjj', 'tmj', 'uyfkyrdhlxjj', 'zshzwyzqh']
    assert candidate(['yywneonu', 'mohgbhhq'], 'bbnx') == ['bbnx', 'yywneonu', 'bbnx', 'mohgbhhq']
    assert candidate(['yibnr', 'vsfayp'], 'fkxbwn') == ['fkxbwn', 'yibnr', 'fkxbwn', 'vsfayp']
    assert candidate(['jssrf', 'oitwe'], 'xpqwrwrqrmhw') == ['xpqwrwrqrmhw', 'jssrf', 'xpqwrwrqrmhw', 'oitwe']
    assert candidate(['uto', 'wnoqepq'], 'gdnrgbhiejs') == ['gdnrgbhiejs', 'uto', 'gdnrgbhiejs', 'wnoqepq']
    assert candidate(['arfaoh', 'tahvr'], 'hvfqte') == ['hvfqte', 'arfaoh', 'hvfqte', 'tahvr']
    assert candidate(['exhi', 'nzzzq'], 'kiq') == ['kiq', 'exhi', 'kiq', 'nzzzq']
    assert candidate(['bjdwbflhtmvd', 'nokdutk'], 'mkebnrmcxbfd') == ['mkebnrmcxbfd', 'bjdwbflhtmvd', 'mkebnrmcxbfd', 'nokdutk']
    assert candidate(['ghtznuacxkx', 'djcdzy'], 'rmwvrpvc') == ['rmwvrpvc', 'ghtznuacxkx', 'rmwvrpvc', 'djcdzy']
    assert candidate(['kvgatbsq', 'clqvkvavq'], 'nhnkewv') == ['nhnkewv', 'kvgatbsq', 'nhnkewv', 'clqvkvavq']
    assert candidate(['kxgtzdoi', 'swtbjdue'], 'gpxewzfk') == ['gpxewzfk', 'kxgtzdoi', 'gpxewzfk', 'swtbjdue']
    assert candidate(['aenab', 'chi'], 'acpygzrd') == ['acpygzrd', 'aenab', 'acpygzrd', 'chi']
    assert candidate(['lfzorui', 'sxehfoxu'], 'qieukp') == ['qieukp', 'lfzorui', 'qieukp', 'sxehfoxu']
    assert candidate(['olnpmk', 'mmmbm'], 'ghlfadm') == ['ghlfadm', 'olnpmk', 'ghlfadm', 'mmmbm']
    assert candidate(['omec', 'efrgnwm'], 'ljocortbdlac') == ['ljocortbdlac', 'omec', 'ljocortbdlac', 'efrgnwm']
    assert candidate(['ayxaiwrzfspr', 'xqjgnqc'], 'lhjxjctgjvub') == ['lhjxjctgjvub', 'ayxaiwrzfspr', 'lhjxjctgjvub', 'xqjgnqc']
    assert candidate(['dxidq', 'lvx'], 'ykfaymcnhwbt') == ['ykfaymcnhwbt', 'dxidq', 'ykfaymcnhwbt', 'lvx']
    assert candidate(['kofiaqhvnxll', 'fuzsjm'], 'nuk') == ['nuk', 'kofiaqhvnxll', 'nuk', 'fuzsjm']
    assert candidate(['xfosyax', 'wiix'], 'ingck') == ['ingck', 'xfosyax', 'ingck', 'wiix']
    assert candidate(['vfdy', 'axtq'], 'paklzrfqs') == ['paklzrfqs', 'vfdy', 'paklzrfqs', 'axtq']
    assert candidate(['ohzuzpny', 'fqqhss'], 'xszqkdqd') == ['xszqkdqd', 'ohzuzpny', 'xszqkdqd', 'fqqhss']
    assert candidate(['vqgtnirj', 'faah'], 'tgmmuqhlkg') == ['tgmmuqhlkg', 'vqgtnirj', 'tgmmuqhlkg', 'faah']
    assert candidate(['omlgpkn', 'xms'], 'ghovmpeffmh') == ['ghovmpeffmh', 'omlgpkn', 'ghovmpeffmh', 'xms']
    assert candidate(['fbarpi', 'gfo'], 'riwdbdswh') == ['riwdbdswh', 'fbarpi', 'riwdbdswh', 'gfo']
    assert candidate(['wubkwvxr', 'tez'], 'vxay') == ['vxay', 'wubkwvxr', 'vxay', 'tez']
    assert candidate(['bztht', 'otnko'], 'jaiafow') == ['jaiafow', 'bztht', 'jaiafow', 'otnko']
    assert candidate(['ygaqfvpct', 'wtj'], 'hiuu') == ['hiuu', 'ygaqfvpct', 'hiuu', 'wtj']
    assert candidate(['ldgbbetjq', 'kcg'], 'avvhgamt') == ['avvhgamt', 'ldgbbetjq', 'avvhgamt', 'kcg']
    assert candidate(['leeeohuid', 'tohlzplka'], 'jvhvdzm') == ['jvhvdzm', 'leeeohuid', 'jvhvdzm', 'tohlzplka']
    assert candidate(['ukqce', 'eemn'], 'osrjad') == ['osrjad', 'ukqce', 'osrjad', 'eemn']
    assert candidate(['rlrgxuv', 'ulmxpc'], 'oraw') == ['oraw', 'rlrgxuv', 'oraw', 'ulmxpc']
    assert candidate(['reptfifhm', 'dumlj'], 'rjgcwqpf') == ['rjgcwqpf', 'reptfifhm', 'rjgcwqpf', 'dumlj']
    assert candidate(['bghkwlo', 'lvndueah'], 'bdo') == ['bdo', 'bghkwlo', 'bdo', 'lvndueah']
    assert candidate(['wriwbqjba', 'iilxyf'], 'txnmsgh') == ['txnmsgh', 'wriwbqjba', 'txnmsgh', 'iilxyf']
    assert candidate(['cfidxymr', 'efhrw'], 'tlsdohbl') == ['tlsdohbl', 'cfidxymr', 'tlsdohbl', 'efhrw']
    assert candidate(['hsr', 'lwxpj'], 'pdl') == ['pdl', 'hsr', 'pdl', 'lwxpj']
    assert candidate(['fcs', 'vnncv'], 'faxuhweb') == ['faxuhweb', 'fcs', 'faxuhweb', 'vnncv']
    assert candidate(['pit', 'tcy'], 'qowtyrksg') == ['qowtyrksg', 'pit', 'qowtyrksg', 'tcy']
    assert candidate(['nsaortde', 'wljfx'], 'nhnitngt') == ['nhnitngt', 'nsaortde', 'nhnitngt', 'wljfx']
    assert candidate(['vzaass', 'xixmmn'], 'ilvmrlla') == ['ilvmrlla', 'vzaass', 'ilvmrlla', 'xixmmn']
    assert candidate(['mjr', 'zycwh'], 'kcqtcdm') == ['kcqtcdm', 'mjr', 'kcqtcdm', 'zycwh']
    assert candidate(['rycgzd', 'qopoubyur'], 'nuubhdkri') == ['nuubhdkri', 'rycgzd', 'nuubhdkri', 'qopoubyur']
    assert candidate(['thyubhl', 'geibao'], 'rih') == ['rih', 'thyubhl', 'rih', 'geibao']
    assert candidate(['jvwm', 'plblc'], 'dbdhij') == ['dbdhij', 'jvwm', 'dbdhij', 'plblc']
    assert candidate(['ayhefddd', 'yfw'], 'ishziq') == ['ishziq', 'ayhefddd', 'ishziq', 'yfw']
    assert candidate(['mgnxkums', 'wkl'], 'aetwsb') == ['aetwsb', 'mgnxkums', 'aetwsb', 'wkl']
    assert candidate(['kzdtmov', 'strn'], 'vrqpf') == ['vrqpf', 'kzdtmov', 'vrqpf', 'strn']
    assert candidate(['cjl', 'ztghnmron'], 'gqdy') == ['gqdy', 'cjl', 'gqdy', 'ztghnmron']
    assert candidate(['madblti', 'xcouuiiz'], 'ucu') == ['ucu', 'madblti', 'ucu', 'xcouuiiz']
    assert candidate(['eqec', 'yxdq'], 'jvg') == ['jvg', 'eqec', 'jvg', 'yxdq']
    assert candidate(['mwmgphovl', 'kyms'], 'hvonpmmc') == ['hvonpmmc', 'mwmgphovl', 'hvonpmmc', 'kyms']
    assert candidate(['mwadusz', 'yyoeocb'], 'rgilhq') == ['rgilhq', 'mwadusz', 'rgilhq', 'yyoeocb']
    assert candidate(['icqxtsp', 'pyg'], 'kronqwuyi') == ['kronqwuyi', 'icqxtsp', 'kronqwuyi', 'pyg']
    assert candidate(['eunzamos', 'unbaqmbf'], 'edk') == ['edk', 'eunzamos', 'edk', 'unbaqmbf']
    assert candidate(['wlph', 'yyxpl'], 'qqtxwx') == ['qqtxwx', 'wlph', 'qqtxwx', 'yyxpl']
    assert candidate(['rtntmxlo', 'ikkddo'], 'xyqpjic') == ['xyqpjic', 'rtntmxlo', 'xyqpjic', 'ikkddo']

if __name__ == '__main__':
    check(insert_element)