from case_MBPP_102 import count_occurance


def check(candidate):
    assert candidate("letstdlenstdporstd") == 3
    assert candidate("truststdsolensporsd") == 1
    assert candidate("makestdsostdworthit") == 2
    assert candidate("ivpiufqxgyyhytnvtwj") == 0
    assert candidate("zeahwashfaoggofcvfyy") == 0
    assert candidate("edmmbetegnwkzutesq") == 0
    assert candidate("brgbduuovcpnjbxhblb") == 0
    assert candidate("axcpqmsmipwuuuydurqx") == 0
    assert candidate("qwsotksicjpzcuvvwwnwe") == 0
    assert candidate("phblwpxfovnghvdloaa") == 0
    assert candidate("gghoeofhhjvsrupfuqela") == 0
    assert candidate("onoapcswusjsqlomhaaaam") == 0
    assert candidate("ibsjqunmfqveamvlklvbpjx") == 0
    assert candidate("bsnckhdzsrzlqulhbudjoeju") == 0
    assert candidate("bdzejjkovsiotpimsj") == 0
    assert candidate("bafontiikwebimhzfah") == 0
    assert candidate("dpawfvqsvfhhqmjbsvrf") == 0
    assert candidate("nlowstjntwflwmarbiohn") == 0
    assert candidate("jktwqogcolnceeowuxqaox") == 0
    assert candidate("eecqzjjwtwiuasyclatj") == 0
    assert candidate("qlmqrwljqnkolmzimarbcfrq") == 0
    assert candidate("usqcumfwuyypohgyra") == 0
    assert candidate("xqgsrxayoavjwlocnwvioj") == 0
    assert candidate("avblquftncyndkcxzwjxx") == 0
    assert candidate("czxatnujybmqxbidxjne") == 0
    assert candidate("dezvnvolrescwoczcrgnwz") == 0
    assert candidate("mcrrhtlrpdxkhwu") == 0
    assert candidate("cyozlwklvvastelwmnlpv") == 0
    assert candidate("ptcvwiffajhqqmsxojw") == 0
    assert candidate("rrqagzbaakgwzdx") == 0
    assert candidate("ozbwtscwmczgizjpvftfd") == 0
    assert candidate("rlmgoihujbubzreamuiuwqb") == 0
    assert candidate("pvwqxedlihdlkqezx") == 0
    assert candidate("xhohqjjvhkoritftnvrzn") == 0
    assert candidate("aazhnjvxwwngzkx") == 0
    assert candidate("iulrbgyeyyrvkqo") == 0
    assert candidate("dnuhlwbxtodzlnt") == 0
    assert candidate("czmhavhxpwuymrmacunv") == 0
    assert candidate("ihkwdzxewftzqtkuj") == 0
    assert candidate("sygibfmqaztjzpjow") == 0
    assert candidate("eeamomyqdesptzmjylqhsyyp") == 0
    assert candidate("metkgzywvvrvuguumyyzcygl") == 0
    assert candidate("kcsyllfqtnvyybysk") == 0
    assert candidate("heibhrhihhircvcml") == 0
    assert candidate("qbzapvnordsuzqyrmr") == 0
    assert candidate("wgchsulgogiafxlcbcgm") == 0
    assert candidate("zotacruqdcghnysgrt") == 0
    assert candidate("qsdkrjerwtvdpfrfvwdhj") == 0
    assert candidate("lcwzdcagimvqjrvmfna") == 0
    assert candidate("ttxknsvwduzcwal") == 0
    assert candidate("lgpmnjkizbsnkrvrhsq") == 0
    assert candidate("ulzpjwpktaynitwkz") == 0
    assert candidate("payuuqunwgzljcp") == 0
    assert candidate("rfhzotvcrdjpiwnblp") == 0
    assert candidate("bbuxzafjanckfjsieu") == 0
    assert candidate("kophmgxpbcjbxeggdbqftz") == 0
    assert candidate("kiizjednsbuyrjbgnaai") == 0
    assert candidate("glhqgpcbkejjgpktgkhtzm") == 0
    assert candidate("hwvyhzjzfnbpbtuig") == 0
    assert candidate("etvfififhidisqpplsfhwqwe") == 0
    assert candidate("jydunlmynzjyuxbuoxfnzomd") == 0
    assert candidate("ulputvclplydufrayhymtzhg") == 0
    assert candidate("kinaenxneasszenx") == 0
    assert candidate("grwonwyzgnuxpnq") == 0
    assert candidate("ldttipomtepcqrklqbvi") == 0
    assert candidate("urtxdvuiqesodcbpmz") == 0
    assert candidate("zpacxoowxrjhwjsree") == 0
    assert candidate("ltwnzkbrmexdfylalkewj") == 0
    assert candidate("gbsjqugotlczknkpgtp") == 0
    assert candidate("mvwphxzgookuffguqwyhne") == 0
    assert candidate("yowqfhwqimxcnwai") == 0
    assert candidate("ndyjhepraqvswtxqb") == 0
    assert candidate("tsygqnnltuwpotsfbsrotnr") == 0
    assert candidate("gjrsmjyhlijvjhahn") == 0
    assert candidate("rczqvzxgrapsiutqehhpd") == 0
    assert candidate("yxkjcwxtyitlynbpujiscuux") == 0
    assert candidate("iuhedvpyubtfjip") == 0
    assert candidate("uaebuytocierienqbmdcejgr") == 0
    assert candidate("tmpnblbwxqhakhft") == 0
    assert candidate("rbughhywlemssazkmgffsavw") == 0
    assert candidate("lpqyjcmoumgnnapmsx") == 0
    assert candidate("ycsutezcjbbpthk") == 0
    assert candidate("bpdmccccjxnkuubdhslalx") == 0
    assert candidate("bemdvcypknpxyxieztnqzr") == 0
    assert candidate("fpdpemtbnqstgnmam") == 0
    assert candidate("rmuvsrqdskabaleec") == 0
    assert candidate("fbxmwgbnpbuzvstxbzkbnt") == 0
    assert candidate("igftodrnjapbnevnvxvk") == 0
    assert candidate("mihjqtjteraokursfnibv") == 0
    assert candidate("ztmxrxadgruwkdbdlulaer") == 0
    assert candidate("uefzwxwctxxuposwvi") == 0
    assert candidate("kdfttuqxnwoulccwavakj") == 0
    assert candidate("purujhrrcjzmzedyl") == 0
    assert candidate("wxeebrmutcnxogzxnfnjypa") == 0
    assert candidate("vgnptghoyxgisifuz") == 0
    assert candidate("fmewvzjfxyxtiaagrwvtgl") == 0
    assert candidate("cmfnmevldnzuwkfjzmlmtqxf") == 0
    assert candidate("zcxotclblqckbrpvvrrm") == 0
    assert candidate("nevyloxnowdnaaa") == 0
    assert candidate("honijwylbxtucrsbigy") == 0
    assert candidate("apvjsvxlhuafxffp") == 0
    assert candidate("nyvxpmvbvjpiqhukrpmtfgbh") == 0

if __name__ == '__main__':
    check(count_occurance)