from case_MBPP_243 import reverse_string_list


def check(candidate):
    assert candidate(['Red', 'Green', 'Blue', 'White', 'Black'])==['deR', 'neerG', 'eulB', 'etihW', 'kcalB']
    assert candidate(['john','amal','joel','george'])==['nhoj','lama','leoj','egroeg']
    assert candidate(['jack','john','mary'])==['kcaj','nhoj','yram']
    assert candidate(['TQHVG', 'AEFpH', 'DHU', 'awymD', 'HvRH']) == ['GVHQT', 'HpFEA', 'UHD', 'Dmywa', 'HRvH']
    assert candidate(['pSbIO', 'LntpuidR', 'jhDQ', 'KfsHCCY', 'yXq']) == ['OIbSp', 'RdiuptnL', 'QDhj', 'YCCHsfK', 'qXy']
    assert candidate(['pvpdsfoCg', 'XhxOc', 'ZpRhSGdK', 'IIE', 'dVDLIQ']) == ['gCofsdpvp', 'cOxhX', 'KdGShRpZ', 'EII', 'QILDVd']
    assert candidate(['lKu', 'WSSP', 'rdGr', 'EfQf', 'ozRP']) == ['uKl', 'PSSW', 'rGdr', 'fQfE', 'PRzo']
    assert candidate(['bneQ', 'IkFz', 'Hde', 'sErKDuU', 'IfTHlT']) == ['Qenb', 'zFkI', 'edH', 'UuDKrEs', 'TlHTfI']
    assert candidate(['Ave', 'psR', 'ZOnSXSGqR', 'mSZOPYMbS', 'EeFa']) == ['evA', 'Rsp', 'RqGSXSnOZ', 'SbMYPOZSm', 'aFeE']
    assert candidate(['hqlJN', 'ujMC', 'QooSrJpZw', 'phqXty', 'XgdzIiak']) == ['NJlqh', 'CMju', 'wZpJrSooQ', 'ytXqhp', 'kaiIzdgX']
    assert candidate(['MtEAOmPqU', 'YOLJliw', 'NEaBmF', 'aFVdwAs', 'lDQsIShxh']) == ['UqPmOAEtM', 'wilJLOY', 'FmBaEN', 'sAwdVFa', 'hxhSIsQDl']
    assert candidate(['EHBw', 'DxspQXl', 'wCZQAqk', 'TseV', 'PuGMol']) == ['wBHE', 'lXQpsxD', 'kqAQZCw', 'VesT', 'loMGuP']
    assert candidate(['pldx', 'jFOAoRW', 'aEAj', 'YrQydo', 'WfWP']) == ['xdlp', 'WRoAOFj', 'jAEa', 'odyQrY', 'PWfW']
    assert candidate(['umzdmK', 'OoZOmNnmj', 'SGNDf', 'PKY', 'fWxtqNTfD']) == ['Kmdzmu', 'jmnNmOZoO', 'fDNGS', 'YKP', 'DfTNqtxWf']
    assert candidate(['PaPYUsme', 'YSgpirZa', 'xnAllb', 'dSqsn', 'iXYNQHI']) == ['emsUYPaP', 'aZripgSY', 'bllAnx', 'nsqSd', 'IHQNYXi']
    assert candidate(['sDN', 'csmVsZL', 'YnB', 'BoYeoFgxN', 'vrTnzwHcz']) == ['NDs', 'LZsVmsc', 'BnY', 'NxgFoeYoB', 'zcHwznTrv']
    assert candidate(['tnCtlxR', 'hYtjiqIm', 'iAdSBUWsB', 'wTzpYZ', 'xDQjO']) == ['RxltCnt', 'mIqijtYh', 'BsWUBSdAi', 'ZYpzTw', 'OjQDx']
    assert candidate(['TLKRwqH', 'zgu', 'xtDlw', 'XNR', 'kuuMY']) == ['HqwRKLT', 'ugz', 'wlDtx', 'RNX', 'YMuuk']
    assert candidate(['pKjrFtoTR', 'WSoet', 'kJFCke', 'fUeKIMp', 'axWE']) == ['RTotFrjKp', 'teoSW', 'ekCFJk', 'pMIKeUf', 'EWxa']
    assert candidate(['akTqnLc', 'rWOI', 'TOQiHRfEz', 'Umu', 'nPaJ']) == ['cLnqTka', 'IOWr', 'zEfRHiQOT', 'umU', 'JaPn']
    assert candidate(['FWS', 'ptOms', 'ksJi', 'COm', 'XRmSmKUb']) == ['SWF', 'smOtp', 'iJsk', 'mOC', 'bUKmSmRX']
    assert candidate(['rAoJVaO', 'YVUvp', 'GytVdI', 'vTvE', 'KXsHza']) == ['OaVJoAr', 'pvUVY', 'IdVtyG', 'EvTv', 'azHsXK']
    assert candidate(['JjAZ', 'yMzvpgkZ', 'vaXBmsiDT', 'JNzrgc', 'gzIfFHB']) == ['ZAjJ', 'ZkgpvzMy', 'TDismBXav', 'cgrzNJ', 'BHFfIzg']
    assert candidate(['cEGWUex', 'XHmi', 'FFNaMit', 'LBTAbimaA', 'LuMV']) == ['xeUWGEc', 'imHX', 'tiMaNFF', 'AamibATBL', 'VMuL']
    assert candidate(['pGYXuj', 'kjC', 'vrJHSo', 'aoxMamy', 'EMIRmHrWj']) == ['juXYGp', 'Cjk', 'oSHJrv', 'ymaMxoa', 'jWrHmRIME']
    assert candidate(['LuB', 'qqsKva', 'WfqQwLlYe', 'TspF', 'RiMo']) == ['BuL', 'avKsqq', 'eYlLwQqfW', 'FpsT', 'oMiR']
    assert candidate(['pqtc', 'acKSWZW', 'uohzBr', 'udLKZXM', 'ReSVuQy']) == ['ctqp', 'WZWSKca', 'rBzhou', 'MXZKLdu', 'yQuVSeR']
    assert candidate(['DqmNBLaF', 'Tzkfz', 'FJOGuSoMW', 'HtyOkJh', 'AsSFxL']) == ['FaLBNmqD', 'zfkzT', 'WMoSuGOJF', 'hJkOytH', 'LxFSsA']
    assert candidate(['KRF', 'VYnRdAL', 'sCNHPN', 'KblUpm', 'jUpBNl']) == ['FRK', 'LAdRnYV', 'NPHNCs', 'mpUlbK', 'lNBpUj']
    assert candidate(['ubvHRY', 'fBguVBq', 'KkL', 'RikIousY', 'wbAEuYWPE']) == ['YRHvbu', 'qBVugBf', 'LkK', 'YsuoIkiR', 'EPWYuEAbw']
    assert candidate(['gtgqJ', 'Kwg', 'LVOII', 'yIOupYrrG', 'zAxX']) == ['Jqgtg', 'gwK', 'IIOVL', 'GrrYpuOIy', 'XxAz']
    assert candidate(['FWJIJHo', 'xaIJeLaL', 'aNvp', 'VBOzuzjy', 'bRTtgXA']) == ['oHJIJWF', 'LaLeJIax', 'pvNa', 'yjzuzOBV', 'AXgtTRb']
    assert candidate(['hTRuHUyKU', 'hTgnyU', 'xTD', 'BMta', 'OPETxHO']) == ['UKyUHuRTh', 'UyngTh', 'DTx', 'atMB', 'OHxTEPO']
    assert candidate(['iJzLkEZEj', 'CjyTDcBg', 'dWxrpNenV', 'DiFa', 'yNx']) == ['jEZEkLzJi', 'gBcDTyjC', 'VneNprxWd', 'aFiD', 'xNy']
    assert candidate(['loMhY', 'NhCqpcI', 'hCwNaqzz', 'fXElYrtet', 'vub']) == ['YhMol', 'IcpqChN', 'zzqaNwCh', 'tetrYlEXf', 'buv']
    assert candidate(['izm', 'wBTd', 'EonfBcVIw', 'zKrQoQVuy', 'QfS']) == ['mzi', 'dTBw', 'wIVcBfnoE', 'yuVQoQrKz', 'SfQ']
    assert candidate(['yqljxwii', 'bwgile', 'wzgjtuir', 'opfdrutyukh']) == ['iiwxjlqy', 'eligwb', 'riutjgzw', 'hkuyturdfpo']
    assert candidate(['pbjy', 'pycabcv', 'hbjjfg', 'ufpjogk']) == ['yjbp', 'vcbacyp', 'gfjjbh', 'kgojpfu']
    assert candidate(['kulsi', 'xtcknhjik', 'ekachzb', 'qlxabpa']) == ['isluk', 'kijhnkctx', 'bzhcake', 'apbaxlq']
    assert candidate(['ltfkmt', 'rbjof', 'zfgmztsgi', 'fiiqb']) == ['tmkftl', 'fojbr', 'igstzmgfz', 'bqiif']
    assert candidate(['kca', 'hoeo', 'ntwfdhxj', 'ctlynuaq']) == ['ack', 'oeoh', 'jxhdfwtn', 'qaunyltc']
    assert candidate(['ndauqr', 'kjkaqhgb', 'jhnn', 'vtxbgcwnk']) == ['rquadn', 'bghqakjk', 'nnhj', 'knwcgbxtv']
    assert candidate(['qbwhxhrc', 'zmqvhgxu', 'frxfqo', 'rce']) == ['crhxhwbq', 'uxghvqmz', 'oqfxrf', 'ecr']
    assert candidate(['yuiekjp', 'yeiqid', 'hvbrgkuis', 'vqq']) == ['pjkeiuy', 'diqiey', 'siukgrbvh', 'qqv']
    assert candidate(['epwh', 'ahgnpzrf', 'ioq', 'jvybnffrs']) == ['hwpe', 'frzpngha', 'qoi', 'srffnbyvj']
    assert candidate(['gts', 'delqnkjk', 'jgn', 'jrwhslpx']) == ['stg', 'kjknqled', 'ngj', 'xplshwrj']
    assert candidate(['dis', 'ijxp', 'jpaiyerqw', 'bdzezltqly']) == ['sid', 'pxji', 'wqreyiapj', 'ylqtlzezdb']
    assert candidate(['ptsxs', 'hhxdb', 'obav', 'zwtriuvgy']) == ['sxstp', 'bdxhh', 'vabo', 'ygvuirtwz']
    assert candidate(['wmcxkw', 'mlpnaw', 'cthzr', 'vbvvj']) == ['wkxcmw', 'wanplm', 'rzhtc', 'jvvbv']
    assert candidate(['cnkqpb', 'mkxzzof', 'qazxmf', 'hdivo']) == ['bpqknc', 'fozzxkm', 'fmxzaq', 'ovidh']
    assert candidate(['bgsyubd', 'mhjvx', 'drrcztk', 'jtpk']) == ['dbuysgb', 'xvjhm', 'ktzcrrd', 'kptj']
    assert candidate(['sxfacpoib', 'dyk', 'tiwfb', 'mio']) == ['biopcafxs', 'kyd', 'bfwit', 'oim']
    assert candidate(['gjrikas', 'hptl', 'kuimcup', 'zbula']) == ['sakirjg', 'ltph', 'pucmiuk', 'alubz']
    assert candidate(['grt', 'jitkf', 'grhy', 'dpra']) == ['trg', 'fktij', 'yhrg', 'arpd']
    assert candidate(['uxpp', 'zbxay', 'agi', 'oautlzgylms']) == ['ppxu', 'yaxbz', 'iga', 'smlygzltuao']
    assert candidate(['vmabg', 'dyvztqve', 'kybcf', 'iodzrqtl']) == ['gbamv', 'evqtzvyd', 'fcbyk', 'ltqrzdoi']
    assert candidate(['xymzcxcs', 'xmq', 'ipcmy', 'itbpha']) == ['scxczmyx', 'qmx', 'ymcpi', 'ahpbti']
    assert candidate(['jlksth', 'pcthn', 'nkgpwgo', 'figlbvg']) == ['htsklj', 'nhtcp', 'ogwpgkn', 'gvblgif']
    assert candidate(['cqsv', 'wapsey', 'asslrzymt', 'wfdbxny']) == ['vsqc', 'yespaw', 'tmyzrlssa', 'ynxbdfw']
    assert candidate(['knr', 'cstnqfhex', 'ostkopds', 'tbdhszvfkcru']) == ['rnk', 'xehfqntsc', 'sdpoktso', 'urckfvzshdbt']
    assert candidate(['lzx', 'tab', 'kmxhxuxps', 'hmuf']) == ['xzl', 'bat', 'spxuxhxmk', 'fumh']
    assert candidate(['psoy', 'hwasddal', 'oyxrq', 'yomncrju']) == ['yosp', 'laddsawh', 'qrxyo', 'ujrcnmoy']
    assert candidate(['zahr', 'wgqd', 'xxhsuezc', 'fhr']) == ['rhaz', 'dqgw', 'czeushxx', 'rhf']
    assert candidate(['onljzmrk', 'dalaubrdm', 'xijjb', 'hiwqup']) == ['krmzjlno', 'mdrbualad', 'bjjix', 'puqwih']
    assert candidate(['ksymsgajy', 'bwjpdhyj', 'rrziht', 'fpdzjnrfea']) == ['yjagsmysk', 'jyhdpjwb', 'thizrr', 'aefrnjzdpf']
    assert candidate(['rebofrdi', 'mjitpsruv', 'qbpfmhr', 'vdagp']) == ['idrfober', 'vursptijm', 'rhmfpbq', 'pgadv']
    assert candidate(['gciswctnz', 'vqtnwfwi', 'cybhe', 'dhtlrcquy']) == ['zntcwsicg', 'iwfwntqv', 'ehbyc', 'yuqcrlthd']
    assert candidate(['pby', 'cgtv', 'xsutmqjxg', 'bmbffwqrpdz']) == ['ybp', 'vtgc', 'gxjqmtusx', 'zdprqwffbmb']
    assert candidate(['zhui', 'xmnpqbijd', 'glromonjb', 'jqtkcdvtz']) == ['iuhz', 'djibqpnmx', 'bjnomorlg', 'ztvdcktqj']
    assert candidate(['sxcc', 'nzdefytm', 'ewnaz']) == ['ccxs', 'mtyfedzn', 'zanwe']
    assert candidate(['oiqmh', 'tqhcg', 'fdbgc']) == ['hmqio', 'gchqt', 'cgbdf']
    assert candidate(['wweadusjd', 'xslnh', 'hiwycluwr']) == ['djsudaeww', 'hnlsx', 'rwulcywih']
    assert candidate(['awd', 'vjois', 'rymlt']) == ['dwa', 'siojv', 'tlmyr']
    assert candidate(['djier', 'fxhnz', 'psjzmce']) == ['reijd', 'znhxf', 'ecmzjsp']
    assert candidate(['lwdjqy', 'nkeigs', 'npt']) == ['yqjdwl', 'sgiekn', 'tpn']
    assert candidate(['fze', 'tqwmfnf', 'ymvtsyu']) == ['ezf', 'fnfmwqt', 'uystvmy']
    assert candidate(['cbk', 'lsfi', 'hyfxh']) == ['kbc', 'ifsl', 'hxfyh']
    assert candidate(['nlux', 'ubhiqpj', 'bxag']) == ['xuln', 'jpqihbu', 'gaxb']
    assert candidate(['egebd', 'fgc', 'nfhazuy']) == ['dbege', 'cgf', 'yuzahfn']
    assert candidate(['frmbypspx', 'zbicu', 'azslvssl']) == ['xpspybmrf', 'ucibz', 'lssvlsza']
    assert candidate(['hkpadncn', 'nssluy', 'hkzceygg']) == ['ncndapkh', 'yulssn', 'ggyeczkh']
    assert candidate(['jej', 'udk', 'fzfan']) == ['jej', 'kdu', 'nafzf']
    assert candidate(['wwhaluj', 'ybjsx', 'vzlnv']) == ['julahww', 'xsjby', 'vnlzv']
    assert candidate(['vqhoplr', 'uwv', 'xuwqrnvui']) == ['rlpohqv', 'vwu', 'iuvnrqwux']
    assert candidate(['qrklletm', 'turhfof', 'jfbylem']) == ['mtellkrq', 'fofhrut', 'melybfj']
    assert candidate(['oudkfbyr', 'rfuyywpfm', 'qefzhx']) == ['rybfkduo', 'mfpwyyufr', 'xhzfeq']
    assert candidate(['snk', 'vvyvu', 'ionwfxytl']) == ['kns', 'uvyvv', 'ltyxfwnoi']
    assert candidate(['hipziuv', 'nakxhvvv', 'qktu']) == ['vuizpih', 'vvvhxkan', 'utkq']
    assert candidate(['luaekasli', 'anlzdzobn', 'nvwpn']) == ['ilsakeaul', 'nbozdzlna', 'npwvn']
    assert candidate(['tkf', 'ragkg', 'sxhnunb']) == ['fkt', 'gkgar', 'bnunhxs']
    assert candidate(['ohmuktn', 'xbczdqk', 'sjgevgh']) == ['ntkumho', 'kqdzcbx', 'hgvegjs']
    assert candidate(['eebq', 'hsgoqmpvz', 'bpxwohbc']) == ['qbee', 'zvpmqogsh', 'cbhowxpb']
    assert candidate(['ijerl', 'ofksxe', 'anao']) == ['lreji', 'exskfo', 'oana']
    assert candidate(['eyam', 'dui', 'oiaxv']) == ['maye', 'iud', 'vxaio']
    assert candidate(['ybjknv', 'ldnt', 'ilglipag']) == ['vnkjby', 'tndl', 'gapilgli']
    assert candidate(['tdciylpl', 'cnmnbjcq', 'ahhib']) == ['lplyicdt', 'qcjbnmnc', 'bihha']
    assert candidate(['jraz', 'cmc', 'lyxfuhjgi']) == ['zarj', 'cmc', 'igjhufxyl']
    assert candidate(['qantyuqz', 'qldhdsj', 'uxtsrgure']) == ['zquytnaq', 'jsdhdlq', 'erugrstxu']
    assert candidate(['mqimj', 'vuh', 'qmuhdm']) == ['jmiqm', 'huv', 'mdhumq']
    assert candidate(['fzco', 'vzrpmbof', 'ekyiwcd']) == ['oczf', 'fobmprzv', 'dcwiyke']
    assert candidate(['yuhgq', 'zkslxio', 'ufitwck']) == ['qghuy', 'oixlskz', 'kcwtifu']
    assert candidate(['tdqrdh', 'waf', 'ggcotcnh']) == ['hdrqdt', 'faw', 'hnctocgg']

if __name__ == '__main__':
    check(reverse_string_list)