from case_MBPP_168 import max_aggregate


def check(candidate):
    assert candidate([('Juan Whelan',90),('Sabah Colley',88),('Peter Nichols',7),('Juan Whelan',122),('Sabah Colley',84)])==('Juan Whelan', 212)
    assert candidate([('Juan Whelan',50),('Sabah Colley',48),('Peter Nichols',37),('Juan Whelan',22),('Sabah Colley',14)])==('Juan Whelan', 72)
    assert candidate([('Juan Whelan',10),('Sabah Colley',20),('Peter Nichols',30),('Juan Whelan',40),('Sabah Colley',50)])==('Sabah Colley', 70)
    assert candidate([('OORZrPCS xAFoD', 95), ('klidjLWRHcgS', 93), ('tQmLFjbFfs', 9), ('FXkKuOvZWA', 126), ('UhVgMRUauHiw', 86)]) == ('FXkKuOvZWA', 126)
    assert candidate([(' sgISDCVhdfsODh', 88), ('FoTMqfbbnHAYvdHd', 93), ('mUYGXomuLdyWcam', 10), ('bnHlxSCjRR', 123), ('TFAdQwwnJf', 86)]) == ('bnHlxSCjRR', 123)
    assert candidate([('cUIYfdGEhdILiO', 86), ('kduWtHhZYsDYDbhBAT', 87), ('SWSMduvZGyR', 8), ('Ecbklv', 119), ('zSWPImXVryS', 81)]) == ('Ecbklv', 119)
    assert candidate([('Ldj lkd', 85), ('TTXeNYXbPhy', 86), ('M rgYccbDYlwKYs', 5), ('QnjQRaQDKZNR', 123), ('skcpHVKQMoQp', 81)]) == ('QnjQRaQDKZNR', 123)
    assert candidate([('cztdzQnz', 91), ('sGzsTTFiKVUoFQ', 84), ('xZDvKAMBJOV', 3), ('SZiXYF wTtNQNu', 118), ('KsiCj bNumMYZsUH', 81)]) == ('SZiXYF wTtNQNu', 118)
    assert candidate([('sGrfDvncaqeRbQS', 87), ('XkMkb DDRuJRoA', 87), ('pSRjUXVlLQQDJvcE', 4), ('eCrTYmOpHY', 126), ('PjMqsaLBmdHj', 88)]) == ('eCrTYmOpHY', 126)
    assert candidate([('oiDeKd', 87), ('LtaXIUNAL', 90), ('yMdigvZlf', 10), ('PtpyoWPHyyByzLM', 126), ('pIeQYtnpWPTKn', 82)]) == ('PtpyoWPHyyByzLM', 126)
    assert candidate([('tNaAUIhWixu', 90), ('UoHwxYdINqmRY', 90), ('yst ILyhuQQNa', 8), ('hpkBTmyVYZKHVCo', 121), ('iEzAiGgtiNB', 83)]) == ('hpkBTmyVYZKHVCo', 121)
    assert candidate([('tROwkjZB', 94), ('wnXyfnyJdA', 90), ('PuiHUFifxFy', 4), ('ruQL HVTL', 126), ('CWLeHDpAjkGNDcip', 80)]) == ('ruQL HVTL', 126)
    assert candidate([('kYQXlFNVcc', 86), ('YqXBjqQJFMP', 84), ('HKSDxuiZvYW', 11), ('CulzRZEVIDjy', 127), ('mTcjuiZVNhwhkVtpD', 85)]) == ('CulzRZEVIDjy', 127)
    assert candidate([('UUwnQNK', 87), ('nutJlpzEET', 86), ('VlhaLJjaBNsrkMSoPA', 10), ('JbLVsQMbv', 126), ('tNMGVijjE yl', 89)]) == ('JbLVsQMbv', 126)
    assert candidate([('SjiESCgeYAPBP', 85), ('HuUlENPZwLfyExn', 88), ('ngRMxFege', 10), ('sjgsPgAT wo', 124), ('BkPLfxAJBJHnV', 85)]) == ('sjgsPgAT wo', 124)
    assert candidate([('ULWBAnRkgnQjfi', 92), ('eeitOtiHzE', 90), ('DUCGVqXOcoy', 4), ('YYstsqSoCy', 127), ('WrfNekASTqD', 88)]) == ('YYstsqSoCy', 127)
    assert candidate([('NmiEBtHJjANjoi', 89), ('iVz iSsIdJiEWmSCTU', 90), ('nfnhRwvGHPwBZUB', 12), ('Gz aguJbNGe', 126), ('WXDpgjZkGJkq OP', 85)]) == ('Gz aguJbNGe', 126)
    assert candidate([('IDHrjEATXURaa', 91), ('ttWGuJSrnFAGBM', 86), ('rzTHhGm Vr', 2), ('HqmkgDVANwQ', 117), ('bgqjnbeginpULsU', 85)]) == ('HqmkgDVANwQ', 117)
    assert candidate([('GgrPVayaHZkApI', 94), ('HRvBrmSsHoyiiD', 83), ('DtBtqbUwFjBPEIZ', 10), ('jHULZnEerym', 120), ('TcFjalpkJa', 79)]) == ('jHULZnEerym', 120)
    assert candidate([('qxXEPvWBLHmc', 92), ('mwbiNKJCpQTKIEl', 90), ('NTqY dJDszSOHIBtOV', 8), ('CvsQVws', 120), ('gMlhkZZUILVwZecTrY', 88)]) == ('CvsQVws', 120)
    assert candidate([('CAhUpWOgpx', 86), ('duVcbviqprr', 89), ('xAnNLHYW ', 7), ('KRWzSBb q', 119), ('ZzEiPIGqGE', 86)]) == ('KRWzSBb q', 119)
    assert candidate([('NRrLLRKuJEpSG', 89), ('bRqvWXMZUQ', 87), ('tBNaoqyjH', 5), ('bFvPHwZnrDs', 122), ('XSuxlaSetH', 80)]) == ('bFvPHwZnrDs', 122)
    assert candidate([('NXbIoksK', 91), ('Wyo njjCLW', 92), ('fIloKVI UXjKSWGHHt', 9), ('lktXlmJea', 122), ('wFdkwMOSxfWs Qdl', 84)]) == ('lktXlmJea', 122)
    assert candidate([('soDKYD', 90), ('NKHOCAEUvQ', 92), ('JdptEktEXyScUVl', 6), ('vBIPoaMM', 120), ('rXrtoORZcLrCqK', 89)]) == ('vBIPoaMM', 120)
    assert candidate([('LSWpJxc', 89), ('vwWFwlUUTMpa', 83), ('ArCqSkeybjhCAdW', 2), ('yeqMfrDx BhV', 125), ('jnIoiMcYHyvie', 84)]) == ('yeqMfrDx BhV', 125)
    assert candidate([('vBXxflboQJsMnmM', 93), ('ipIBrzMcrjbxWVy', 89), ('xpmADjLjhmpouLhKou', 2), ('FZolgtl', 122), ('xfYIreExlOvRQTO', 83)]) == ('FZolgtl', 122)
    assert candidate([('bHyezDnweqZn', 87), ('MJaHEPBObCNX vocEt', 91), ('ObeBnEvus', 12), ('JxmmOUsbfVg', 121), ('IMgibiOzsGH Uz', 79)]) == ('JxmmOUsbfVg', 121)
    assert candidate([('shlvEOoepNwwK', 93), ('eaGgEOztzjpzTwvH', 93), ('VcDDWCSwgESB', 10), ('LMrjkczP', 117), ('RtzPeewxBpWuP', 89)]) == ('LMrjkczP', 117)
    assert candidate([('YTgtZA', 93), ('bDRPHBFzh', 83), ('noaUwjaKGbEU', 9), ('fweo HJcc', 120), ('COzOntPtXgfhOAKrGG', 84)]) == ('fweo HJcc', 120)
    assert candidate([('LMqn YhwgUpoMpE', 91), ('FHMswEgugIzkH', 87), ('CoScIySTRiJR', 9), ('gqIIEz', 123), ('FMRRXEdixyw', 79)]) == ('gqIIEz', 123)
    assert candidate([('yRAOz cw dncvg', 85), ('jNyoskCQYezbH', 84), ('mFhgZLNlYMjf', 12), ('qPykVPOZYeI', 123), ('vkAXxTWWVfvTQWd', 81)]) == ('qPykVPOZYeI', 123)
    assert candidate([('APjLVO', 95), ('GCoSATOMxCDivGKEf', 90), ('HYolrlFddqabPeTy', 2), ('uvLoAr', 117), (' EZtvGOOJhtLmYZeqd', 79)]) == ('uvLoAr', 117)
    assert candidate([('wjdKIvdYPzgptx', 87), ('dcHXIeiglhcIIiN', 93), ('fExqSADKRSRgwSbg', 3), ('iMROeCFEvkp', 125), ('LRofWPJJpvwAS', 79)]) == ('iMROeCFEvkp', 125)
    assert candidate([('czncvKL', 90), ('vGidGeqjXbVf', 90), ('cpKVOvpMxTPhRhsXfg', 9), ('OTlBjCWmQRZejkn', 124), ('yGfqUIBsIsGYMIKkof', 86)]) == ('OTlBjCWmQRZejkn', 124)
    assert candidate([('ZTIMtdgpqrDQ', 88), ('pxcIGQPUgDTdxRQB Y', 87), ('bxhYSMGj  JoQ', 12), ('yFfpwBpBwMPGIvM', 117), ('yJGbFQHroAOpEVYqRt', 79)]) == ('yFfpwBpBwMPGIvM', 117)
    assert candidate([('pHgOPLKP', 85), ('WBehInAma', 88), ('nkpfqxbzCjBgNBnS', 12), ('QrlhUSkSBt', 117), ('cdFFM kYgvAJetfmT', 85)]) == ('QrlhUSkSBt', 117)
    assert candidate([('OVmGXIkZZWIKsN', 48), ('xnaLQxHLknHXKYaHR', 43), ('CBmXHPDRcREM', 40), ('zqAszyZWUR', 19), ('JUxTzOEnQBaxUTm', 19)]) == ('OVmGXIkZZWIKsN', 48)
    assert candidate([('PcgmLzsv', 52), (' OjEuretvHWNPADExf', 43), ('xuzqzNZHHmk', 32), ('qLsxgFWeLVQYw', 21), ('xCpWSiPfnztdXF', 19)]) == ('PcgmLzsv', 52)
    assert candidate([(' mNmFZrrGorNbs', 48), ('MQpnFBoKWeB', 49), ('wjifjOwkJSetssJ', 41), ('ouVRRFC', 26), ('zourphuQcTeGHDyv', 13)]) == ('MQpnFBoKWeB', 49)
    assert candidate([('mMCQqhIGCOuV', 54), ('hTncdJJiyBIlo', 45), ('cjvwtoMvEvedv wqbK', 34), ('neJkzahftD', 19), ('BuxEBSjGn', 12)]) == ('mMCQqhIGCOuV', 54)
    assert candidate([('CMGEQG', 45), ('hBHYXdVhhWly', 45), ('PqkCLrmnhAVPxfuUG', 40), ('tdhGXJuQQGMMN', 22), ('WVVKuhnukTeqb LSj', 11)]) == ('CMGEQG', 45)
    assert candidate([('nYPwpu', 51), ('fKnEoszAlYjA', 51), ('RdscuGglABEPzf', 42), ('XgoJRYzA', 22), ('EvufxJIJbZBZexDqVB', 16)]) == ('nYPwpu', 51)
    assert candidate([(' eJRUUHctDf', 55), ('XLqQMPZTb', 46), ('kaaTUOJwv', 35), ('PGbmJ adU', 26), ('NplNVHUNJ', 15)]) == (' eJRUUHctDf', 55)
    assert candidate([('abQzwgtRNfVrrWW', 47), ('BtTCHCZkGjCbjatKxt', 50), ('KTSiheqXNybqq', 40), ('suXcGDjyuJZuP', 17), ('qNMRZbnRP', 19)]) == ('BtTCHCZkGjCbjatKxt', 50)
    assert candidate([('ecapgUWDApT', 54), ('SIzDyCDAUakOnaOZM', 53), ('AhUFRQp RFTf', 38), ('DrfUSAa', 27), ('WVzTgKfweptJ', 14)]) == ('ecapgUWDApT', 54)
    assert candidate([('WaiCSfZNEE', 53), ('LBAYlPpiuVdWCbLM', 48), ('FrCLmONFyVEUB', 40), ('mawbVLQimNtw', 22), ('cAaTqRgymzaSyPrff', 16)]) == ('WaiCSfZNEE', 53)
    assert candidate([('BMzugZkch', 47), ('kKtHlwOChD', 48), ('mmnbtrjkDFSm', 39), ('SLqTpfUF WL', 27), ('BNqYNJZKDkj', 11)]) == ('kKtHlwOChD', 48)
    assert candidate([('OVQYBvz', 52), ('seKZWAwoLlbjkc', 49), ('NAhRwbBuvG', 33), ('FGfBxkdrVxkLQx', 17), ('BfyPsZlpGXbjFKYil', 17)]) == ('OVQYBvz', 52)
    assert candidate([('zdUwVHLZT', 52), ('TWLHUBeAr', 47), ('aCL XbWVjJUATJhMVD', 40), ('VxYwmVI', 17), ('vnDlCLdEamOsxIlM', 13)]) == ('zdUwVHLZT', 52)
    assert candidate([('KpZsPUcnYXA', 54), ('IMCTegaBW', 44), ('wRgbcGfDc', 34), ('ntLfwSDUri', 19), ('YqtDORvyCMIOdP', 10)]) == ('KpZsPUcnYXA', 54)
    assert candidate([('ZnRDGYELB', 51), ('iSOvjwKUEFq', 53), ('npNIlBbXzD j swaD', 41), ('YliYCxW PVmfC', 27), ('xQoPduFcbN RsvHzn', 13)]) == ('iSOvjwKUEFq', 53)
    assert candidate([('VzbSYW', 45), ('MZtCddqzurEx', 53), ('UihltVeATh', 32), ('QcWVwRzpb', 27), ('Upb louEy On', 15)]) == ('MZtCddqzurEx', 53)
    assert candidate([('JSdQnHXSzvCSfZc', 51), ('OJNPgztfUGPx', 44), ('eusmpsvoFzkAHmH', 36), ('CQgcukSX w', 27), ('RJHHINwf NRtNI iB', 16)]) == ('JSdQnHXSzvCSfZc', 51)
    assert candidate([('AkVEwZFOosuau', 55), ('ezOPNVkGDtUIJoWfm', 44), ('OzcnmvTvGIedjHOyFV', 32), ('JXMEMIBJ', 19), ('LRseVXRDzswaqgBsn', 18)]) == ('AkVEwZFOosuau', 55)
    assert candidate([('XkacAfEEmlN', 52), ('fPaMiNjJnEBdFsGxK', 52), ('AOcroJJmGBFt', 42), ('UzEfkqGoAXn', 26), ('RbuFYzfLcbHopLZzB', 18)]) == ('XkacAfEEmlN', 52)
    assert candidate([('zClDnlpzNmHnJcZ', 46), ('iYAIuHxKm fqfCW', 45), ('OywzPnvNsMu', 32), ('JbUybslddP', 18), ('DZaOIEpUzwUjM', 13)]) == ('zClDnlpzNmHnJcZ', 46)
    assert candidate([('pDYcZH', 49), ('KPWgwsZzluI', 49), ('pqcsXLQkcCobWWaVM', 37), ('PEhLxIO kV', 20), ('Ngltk anrtlRtsMliN', 13)]) == ('pDYcZH', 49)
    assert candidate([('wpGSeDoRRMjtm', 55), ('LpWHmONwDRNm', 51), ('QhHkMLedZfGc', 36), ('KdXhRePoU', 23), ('HpDPXJpLjbBcf', 14)]) == ('wpGSeDoRRMjtm', 55)
    assert candidate([('UKOEB kUglv', 54), ('SRhMMMfSYMqXWbX', 50), ('FrczYAwNjrSXOGG', 40), ('LaTwAOSahpIuUD', 19), ('BFjGpsPOIo', 14)]) == ('UKOEB kUglv', 54)
    assert candidate([('KduSNaCCY', 46), ('TIpSnAtsFhHRxToQ', 45), ('nOKqfxsaNmNb', 35), ('QWtaywTQOLSyRM', 20), ('fTqickmFDPOU', 15)]) == ('KduSNaCCY', 46)
    assert candidate([('BBmKKaQshRM', 46), ('uavQbBxPupc', 46), ('aVCIefkIzy', 41), (' zguGq jvCwM', 27), ('LEobCmVLmIP', 11)]) == ('BBmKKaQshRM', 46)
    assert candidate([('yNfPDFv', 55), (' hIYxrJVYi', 53), ('tpShvrWAXYDb', 40), ('lAuxNcJqCyBx', 20), ('Y UsmTyJYmpUieT', 18)]) == ('yNfPDFv', 55)
    assert candidate([('hmFjEyCNGAx', 47), ('BltnuoFqHgtbTizP', 53), ('elnqLUULLBR', 37), ('aXEeaBWUu', 23), ('jsDPHqXZH wvlEvlzI', 16)]) == ('BltnuoFqHgtbTizP', 53)
    assert candidate([('WQobGq kpR', 46), (' jlSlBSSXggcRELs', 47), ('HywUmiZVLJMBG', 32), ('CAGwgqlQveNvj', 23), ('EmxMUHtXah', 11)]) == (' jlSlBSSXggcRELs', 47)
    assert candidate([('sbiFsIvPTh oMZ', 49), ('SMXACEgLtEveWt', 44), ('IjdUXIdbhtudV', 39), ('FYmhsqAUZln', 27), ('TFUgHXUNfbdDifqnf', 15)]) == ('sbiFsIvPTh oMZ', 49)
    assert candidate([('wJtPFflsRUsX', 46), ('HFWoyezhxax', 51), ('edNVzmRfjcHSYT', 42), ('igjZqzlJz', 18), ('boAUgfreHz', 14)]) == ('HFWoyezhxax', 51)
    assert candidate([('biiPILDzwkzQOH', 49), ('CIoUlfpTsANksnS', 53), ('EViBZsGQyWM', 37), ('HqyJnvgglEzB', 26), ('EqZIEUxTonWV', 11)]) == ('CIoUlfpTsANksnS', 53)
    assert candidate([('DDYdsi', 49), ('HHhPzXNWWIV R', 48), ('WknbgzKApLjKcB', 39), ('GWZUYKWlvv ykk', 27), ('TMyFrjwe dPdADWYD', 14)]) == ('DDYdsi', 49)
    assert candidate([('qlQYEDZMFZVWMa', 49), ('LObMiAjZNBguyFZ', 50), ('tuyZMFkhiwXxQnRIY', 40), ('GozKzjrS', 25), ('EbYDuhccq ', 11)]) == ('LObMiAjZNBguyFZ', 50)
    assert candidate([('LQLtKOCEiNyVuW', 10), ('VCdhYRTsMMljAgTvt', 16), ('JZpyZBd Ggd', 27), ('pVSArmrB', 37), ('CSWYyBAveIAOz', 52)]) == ('CSWYyBAveIAOz', 52)
    assert candidate([('edwmlEXsCmA', 13), ('ykLIaRjsxp', 23), ('FqlnWbMqXM', 31), ('YFtOsEMc', 39), ('PRnzYJKVleHbGepW', 51)]) == ('PRnzYJKVleHbGepW', 51)
    assert candidate([('fSAXABnwaN teCg', 13), ('zfVFdVwRcRidUcYg', 25), ('EMhrcseck', 31), ('OgiWd uEgwWnwM', 45), ('bkde vgDKrougKd', 49)]) == ('bkde vgDKrougKd', 49)
    assert candidate([('jfP Kvqu', 5), ('AffNLSMlOc', 25), ('xrDecyYWzJHcEq', 28), ('DdxRTiuKf', 45), ('rGakHCLlGfDaKhciu', 46)]) == ('rGakHCLlGfDaKhciu', 46)
    assert candidate([('cwICCkuFid', 11), ('OZYroTmXjNyQ', 15), ('xsUNUCIVUgQH', 27), ('jgcotAIwsMgm', 42), ('LlBcSDlDaVp', 55)]) == ('LlBcSDlDaVp', 55)
    assert candidate([('Rf ubZefvpUuE', 14), ('ktvHggxlLItvpZ', 20), ('EDGbIAuAMoQjmN', 26), (' bPfhCL', 42), ('dkCHBHtVNwBD', 46)]) == ('dkCHBHtVNwBD', 46)
    assert candidate([('WpIYslFZDyGEnoT', 12), ('jpguwegfPYMUOAecp', 23), ('sakXnYCHbm', 27), ('jEdCCGDAZ', 42), ('mHbZtGgYOvzFpcOm', 51)]) == ('mHbZtGgYOvzFpcOm', 51)
    assert candidate([('tPMhLS', 6), ('YfbTpqNbF', 22), ('Ed lewOQEdGuCNsVNr', 32), ('usg RHHmOGUv', 36), ('frsVNBUpyD', 55)]) == ('frsVNBUpyD', 55)
    assert candidate([('nXcESUyYyRyB', 8), ('BsOexuIpbbYaiIjFE', 18), ('EjMsjtNMnT', 29), ('PrBtSLrUdQssKx', 39), ('QnjbLeLstcV', 49)]) == ('QnjbLeLstcV', 49)
    assert candidate([('UzhfgAOl', 6), ('ABRabpLOMFdVPIad', 22), ('TfkGpokaXuYAXNeZv', 29), ('fuGcCiZINAEXh', 40), ('vCGZvfNpFaP', 45)]) == ('vCGZvfNpFaP', 45)
    assert candidate([('pKIeAtnCxMPbvmh', 13), ('wbyYDtrezdtBi', 18), ('XASPGuUXxNgtiS', 26), ('MttOUJOS', 41), ('ZjdxcxXwJsfH', 47)]) == ('ZjdxcxXwJsfH', 47)
    assert candidate([('JommpC', 14), ('vtPMAVoQuUOUkJZ', 16), ('lBvWUsSNpgVEIbusqt', 26), ('voEqZH', 38), ('klOgMUTcygzHnM', 46)]) == ('klOgMUTcygzHnM', 46)
    assert candidate([('DzEF IPxMxV', 11), ('Zik TFdYIlxpjT', 18), ('AkanVBExbauZ', 33), ('MfRCKXWVmqftOxV', 36), (' TfryXdUdkQQbARF', 45)]) == (' TfryXdUdkQQbARF', 45)
    assert candidate([('otChZJdg', 15), ('LZshRahPwqKaBK y', 20), ('ovlmUOlXyqN', 28), ('LDwCPkktPVZlH', 38), ('eoHfSWgGDODCHelwNU', 47)]) == ('eoHfSWgGDODCHelwNU', 47)
    assert candidate([('MB UTYbKwRm', 13), ('BfpfkFpVWCtxnOTXhy', 21), ('IsGzIqnyudBKjL', 32), ('RkzZMTBXy', 43), ('pZuUdIAWYICX', 45)]) == ('pZuUdIAWYICX', 45)
    assert candidate([('sYUEnZlMz', 6), ('TlcWEurgXmHrn', 23), ('uxsW pWgNbICrS', 29), ('wchBpNDBMvxt', 38), ('fQTyCZzRCXnlCmjN', 47)]) == ('fQTyCZzRCXnlCmjN', 47)
    assert candidate([('NETSjEj', 6), ('iPcZGZOwtqQiL', 17), ('GKdOxNzbs', 35), ('QgxonbXMkrR', 41), ('kipqFwMNfga', 47)]) == ('kipqFwMNfga', 47)
    assert candidate([('DRrVuo', 11), ('LcXulAovJu', 18), ('RkUSRicoHdXzUByk', 25), ('BnggqjiMhO', 43), ('iZwwnRfp UsRNAWItw', 46)]) == ('iZwwnRfp UsRNAWItw', 46)
    assert candidate([('usMGUtIqQrOhAyt', 15), ('YvOmWNBLR s', 20), ('BVjNej aBpm', 33), ('arubSYORrNRmKUA', 43), ('xYVmcAs oolx WWAhw', 54)]) == ('xYVmcAs oolx WWAhw', 54)
    assert candidate([('QCnJfYPFy', 14), ('NNXEYoSJdFYyHp', 16), ('VQtegrkBBDDMqUiy', 30), ('roZxoqhxboMhurQ', 39), ('ugtbsSomEta', 47)]) == ('ugtbsSomEta', 47)
    assert candidate([('aOKVJrYQvVAYuYt', 7), ('rIubvBOYUO', 17), ('LLkeuHceRdseQ', 29), ('Fd VVJffcIokerA', 40), ('UqkCyljjFIXpCjR', 55)]) == ('UqkCyljjFIXpCjR', 55)
    assert candidate([('EpHTnIBzocCZYm', 9), ('OfPdOsgMmMQAYdOo D', 19), ('jeGAvbDHuPiQGKtFFt', 34), ('pciEoYueVn', 37), ('OSMJpRIdos', 49)]) == ('OSMJpRIdos', 49)
    assert candidate([('hMDIpOSi vmajId', 13), ('abQdXhJzxHmmJQ', 17), ('EIkGjiqEvEEMWssY', 30), ('muUfWzxdDxemtZ', 35), ('yNdPnPIaSdHCJUdIkQ', 49)]) == ('yNdPnPIaSdHCJUdIkQ', 49)
    assert candidate([('ngDzR AFshoFrD', 6), ('FLnjMDZoHdKtr tMrn', 23), ('mISHaasDdYBGDSpUh', 25), ('elDtVAevTpl', 36), ('HqIXKHmgKuXHBDtwA', 51)]) == ('HqIXKHmgKuXHBDtwA', 51)
    assert candidate([('TrrLPXSbwfrN', 10), ('LarCMzhlWaNa', 18), ('JuZqHOqAbmJMxKYw', 35), ('nEfiahKMGseFB', 36), ('SinEQfRXGcJYwxMsX', 49)]) == ('SinEQfRXGcJYwxMsX', 49)
    assert candidate([('OLHeiOrKQWADZ', 11), ('KruWhOjaqnqM q', 18), ('iwjEjQaGUmy', 28), ('HfZblqHtqDT x', 37), ('iCRlLLJloItiUM', 45)]) == ('iCRlLLJloItiUM', 45)
    assert candidate([('dBekNRhtZea', 13), ('yggfKJHUpnHxbMpyI', 17), ('PHuTmDOwNmiiEMJPq', 27), ('MrNgYNVhcD', 35), ('odsxMCmMRTpgt', 46)]) == ('odsxMCmMRTpgt', 46)
    assert candidate([('LbWXdXz', 7), (' HXhOygXlm b', 19), ('JSjyptGALr', 25), ('UEPDmF', 42), ('GE qvTQfGUEFsUPK', 53)]) == ('GE qvTQfGUEFsUPK', 53)
    assert candidate([('OFcCXxsKWENXhFN', 8), ('UjaXRUdFxqn', 16), ('saYgHqfeVylEUQ', 33), ('LOLLWQadqJ', 42), ('bhOVMCGOl', 54)]) == ('bhOVMCGOl', 54)
    assert candidate([('vdNfhi', 13), ('tXBxQbubdi', 23), ('LdqJSLIQaQgWKgXTp', 32), ('celcsjLlhrNoZpp', 42), ('UHKxqyOF ', 49)]) == ('UHKxqyOF ', 49)
    assert candidate([('VXIgiBUane', 9), ('qVcj ZctOOgShwPL', 16), ('YvuxCWwAuayAYZNqRu', 28), ('AlaazyZ', 38), ('CfUgXpGRLT', 55)]) == ('CfUgXpGRLT', 55)
    assert candidate([('HRDbD At', 9), ('VdnvmiiPrB', 25), ('UmzMMIUMWn', 31), ('LxRxOAf', 37), ('xMesASmYJ', 45)]) == ('xMesASmYJ', 45)
    assert candidate([('qWotHymnIwAKe', 11), ('XPIkNaAKIeIXYBDOK', 18), ('layvHtwTjM', 31), ('DcLQWhltMCOS', 39), ('zvTVKFlplDfBxCAN', 54)]) == ('zvTVKFlplDfBxCAN', 54)

if __name__ == '__main__':
    check(max_aggregate)