from case_MBPP_342 import text_match_wordz_middle


def check(candidate):
    assert candidate("pythonzabc.")==('Found a match!')
    assert candidate("xyzabc.")==('Found a match!')
    assert candidate("  lang  .")==('Not matched!')
    assert candidate("zloyfazw") == "Found a match!"
    assert candidate("a.jfqjo.ay") == "Not matched!"
    assert candidate("wphyflgvax.js") == "Not matched!"
    assert candidate("asdzamruji") == "Found a match!"
    assert candidate("xwm.h.vnjymdcy") == "Not matched!"
    assert candidate("qnhrhplwim") == "Not matched!"
    assert candidate("ufbvjlakkbeb.") == "Not matched!"
    assert candidate("lkupyn.dhz") == "Not matched!"
    assert candidate("qsvjrggiktknd") == "Not matched!"
    assert candidate("utdclt") == "Not matched!"
    assert candidate("kivcm.nkyzt") == "Found a match!"
    assert candidate("xzjtvkzi") == "Found a match!"
    assert candidate("d.kfprvk.ft") == "Not matched!"
    assert candidate("tpqgjhuzbxs") == "Found a match!"
    assert candidate("a.ju.mwgxpaf.f.") == "Not matched!"
    assert candidate("gguymr.bz") == "Not matched!"
    assert candidate("ougthh") == "Not matched!"
    assert candidate("xlvtinhcxdjv.") == "Not matched!"
    assert candidate("wkaptbldzxi") == "Found a match!"
    assert candidate(".k.acz") == "Not matched!"
    assert candidate("kykdiojsyumm") == "Not matched!"
    assert candidate("ozmwvrcqqigq") == "Found a match!"
    assert candidate("xpdpzqziwvoh") == "Found a match!"
    assert candidate("pihsfptygc.") == "Not matched!"
    assert candidate("cnwkty.jk.r.y") == "Not matched!"
    assert candidate("ystrnnmjzu") == "Found a match!"
    assert candidate("anykwdp") == "Not matched!"
    assert candidate("q.unnv") == "Not matched!"
    assert candidate("awpquhohwfkndm") == "Not matched!"
    assert candidate("ugklrzprk") == "Found a match!"
    assert candidate("oxoxen") == "Not matched!"
    assert candidate("zwziffzhw") == "Found a match!"
    assert candidate("kdghelysdh") == "Not matched!"
    assert candidate("izth") == "Found a match!"
    assert candidate("f.lis") == "Not matched!"
    assert candidate("ovsq") == "Not matched!"
    assert candidate("cllyieekr") == "Not matched!"
    assert candidate("v.glqlodxjt") == "Not matched!"
    assert candidate("l.btno") == "Not matched!"
    assert candidate("kwxykcuqh") == "Not matched!"
    assert candidate("qrbjuznu") == "Found a match!"
    assert candidate("dyoa") == "Not matched!"
    assert candidate(".midm") == "Not matched!"
    assert candidate("yzxkiigmr.") == "Found a match!"
    assert candidate("qaimznftjh") == "Found a match!"
    assert candidate("hwi") == "Not matched!"
    assert candidate("ssyhpktyfeuk") == "Not matched!"
    assert candidate("blwadycqij") == "Not matched!"
    assert candidate("onnfajjaqtnb") == "Not matched!"
    assert candidate("pamzzxzogbzx") == "Found a match!"
    assert candidate("yhkffieu") == "Not matched!"
    assert candidate("hcqvfh") == "Not matched!"
    assert candidate("qdecvappwky") == "Not matched!"
    assert candidate("mqty") == "Not matched!"
    assert candidate("endzjyrvsrz") == "Found a match!"
    assert candidate("tjjyvep") == "Not matched!"
    assert candidate("m.vhxxds") == "Not matched!"
    assert candidate("rvc.zxnhzzf") == "Found a match!"
    assert candidate("qxga") == "Not matched!"
    assert candidate("coa") == "Not matched!"
    assert candidate("qeeqfsglcr") == "Not matched!"
    assert candidate("kpxltd") == "Not matched!"
    assert candidate("wd.qhzev") == "Found a match!"
    assert candidate("jmnximi") == "Not matched!"
    assert candidate("bzxitqi") == "Found a match!"
    assert candidate("znfwvswkghg") == "Not matched!"
    assert candidate("ln.rexx") == "Not matched!"
    assert candidate("xfokqlig") == "Not matched!"
    assert candidate("lrthadqcdiak") == "Not matched!"
    assert candidate(" osrboag") == "Not matched!"
    assert candidate("cihxoodeqkgdt") == "Not matched!"
    assert candidate("agzlkniwyuhtao") == "Found a match!"
    assert candidate("xmic.jqiqvd.kax") == "Not matched!"
    assert candidate(".tqzzq") == "Found a match!"
    assert candidate("s.jk y icsljb") == "Not matched!"
    assert candidate("bsnq.tr.sgj ") == "Not matched!"
    assert candidate("uf.jpmt") == "Not matched!"
    assert candidate("if dwzirs") == "Found a match!"
    assert candidate("vfmoepbopsrs") == "Not matched!"
    assert candidate(" ubialxd.ppaih") == "Not matched!"
    assert candidate("pxjcavjb.k") == "Not matched!"
    assert candidate("bgrzmmvd.") == "Found a match!"
    assert candidate("ajgaqqqvvb") == "Not matched!"
    assert candidate("aythlh ubh") == "Not matched!"
    assert candidate("lslp.kgjgi") == "Not matched!"
    assert candidate("xhh gvkad") == "Not matched!"
    assert candidate("bfhqvidenw") == "Not matched!"
    assert candidate("qglwmyppzqakjad") == "Found a match!"
    assert candidate("yyrcst") == "Not matched!"
    assert candidate("pylmc.j") == "Not matched!"
    assert candidate("jbutwue") == "Not matched!"
    assert candidate("brzqr..xswjbjn") == "Found a match!"
    assert candidate(" ockukrkuzfz") == "Found a match!"
    assert candidate("gmvjzfrj.") == "Found a match!"
    assert candidate("hlrgimc") == "Not matched!"
    assert candidate("tbvchoqqrofsiw") == "Not matched!"
    assert candidate("wnncgnlfjx grlw") == "Not matched!"
    assert candidate("dvimpnqtmfdwax") == "Not matched!"
    assert candidate("qy rnx") == "Not matched!"

if __name__ == '__main__':
    check(text_match_wordz_middle)