from case_MBPP_050 import divisor


def check(candidate):
    assert candidate(15) == 4 
    assert candidate(12) == 6
    assert candidate(9) == 3
    assert candidate(11) == 2
    assert candidate(13) == 2
    assert candidate(12) == 6
    assert candidate(19) == 2
    assert candidate(15) == 4
    assert candidate(10) == 4
    assert candidate(14) == 4
    assert candidate(14) == 4
    assert candidate(13) == 2
    assert candidate(10) == 4
    assert candidate(16) == 5
    assert candidate(11) == 2
    assert candidate(20) == 6
    assert candidate(18) == 6
    assert candidate(14) == 4
    assert candidate(18) == 6
    assert candidate(10) == 4
    assert candidate(10) == 4
    assert candidate(17) == 2
    assert candidate(12) == 6
    assert candidate(16) == 5
    assert candidate(14) == 4
    assert candidate(16) == 5
    assert candidate(13) == 2
    assert candidate(20) == 6
    assert candidate(20) == 6
    assert candidate(19) == 2
    assert candidate(15) == 4
    assert candidate(11) == 2
    assert candidate(11) == 2
    assert candidate(13) == 2
    assert candidate(13) == 2
    assert candidate(19) == 2
    assert candidate(12) == 6
    assert candidate(8) == 4
    assert candidate(11) == 2
    assert candidate(13) == 2
    assert candidate(11) == 2
    assert candidate(10) == 4
    assert candidate(11) == 2
    assert candidate(12) == 6
    assert candidate(13) == 2
    assert candidate(17) == 2
    assert candidate(15) == 4
    assert candidate(14) == 4
    assert candidate(14) == 4
    assert candidate(9) == 3
    assert candidate(7) == 2
    assert candidate(15) == 4
    assert candidate(7) == 2
    assert candidate(9) == 3
    assert candidate(13) == 2
    assert candidate(7) == 2
    assert candidate(12) == 6
    assert candidate(15) == 4
    assert candidate(15) == 4
    assert candidate(14) == 4
    assert candidate(8) == 4
    assert candidate(11) == 2
    assert candidate(17) == 2
    assert candidate(9) == 3
    assert candidate(11) == 2
    assert candidate(9) == 3
    assert candidate(10) == 4
    assert candidate(15) == 4
    assert candidate(16) == 5
    assert candidate(8) == 4
    assert candidate(6) == 4
    assert candidate(14) == 4
    assert candidate(12) == 6
    assert candidate(9) == 3
    assert candidate(10) == 4
    assert candidate(10) == 4
    assert candidate(4) == 3
    assert candidate(10) == 4
    assert candidate(8) == 4
    assert candidate(13) == 2
    assert candidate(13) == 2
    assert candidate(4) == 3
    assert candidate(12) == 6
    assert candidate(14) == 4
    assert candidate(11) == 2
    assert candidate(13) == 2
    assert candidate(13) == 2
    assert candidate(4) == 3
    assert candidate(13) == 2
    assert candidate(5) == 2
    assert candidate(13) == 2
    assert candidate(11) == 2
    assert candidate(12) == 6
    assert candidate(12) == 6
    assert candidate(10) == 4
    assert candidate(7) == 2
    assert candidate(13) == 2
    assert candidate(6) == 4
    assert candidate(14) == 4
    assert candidate(11) == 2
    assert candidate(4) == 3
    assert candidate(8) == 4

if __name__ == '__main__':
    check(divisor)