from case_MBPP_015 import check


def check(candidate):
    assert candidate(70) == False
    assert candidate(23) == False
    assert candidate(73) == True
    assert candidate(68) == False
    assert candidate(73) == True
    assert candidate(69) == False
    assert candidate(68) == False
    assert candidate(67) == False
    assert candidate(74) == False
    assert candidate(68) == False
    assert candidate(71) == False
    assert candidate(66) == False
    assert candidate(67) == False
    assert candidate(65) == False
    assert candidate(72) == False
    assert candidate(72) == False
    assert candidate(74) == False
    assert candidate(67) == False
    assert candidate(68) == False
    assert candidate(70) == False
    assert candidate(71) == False
    assert candidate(74) == False
    assert candidate(67) == False
    assert candidate(66) == False
    assert candidate(73) == True
    assert candidate(66) == False
    assert candidate(65) == False
    assert candidate(72) == False
    assert candidate(65) == False
    assert candidate(75) == False
    assert candidate(72) == False
    assert candidate(70) == False
    assert candidate(68) == False
    assert candidate(75) == False
    assert candidate(72) == False
    assert candidate(71) == False
    assert candidate(24) == False
    assert candidate(22) == False
    assert candidate(18) == False
    assert candidate(26) == False
    assert candidate(25) == False
    assert candidate(21) == False
    assert candidate(18) == False
    assert candidate(26) == False
    assert candidate(20) == False
    assert candidate(26) == False
    assert candidate(25) == False
    assert candidate(28) == False
    assert candidate(28) == False
    assert candidate(28) == False
    assert candidate(22) == False
    assert candidate(24) == False
    assert candidate(20) == False
    assert candidate(25) == False
    assert candidate(23) == False
    assert candidate(19) == False
    assert candidate(25) == False
    assert candidate(19) == False
    assert candidate(18) == False
    assert candidate(23) == False
    assert candidate(28) == False
    assert candidate(27) == False
    assert candidate(22) == False
    assert candidate(19) == False
    assert candidate(23) == False
    assert candidate(24) == False
    assert candidate(18) == False
    assert candidate(19) == False
    assert candidate(24) == False
    assert candidate(72) == False
    assert candidate(72) == False
    assert candidate(74) == False
    assert candidate(74) == False
    assert candidate(70) == False
    assert candidate(72) == False
    assert candidate(74) == False
    assert candidate(74) == False
    assert candidate(75) == False
    assert candidate(70) == False
    assert candidate(74) == False
    assert candidate(69) == False
    assert candidate(70) == False
    assert candidate(68) == False
    assert candidate(72) == False
    assert candidate(71) == False
    assert candidate(70) == False
    assert candidate(72) == False
    assert candidate(71) == False
    assert candidate(74) == False
    assert candidate(72) == False
    assert candidate(73) == True
    assert candidate(71) == False
    assert candidate(74) == False
    assert candidate(70) == False
    assert candidate(77) == False
    assert candidate(78) == False
    assert candidate(76) == False
    assert candidate(74) == False
    assert candidate(75) == False
    assert candidate(73) == True
    assert candidate(71) == False
    assert candidate(70) == False

if __name__ == '__main__':
    check(check)