from case_MBPP_131 import count_Primes_nums


def check(candidate):
    assert candidate(5) == 2
    assert candidate(10) == 4
    assert candidate(100) == 25
    assert candidate(2) == 0
    assert candidate(3) == 1
    assert candidate(9) == 4
    assert candidate(5) == 2
    assert candidate(5) == 2
    assert candidate(7) == 3
    assert candidate(5) == 2
    assert candidate(5) == 2
    assert candidate(1) == 0
    assert candidate(5) == 2
    assert candidate(8) == 4
    assert candidate(1) == 0
    assert candidate(4) == 2
    assert candidate(6) == 3
    assert candidate(5) == 2
    assert candidate(8) == 4
    assert candidate(4) == 2
    assert candidate(7) == 3
    assert candidate(7) == 3
    assert candidate(8) == 4
    assert candidate(6) == 3
    assert candidate(9) == 4
    assert candidate(7) == 3
    assert candidate(5) == 2
    assert candidate(7) == 3
    assert candidate(3) == 1
    assert candidate(8) == 4
    assert candidate(3) == 1
    assert candidate(1) == 0
    assert candidate(4) == 2
    assert candidate(2) == 0
    assert candidate(8) == 4
    assert candidate(9) == 4
    assert candidate(6) == 3
    assert candidate(15) == 6
    assert candidate(11) == 4
    assert candidate(10) == 4
    assert candidate(14) == 6
    assert candidate(11) == 4
    assert candidate(13) == 5
    assert candidate(14) == 6
    assert candidate(12) == 5
    assert candidate(9) == 4
    assert candidate(13) == 5
    assert candidate(10) == 4
    assert candidate(9) == 4
    assert candidate(10) == 4
    assert candidate(6) == 3
    assert candidate(11) == 4
    assert candidate(6) == 3
    assert candidate(8) == 4
    assert candidate(15) == 6
    assert candidate(9) == 4
    assert candidate(11) == 4
    assert candidate(5) == 2
    assert candidate(10) == 4
    assert candidate(5) == 2
    assert candidate(14) == 6
    assert candidate(12) == 5
    assert candidate(8) == 4
    assert candidate(9) == 4
    assert candidate(14) == 6
    assert candidate(12) == 5
    assert candidate(12) == 5
    assert candidate(8) == 4
    assert candidate(5) == 2
    assert candidate(98) == 25
    assert candidate(99) == 25
    assert candidate(104) == 27
    assert candidate(101) == 25
    assert candidate(103) == 26
    assert candidate(100) == 25
    assert candidate(100) == 25
    assert candidate(103) == 26
    assert candidate(104) == 27
    assert candidate(97) == 24
    assert candidate(97) == 24
    assert candidate(100) == 25
    assert candidate(95) == 24
    assert candidate(95) == 24
    assert candidate(99) == 25
    assert candidate(96) == 24
    assert candidate(98) == 25
    assert candidate(101) == 25
    assert candidate(96) == 24
    assert candidate(102) == 26
    assert candidate(103) == 26
    assert candidate(105) == 27
    assert candidate(102) == 26
    assert candidate(97) == 24
    assert candidate(96) == 24
    assert candidate(101) == 25
    assert candidate(104) == 27
    assert candidate(104) == 27
    assert candidate(105) == 27
    assert candidate(95) == 24
    assert candidate(103) == 26
    assert candidate(104) == 27
    assert candidate(96) == 24

if __name__ == '__main__':
    check(count_Primes_nums)