from case_MBPP_330 import replace_spaces


def check(candidate):
    assert candidate("My Name is Dawood") == 'My%20Name%20is%20Dawood'
    assert candidate("I am a Programmer") == 'I%20am%20a%20Programmer'
    assert candidate("I love Coding") == 'I%20love%20Coding'
    assert candidate("Sg TiWFZDqJVrOsWj") == "Sg%20TiWFZDqJVrOsWj"
    assert candidate("NSbkMcCp DONTFjNVzZym") == "NSbkMcCp%20DONTFjNVzZym"
    assert candidate("AMuQLrarLfzAkXOcqs") == "AMuQLrarLfzAkXOcqs"
    assert candidate("NqHoBtOfZrvWkDEAUa") == "NqHoBtOfZrvWkDEAUa"
    assert candidate("ESSKPXITLNoLIZoeexXzi") == "ESSKPXITLNoLIZoeexXzi"
    assert candidate("BKXdfdyUvw PDkt") == "BKXdfdyUvw%20PDkt"
    assert candidate("veLkwhYfytGUtgzy") == "veLkwhYfytGUtgzy"
    assert candidate("wicwnnXoDejKJIQSr") == "wicwnnXoDejKJIQSr"
    assert candidate("RhTflnwloFMirifriEwE") == "RhTflnwloFMirifriEwE"
    assert candidate("bklE fyDDXeBUuaWgZbKz") == "bklE%20fyDDXeBUuaWgZbKz"
    assert candidate("zFpBTCTroSMCX IR") == "zFpBTCTroSMCX%20IR"
    assert candidate("mXMYVXaqjOirlWGVSEza") == "mXMYVXaqjOirlWGVSEza"
    assert candidate("fGOeEoIljUqjiZfMH") == "fGOeEoIljUqjiZfMH"
    assert candidate("qkvszrXTPgUMjESGHdIX") == "qkvszrXTPgUMjESGHdIX"
    assert candidate("twMmYIRWpxfxRTTLJPy ") == "twMmYIRWpxfxRTTLJPy"
    assert candidate("Z rTmQlhDZH LA") == "Z%20rTmQlhDZH%20LA"
    assert candidate("IITLRDqNYkBLTpge jbJ") == "IITLRDqNYkBLTpge%20jbJ"
    assert candidate("rjkbdzrPeLfEZiKS") == "rjkbdzrPeLfEZiKS"
    assert candidate("IoQqGgCQoGhHAwi ") == "IoQqGgCQoGhHAwi"
    assert candidate("UEeh TbmBuLPr") == "UEeh%20TbmBuLPr"
    assert candidate("UciB WkGfqqrtzxyH") == "UciB%20WkGfqqrtzxyH"
    assert candidate("YOfnidyIQndtBgTlqaGu") == "YOfnidyIQndtBgTlqaGu"
    assert candidate("yrMEvkzYqf zCX") == "yrMEvkzYqf%20zCX"
    assert candidate("WvQaDTynXs Zev") == "WvQaDTynXs%20Zev"
    assert candidate("TXbteXAgqiyaoNh") == "TXbteXAgqiyaoNh"
    assert candidate("iygJmTtcuW yBvhGmwfyh") == "iygJmTtcuW%20yBvhGmwfyh"
    assert candidate("uCaenCMp MIEC ErrQau") == "uCaenCMp%20MIEC%20ErrQau"
    assert candidate("gGrZiOBqkuzSizsr") == "gGrZiOBqkuzSizsr"
    assert candidate("ziHCpzakJPQaDq HZWW") == "ziHCpzakJPQaDq%20HZWW"
    assert candidate("oElEznYXoOEsZzS") == "oElEznYXoOEsZzS"
    assert candidate("OSpjjiWxi TTBfq") == "OSpjjiWxi%20TTBfq"
    assert candidate("ceFSEAMyAVdzDdXgA") == "ceFSEAMyAVdzDdXgA"
    assert candidate("xyKPmKDdBSYHRPWSPBi") == "xyKPmKDdBSYHRPWSPBi"
    assert candidate("cxii ShehaeSdAKaK") == "cxii%20ShehaeSdAKaK"
    assert candidate("WIWeTAqCpyyWVmrK") == "WIWeTAqCpyyWVmrK"
    assert candidate("llmSaR ahZgzT") == "llmSaR%20ahZgzT"
    assert candidate("jgFojsvLexqkPta") == "jgFojsvLexqkPta"
    assert candidate("BnDkqviCUJyFo") == "BnDkqviCUJyFo"
    assert candidate("RsqiIUlwNekVIyViLaIn") == "RsqiIUlwNekVIyViLaIn"
    assert candidate("YxjZaDlWRWnlrsWpefn") == "YxjZaDlWRWnlrsWpefn"
    assert candidate(" EApUUGzVrsMavpuxqkZG") == "EApUUGzVrsMavpuxqkZG"
    assert candidate("tKGfuAkPlfEeCNyWFat") == "tKGfuAkPlfEeCNyWFat"
    assert candidate("vlUgOmoMqGqwnB") == "vlUgOmoMqGqwnB"
    assert candidate("nIZyYewwQWpwBXTHuVY") == "nIZyYewwQWpwBXTHuVY"
    assert candidate("pqqOlNNSifXW") == "pqqOlNNSifXW"
    assert candidate("gUIEontGtiSwmldFEuIK") == "gUIEontGtiSwmldFEuIK"
    assert candidate("WIXiwGiQVEkGLCOWHba") == "WIXiwGiQVEkGLCOWHba"
    assert candidate("uNFCMQFNaPhgBBls") == "uNFCMQFNaPhgBBls"
    assert candidate("Cdlny  bfgKD") == "Cdlny%20%20bfgKD"
    assert candidate("jBBfWijVJrCvztdqjbTl") == "jBBfWijVJrCvztdqjbTl"
    assert candidate("OKAPsQawnHUHOnSSLSfED") == "OKAPsQawnHUHOnSSLSfED"
    assert candidate("DLVDxQZtkBEds") == "DLVDxQZtkBEds"
    assert candidate("vsZTUyOzaOjWCkdYlsO") == "vsZTUyOzaOjWCkdYlsO"
    assert candidate("  RHofIesaut") == "RHofIesaut"
    assert candidate("AKFrJLkmuxxpbiBOYlt") == "AKFrJLkmuxxpbiBOYlt"
    assert candidate("cCChbewCMvzWU") == "cCChbewCMvzWU"
    assert candidate("DnALxlpQTALtNuoBO") == "DnALxlpQTALtNuoBO"
    assert candidate("ZCJggDDVQZpuCxVOi") == "ZCJggDDVQZpuCxVOi"
    assert candidate("svMTmFgtqruRihDWFN nC") == "svMTmFgtqruRihDWFN%20nC"
    assert candidate("d RzrEXQgpavOY") == "d%20RzrEXQgpavOY"
    assert candidate("FNuoliGblZMTuB") == "FNuoliGblZMTuB"
    assert candidate("xCRhoYQIDOEez T") == "xCRhoYQIDOEez%20T"
    assert candidate("QNLLpZXhxSMMtL") == "QNLLpZXhxSMMtL"
    assert candidate("nxJArAZUIkVxslrB") == "nxJArAZUIkVxslrB"
    assert candidate("ocdOImDi NNJPFJNsdPG") == "ocdOImDi%20NNJPFJNsdPG"
    assert candidate("cHMxDGLUhyQsOSfsGBihd") == "cHMxDGLUhyQsOSfsGBihd"
    assert candidate("OZDMVoOwkWNqMCjqBo") == "OZDMVoOwkWNqMCjqBo"
    assert candidate(" pFgv CvKHAd") == "pFgv%20CvKHAd"
    assert candidate("nfchbJzqZ") == "nfchbJzqZ"
    assert candidate("iXmJLLheEBqb") == "iXmJLLheEBqb"
    assert candidate("YWZQOuyzOzfhs") == "YWZQOuyzOzfhs"
    assert candidate("EcurdqZRmVB") == "EcurdqZRmVB"
    assert candidate("nNHdrvLUvFYXzzwv") == "nNHdrvLUvFYXzzwv"
    assert candidate("rWyLcslRGqB") == "rWyLcslRGqB"
    assert candidate("OkSdaxXdoqQ k") == "OkSdaxXdoqQ%20k"
    assert candidate("CeFPOFuUsRfcsBOZ") == "CeFPOFuUsRfcsBOZ"
    assert candidate("PnVLIyFUQbyUWwSW") == "PnVLIyFUQbyUWwSW"
    assert candidate("DLZegttCPQQRw") == "DLZegttCPQQRw"
    assert candidate("uDPHrLKyyOpxRs") == "uDPHrLKyyOpxRs"
    assert candidate("zwfzsCBMsc") == "zwfzsCBMsc"
    assert candidate("cLhLZVBLXR") == "cLhLZVBLXR"
    assert candidate("IdtWPzqjIGiH") == "IdtWPzqjIGiH"
    assert candidate("atIzu gQwLIZ") == "atIzu%20gQwLIZ"
    assert candidate("AQPErLtIUVQ") == "AQPErLtIUVQ"
    assert candidate("WmXZTeuTncxJYvM") == "WmXZTeuTncxJYvM"
    assert candidate("OLTLaCzEQqQlorhnz") == "OLTLaCzEQqQlorhnz"
    assert candidate("yhffqqMIUifU") == "yhffqqMIUifU"
    assert candidate("EmlfvXxowO") == "EmlfvXxowO"
    assert candidate("ThqXtUsbOzILi") == "ThqXtUsbOzILi"
    assert candidate("IHxPjdBMnTjLn") == "IHxPjdBMnTjLn"
    assert candidate("YtjrQPjmzUfXWp") == "YtjrQPjmzUfXWp"
    assert candidate("ZBeFYmLsNAnmRBgJ") == "ZBeFYmLsNAnmRBgJ"
    assert candidate("sHttoIAnP") == "sHttoIAnP"
    assert candidate("iHXRRxjcpx") == "iHXRRxjcpx"
    assert candidate("uJWYIJcDNHLcGAZRrQ") == "uJWYIJcDNHLcGAZRrQ"
    assert candidate("QkgdfGWRqsVIpfjFq") == "QkgdfGWRqsVIpfjFq"
    assert candidate("VYzJOJaabryypinwl") == "VYzJOJaabryypinwl"
    assert candidate("ylMlxLFsCHolPnTRH") == "ylMlxLFsCHolPnTRH"
    assert candidate("hPdSfvTkUBcjT") == "hPdSfvTkUBcjT"

if __name__ == '__main__':
    check(replace_spaces)