from case_MBPP_423 import max_run_uppercase


def check(candidate):
    assert candidate('GeMKSForGERksISBESt') == 5
    assert candidate('PrECIOusMOVemENTSYT') == 6
    assert candidate('GooGLEFluTTER') == 4
    assert candidate("gZaCFkrHNVqFtgOejMNBD") == 4
    assert candidate("YwbacUeVJAlPlwg") == 0
    assert candidate("goFZYmSbnggdSszolygm") == 0
    assert candidate("eybNLodecJqoyFUPEzgXRys") == 0
    assert candidate("kXqyPwYzYibgEtdZHmnlwOVG") == 3
    assert candidate("lmLpTeCYsjTpwfXB") == 2
    assert candidate("oLjKOXfLRDeOIYZnNBcoi") == 0
    assert candidate("GOxamDmGyaYzfBJXRnhcvGT") == 2
    assert candidate("LfPMRIcvaNhMjoS") == 1
    assert candidate("ulkgLPJLaayZTNzvCMUWmqhm") == 0
    assert candidate("RXOElAzPySKcDUn") == 2
    assert candidate("NmHePauRgBomaAcBZVsCh") == 1
    assert candidate("TSeJJMSaqHyQUWm") == 3
    assert candidate("VktGManHaMImCye") == 0
    assert candidate("jsaUCUTjdlyIwxIkDA") == 2
    assert candidate("ogeTnfiLwoagoJc") == 1
    assert candidate("bSnRDupsRpaaxArmROjXmVuc") == 0
    assert candidate("JXpqVqRzpJDWbMNGX") == 4
    assert candidate("EPjKCyHKrtxbdaDjL") == 1
    assert candidate("PyQyQDvdLOiaRhTySw") == 1
    assert candidate("GLUkdlvTSCowGZIKz") == 4
    assert candidate("NlWqqGAXnGizfaVTicrEHG") == 3
    assert candidate("RdgTOTPYzNxUHxyCpPtJIpDO") == 2
    assert candidate("zQAOVQFTqDjiEFgE") == 1
    assert candidate("xwMbsMbQKWLEyaZrPO") == 2
    assert candidate("DtUvhgbydtEYlXAor") == 0
    assert candidate("vXEbETlAiPwoUbu") == 0
    assert candidate("urYCLeqpZQajTlp") == 0
    assert candidate("MdpJknbiIeZGNGF") == 5
    assert candidate("lUXfMkfChPTLJjaKunxsgxh") == 0
    assert candidate("hYbClkJBImtBhABDmsKrJcgf") == 0
    assert candidate("RwkYuOLFCGkfETJAbbUqNMU") == 3
    assert candidate("XfRJgvDquwMxhvVNguntZmt") == 0
    assert candidate("psRdeEaXeVfWClzCsJzLl") == 1
    assert candidate("EfBxHKLktMhvzTkzgDUP") == 3
    assert candidate("whAFtwYldMhIdsfyPk") == 1
    assert candidate("qwxsWEeapEmnniDcxd") == 0
    assert candidate("IVWiysrBwTjPYBlkAsOy") == 1
    assert candidate("cwOgRfBgfgJUIWedKnOW") == 2
    assert candidate("arLnfmfmpxGmGUBKIp") == 5
    assert candidate("ZTOffOyEJUEfBaUDZiE") == 1
    assert candidate("wwFoqGZIujuZUYzMAO") == 3
    assert candidate("rXDRRNjtZqTQSPXorzRbHR") == 2
    assert candidate("iTgACBGdtLBPHdZKgV") == 1
    assert candidate("wsTpGsuNFyjRUoLAcZkf") == 0
    assert candidate("LnHeCeNnRIZnpnABxNCKM") == 4
    assert candidate("uKEjdWzbSQZxBKdpq") == 0
    assert candidate("vMbWiFvvClpvIbJiTiez") == 0
    assert candidate("JzsPRdZOdSOsFKJLJWtZQtR") == 1
    assert candidate("PEKbgajQhXyPPiKqkBMJ") == 3
    assert candidate("MqkIFwSFisXasYypi") == 0
    assert candidate("JRWQGrInSkFhNMVHJkcCy") == 1
    assert candidate("XluLAhkLWdJoZIbMB") == 2
    assert candidate("DBrXUhUTDwhrKKcjz") == 0
    assert candidate("hKklXMcPGCKNfdtGlQm") == 1
    assert candidate("LNKCHIcjRTnArcOjHVmaRF") == 2
    assert candidate("AlLtlDlVSzcLJosCqcn") == 0
    assert candidate("kOWUQhvYfjLYVPrqA") == 1
    assert candidate("XMCYpnPhOFtxOvmZHdis") == 0
    assert candidate("uqQDeilAgvATzGqL") == 1
    assert candidate("lVqyRJVpITNhIdhJzqkQUCP") == 4
    assert candidate("HsWmciTOcEntMpP") == 1
    assert candidate("FnZzpAZPkQjQYfToxhQyKCv") == 2
    assert candidate("mgDzZpsXBLoYETLwRhk") == 0
    assert candidate("trZXOtdsvtWcJEfujJ") == 1
    assert candidate("jDMiZwaUaAQjnCeFzC") == 1
    assert candidate("YApansafq") == 0
    assert candidate("eCSBCVaOXmaSZI") == 3
    assert candidate("vwxfGGenVztb") == 0
    assert candidate("hTtyaKRGjRSseJlXFh") == 2
    assert candidate("qgtSDrbScIij") == 0
    assert candidate("dQYTNKjXV") == 2
    assert candidate("PkoXGXKYyNaLMm") == 2
    assert candidate("BIAUxNgcV") == 1
    assert candidate("OyxoOzbuPvGs") == 1
    assert candidate("LTMpKicWUPMoaVM") == 2
    assert candidate("XLjIXKEXMUFW") == 9
    assert candidate("NZtSjOYIsyNxGf") == 1
    assert candidate("BjNAgbuTuaZkrtCUsX") == 1
    assert candidate("FMXyssbDdPwx") == 0
    assert candidate("jgcNufPBLdlWSRV") == 4
    assert candidate("EPCPuSWmnqUqNdd") == 0
    assert candidate("shMtrcAISTDIlg") == 0
    assert candidate("zSjsQwXuIItrY") == 1
    assert candidate("mujrwPwZQ") == 2
    assert candidate("sKkeQnNKUP") == 4
    assert candidate("fxXVXCiRh") == 1
    assert candidate("JFcRzPEli") == 0
    assert candidate("OQSPdoYcyvdIxpwHl") == 1
    assert candidate("hICcbfFNdxOxztNEv") == 2
    assert candidate("BeCRVyhBiKawS") == 1
    assert candidate("wwzsLFrAqDvxdPmJl") == 1
    assert candidate("itWVdrJlWdryrwgkEj") == 1
    assert candidate("jLjywZJgBABmTyhr") == 0
    assert candidate("FgkvwQHWUNcLVnVeUC") == 2
    assert candidate("VclBbKIJy") == 3
    assert candidate("gYBjRBigkSVx") == 2
    assert candidate("oMHBjPUunK") == 1
    assert candidate("MVqkCETqoFKiP") == 1

if __name__ == '__main__':
    check(max_run_uppercase)