from case_MBPP_184 import get_max_sum 


def check(candidate):
    assert get_max_sum(60) == 106
    assert get_max_sum(10) == 12
    assert get_max_sum(2) == 2
    assert get_max_sum(57) == 90
    assert get_max_sum(62) == 106
    assert get_max_sum(62) == 106
    assert get_max_sum(61) == 106
    assert get_max_sum(55) == 90
    assert get_max_sum(59) == 90
    assert get_max_sum(60) == 106
    assert get_max_sum(63) == 106
    assert get_max_sum(57) == 90
    assert get_max_sum(64) == 114
    assert get_max_sum(55) == 90
    assert get_max_sum(59) == 90
    assert get_max_sum(63) == 106
    assert get_max_sum(65) == 114
    assert get_max_sum(62) == 106
    assert get_max_sum(60) == 106
    assert get_max_sum(56) == 90
    assert get_max_sum(58) == 90
    assert get_max_sum(59) == 90
    assert get_max_sum(58) == 90
    assert get_max_sum(57) == 90
    assert get_max_sum(56) == 90
    assert get_max_sum(56) == 90
    assert get_max_sum(63) == 106
    assert get_max_sum(62) == 106
    assert get_max_sum(64) == 114
    assert get_max_sum(58) == 90
    assert get_max_sum(59) == 90
    assert get_max_sum(63) == 106
    assert get_max_sum(63) == 106
    assert get_max_sum(60) == 106
    assert get_max_sum(65) == 114
    assert get_max_sum(58) == 90
    assert get_max_sum(11) == 12
    assert get_max_sum(15) == 18
    assert get_max_sum(10) == 12
    assert get_max_sum(7) == 7
    assert get_max_sum(15) == 18
    assert get_max_sum(6) == 7
    assert get_max_sum(10) == 12
    assert get_max_sum(10) == 12
    assert get_max_sum(11) == 12
    assert get_max_sum(6) == 7
    assert get_max_sum(8) == 9
    assert get_max_sum(15) == 18
    assert get_max_sum(10) == 12
    assert get_max_sum(11) == 12
    assert get_max_sum(11) == 12
    assert get_max_sum(9) == 10
    assert get_max_sum(9) == 10
    assert get_max_sum(5) == 5
    assert get_max_sum(7) == 7
    assert get_max_sum(13) == 16
    assert get_max_sum(6) == 7
    assert get_max_sum(6) == 7
    assert get_max_sum(5) == 5
    assert get_max_sum(13) == 16
    assert get_max_sum(8) == 9
    assert get_max_sum(15) == 18
    assert get_max_sum(15) == 18
    assert get_max_sum(11) == 12
    assert get_max_sum(5) == 5
    assert get_max_sum(14) == 16
    assert get_max_sum(10) == 12
    assert get_max_sum(12) == 16
    assert get_max_sum(5) == 5
    assert get_max_sum(2) == 2
    assert get_max_sum(5) == 5
    assert get_max_sum(1) == 1
    assert get_max_sum(5) == 5
    assert get_max_sum(1) == 1
    assert get_max_sum(4) == 4
    assert get_max_sum(2) == 2
    assert get_max_sum(4) == 4
    assert get_max_sum(6) == 7
    assert get_max_sum(6) == 7
    assert get_max_sum(4) == 4
    assert get_max_sum(4) == 4
    assert get_max_sum(2) == 2
    assert get_max_sum(7) == 7
    assert get_max_sum(1) == 1
    assert get_max_sum(2) == 2
    assert get_max_sum(6) == 7
    assert get_max_sum(2) == 2
    assert get_max_sum(5) == 5
    assert get_max_sum(7) == 7
    assert get_max_sum(5) == 5
    assert get_max_sum(3) == 3
    assert get_max_sum(3) == 3
    assert get_max_sum(6) == 7
    assert get_max_sum(7) == 7
    assert get_max_sum(2) == 2
    assert get_max_sum(7) == 7
    assert get_max_sum(3) == 3
    assert get_max_sum(4) == 4
    assert get_max_sum(2) == 2
    assert get_max_sum(3) == 3
    assert get_max_sum(3) == 3
    assert get_max_sum(1) == 1

if __name__ == '__main__':
    check(get_max_sum )