from case_MBPP_363 import all_Characters_Same


def check(candidate):
    assert candidate("python") == False
    assert candidate("aaa") == True
    assert candidate("data") == False
    assert candidate("fksdsovxraz") == False
    assert candidate("rvnqyggw") == False
    assert candidate("ghvfsuywfn") == False
    assert candidate("btzwwgtedm") == False
    assert candidate("edlfwrvgc") == False
    assert candidate("dlhsj") == False
    assert candidate("kxsejrswz") == False
    assert candidate("qzmolhtpt") == False
    assert candidate("chxiilsnflqk") == False
    assert candidate("yaqtzpfkbikc") == False
    assert candidate("gkt") == False
    assert candidate("tjbloxrmne") == False
    assert candidate("jngwg") == False
    assert candidate("toyu") == False
    assert candidate("cmymzbm") == False
    assert candidate("lhzpfjqlu") == False
    assert candidate("xivtdcfylb") == False
    assert candidate("razzhr") == False
    assert candidate("ukhdxjqizgnn") == False
    assert candidate("eesbwiqcmnlh") == False
    assert candidate("lbdbfezzyyb") == False
    assert candidate("hnvyblpyik") == False
    assert candidate("doybe") == False
    assert candidate("gyfdvsqbu") == False
    assert candidate("vcudaglb") == False
    assert candidate("okejnknzs") == False
    assert candidate("ucpuvytvkm") == False
    assert candidate("but") == False
    assert candidate("tdin") == False
    assert candidate("vco") == False
    assert candidate("nizkvqcrow") == False
    assert candidate("zfvitxtawolw") == False
    assert candidate("auodvpcjdhfz") == False
    assert candidate("nxzoqyfv") == False
    assert candidate("ueqzlfmg") == False
    assert candidate("ecfa") == False
    assert candidate("ppai") == False
    assert candidate("oovi") == False
    assert candidate("vhoqmxft") == False
    assert candidate("jugfsiizw") == False
    assert candidate("fopyf") == False
    assert candidate("aop") == False
    assert candidate("odudze") == False
    assert candidate("itlgufm") == False
    assert candidate("cblj") == False
    assert candidate("jezjr") == False
    assert candidate("jencdknrt") == False
    assert candidate("mzuzfmd") == False
    assert candidate("tqrfgne") == False
    assert candidate("rdtfyjpd") == False
    assert candidate("qgz") == False
    assert candidate("bna") == False
    assert candidate("yjvig") == False
    assert candidate("bzbry") == False
    assert candidate("xyqyo") == False
    assert candidate("mtawxwfr") == False
    assert candidate("emfm") == False
    assert candidate("giiwd") == False
    assert candidate("yvncxg") == False
    assert candidate("kycrssu") == False
    assert candidate("pbuiijg") == False
    assert candidate("szxqau") == False
    assert candidate("lmrfh") == False
    assert candidate("fbyreme") == False
    assert candidate("gytnxi") == False
    assert candidate("qybhz") == False
    assert candidate("hvqupxdp") == False
    assert candidate("swmysfbb") == False
    assert candidate("vxg") == False
    assert candidate("pxexdfgb") == False
    assert candidate("irftv") == False
    assert candidate("uzs") == False
    assert candidate("sacee") == False
    assert candidate("jly") == False
    assert candidate("qth") == False
    assert candidate("yhrsvfhm") == False
    assert candidate("njeqimpu") == False
    assert candidate("woo") == False
    assert candidate("pea") == False
    assert candidate("gxoq") == False
    assert candidate("nlzywycgc") == False
    assert candidate("bxdhekreg") == False
    assert candidate("kqhxovb") == False
    assert candidate("ofwf") == False
    assert candidate("xbimdpy") == False
    assert candidate("xxzauq") == False
    assert candidate("ylabxujyd") == False
    assert candidate("ypqx") == False
    assert candidate("bxx") == False
    assert candidate("ycmhjsped") == False
    assert candidate("ppeg") == False
    assert candidate("mnzfcrtx") == False
    assert candidate("wcppta") == False
    assert candidate("xktmbe") == False
    assert candidate("tnvmr") == False
    assert candidate("gapodndcp") == False
    assert candidate("fiz") == False
    assert candidate("ufghjrdqa") == False
    assert candidate("lzytv") == False

if __name__ == '__main__':
    check(all_Characters_Same)