from case_MBPP_006 import find_Rotations


def check(candidate):
    assert candidate("aaaa") == 1
    assert candidate("ab") == 2
    assert candidate("abc") == 3
    assert candidate("kcwa") == 4
    assert candidate("ezxpedrz") == 8
    assert candidate("fgluxhtza") == 9
    assert candidate("mjoaexpfz") == 9
    assert candidate("linyxx") == 6
    assert candidate("pay") == 3
    assert candidate("rxmc") == 4
    assert candidate("qkkjahy") == 7
    assert candidate("slcswzxu") == 8
    assert candidate("zoiy") == 4
    assert candidate("rhjaux") == 6
    assert candidate("fkjfimi") == 7
    assert candidate("pbkflfnd") == 8
    assert candidate("rthqixv") == 7
    assert candidate("rej") == 3
    assert candidate("ifhbywu") == 7
    assert candidate("oost") == 4
    assert candidate("nxwjjwsas") == 9
    assert candidate("moockefg") == 8
    assert candidate("qqydevz") == 7
    assert candidate("wwivmp") == 6
    assert candidate("togvvenfp") == 9
    assert candidate("oolvpej") == 7
    assert candidate("tzegpv") == 6
    assert candidate("beahzutke") == 9
    assert candidate("xzwepkip") == 8
    assert candidate("sis") == 3
    assert candidate("qtbflguk") == 8
    assert candidate("jam") == 3
    assert candidate("gqbzuvv") == 7
    assert candidate("abvgipdym") == 9
    assert candidate("ttff") == 4
    assert candidate("jjeu") == 4
    assert candidate("rphw") == 4
    assert candidate("nbgwgz") == 6
    assert candidate("setbdn") == 6
    assert candidate("pscwbl") == 6
    assert candidate("flgboo") == 6
    assert candidate("bfxpdk") == 6
    assert candidate("mofei") == 5
    assert candidate("qyr") == 3
    assert candidate("uxk") == 3
    assert candidate("nbmy") == 4
    assert candidate("ege") == 3
    assert candidate("usoriq") == 6
    assert candidate("wjuwlt") == 6
    assert candidate("bnodui") == 6
    assert candidate("aevvqf") == 6
    assert candidate("iaktug") == 6
    assert candidate("vhufs") == 5
    assert candidate("hiat") == 4
    assert candidate("mzaym") == 5
    assert candidate("xnlqu") == 5
    assert candidate("zqdb") == 4
    assert candidate("flq") == 3
    assert candidate("oar") == 3
    assert candidate("fezfrb") == 6
    assert candidate("ipszr") == 5
    assert candidate("edyr") == 4
    assert candidate("nve") == 3
    assert candidate("yti") == 3
    assert candidate("bmfvr") == 5
    assert candidate("psafv") == 5
    assert candidate("zlhtd") == 5
    assert candidate("pacp") == 4
    assert candidate("qhgsk") == 5
    assert candidate("eyde") == 4
    assert candidate("eyv") == 3
    assert candidate("dxbgtvxq") == 8
    assert candidate("mfdx") == 4
    assert candidate("xask") == 4
    assert candidate("qddp") == 4
    assert candidate("oas") == 3
    assert candidate("fjilakl") == 7
    assert candidate("xwdsk") == 5
    assert candidate("owqgr") == 5
    assert candidate("lxv") == 3
    assert candidate("bxbb") == 4
    assert candidate("jbfisms") == 7
    assert candidate("zqupo") == 5
    assert candidate("qye") == 3
    assert candidate("hhxosqlg") == 8
    assert candidate("zhb") == 3
    assert candidate("iwkj") == 4
    assert candidate("maen") == 4
    assert candidate("lsliyhze") == 8
    assert candidate("doocsri") == 7
    assert candidate("cjc") == 3
    assert candidate("avi") == 3
    assert candidate("rfit") == 4
    assert candidate("tlgffvv") == 7
    assert candidate("vlk") == 3
    assert candidate("ljeftwkpr") == 9
    assert candidate("itzso") == 5
    assert candidate("zxfscko") == 7
    assert candidate("ewzfvb") == 6
    assert candidate("wdk") == 3
    assert candidate("gmlivxfm") == 8
    assert candidate("yvsnt") == 5

if __name__ == '__main__':
    check(find_Rotations)