from case_MBPP_038 import sequence


def check(candidate):
    assert candidate(10) == 6
    assert candidate(2) == 1
    assert candidate(3) == 2
    assert candidate(13) == 8
    assert candidate(9) == 5
    assert candidate(13) == 8
    assert candidate(5) == 3
    assert candidate(7) == 4
    assert candidate(11) == 7
    assert candidate(8) == 4
    assert candidate(6) == 4
    assert candidate(12) == 7
    assert candidate(15) == 8
    assert candidate(13) == 8
    assert candidate(11) == 7
    assert candidate(6) == 4
    assert candidate(13) == 8
    assert candidate(13) == 8
    assert candidate(15) == 8
    assert candidate(13) == 8
    assert candidate(7) == 4
    assert candidate(10) == 6
    assert candidate(5) == 3
    assert candidate(15) == 8
    assert candidate(9) == 5
    assert candidate(10) == 6
    assert candidate(8) == 4
    assert candidate(8) == 4
    assert candidate(6) == 4
    assert candidate(11) == 7
    assert candidate(10) == 6
    assert candidate(7) == 4
    assert candidate(14) == 8
    assert candidate(10) == 6
    assert candidate(10) == 6
    assert candidate(6) == 4
    assert candidate(2) == 1
    assert candidate(1) == 1
    assert candidate(3) == 2
    assert candidate(5) == 3
    assert candidate(3) == 2
    assert candidate(5) == 3
    assert candidate(2) == 1
    assert candidate(1) == 1
    assert candidate(5) == 3
    assert candidate(7) == 4
    assert candidate(2) == 1
    assert candidate(7) == 4
    assert candidate(1) == 1
    assert candidate(3) == 2
    assert candidate(7) == 4
    assert candidate(6) == 4
    assert candidate(3) == 2
    assert candidate(5) == 3
    assert candidate(5) == 3
    assert candidate(5) == 3
    assert candidate(7) == 4
    assert candidate(1) == 1
    assert candidate(6) == 4
    assert candidate(5) == 3
    assert candidate(6) == 4
    assert candidate(5) == 3
    assert candidate(7) == 4
    assert candidate(4) == 2
    assert candidate(1) == 1
    assert candidate(2) == 1
    assert candidate(1) == 1
    assert candidate(1) == 1
    assert candidate(6) == 4
    assert candidate(3) == 2
    assert candidate(3) == 2
    assert candidate(6) == 4
    assert candidate(5) == 3
    assert candidate(3) == 2
    assert candidate(8) == 4
    assert candidate(7) == 4
    assert candidate(4) == 2
    assert candidate(3) == 2
    assert candidate(6) == 4
    assert candidate(5) == 3
    assert candidate(1) == 1
    assert candidate(3) == 2
    assert candidate(2) == 1
    assert candidate(2) == 1
    assert candidate(4) == 2
    assert candidate(5) == 3
    assert candidate(8) == 4
    assert candidate(3) == 2
    assert candidate(5) == 3
    assert candidate(4) == 2
    assert candidate(3) == 2
    assert candidate(2) == 1
    assert candidate(4) == 2
    assert candidate(7) == 4
    assert candidate(3) == 2
    assert candidate(5) == 3
    assert candidate(7) == 4
    assert candidate(6) == 4
    assert candidate(3) == 2
    assert candidate(7) == 4
    assert candidate(1) == 1
    assert candidate(7) == 4

if __name__ == '__main__':
    check(sequence)