from case_MBPP_378 import text_match_zero_one


def check(candidate):
    assert candidate("ac")==('Found a match!')
    assert candidate("dc")==('Not matched!')
    assert candidate("abbbba")==('Found a match!')
    assert candidate("wcw") == "Not matched!"
    assert candidate("jxn") == "Not matched!"
    assert candidate("pje") == "Not matched!"
    assert candidate("isgx") == "Not matched!"
    assert candidate("lppyn") == "Not matched!"
    assert candidate("bmzx") == "Not matched!"
    assert candidate("vbkf") == "Not matched!"
    assert candidate("uqwhcj") == "Not matched!"
    assert candidate("apgp") == "Found a match!"
    assert candidate("hnej") == "Not matched!"
    assert candidate("dawn") == "Found a match!"
    assert candidate("yniz") == "Not matched!"
    assert candidate("tgbsoj") == "Not matched!"
    assert candidate("uyj") == "Not matched!"
    assert candidate("dihup") == "Not matched!"
    assert candidate("ggkhsy") == "Not matched!"
    assert candidate("kcual") == "Found a match!"
    assert candidate("dywo") == "Not matched!"
    assert candidate("bqlj") == "Not matched!"
    assert candidate("yndy") == "Not matched!"
    assert candidate("trtj") == "Not matched!"
    assert candidate("rwjj") == "Not matched!"
    assert candidate("yew") == "Not matched!"
    assert candidate("rea") == "Found a match!"
    assert candidate("jyxgb") == "Not matched!"
    assert candidate("wavx") == "Found a match!"
    assert candidate("ipwo") == "Not matched!"
    assert candidate("czblf") == "Not matched!"
    assert candidate("jgdbsm") == "Not matched!"
    assert candidate("aeskm") == "Found a match!"
    assert candidate("ecr") == "Not matched!"
    assert candidate("johb") == "Not matched!"
    assert candidate("fniag") == "Found a match!"
    assert candidate("ufk") == "Not matched!"
    assert candidate("decr") == "Not matched!"
    assert candidate("bsbfuc") == "Not matched!"
    assert candidate("wfmjcf") == "Not matched!"
    assert candidate("soool") == "Not matched!"
    assert candidate("umf") == "Not matched!"
    assert candidate("kskxco") == "Not matched!"
    assert candidate("qvpmhe") == "Not matched!"
    assert candidate("nkcr") == "Not matched!"
    assert candidate("hmyqvk") == "Not matched!"
    assert candidate("lnbu") == "Not matched!"
    assert candidate("npfqbh") == "Not matched!"
    assert candidate("otaeb") == "Found a match!"
    assert candidate("bnb") == "Not matched!"
    assert candidate("wrr") == "Not matched!"
    assert candidate("www") == "Not matched!"
    assert candidate("dowu") == "Not matched!"
    assert candidate("vixk") == "Not matched!"
    assert candidate("icjcne") == "Not matched!"
    assert candidate("bzmzh") == "Not matched!"
    assert candidate("blhd") == "Not matched!"
    assert candidate("swt") == "Not matched!"
    assert candidate("mziz") == "Not matched!"
    assert candidate("qvne") == "Not matched!"
    assert candidate("gotmva") == "Found a match!"
    assert candidate("sdda") == "Found a match!"
    assert candidate("rfk") == "Not matched!"
    assert candidate("ywpo") == "Not matched!"
    assert candidate("zfhqno") == "Not matched!"
    assert candidate("eecjz") == "Not matched!"
    assert candidate("reguz") == "Not matched!"
    assert candidate("attp") == "Found a match!"
    assert candidate("ppx") == "Not matched!"
    assert candidate("deljwb") == "Not matched!"
    assert candidate("pkjut") == "Not matched!"
    assert candidate("ciasu") == "Found a match!"
    assert candidate("uksowe") == "Not matched!"
    assert candidate("nzhukdpcuwof") == "Not matched!"
    assert candidate("urnbzyyyv") == "Not matched!"
    assert candidate("eehrjzk") == "Not matched!"
    assert candidate("bydyetecm") == "Not matched!"
    assert candidate("cds") == "Not matched!"
    assert candidate("tsxjjlcsxep") == "Not matched!"
    assert candidate("odosnyohjruz") == "Not matched!"
    assert candidate("karyqwyioyr") == "Found a match!"
    assert candidate("ymq") == "Not matched!"
    assert candidate("skqcia") == "Found a match!"
    assert candidate("hgagzkxq") == "Found a match!"
    assert candidate("iwdrjauc") == "Found a match!"
    assert candidate("bkkdb") == "Not matched!"
    assert candidate("fikewuyvtvil") == "Not matched!"
    assert candidate("cfsyeeivpl") == "Not matched!"
    assert candidate("qqhhkccq") == "Not matched!"
    assert candidate("todqrsmymwc") == "Not matched!"
    assert candidate("iyxnlwylnwaj") == "Found a match!"
    assert candidate("ejtxbjwu") == "Not matched!"
    assert candidate("ywou") == "Not matched!"
    assert candidate("dionwpxoqs") == "Not matched!"
    assert candidate("eczmsphrize") == "Not matched!"
    assert candidate("udge") == "Not matched!"
    assert candidate("jylmh") == "Not matched!"
    assert candidate("udenbrcyp") == "Not matched!"
    assert candidate("mmvcfjfai") == "Found a match!"
    assert candidate("nztfocxrm") == "Not matched!"
    assert candidate("ochdfl") == "Not matched!"
    assert candidate("sanq") == "Found a match!"

if __name__ == '__main__':
    check(text_match_zero_one)