from case_MBPP_420 import is_Perfect_Square


def check(candidate):
    assert candidate(10) == False
    assert candidate(36) == True
    assert candidate(14) == False
    assert candidate(5) == False
    assert candidate(11) == False
    assert candidate(13) == False
    assert candidate(13) == False
    assert candidate(15) == False
    assert candidate(11) == False
    assert candidate(9) == True
    assert candidate(8) == False
    assert candidate(15) == False
    assert candidate(7) == False
    assert candidate(14) == False
    assert candidate(7) == False
    assert candidate(5) == False
    assert candidate(10) == False
    assert candidate(14) == False
    assert candidate(11) == False
    assert candidate(9) == True
    assert candidate(7) == False
    assert candidate(7) == False
    assert candidate(8) == False
    assert candidate(8) == False
    assert candidate(5) == False
    assert candidate(15) == False
    assert candidate(5) == False
    assert candidate(5) == False
    assert candidate(5) == False
    assert candidate(6) == False
    assert candidate(10) == False
    assert candidate(11) == False
    assert candidate(5) == False
    assert candidate(10) == False
    assert candidate(15) == False
    assert candidate(15) == False
    assert candidate(39) == False
    assert candidate(41) == False
    assert candidate(35) == False
    assert candidate(40) == False
    assert candidate(33) == False
    assert candidate(41) == False
    assert candidate(31) == False
    assert candidate(36) == True
    assert candidate(38) == False
    assert candidate(34) == False
    assert candidate(37) == False
    assert candidate(35) == False
    assert candidate(37) == False
    assert candidate(37) == False
    assert candidate(31) == False
    assert candidate(37) == False
    assert candidate(36) == True
    assert candidate(37) == False
    assert candidate(31) == False
    assert candidate(36) == True
    assert candidate(31) == False
    assert candidate(36) == True
    assert candidate(31) == False
    assert candidate(40) == False
    assert candidate(40) == False
    assert candidate(37) == False
    assert candidate(39) == False
    assert candidate(37) == False
    assert candidate(35) == False
    assert candidate(38) == False
    assert candidate(32) == False
    assert candidate(39) == False
    assert candidate(32) == False
    assert candidate(10) == False
    assert candidate(19) == False
    assert candidate(12) == False
    assert candidate(19) == False
    assert candidate(11) == False
    assert candidate(15) == False
    assert candidate(19) == False
    assert candidate(18) == False
    assert candidate(17) == False
    assert candidate(9) == True
    assert candidate(14) == False
    assert candidate(18) == False
    assert candidate(13) == False
    assert candidate(13) == False
    assert candidate(14) == False
    assert candidate(11) == False
    assert candidate(17) == False
    assert candidate(10) == False
    assert candidate(9) == True
    assert candidate(14) == False
    assert candidate(16) == True
    assert candidate(19) == False
    assert candidate(16) == True
    assert candidate(14) == False
    assert candidate(9) == True
    assert candidate(19) == False
    assert candidate(16) == True
    assert candidate(16) == True
    assert candidate(15) == False
    assert candidate(11) == False
    assert candidate(9) == True
    assert candidate(19) == False
    assert candidate(14) == False

if __name__ == '__main__':
    check(is_Perfect_Square)