from case_MBPP_306 import is_Even


def check(candidate):
    assert candidate(1) == False
    assert candidate(2) == True
    assert candidate(3) == False
    assert candidate(5) == False
    assert candidate(4) == True
    assert candidate(4) == True
    assert candidate(4) == True
    assert candidate(3) == False
    assert candidate(5) == False
    assert candidate(1) == False
    assert candidate(6) == True
    assert candidate(1) == False
    assert candidate(5) == False
    assert candidate(4) == True
    assert candidate(3) == False
    assert candidate(2) == True
    assert candidate(5) == False
    assert candidate(5) == False
    assert candidate(3) == False
    assert candidate(6) == True
    assert candidate(1) == False
    assert candidate(5) == False
    assert candidate(4) == True
    assert candidate(1) == False
    assert candidate(3) == False
    assert candidate(6) == True
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(1) == False
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(3) == False
    assert candidate(3) == False
    assert candidate(6) == True
    assert candidate(5) == False
    assert candidate(5) == False
    assert candidate(3) == False
    assert candidate(5) == False
    assert candidate(3) == False
    assert candidate(6) == True
    assert candidate(1) == False
    assert candidate(6) == True
    assert candidate(6) == True
    assert candidate(2) == True
    assert candidate(2) == True
    assert candidate(4) == True
    assert candidate(7) == False
    assert candidate(3) == False
    assert candidate(5) == False
    assert candidate(6) == True
    assert candidate(6) == True
    assert candidate(2) == True
    assert candidate(2) == True
    assert candidate(2) == True
    assert candidate(1) == False
    assert candidate(5) == False
    assert candidate(2) == True
    assert candidate(5) == False
    assert candidate(7) == False
    assert candidate(3) == False
    assert candidate(5) == False
    assert candidate(6) == True
    assert candidate(3) == False
    assert candidate(3) == False
    assert candidate(4) == True
    assert candidate(2) == True
    assert candidate(5) == False
    assert candidate(1) == False
    assert candidate(7) == False
    assert candidate(4) == True
    assert candidate(3) == False
    assert candidate(8) == True
    assert candidate(7) == False
    assert candidate(7) == False
    assert candidate(1) == False
    assert candidate(2) == True
    assert candidate(3) == False
    assert candidate(4) == True
    assert candidate(8) == True
    assert candidate(2) == True
    assert candidate(7) == False
    assert candidate(5) == False
    assert candidate(8) == True
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(6) == True
    assert candidate(6) == True
    assert candidate(4) == True
    assert candidate(1) == False
    assert candidate(3) == False
    assert candidate(2) == True
    assert candidate(8) == True
    assert candidate(2) == True
    assert candidate(1) == False
    assert candidate(3) == False
    assert candidate(8) == True
    assert candidate(5) == False
    assert candidate(8) == True
    assert candidate(2) == True
    assert candidate(7) == False
    assert candidate(6) == True
    assert candidate(7) == False

if __name__ == '__main__':
    check(is_Even)