from case_HE_014 import all_prefixes


def check(candidate):
    assert candidate("KOIA") == ['K', 'KO', 'KOI', 'KOIA']
    assert candidate("IDRTXBQ") == ['I', 'ID', 'IDR', 'IDRT', 'IDRTX', 'IDRTXB', 'IDRTXBQ']
    assert candidate("CEHRRF") == ['C', 'CE', 'CEH', 'CEHR', 'CEHRR', 'CEHRRF']
    assert candidate("SCITGFWZ") == ['S', 'SC', 'SCI', 'SCIT', 'SCITG', 'SCITGF', 'SCITGFW', 'SCITGFWZ']
    assert candidate("FNWOUNG") == ['F', 'FN', 'FNW', 'FNWO', 'FNWOU', 'FNWOUN', 'FNWOUNG']
    assert candidate("DMNCTHY") == ['D', 'DM', 'DMN', 'DMNC', 'DMNCT', 'DMNCTH', 'DMNCTHY']
    assert candidate("ublzubjntg") == ['u', 'ub', 'ubl', 'ublz', 'ublzu', 'ublzub', 'ublzubj', 'ublzubjn', 'ublzubjnt', 'ublzubjntg']
    assert candidate("i") == ['i']
    assert candidate("qta") == ['q', 'qt', 'qta']
    assert candidate("dim") == ['d', 'di', 'dim']
    assert candidate("xqqbtqs") == ['x', 'xq', 'xqq', 'xqqb', 'xqqbt', 'xqqbtq', 'xqqbtqs']
    assert candidate("fnvuag") == ['f', 'fn', 'fnv', 'fnvu', 'fnvua', 'fnvuag']
    assert candidate("pjxmq") == ['p', 'pj', 'pjx', 'pjxm', 'pjxmq']
    assert candidate("KVKDKNQN") == ['K', 'KV', 'KVK', 'KVKD', 'KVKDK', 'KVKDKN', 'KVKDKNQ', 'KVKDKNQN']
    assert candidate("hqj") == ['h', 'hq', 'hqj']
    assert candidate("sg") == ['s', 'sg']
    assert candidate("r") == ['r']
    assert candidate("iiryo") == ['i', 'ii', 'iir', 'iiry', 'iiryo']
    assert candidate("fz") == ['f', 'fz']
    assert candidate("jjr") == ['j', 'jj', 'jjr']
    assert candidate("m") == ['m']
    assert candidate("iwtoy") == ['i', 'iw', 'iwt', 'iwto', 'iwtoy']
    assert candidate("ojigt") == ['o', 'oj', 'oji', 'ojig', 'ojigt']
    assert candidate("vvqlrsbcu") == ['v', 'vv', 'vvq', 'vvql', 'vvqlr', 'vvqlrs', 'vvqlrsb', 'vvqlrsbc', 'vvqlrsbcu']
    assert candidate("sm") == ['s', 'sm']
    assert candidate("lfx") == ['l', 'lf', 'lfx']
    assert candidate("JFLH") == ['J', 'JF', 'JFL', 'JFLH']
    assert candidate("nco") == ['n', 'nc', 'nco']
    assert candidate("IBJBYYF") == ['I', 'IB', 'IBJ', 'IBJB', 'IBJBY', 'IBJBYY', 'IBJBYYF']
    assert candidate("spscmibevhqa") == ['s', 'sp', 'sps', 'spsc', 'spscm', 'spscmi', 'spscmib', 'spscmibe', 'spscmibev', 'spscmibevh', 'spscmibevhq', 'spscmibevhqa']
    assert candidate("aiu") == ['a', 'ai', 'aiu']
    assert candidate("ryxwg") == ['r', 'ry', 'ryx', 'ryxw', 'ryxwg']
    assert candidate("OCEWQCB") == ['O', 'OC', 'OCE', 'OCEW', 'OCEWQ', 'OCEWQC', 'OCEWQCB']
    assert candidate("wmmbyciijt") == ['w', 'wm', 'wmm', 'wmmb', 'wmmby', 'wmmbyc', 'wmmbyci', 'wmmbycii', 'wmmbyciij', 'wmmbyciijt']
    assert candidate("SHMDGI") == ['S', 'SH', 'SHM', 'SHMD', 'SHMDG', 'SHMDGI']
    assert candidate("ehcx") == ['e', 'eh', 'ehc', 'ehcx']
    assert candidate("QTLN") == ['Q', 'QT', 'QTL', 'QTLN']
    assert candidate("tp") == ['t', 'tp']
    assert candidate("fb") == ['f', 'fb']
    assert candidate("iy") == ['i', 'iy']
    assert candidate("pagbqxbsrmkp") == ['p', 'pa', 'pag', 'pagb', 'pagbq', 'pagbqx', 'pagbqxb', 'pagbqxbs', 'pagbqxbsr', 'pagbqxbsrm', 'pagbqxbsrmk', 'pagbqxbsrmkp']
    assert candidate("OTQXZF") == ['O', 'OT', 'OTQ', 'OTQX', 'OTQXZ', 'OTQXZF']
    assert candidate("puotipoqoyxk") == ['p', 'pu', 'puo', 'puot', 'puoti', 'puotip', 'puotipo', 'puotipoq', 'puotipoqo', 'puotipoqoy', 'puotipoqoyx', 'puotipoqoyxk']
    assert candidate("afkgqemxrgpa") == ['a', 'af', 'afk', 'afkg', 'afkgq', 'afkgqe', 'afkgqem', 'afkgqemx', 'afkgqemxr', 'afkgqemxrg', 'afkgqemxrgp', 'afkgqemxrgpa']
    assert candidate("kxem") == ['k', 'kx', 'kxe', 'kxem']
    assert candidate("lpkhdk") == ['l', 'lp', 'lpk', 'lpkh', 'lpkhd', 'lpkhdk']
    assert candidate("yqhwkt") == ['y', 'yq', 'yqh', 'yqhw', 'yqhwk', 'yqhwkt']
    assert candidate("z") == ['z']
    assert candidate("EFDX") == ['E', 'EF', 'EFD', 'EFDX']
    assert candidate("tht") == ['t', 'th', 'tht']
    assert candidate("zddiegkett") == ['z', 'zd', 'zdd', 'zddi', 'zddie', 'zddieg', 'zddiegk', 'zddiegke', 'zddiegket', 'zddiegkett']
    assert candidate('') == []
    assert candidate("JZMMI") == ['J', 'JZ', 'JZM', 'JZMM', 'JZMMI']
    assert candidate("eblqqzhzhldy") == ['e', 'eb', 'ebl', 'eblq', 'eblqq', 'eblqqz', 'eblqqzh', 'eblqqzhz', 'eblqqzhzh', 'eblqqzhzhl', 'eblqqzhzhld', 'eblqqzhzhldy']
    assert candidate("eyqoxnaqj") == ['e', 'ey', 'eyq', 'eyqo', 'eyqox', 'eyqoxn', 'eyqoxna', 'eyqoxnaq', 'eyqoxnaqj']
    assert candidate("xwxghx") == ['x', 'xw', 'xwx', 'xwxg', 'xwxgh', 'xwxghx']
    assert candidate("mp") == ['m', 'mp']
    assert candidate("er") == ['e', 'er']
    assert candidate("ZXWA") == ['Z', 'ZX', 'ZXW', 'ZXWA']
    assert candidate("kyt") == ['k', 'ky', 'kyt']
    assert candidate("rhc") == ['r', 'rh', 'rhc']
    assert candidate("QGZFIN") == ['Q', 'QG', 'QGZ', 'QGZF', 'QGZFI', 'QGZFIN']
    assert candidate("vu") == ['v', 'vu']
    assert candidate("DVBCCKAVZ") == ['D', 'DV', 'DVB', 'DVBC', 'DVBCC', 'DVBCCK', 'DVBCCKA', 'DVBCCKAV', 'DVBCCKAVZ']
    assert candidate("h") == ['h']
    assert candidate("yrx") == ['y', 'yr', 'yrx']
    assert candidate('WWW') == ['W', 'WW', 'WWW']
    assert candidate("dmhwsbf") == ['d', 'dm', 'dmh', 'dmhw', 'dmhws', 'dmhwsb', 'dmhwsbf']
    assert candidate("PFTHZB") == ['P', 'PF', 'PFT', 'PFTH', 'PFTHZ', 'PFTHZB']
    assert candidate("ov") == ['o', 'ov']
    assert candidate("s") == ['s']
    assert candidate("dsdapg") == ['d', 'ds', 'dsd', 'dsda', 'dsdap', 'dsdapg']
    assert candidate("PPSY") == ['P', 'PP', 'PPS', 'PPSY']
    assert candidate("REUNT") == ['R', 'RE', 'REU', 'REUN', 'REUNT']
    assert candidate("HDEXJYYTU") == ['H', 'HD', 'HDE', 'HDEX', 'HDEXJ', 'HDEXJY', 'HDEXJYY', 'HDEXJYYT', 'HDEXJYYTU']
    assert candidate("sjie") == ['s', 'sj', 'sji', 'sjie']
    assert candidate("lixursxputz") == ['l', 'li', 'lix', 'lixu', 'lixur', 'lixurs', 'lixursx', 'lixursxp', 'lixursxpu', 'lixursxput', 'lixursxputz']
    assert candidate("IESMY") == ['I', 'IE', 'IES', 'IESM', 'IESMY']
    assert candidate("tktjg") == ['t', 'tk', 'tkt', 'tktj', 'tktjg']
    assert candidate("rk") == ['r', 'rk']
    assert candidate("cjzbbphopmc") == ['c', 'cj', 'cjz', 'cjzb', 'cjzbb', 'cjzbbp', 'cjzbbph', 'cjzbbpho', 'cjzbbphop', 'cjzbbphopm', 'cjzbbphopmc']
    assert candidate("JJGOX") == ['J', 'JJ', 'JJG', 'JJGO', 'JJGOX']
    assert candidate("RJXCAY") == ['R', 'RJ', 'RJX', 'RJXC', 'RJXCA', 'RJXCAY']
    assert candidate("hffq") == ['h', 'hf', 'hff', 'hffq']
    assert candidate("XIYOET") == ['X', 'XI', 'XIY', 'XIYO', 'XIYOE', 'XIYOET']
    assert candidate("f") == ['f']
    assert candidate("CXALTGYJG") == ['C', 'CX', 'CXA', 'CXAL', 'CXALT', 'CXALTG', 'CXALTGY', 'CXALTGYJ', 'CXALTGYJG']
    assert candidate('asdfgh') == ['a', 'as', 'asd', 'asdf', 'asdfg', 'asdfgh']
    assert candidate("CZYTRZCTB") == ['C', 'CZ', 'CZY', 'CZYT', 'CZYTR', 'CZYTRZ', 'CZYTRZC', 'CZYTRZCT', 'CZYTRZCTB']
    assert candidate("fotrmhplhes") == ['f', 'fo', 'fot', 'fotr', 'fotrm', 'fotrmh', 'fotrmhp', 'fotrmhpl', 'fotrmhplh', 'fotrmhplhe', 'fotrmhplhes']
    assert candidate("jv") == ['j', 'jv']
    assert candidate("dm") == ['d', 'dm']
    assert candidate("fkkzva") == ['f', 'fk', 'fkk', 'fkkz', 'fkkzv', 'fkkzva']
    assert candidate("v") == ['v']
    assert candidate("WNPWFPYAX") == ['W', 'WN', 'WNP', 'WNPW', 'WNPWF', 'WNPWFP', 'WNPWFPY', 'WNPWFPYA', 'WNPWFPYAX']
    assert candidate("n") == ['n']
    assert candidate("BXEGBEDWY") == ['B', 'BX', 'BXE', 'BXEG', 'BXEGB', 'BXEGBE', 'BXEGBED', 'BXEGBEDW', 'BXEGBEDWY']
    assert candidate("xb") == ['x', 'xb']
    assert candidate("puf") == ['p', 'pu', 'puf']
    assert candidate("b") == ['b']
    assert candidate("qiwzhuchprwa") == ['q', 'qi', 'qiw', 'qiwz', 'qiwzh', 'qiwzhu', 'qiwzhuc', 'qiwzhuch', 'qiwzhuchp', 'qiwzhuchpr', 'qiwzhuchprw', 'qiwzhuchprwa']
    assert candidate("KSLBUOMQ") == ['K', 'KS', 'KSL', 'KSLB', 'KSLBU', 'KSLBUO', 'KSLBUOM', 'KSLBUOMQ']
    assert candidate("ayu") == ['a', 'ay', 'ayu']
    assert candidate("MPOFCXOL") == ['M', 'MP', 'MPO', 'MPOF', 'MPOFC', 'MPOFCX', 'MPOFCXO', 'MPOFCXOL']
    assert candidate("bwufz") == ['b', 'bw', 'bwu', 'bwuf', 'bwufz']
    assert candidate("trksbkxrclj") == ['t', 'tr', 'trk', 'trks', 'trksb', 'trksbk', 'trksbkx', 'trksbkxr', 'trksbkxrc', 'trksbkxrcl', 'trksbkxrclj']
    assert candidate("KCDHZFX") == ['K', 'KC', 'KCD', 'KCDH', 'KCDHZ', 'KCDHZF', 'KCDHZFX']
    assert candidate("cpz") == ['c', 'cp', 'cpz']
    assert candidate("woesuowbhauo") == ['w', 'wo', 'woe', 'woes', 'woesu', 'woesuo', 'woesuow', 'woesuowb', 'woesuowbh', 'woesuowbha', 'woesuowbhau', 'woesuowbhauo']
    assert candidate("nfsdghjrsk") == ['n', 'nf', 'nfs', 'nfsd', 'nfsdg', 'nfsdgh', 'nfsdghj', 'nfsdghjr', 'nfsdghjrs', 'nfsdghjrsk']
    assert candidate("dgx") == ['d', 'dg', 'dgx']
    assert candidate("zk") == ['z', 'zk']
    assert candidate("ljzksaqqu") == ['l', 'lj', 'ljz', 'ljzk', 'ljzks', 'ljzksa', 'ljzksaq', 'ljzksaqq', 'ljzksaqqu']
    assert candidate("OGGXLN") == ['O', 'OG', 'OGG', 'OGGX', 'OGGXL', 'OGGXLN']
    assert candidate("OXUAIVN") == ['O', 'OX', 'OXU', 'OXUA', 'OXUAI', 'OXUAIV', 'OXUAIVN']
    assert candidate("UTT") == ['U', 'UT', 'UTT']
    assert candidate("BEIPFLDD") == ['B', 'BE', 'BEI', 'BEIP', 'BEIPF', 'BEIPFL', 'BEIPFLD', 'BEIPFLDD']
    assert candidate("u") == ['u']
    assert candidate("CDFGF") == ['C', 'CD', 'CDF', 'CDFG', 'CDFGF']
    assert candidate("EPBMY") == ['E', 'EP', 'EPB', 'EPBM', 'EPBMY']
    assert candidate("xpvvkp") == ['x', 'xp', 'xpv', 'xpvv', 'xpvvk', 'xpvvkp']
    assert candidate("ebm") == ['e', 'eb', 'ebm']
    assert candidate("gaepxli") == ['g', 'ga', 'gae', 'gaep', 'gaepx', 'gaepxl', 'gaepxli']
    assert candidate("BFMGS") == ['B', 'BF', 'BFM', 'BFMG', 'BFMGS']
    assert candidate("HRKB") == ['H', 'HR', 'HRK', 'HRKB']
    assert candidate("HTV") == ['H', 'HT', 'HTV']
    assert candidate("a") == ['a']

if __name__ == '__main__':
    check(all_prefixes)